### ISSUE TITLE
[Proposal] Add a new command to tmux for streamlining the launching multi-headed sessions

### ISSUE THREAD

**Issue by SeamusConnor** [tmux/tmux#449] opened 2016-06-14 16:59 UTC
Update:

Plan is to add a flag to new-session to provide some of the functionality, as discussed below.

------------------------

I am not sure if baking this into tmux is the correct thing to do, but I have a wrapper for launching tmux that:

1. Allows for the easy creating of multiple sessions on the same server, used for launching multiple terminal emulators attached to the same server, it also automatically reuses unattached sessions.  It automatically decides between attaching or launching a new session.
2. Provides a confirmation dialog before the process launched in window 0 is closed, so that the server doesn't go away through accidental overzealous us of CTRL-D .
3. Launches tmux sessions in their own systemd scope so that logouts don't kill the server

I know that number 3 has been a source of controversy, so I am not asking to roll that into tmux, but the other capabilities might make good flags for the new-session command. However, by providing a backstop to keep the last running session alive, tmux could easily be launched with a systemd unit file and left running.  This provides a partial workaround for the problems caused by systemd, at least for my use cases. 

If I were to create a PR with 1 and 2, would there be any interest in merging it in?

**Comment by nicm** [comment] 2016-06-14 18:57
Hi

1) I don't know what this means, what would the commands look like?

2) You can already use remain-on-exit either for one window or globally and tmux will not exit with ^D.

3) Not until there is a way to do this without pulling in large thirdparty libraries.

**Comment by StrongGoat** [comment] 2016-06-14 19:21
The runs one of the following:

1) systemd-run tmux if no session is currently running (not interested in adding this upstream)
2) tmux attach -t xxxx if one or more detached sessions are running
3) tmux new-session if no attached sessions are running.

This allows me to run my script in any number of terminals and have them all share a socket.  Using it this way is sort of like doing splits inside tmux, but it lets me move the windows around between monitors, and manage them with the mouse.

https://gist.github.com/StrongGoat/d269963ac1a75e2865aec9cd3fd820fe

**Comment by nicm** [comment] 2016-06-14 19:23
This is so easy to do with existing commands I think it doesn't need to be
builtin.

**Comment by StrongGoat** [comment] 2016-06-14 19:24
I guess another way to put it is extending 'new-session -A' so that you dont have to specify a name for the session.

**Comment by nicm** [comment] 2016-06-14 19:25
Yes making new -A work without a session would be fine.

**Comment by StrongGoat** [comment] 2016-06-14 19:27
Ok, sounds good.  I will look at adding that in.  Want me to update this issue to match the discussion?

**Comment by StrongGoat** [comment] 2016-06-17 19:46
Alright, I have a commit that I am currently testing.  I ended up adding a new flag to new-session that provides a mechanism for naming session-groups/attaching to existing named session-groups.  Thoughts?
https://github.com/StrongGoat/tmux/commit/0ee796bcd2370af104c1beeaaa935aeda5f1db6b

**Comment by nicm** [comment] 2016-06-17 21:13
I think I would prefer if -A together with -t behaved like -A with -n does,
if you see what I mean.

Also please remove all the extra whitespace changes.

**Comment by StrongGoat** [comment] 2016-06-17 21:37
The only wrinkle for me with -At is that -t expects a session, which may or may not exist before the command is run, and each session in a group will have a different name.  What do you think about the named session groups?  I could change it to something like `-Ag group-name`.

Now that I have dug into the code a bit, I think I can explain the problem I am trying to solve a bit more exactly.  In my work flow, I have 1 or more sessions in the same group.  I want to be able to launch as many of these sessions as I want, without having to look through the output of 'list-sessions' for a session within the group I am attaching to.  Ideally, I would be able to create an alias for some tmux command that would 1) create a session inside a group if there is no detached session available, 2) attach to a detached session automatically if one exists.  This would be exactly like `new-group -As session-name`, except that it would operate on session groups instead of individual sessions.

Anyway, I hope that it is more clear what I am going for.  Thanks for working with me on this, I have really gotten a lot of mileage out of tmux over the years.

**Comment by ThomasAdam** [comment] 2016-06-17 21:42
Sounds to me like this is a good candidate for using hooks.

-- Thomas Adam

**Comment by StrongGoat** [comment] 2016-06-17 22:14
Interesting.  How would I use hooks to do this?

**Comment by StrongGoat** [comment] 2016-06-19 18:25
I updated to add a `-g` flag to new-session and attach.  `new-session -Ag group-name` covers my use case (and replaces `-N`).  There are even more whitespace errors, and the docs aren't updated yet, but here is what I have currently.

1. session_group struct updated with a name field
2. `new-session -g group-name` creates new sessions in the named session group
3. `new-session -Ag group-name` attaches to the first detached session in the named session group, or creates a new one if one does not exist.  Should be an analog for `new-session -At session-name`.
4. `attach -g group-name` attaches to the first detached session in the named group, fails if the named group does not exist, or there are no detached sessions.

Commit Here:
StrongGoat@60310262fcc800e37b9def37889b1a40f4d5c6c2

Some things that I haven't considered:

1. `tmux -C` integration for named-groups
2. ???

Also, I am a little unclear by what you mean by having `-At` work along the lines of `-An`.  To my understanding `-A` is currently only valid with `-s`.  Am I missing something here?

**Comment by nicm** [comment] 2016-06-22 18:03
I don't really see the point in this, it doesn't matter which session in a group you use with new, news etc, so effectively the group is named after all its sessions. It would be different if there was some other attributes affecting all group members but if the only thing you want us a name, why not just give the first session in a group a predictable name?

**Comment by nicm** [comment] 2016-06-22 18:26
It seems like your requirement would be trivially scriptable if you just give all the sessions in the same group a similar name prefix (and I guess this is what you have already scripted). So I am not convinced this is generally useful.

Ultimately I think perhaps we should implement groups differently. At the moment they are sort of a link object, so that when new-window (for example) creates a new window in session foo, it knows to also go and create one in session bar. It would be better if the group itself was the container for the windows, so that creating a window in a group automatically created it in all sessions. This would also allow us to share options and perhaps other bits and pieces between sessions. So the group would become the container for the options and windows, and the session the container for the active window and the session name. However, this would be a much more substantial change, and I'm not sure it is worth it either.

**Comment by StrongGoat** [comment] 2016-06-22 18:45
So imagine this:

1. gnome-terminal is launched (instance 1), run command tmux new-session -As test
2. gnome-terminal is launched again (instance 2), run command tmux new-session -t test

Tmux list-sessions now shows session 'test' and session '0', and also shows them as part of group '0'.   Now close gnome terminal instance 1.  You are left with no session group, and a session named '0', which means that you lose your 'test' session name.  If you wanted to correct this you would have to first determine what that session should have been named, then call rename-session on one of the existing sessions.  This gets more complicated with the following scenario.

1. gnome-terminal is launched (instance 1), run command tmux new-session -As do_kernel_stuff
2. gnome-terminal is launched again (instance 2), run command tmux new-session -t do_kernel_stuff
3. Sessions 'do_kernel_stuff' and '0' are detached.
4. gnome terminal instance 1, run tmux new-session -As do_python_stuff
5. gnome terminal instance 2, run tmux new-session -t do_python_stuff

So this is my real use case.  What you end up with the above is this:

```
7: 1 windows (created Wed Jun 22 12:31:18 2016) [80x20] (group 0)
9: 1 windows (created Wed Jun 22 12:31:38 2016) [80x20] (group 1)
do_kernel_stuff: 1 windows (created Wed Jun 22 12:31:09 2016) [80x20] (group 0)
do_python_stuff: 1 windows (created Wed Jun 22 12:31:31 2016) [80x20] (group 1)
```

If you happen to kill do_kernel_stuff for example, you would end up with a session '7' in this case just hanging out on its own with no information about the task it was intended for.  To work around this the script would have to:

1. Probably make use of separate sockets (-L) for each task because there is no way to track groups unless there is more than 1 session in that group.  Basically you would be using sockets as named session groups.
2. Name new sessions based on the socket selected.
3. parse through the running sessions to see if one is available to be attached
4. provide some way of statusing the whole thing, which should be straightforward, as long as the sockets managed by the script are easily distinguishable from sockets launched normally.

On the flipside, the PR I submitted adds a way to not lose that initial information (do_kernel_stuff), so all of the sessions that are for that task can easily be re-attached/destroyed/statused using existing tools, and my script becomes `alias t='tmux new-session -Ag'`.  Also, iTerm2 could potentially use this along side `tmux -C` to associate tmux grouped windows with separate profiles.

**Comment by StrongGoat** [comment] 2016-06-22 19:33
You know, before sending you a wall of text I probably should have checked to see if you were clear on my use case.  If it is clear to you, and you still don't want the change, I am happy (if a little disappointed) to withdrawal the PR and close the issue.

**Comment by nicm** [comment] 2016-06-22 19:50
I am not particularly convinced by your use case because it seems like the whole thing would be easily solved with a short script that names your sessions and some care with kill-session. But I think it would be nice if groups had names instead of indexes.

I don't think we should have -g, and or that we should have "unnamed" groups, and groups shouldn't be persistent if they have no sessions. I think we should just do this:

- All groups have a name /instead/ of the index (session_group format now returns the name).
- The name comes from the first session they are created from.
- Accept the group name to new-window -t and only try to use the session if it can't be found.
- Make the default name of new windows in a group groupname-0, groupname-2 etc.

**Comment by StrongGoat** [comment] 2016-06-22 20:41
Hmm.  Giving it a little more thought, the big issue that I run into reliably scripting this is the session groups disappearing when the group drops to one member, so if I _only_ kept the change that keeps session groups around with 1 member, then the script would be much cleaner.

I do like the named groups as it makes it a little more clear for me, so I would be happy to redo that in the way you described.

As an aside, I have never gotten around to contributing changes I have made to OSS back up stream before, so this is super fun for me.  Thanks for working with me.

**Comment by StrongGoat** [comment] 2016-06-26 23:39
Hello again.

I gave using '-t' with named groups a shot and it got a little too complicated and overloaded the meaning of too many things.  I think I will stick with `-g` for my personal use.

Thanks

**Comment by nicm** [comment] 2016-07-01 12:02
Try this please: [tmux-sg.diff.txt](https://github.com/tmux/tmux/files/343395/tmux-sg.diff.txt)

This makes:

tmux new -sfoo -tbar <-- create a session foo in group bar
tmux new -tbar <-- create a session in group bar
tmux new -tfoo <-- create a session in the same group as session foo

And also changes so that although you can't have empty session groups, you can have them with only one member. So the name will be preserved so long as any session exists in that group.

My only concerns are:

- If you have a mixture of groups and sessions with the same names or the same name prefix, it will be confusing.

- It seems like it is is neither one thing nor the other. If we have named groups... why can't I rename a group? Why can't I do kill-session with a group name to kill everything in the group? etc etc

Still, perhaps this is enough for now.

**Comment by SeamusConnor** [comment] 2016-07-06 19:27
Hey, I haven't forgotten about this.  I have just been in crunch mode at work.  I will swing back around here this weekend.

**Comment by indirect** [comment] 2016-10-11 20:47
@SeamusConnor I wrote a script that (I think, if I understand you) manages to do exactly the thing you are describing completely in Bash using existing tmux commands. Usage is `tmux-named NAME`, and running that command will create a group named NAME if it does not exist, create a new session, and then join that session to group NAME.

https://gist.github.com/indirect/7510753

**Closed** 2016-10-19 10:19 UTC
