### ISSUE TITLE
Conflicting types of forkpty while building tmux-3.1b

### ISSUE THREAD

**Issue by paldebjit** [tmux/tmux#2274] opened 2020-06-19 17:58 UTC
Dependencies installed: 

**libevent**: release-2.1.11-stable
**Configured with the command**: ./configure --prefix=/home/dp638/Tools/libevent --enable-shared

**ncurses**: ncurses-6.2
**Configured with the command**: ./configure --prefix=/home/dp638/Tools/ncurses --with-shared --with-termlib --enable-pc-files --with-pkg-config-libdir=/home/dp638/Tools/ncurses/lib/pkgconfig

**tmux**: tmux-3.1b
**Configured with the command**: PKG_CONFIG_PATH=/home/dp638/Tools/libevent/lib/pkgconfig:/home/dp638/Tools/ncurses/lib/pkgconfig ./configure --prefix=/home/dp638/Tools/tmux

Tmux config.log attached. It shows it cannot find libtinfo whereas libtinfo is pretty much there in /home/dp638/Tools/ncurses/lib .
![Capture](https://user-images.githubusercontent.com/49922297/85165953-9705ba80-b234-11ea-87c5-c100cd33467a.PNG)
[config.log](https://github.com/tmux/tmux/files/4806068/config.log)

I have even included the lib directory path of both nurses and libevent in the LD_LIBRARY_PATH. Not sure why Tmux build still fails or why it cannot find the libtinfo.
![Capture1](https://user-images.githubusercontent.com/49922297/85166149-df24dd00-b234-11ea-8740-bca4eecffb0c.PNG)

Any suggestions would be very helpful.

**Comment by nicm** [comment] 2020-06-19 18:04
If you set `PKG_CONFIG_PATH` the same as for building tmux what do `pkg-config --cflags tinfo` and `pkg-config --libs tinfo` show?

**Comment by paldebjit** [comment] 2020-06-19 18:27
![Capture2](https://user-images.githubusercontent.com/49922297/85168814-e352f980-b238-11ea-9924-d4aa703214e3.PNG)


**pkg-config --cflags tinfo**:  -D_GNU_SOURCE -I/home/dp638/Tools/ncurses/include/ncurses -I/home/dp638/Tools/ncurses/include
**pkg-config -libs tinfo**: -ltinfo

Its not showing the library path for some reason.

**Comment by nicm** [comment] 2020-06-19 18:29
What about the same for ncurses instead of tinfo? Does it have the -L in --libs?

**Comment by paldebjit** [comment] 2020-06-19 18:30
No it does not. When I do 

pkg-config --libs ncurses

it returns the following:

-lncurses -ltinfo

**Comment by paldebjit** [comment] 2020-06-19 18:36
I think ncurses have something messed up. When I look into the .pc file, the Libs line does not have -L${libdir} but only -lncurses etc.

**Comment by nicm** [comment] 2020-06-19 18:37
Yes, I just tried it and I see the same - it probably worked for me because I installed libevent in the same directory and its .pc file has the right -L.

**Comment by paldebjit** [comment] 2020-06-19 18:39
But my original error was that it was having conflict with forkpty. Can that be for this reason?

**Comment by nicm** [comment] 2020-06-19 18:39
Yes, the configure tests can't find -ltinfo so the test for forkpty also fails.

**Comment by nicm** [comment] 2020-06-19 18:47
Very odd, if I run gen-pkgconfig in ncurses manually it works.

**Comment by paldebjit** [comment] 2020-06-19 18:48
Ok. I just tried with ncurses-6.0. It worked fine as they have the right -L in the PC files. Possibly this bug was introduced in 6.2. You may want to tell the users to use ncurses-6.0 for the time being. I will see if I can file a bug report with ncurses.

**Comment by nicm** [comment] 2020-06-19 18:54
The problem is this line in misc/gen-pkgconfig:
~~~~
        [ -d ${opt##-L} ] || continue
~~~~
The install directory does not exist yet because you have only done `make`, not `make install`.

**Comment by nicm** [comment] 2020-06-19 18:55
@ThomasDickey?

**Comment by paldebjit** [comment] 2020-06-19 18:56
With all due respect, that's not true. I did make install because my installation directory is different from that of ncurses source directory. And using the same configure, make, make install sequence, ncurses-6.0 worked.

**Comment by nicm** [comment] 2020-06-19 18:57
It is correct, the .pc files are generated by make not make install, and at that point the directory does not exist.

**Comment by paldebjit** [comment] 2020-06-19 18:59
The point is I did make install after doing make. I always keep my installations sane. In fact, ncurses-6.0 worked with same sequence. You may try with ncurses-6.2.tar.gz that was released on 2/12/2020 from https://invisible-mirror.net/archives/ncurses/ncurses-6.2.tar.gz

**Comment by nicm** [comment] 2020-06-19 19:01
I don't know what you are talking about. You can't do make install without doing make first. When you run make, the directory does not exist and so gen-pkgconfig does not include the -L flags in the .pc files and they are not correct.

**Comment by nicm** [comment] 2020-06-19 19:02
If you do `make clean; make; make install` again a second time after the first time you install, then it will create correct .pc files. This is a bug in ncurses gen-pkgconfig script.

**Comment by nicm** [comment] 2020-06-19 19:03
It looks like this problem was introduced in ncurses 6.1 patch 20191012.

**Comment by paldebjit** [comment] 2020-06-19 19:09
What I am saying is the following message:

https://github.com/tmux/tmux/issues/2274#issuecomment-646816867


Please see what sequence I did, configure, make, make install. I am well aware that I cannot do make install without doing make. And what I am suggesting is it is a bug in ncurses-6,2 package.

**Comment by nicm** [comment] 2020-06-19 19:13
Ah right OK, sorry - I am not saying you are doing anything wrong, I am saying that because you (or anyone else) has to run `make` before `make install`, and the .pc files are generated during `make`, a custom libdir will not exist at that point and so they wille be wrong. The bug is that ncurses's `gen-pkgconfig` script requires that the libdir exist - if it does not, it is not put into the .pc files.

Hopefully @ThomasDickey will comment and either fix this in newer ncurses versions or perhaps say that it is necessary.

In the meantime, you can use ncurses 6.2 by running `make; make install` twice so that libdir exists by the second time around - then your .pc files should be correct:

~~~~
make; make install; make clean; make; make install

**Comment by nicm** [comment] 2020-06-19 19:15
Well, I am not absolutely certain they are generated in make and not make install, but certainly it seems to be before libdir is created!

**Comment by nicm** [comment] 2020-06-22 07:48
I am going to close this issue since it is not a problem with tmux, if you want to report it to the ncurses ML then please go ahead.

**Closed by nicm** 2020-06-22 07:48 UTC
