### ISSUE TITLE
Send the version in the version response

### ISSUE THREAD

**Issue by xordspar0** [tmux/tmux#2069] opened 2020-01-27 19:26 UTC
This is a feature request, not a bug.

When a program requests the version of the terminal it's running in, tmux responds with `^[[>84;0;0c`: https://github.com/tmux/tmux/blob/5f5f029e3b3a782dc616778739b2801b00b17c0e/input.c#L1397

tmux uses the `84` part to identify itself to programs. The second part, the `;0;` is the patch level. Some other terminal emulators use this to specify the version, but tmux always returns 0.

It can be useful to tell programs what version of tmux is running. Vim checks the version of many terminal so that it can selectively enable features that were only added in recent versions of some terminal: https://github.com/xordspar0/vim/blob/master/src/term.c#L4586-L4628

It would be useful if tmux sent its version to programs in the patch level section instead of 0. One example of where this could be useful is detecting SGR mouse support, which was added to tmux in version 1.8. Attempting to use the SGR mouse protocol with a terminal that doesn't support it can cause problems for the program.

**Comment by nicm** [comment] 2020-01-27 20:04
I don't like modifying DA like this and TBH I wouldn't rely on it returning
84 for tmux because I'm not going to promise not to change it.

iTerm2 has DSR 1337 which returns it's version, I would suggest adding that
to tmux instead.

I don't think SGR mouse is a terribly good example because it was designed
so programs could tell the difference and could just turn it on regardless.
And tmux 1.8 has not been supported for more than 6 years :-).

**Comment by nicm** [comment] 2020-01-28 10:59
I have added support for DSR 1337 to OpenBSD now, it will be in GitHub later on.

**Closed** 2020-01-28 11:40 UTC

**Comment by xordspar0** [comment] 2020-01-29 13:31
Great, thanks for the quick response and feature implementation.
