### ISSUE TITLE
Hook "after-select-pane" doesn't work with "select-pane -T"

### ISSUE THREAD

**Issue by Technik-J** [tmux/tmux#2311] opened 2020-07-16 10:48 UTC
I'm trying to run a command after renaming pane title with `select-pane -T`, but hook `after-select-pane` won't work with this. It's works fine with just `select-pane`.

Is it an intended behavior or a bug? If it intended then how can I run a command after pane title change, if it even possible?

Tested on tmux version from commit ab8d685.

**Comment by nicm** [comment] 2020-07-21 05:42
Well I wouldn't say it was intended particularly. I think it'd be better to add a separet pane-title-changed hook though. Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/4951520/x.diff.txt)

**Comment by Technik-J** [comment] 2020-07-22 09:22
It's works. Thank you.

During testing I noticed one thing. Command in `set-hook` will run in the pane or window that produced this hook. This is not mentioned in documentation, but I noticed this behavior while working with tmux.

Only `run-shell` doesn't do that. E.g I have this settings:
```
set-hook -g pane-title-changed 'send-keys "a"; run "tmux send-keys a"'
set-hook -g alert-activity 'send-keys "a"; run "tmux send-keys a"'
```
After either of this hooks triggered, I get "a" typed in the current pane, and in the pane that triggered the hook. So the `send-keys "a"` was run in pane that triggered the hook, but `run "tmux send-keys a"` was run in current pane.

I'm I wrong to assume that commands should be run in the pane or window that triggered the hook? Is this a bug or intended behavior of the `run-shell` command?

**Comment by nicm** [comment] 2020-07-24 07:11
Applied to OpenBSD now, will be in GitHub later. Thanks!

The `send-keys` run from `run-shell` does not have a way to know which pane it was run from so it has to guess. You can work around this by telling it explicitly (`run-shell` will expand `#{pane_id}` using the hook's pane):
~~~~
set-hook -g pane-title-changed 'send-keys "a"; run "tmux send-keys -t#{pane_id} a"'

**Closed** 2020-07-24 07:11 UTC
