### ISSUE TITLE
bell-action other ignored

### ISSUE THREAD

**Issue by ondrejj** [tmux/tmux#1027] opened 2017-07-29 18:14 UTC
set -g bell-action other                
is ignored. Bell still triggers in current window too.
tmux version: 2.5 (last known worked version: 2.3)
platform: Fedora 26 Linux

**Comment by nicm** [comment] 2017-07-29 19:15
Does it work on master? If not please provide proper steps to reproduce.

On 29 Jul 2017 7:14 pm, "ondrejj" <notifications@github.com> wrote:

set -g bell-action other
is ignored. Bell still triggers in current window too.
tmux version: 2.5 (last known worked version: 2.3)
platform: Fedora 26 Linux

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/1027>, or mute the thread

**Comment by ondrejj** [comment] 2017-07-30 05:44
Yes, same problem on master (if I tested right way).
Steps to reproduce are simple for bash:
1. tmux # start tmux
2. tmux set -g bell-action other
3. sleep 3s && echo ^V^G

(^V represents keys CTRL+V, ^G represents CTRL+G)
These keys adds bell action. You can use also different ways to activate a bell.
Other and current values for bell-action should be opposite, but for me there are no difference in latest tmux version. Here is part of documentation:
                     current means only bells in windows other than
                     the current window are ignored and other means bells in
                     the current window are ignored but not those in other
                     windows.

**Comment by nicm** [comment] 2017-07-30 13:49
Pretty sure this is fixed in master, it works for me. Did you restart entirely after you updated?

**Comment by ondrejj** [comment] 2017-07-31 05:12
Sorry, my testing of latest version was wrong. Sure, it's fixed, thanks. Can you please point me to an commit, which can be backported as fix?

**Comment by nicm** [comment] 2017-07-31 14:44
Dunno probably one of the recent changes to alerts.c.

**Comment by nicm** [comment] 2017-07-31 14:45
This might fix it but YMMV

**Closed** 2017-08-01 10:43 UTC
