### ISSUE TITLE
Zoomed panes of non-attached windows are not redrawn on terminal emulator resize

### ISSUE THREAD

**Issue by facadeproof** [tmux/tmux#2252] opened 2020-05-31 23:55 UTC
### Issue description
Getting an identical behaviour to #2237 in zoomed-in panes. To better visualize it, here's a short screencast.

![video](https://0x0.st/ifFP.gif)

Note that window status where there is a maximized pane are shown with icon `↕`.

### Required information

Please provide the following information:

* tmux version: `tmux next-3.2`
* Platform: `Linux unknown`
* $TERM inside and outside of tmux: `xterm-kitty`

**Comment by rmo20** [comment] 2020-06-01 18:24
Same problem 

![image](https://s7.gifyu.com/images/2020_06_01__13_13_36.gif)

with the same version

```
$ tmux -V
tmux next-3.2
```

**Comment by nicm** [comment] 2020-06-02 11:42
I can't reproduce by following your instructions:

1 - `tmux -Ltest kill-server; tmux -Ltest -f/dev/null new`
2 - create/split to have three windows: w0 with 2 panes (emacs and shell), w1 with 1 pane (shell), w2 with 2 panes (emacs and shell);
3 - zoom emacs in both w0 and w2;
4 - select w0 then `C-b c` to create window w3;
5 - select w1 and w2.

Both windows 1 and 2 look perfectly normal to me and are just as I left them.

**Comment by nicm** [comment] 2020-06-02 11:55
Well that wasn't quite right - w0 should have onepane and w1,w2 two panes each, but it is the same.

**Comment by facadeproof** [comment] 2020-06-02 15:55
I think in order to reproduce you'd need to open a non-tmux w3, at least that's what triggers it for me

**Comment by nicm** [comment] 2020-06-02 19:13
Do you mean resize the terminal containing tmux?

**Comment by facadeproof** [comment] 2020-06-02 20:28
You could try it, in my case I'm using `bspwm` to launch new windows and by default it resizes the previous windows.

**Comment by nicm** [comment] 2020-06-02 20:56
You all need to explain what you are doing more clearly instead of making videos where it is impossible to tell what is going on...

**Comment by nicm** [comment] 2020-06-02 20:58
I cannot make tmux not redraw properly even if I resize the terminal while a zoomed window is not the current window.

**Comment by facadeproof** [comment] 2020-06-02 22:30
Sorry for being unclear, I thought mentioning the other issue would suffice. The following is what I do to reproduce:
1. Have a running tmux session in one terminal emulator window with one window `w1` with one non-zoomed pane and another window `w2` with two non-zoomed-panes.
2. Go to `w2` and zoom in any of the two panes.
3. Return to `w1`
3. Open a new terminal emulator through a hotkey **without** a running tmux session
4. Close the just-opened terminal emulator through a hotkey
5. Go back to the window with the terminal emulator running a tmux session
6. Go back to `w2`. This yields a non-redrawn zoomed pane.

**Comment by rmo20** [comment] 2020-06-02 22:35
The title "Zoomed panes of non-attached windows of the attached session are not redrawn when the size of the terminal emulator has changed" could describe the issue better.

**Comment by lukas-reineke** [comment] 2020-06-04 14:11
this happens to me with single terminal emulator, just by switching tmux sessions.

I'm in a session with 1 window, 2 panes. One is zoomed.
Switch to a different session.
Switch back to the first session, pane is still zoomed, but only half gets drawn. (the half the pane would be in when not zoomed)

**Comment by nicm** [comment] 2020-06-04 15:54
Can you try this please and see if it fixes the problem, or adds any new ones? [tmux-layout-resize.diff.txt](https://github.com/tmux/tmux/files/4731221/tmux-layout-resize.diff.txt)

**Comment by lukas-reineke** [comment] 2020-06-05 02:05
still same behavior with the patch for me.

**Comment by lukas-reineke** [comment] 2020-06-05 03:11
I did some more testing.
It has nothing to do with the tmux config, it still happens with an empty config.
I tried different terminal emulators, all behave the same.
It does not happen for normal terminal output. eg. `ls` is redrawn fine over the whole screen. But it does happen fur TUI programs like `htop` or `vim`
It only happens for horizontal splits. Zooming on a vertical split works fine.
The part of the window that is redrawn is actually not related to where the split would be. Its always drawn from the top, but stops at the size the split would be.

**Comment by nicm** [comment] 2020-06-05 04:47
Your problem is not the same as the one in this issue.

**Comment by lukas-reineke** [comment] 2020-06-05 05:18
very possible, i don't know enough about tmux to tell. I thought they where at least related because in both cases a zoomed pane does not get redrawn fully.

should i open a new issue instead?

**Comment by nicm** [comment] 2020-06-05 05:19
You are not resizing though, so it is not the same thing. If you can reproduce with master then yes please open a new issue.

**Comment by nicm** [comment] 2020-06-05 13:06
I think this will also be fixed by https://github.com/tmux/tmux/commit/d919fa1ed0ea3b167ffc811abba26a2dbcd20631, however it would be good to test the patch I posted above as well since it will avoid unnecessary resizing.

**Comment by facadeproof** [comment] 2020-06-05 21:01
Just did a `git pull --rebase` and applied the patch with `git apply tmux-layout-resize.diff.txt` and the same behaviour occurs. I tried to print out logs with `tmux -vvvv` but no `tmux-server-XXXXX.log` is being output in my installation folder.

**Comment by nicm** [comment] 2020-06-05 21:05
If `-vv` is not creating a server log then you didn't completely kill tmux. Try `tmux kill-server`.

**Closed** 2020-06-11 09:54 UTC
