### ISSUE TITLE
menu items not operational with a mouse

### ISSUE THREAD

**Issue by mbm329** [tmux/tmux#2869] opened 2021-09-06 05:58 UTC
### Issue description
When right-clicking the pane, I get a menu, but am unable to select anything in the menu with the mouse.  I can only operate selection of menu-items by using the arrow and Enter keys.

`list-keys` shows the `MouseDown3Pane` is not passing the `-O` to `display-menu` and the menu is behaving as if it was (staying up).  Furthermore, left-clicking the menu item does nothing and right-clicking the menu or anywhere on screen pastes whatever is in the buffer.  And if that paste triggers an action character (like "h" for horizontal split) the action happens and the rest from the buffer is pasted into the command-line.

This same behavior goes for any other mouse-driven menus.

As the CHANGES file indicates, this behavior changed in 3.2; last working version was 3.1c.  I'm unable to produce _this functionality_ in any build since 3.2.

### Required information
Please include the output of:
uname -sp && tmux -V && echo $TERM
```
Linux x86_64
tmux next-3.3
tmux-256color
```
(compiled from master on 09/06/2021)

Your platform (Linux, OS X, or whatever).
CentOS Linux release 8.4.2105

A minimal tmux config, if you can't reproduce without a config.
```
set -g mouse on
```

Your terminal, and $TERM inside and outside of tmux.
PuTTY v0.76 (with _Default Settings_ profile)
`tmux-256color` (inside)
`xterm` (outside)

[tmux_logs_sshots.zip](https://github.com/tmux/tmux/files/7113549/tmux_logs_sshots.zip)

**Comment by nicm** [comment] 2021-09-06 06:17
Does this still happen in xterm or gnome-terminal or similar rather than putty?

**Comment by mbm329** [comment] 2021-09-06 06:58
Just launched xterm and behavior is as expected.  Right-clicking brings up menu and holding while selecting highlights items and releasing performs actions properly.

**Comment by nicm** [comment] 2021-09-06 07:09
It seems like putty either does not correctly support "ANY_EVENT" mouse mode. Are you sure it worked with tmux 3.1c?

If you do this inside tmux:
~~~~
printf '\033[?1006h\033[?1003h'
cat
~~~~
And move the mouse, do you see mouse sequences?

**Comment by nicm** [comment] 2021-09-06 07:14
It looks like putty does not support this, although it does have mode 1002 which may be enough. Does it work if you make this change:
~~~~
--- menu.c	13 Aug 2021 18:54:54 -0000	1.35
+++ menu.c	6 Sep 2021 07:13:38 -0000
@@ -381,7 +381,7 @@ menu_prepare(struct menu *menu, int flag
 		cmd_find_copy_state(&md->fs, fs);
 	screen_init(&md->s, menu->width + 4, menu->count + 2, 0);
 	if (~md->flags & MENU_NOMOUSE)
-		md->s.mode |= MODE_MOUSE_ALL;
+		md->s.mode |= MODE_MOUSE_BUTTON;
 	md->s.mode &= ~MODE_CURSOR;

 	md->px = px;

**Comment by mbm329** [comment] 2021-09-06 07:36
I tested it on the `3.1c` tag and it worked.  One thing to note was that my term inside tmux was `screen` there whereas in >=3.2 it was `tmux-256color`.

And yes, that patch fixed it.

**Comment by nicm** [comment] 2021-09-09 19:36
I accidentally committed this change but I didn't mean to, the problem is that using "button" mode breaks highlighting the menu items if you *do* use `-O`, for example:
~~~~
bind -n MouseDown1Pane menu -O a b c a b c
~~~~
I am going to do this to turn on both modes, and if putty does not work we will just need to accept it:
~~~~
@@ -381,7 +381,7 @@ menu_prepare(struct menu *menu, int flags, struct cmdq_item *item, u_int px,
                cmd_find_copy_state(&md->fs, fs);
        screen_init(&md->s, menu->width + 4, menu->count + 2, 0);
        if (~md->flags & MENU_NOMOUSE)
-               md->s.mode |= MODE_MOUSE_BUTTON;
+               md->s.mode |= (MODE_MOUSE_ALL|MODE_MOUSE_BUTTON);
        md->s.mode &= ~MODE_CURSOR;

        md->px = px;
~~~~

**Comment by mbm329** [comment] 2021-09-09 21:12
For the record, this fix appears to satisfy both xterm and PuTTY _without_ `-O`.

When using `-O`, and right-clicking the pane, if you hold the right-button down and drag, the items highlight (expected) and when released on an item, execute the action (expected).

However, when immediately releasing the right-button, the menu stays (expected), but neither left nor right button will activate an action on click of the menu item (**not expected**).  Using keystrokes, e.g., `v` for Vertical Split or arrow keys, do work (expected).

Thanks!

**Comment by nicm** [comment] 2021-09-09 22:55
Yeah with -O it expects the menu item to be highlighted (which needs the movement event over it). It could probably accept a click as well, I'll take a look.

**Comment by nicm** [comment] 2021-09-10 14:11
Does this make clicking on an item work with -O?

You can try `bind -n MouseDown1Pane menu -O a b c a b c`.
~~~
--- a/menu.c
+++ b/menu.c
@@ -222,7 +222,8 @@ menu_key_cb(struct client *c, void *data, struct key_event *event)
                                if (MOUSE_RELEASE(m->b))
                                        return (1);
                        } else {
-                               if (!MOUSE_RELEASE(m->b) &&
+                               if (MOUSE_BUTTONS(m->b) == 0 &&
+                                   !MOUSE_RELEASE(m->b) &&
                                    MOUSE_WHEEL(m->b) == 0 &&
                                    !MOUSE_DRAG(m->b))
                                        return (1);

**Comment by mbm329** [comment] 2021-09-11 03:56
That does not appear to work in PuTTY; same effect as before - menu appears, but no highlighting on mouse movement nor action on click.  xterm appears to still work as we would expect.

**Comment by nicm** [comment] 2021-09-11 07:03
OK I think I will leave it as it is for the moment then. Thanks!

**Closed by nicm** 2021-09-11 07:03 UTC
