### ISSUE TITLE
resize-pane on top panes off by one

### ISSUE THREAD

**Issue by jaclu** [tmux/tmux#3050] opened 2022-01-30 20:36 UTC
### Issue description

I have this in my .tmux.conf

bind -N "Set pane size" S command-prompt -p "Pane width","Pane height (add 1 for top panes)"   "resize-pane -x %1 -y %2"

For top panes I have to give a height one larger than the intended, for non-top panes, the size is set correctly.

### Required information

Please provide the following information:

* tmux version: 3.2a
* Platforms: Darwin i386, Linux x86_64, iSH (gives Linux unknown for uname -sp :)
* $TERM inside and outside of tmux: xterm-256color / screen-256color (I use iTerm2)

**Comment by nicm** [comment] 2022-02-03 07:30
Does this still happen if you build tmux from master?

**Comment by jaclu** [comment] 2022-02-03 08:40
It works correctly in versions 1.8 - 2.2
This off by one was introduced in 2.3
in 3.3-rc  it has gotten much worse, resize-pane will resize the pane but not seem to care at all about the requested size regardless if it is a top pane or other location.

I have never built tmux from source, but if you have, this test takes like 5 seconds :) Not meant to be unhelpful, but I don't have any meaningful build environ at the moment.

**Comment by jaclu** [comment] 2022-02-03 08:53
I decided to give it a go, one issue and one failure with the README build instructions
1) "To build and install tmux from a release tarball, use:"
This goes directly to ./configure and forgets to mention you have to run automake, I could find it via google, but why not mention it since you write it like a step-by-step guide?

2) having the listed dependencies automake fails with:

configure.ac: error: required file 'etc/ylwrap' not found
configure.ac:   'automake --add-missing' can install 'ylwrap'

A quick google didn't give me any pointers, perhaps you can?

**Comment by jaclu** [comment] 2022-02-03 09:02
Oops my bad, I focused on the "From release tarball" instruction steps, totally missing the following "From version control"
its building I will get back once I can test it

**Comment by jaclu** [comment] 2022-02-03 09:06
Ok tested with current master, it has improved since 3.3-rc
so now it is back into the old broken state that has been the case since vers 2.3 Any pane touching the top border is off by one, requesting 80x24 results in 80x23

**Comment by nicm** [comment] 2022-02-03 09:06
Of course I tested it and it is fine for me.

**Comment by jaclu** [comment] 2022-02-03 09:06
i hope i didnt come of rude, that was not my intent

**Comment by jaclu** [comment] 2022-02-03 09:07
i just built it and the issue remains on both linux and MacOS at least for me

**Comment by jaclu** [comment] 2022-02-03 09:08
I am using iTerm2, since it has some terminal issues with tmux, could that be related? Will try the Apple terminal

**Comment by nicm** [comment] 2022-02-03 09:10
~~~~
$ cat ~/x.sh
tmux -Ltest new -d \; splitw
tmux -Ltest lsp \; resizep -t'{top}' -y 10 \; lsp
tmux -Ltest kill-server
$ sh x.sh
~~~~
0: [80x12] [history 0/100000, 384 bytes] %0
1: [80x11] [history 0/100000, 552 bytes] %1 (active)
0: [80x10] [history 0/100000, 320 bytes] %0
1: [80x13] [history 0/100000, 616 bytes] %1 (active)
~~~~
Note after resize, pane 0 is 80x10 - so the height is correct.

It is also correct if I use your key binding to do the same.

**Comment by jaclu** [comment] 2022-02-03 09:12
The issue is the same in Apple Term, so doesn't seem to be iTerm related

**Comment by nicm** [comment] 2022-02-03 09:13
Show server log from reproducing on master please (kill tmux, start with -vv, reproduce once, then exit).

**Comment by jaclu** [comment] 2022-02-03 09:14
I dont doubt it works for you, that is often the case, two people getting different results when bug chasing

I don't think the keybinding is related I have tried it as a standalone cmd `tmux resize-pane -x 80 -y 24` with same result

**Comment by jaclu** [comment] 2022-02-03 09:21
[tmux-client-3986325.log](https://github.com/tmux/tmux/files/7993221/tmux-client-3986325.log)
[tmux-out-3986327.log](https://github.com/tmux/tmux/files/7993222/tmux-out-3986327.log)
[tmux-server-3986327.log](https://github.com/tmux/tmux/files/7993223/tmux-server-3986327.log)

**Comment by nicm** [comment] 2022-02-03 10:11
You have changed `pane-border-status` set to `top` which would have been helpful to include in your steps to reproduce.

**Comment by jaclu** [comment] 2022-02-03 10:14
Sorry if that complicated things, I set that style up years ago to have tmux as kind of my text-mode windows handler, and since all other envs have window (or in tmux terms pane) labels on top, so it seemed only the natural thing to do.

**Comment by jaclu** [comment] 2022-02-03 10:15
ok not all, but the vast majority

**Comment by nicm** [comment] 2022-02-03 10:24
OK, well the problem is that since the status line for the top pane doesn't exist at all when it is off - unlike for "middle" panes where the border line does exist even without a status line - it is included as part of the pane's size, but `resize-pane` doesn't know this will happen so you end up with one line less than you asked for.

The simplest thing to do is just to account for this and adjust the size in `resize-pane`. Please try this diff against master: [x.diff.txt](https://github.com/tmux/tmux/files/7993645/x.diff.txt)

You can apply it with `patch -p1 <x.diff.txt` then rebuild/reinstall tmux.

**Comment by jaclu** [comment] 2022-02-03 10:37
Will try. Btw not insinuating that you are wrong in not putting the pane-border-status at the top or anything, but when I google tmux pane-border-status, all the mentions and screenshots I found talking about how to use it used top location, well one of them mentioned in passing that you can put it at the bottom, but then continues to show how to set it to top. So that leads me to believe that I am far from the only one doing it that way, and thus I'm curious as to why it surprised you, it seems like the majority of users do it that way.

**Comment by jaclu** [comment] 2022-02-03 10:41
I switched to set pane-border-status to bottom, the bug remains, the only change is that this makes panes touching the bottom edge of the window being off by one, so it seems pane border location only moves the problematic end of the window


Now I will check that patch

**Comment by nicm** [comment] 2022-02-03 10:42
The default is off, I am pretty sure most people leave it off, and if you are opening an issue you should preferably be either reproducing with the default config or showing the config you are using. See https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md#what-should-i-include-in-an-issue.

**Comment by jaclu** [comment] 2022-02-03 10:44
Am I doing something wrong?
 
```
/home/jaclu/git_repos/others/tmux
> patch -p1 < ~/x.diff.txt
can't find file to patch at input line 8
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|Index: cmd-resize-pane.c
|===================================================================
|RCS file: /cvs/src/usr.bin/tmux/cmd-resize-pane.c,v
|retrieving revision 1.51
|diff -u -p -r1.51 cmd-resize-pane.c
|--- cmd-resize-pane.c	21 Aug 2021 10:28:05 -0000	1.51
|+++ cmd-resize-pane.c	3 Feb 2022 10:20:27 -0000
--------------------------
File to patch:
```

**Comment by jaclu** [comment] 2022-02-03 10:56
Still running master version, without any tmux.conf both top and bottom level panes will get the assigned height. So the  bug should have been listed as "Pane height off by one when using pane-border-status top or bottom"

**Comment by nicm** [comment] 2022-02-03 10:57
Sorry try without -p1 `patch <x.diff.txt`?

**Comment by jaclu** [comment] 2022-02-03 10:58
that worked! Rebuilding...

**Comment by jaclu** [comment] 2022-02-03 11:02
That patch solved it, now pane size is correct both when using pane-border-status top & bottom!

Thx for solving it. Great work!

**Comment by nicm** [comment] 2022-02-03 11:06
Great, applied to OpenBSD now, will be in GitHub later when it syncs up. Thanks!

**Closed by nicm** 2022-02-03 11:06 UTC

**Comment by jaclu** [comment] 2022-02-03 11:08
Sorry if I caused you extra hassle by being clueless, not meant to be disrespectful, I deal far too much with clueless support tickets myself, so should deffo know better, I learned something today!

**Comment by nicm** [comment] 2022-02-03 11:10
It's OK, it's just quicker all round if everything is there up front.
