### ISSUE TITLE
High CPU usage when pressing n/N in search mode

### ISSUE THREAD

**Issue by balta2ar** [tmux/tmux#2258] opened 2020-06-04 13:44 UTC
This is a continuation of this issue: https://github.com/tmux/tmux/issues/2203. Copying from there:

I'm still experiencing significant performance regressions with search and navigation. I've just checkouted e71c5efd and recompiled.

My current tmux window shows the following when I enter scroll mode: (229 results) [4515/45261]
Two scenarios:
1. I search for something forward or backward direction and then I just press and hold `n` key without releasing. tmux instantly becomes unresponsive. When I release the key it takes several seconds for tmux to become responsive again. For comparison, I saved that buffer with 45261 lines into a file and tried searching in neovim -- it's always responsive and fast.
2. After I searched for something, I scroll the screen using arrows (up and down). Until the cursor is within the screen, performance of navigation is fine, but once the screen needs a redrawal, it gets suddenly worse. Just press and hold Up arrow, for example. It's important that you're in search mode -- otherwise scrolling is fast.

I used default search settings, which I believe use regexp engine now. I tried binding `?` and `/` to `-text` and `-incremental` but all of them are noticeably slow:
```
bind-key -T copy-mode-vi / command-prompt -i -p "search down" "send -X search-forward-text \"%%%\""
bind-key -T copy-mode-vi ? command-prompt -i -p "search up" "send -X search-backward-text \"%%%\""
```

### Required information

* tmux version (`tmux -V`): tmux next-3.2 (e71c5efd)
* Platform (`uname -sp`): Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`): screen-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`): omitted. I think the issue should be reproducible, but let me know whether these logs from my machine are paramount for the investigation.

**Comment by nicm** [comment] 2020-06-04 14:00
This is completely different from #2203 where the server was hanging completely.

What are you searching for?

**Comment by balta2ar** [comment] 2020-06-04 14:07
> What are you searching for?

Doesn't really matter: any text that can be found with multiple occurrences.

**Comment by nicm** [comment] 2020-06-04 14:17
Does it fix it if you reduce `WINDOW_COPY_SEARCH_ALL_TIMEOUT` in window-copy.c? Try 10 or 50.

**Comment by nicm** [comment] 2020-06-04 14:19
I expect the problem is that since you are holding down a key, you get a ton of key presses queued up during each timeout.

**Comment by nicm** [comment] 2020-06-04 14:20
Maybe once we repeat a search, we do not do let it repeat again for a short time and let any queued keys drain.

**Comment by nicm** [comment] 2020-06-04 14:48
Well, it is relatively easy to do this for repeating a search but incremental seach and repeating due to scrolling are a different matter.

I think there are a few things we can do:

- Repeating a search can refuse to repeat too fast.
- I don't think there is any point in doing a full search for scrolling, we might as well just search the visible terminal.
- Incremental search I think it will need to report incremental changes on a timer.

**Comment by nicm** [comment] 2020-06-04 14:59
Try this please which does the first two, although it needs some cleanup: [x.diff.txt](https://github.com/tmux/tmux/files/4730890/x.diff.txt)

**Comment by nicm** [comment] 2020-06-04 15:19
Here is another idea, as well as doing a visible-only search when the user scrolls, we can also do one if the search term hasn't changed and the search itself doesn't scroll: [y.diff.txt](https://github.com/tmux/tmux/files/4730992/y.diff.txt)

**Comment by balta2ar** [comment] 2020-06-04 20:03
Both patches give very promising results. I've tried to establish a little benchmarking framework so that it's not just my perception.

I used this to generate testing file that will fill up tmux history after tmux startup. After generation, it contains 100K lines:
```bash
python3 -c 'line = " ".join([str(x) for x in range(1000, 1021)])+"\n"; print(line*100000)' > /tmp/test.txt
```

I used two scripts to run benchmarks.
`tmux-setup.sh`
```bash
#!/bin/bash

# python3 -c 'line = " ".join([str(x) for x in range(1000, 1021)])+"\n"; print(line*100000)' > /tmp/test.txt
# wmctrl -lp | grep Tilix

wmctrl -ia 0x03400007
xdotool type 'time ~/.local/src/tmux/tmux'
xdotool key 'Return'
sleep 1
xdotool type 'cat /tmp/test.txt'
xdotool key 'Return'
sleep 1
xdotool key ctrl+t bracketleft
xdotool key shift+question
xdotool type '1010'
xdotool key 'Return'
```

`tmux-search.sh`:
```bash
#!/bin/bash

for x in `seq 30`; do
    xdotool key n
    #xdotool key Page_Up
done
xdotool key q
xdotool key ctrl+d
```

Numbers in the table below are taken from this command output: `xdotool type 'time ~/.local/src/tmux/tmux'`, e.g. it looked likes this: `~/.local/src/tmux/tmux  0.00s user 0.00s system 0% cpu 8.619 total`
Which includes tmux startup time, `cat /tmp/test.txt`, entering search mode, typing search query, pressing Enter, and pressing `n` or `Page_Up` depending on the test (I conducted two types of tests). I also provide baseline timing in case you want to subtract "warmup" time.

I used sleeps because xdotool is not synchronous, and sometimes keys are lost if not awaited processing. For this reason I'm not sure all the keys in "search" part of a test were processed, but still numbers are pretty demonstrative.

Below, when I write `master` I mean this commit: c8bddfb
| Source code | Test name | tmux execution time (5 runs) |
| --- | --- | --- |
| master | baseline, no searches, just setup | 2.532 2.588 2.535 2.540 2.540 |
| master | setup + 30 `n` keypresses | 14.612 14.624 14.614 14.603 14.592 |
| master + x.diff.txt | setup + 30 `n` keypresses | 3.030 2.811 2.853 2.849 2.870 |
| master + y.diff.txt | setup + 30 `n` keypresses | 2.911 2.928 2.931 2.926 2.896 |
| master | setup + 30 `Page_Up` keypresses | 8.619 8.617 8.596 8.596 8.613 |
| master + x.diff.txt | setup + 30 `Page_Up` keypresses | 2.895 2.893 2.905 2.867 2.965 |
| master + y.diff.txt | setup + 30 `Page_Up` keypresses | 2.911 2.942 2.902 2.899 2.904 |

**Comment by balta2ar** [comment] 2020-06-04 20:05
If you're interested, I can run other types of search tests, maybe with different configuration settings, e.g. normal search, regexp search, incremental search (in that case please write the exact tmux config that I should use for each test).

**Comment by nicm** [comment] 2020-06-04 20:16
Thanks. The way it works is that tmux will try to do a full search of the history to establish a match count, if this takes more than 200 milliseconds then it will give up and only search the visible text. Any gains to be made are by reducing the number of times that we need to do a full search, these diffs do that by assuming that if the search text has not changed (that is, if we are searching again just because of scrolling or repeating the search) then there is no point in doing a full search because the match count will not have changed.

**Comment by nicm** [comment] 2020-06-04 20:23
I already spent some time profiling regex searching (that is, how long a visible search takes or how much searching is done in 200 milliseconds) and without major changes to how searching works IIRC we are now largely at the mercy of the regex engine. If we could always do a visible-only search I don't think there would ever be a noticeable problem, but we need to do a full search sometime to get the match count (hence the 200 ms limit).

If you want to look at it further I would suggest using your tests with a profiling too. Very unusually, Apple have an excellent profiling tool if you have access to a macOS box. The equivalents on Linux are not quite so good but would probably work too.

**Comment by nicm** [comment] 2020-06-04 20:23
I already spent some time profiling regex searching (that is, how long a visible search takes or how much searching is done in 200 milliseconds) and without major changes to how searching works IIRC we are now largely at the mercy of the regex engine. If we could always do a visible-only search I don't think there would ever be a noticeable problem, but we need to do a full search sometime to get the match count (hence the 200 ms limit).

If you want to look at it further I would suggest using your tests with a profiling too. Very unusually, Apple have an excellent profiling tool if you have access to a macOS box. The equivalents on Linux are not quite so good but would probably work too.

**Comment by nicm** [comment] 2020-06-04 20:42
I have applied this change with some tweaks and cleanup to OpenBSD now, it will be in GitHub later. Please let me know if you see any problems or any other slow cases.

**Comment by balta2ar** [comment] 2020-06-04 20:59
Unfortunately, I have access only to a Linux machine. Sure, more fine-tuned profiling is great if you need to find the exact bottleneck, but here I merely wanted to compare changes on a use-case high-level basis.

On top of these tests I've been running the search manually (sorry, no numbers, just my feelings). Page_Up/Down is pretty comfortable in terms of speed now. Moving cursor with arrow keys (up & down) and flipping pages (screens) is also good.

`n` & `N` are, however, a bit more delayed. I see a spike of delay when I press and hold `n`, and then currently found word reaches the last element on the screen and the screen has to be flipped (redrawn). Also, cursor travels/moves noticeably slower with `n` compared to just up/down arrows. This seems unreasonable when another search result is very close to the current one, e.g. when I search for "1010" backwards and press `n` on a screen like below. The next result is literally next line.

```
1000 1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015 1016 1017 1018 1019 1020        
1000 1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015 1016 1017 1018 1019 1020        
1000 1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015 1016 1017 1018 1019 1020
```

CPU usage, though, is fine, it doesn't spike. Overall, sure it's better than before, but this `n` search gives uncomfortable user experience. Please don't get me wrong, I'm not trying to be deliberately picky here, I'm trying to point out strange behavior where it is reasonable to expect normal behavior.

To give you a feeling of the difference, I've tried to record two gifs. On the first one I search for "1010" and I move cursor with Up arrow. Notice the rate of change of the current line (top-right). (by the way, it indicates 0 results -- does it mean search timed out?)

![tmux-arrows](https://user-images.githubusercontent.com/340676/83809199-59daed80-a6b6-11ea-814f-a383a6e8ed01.gif)

And now the same buffer, same search query but now I move cursor with `n`. The rate of changes is significantly slower while it probably shouldn't be:

![tmux-next-search-occurence](https://user-images.githubusercontent.com/340676/83809288-79721600-a6b6-11ea-902f-fd8fe72f264b.gif)

Maybe it indicates some other issues.

**Comment by balta2ar** [comment] 2020-06-04 21:09
> hence the 200 ms limit

I think it would be nice to have it configurable (I don't know whether it is or it is not) and if I understand this limit correctly, I'd want to set it lower, maybe 50ms. In this whole search story I feel like I can easily trade accuracy of the number of search results for responsiveness. For me it's fine if the search times out and I don't get the accurate number of occurrences (e.g. having a status line "5000+ results" is fine, which will mean that "I've been searching for 200ms and found at least 5000 entries, but there may be more"), it's much more important that tmux is snappy and gives instant, blazing-fast response.

**Comment by nicm** [comment] 2020-06-04 21:29
Repeating the search does not wait for 200 ms because it uses the same search string, since we don't do a full search with repeat anymore we probably don't need to rate limit repeats so much, or maybe not at all. Try changing `WINDOW_COPY_SEARCH_REPEAT` to 1 and see if you can make tmux stop responding by holding down `n`, if you can then increase the value until you can't and see what number you get.

**Comment by nicm** [comment] 2020-06-04 21:48
For me it seems fine as it is even with key repeat set the fastest it can be, but perhaps either your key repeat is faster or your computer is slower or both...

**Comment by nicm** [comment] 2020-06-04 21:50
You shouldn't see "0 results", that seems like a bug.

**Comment by balta2ar** [comment] 2020-06-04 22:02
My computer should be pretty ok but you're totally right about the key rate. Comparing to regular setups my repeat rate is 2-3 times faster. If you have access to a Linux machine, you can try my rate (copy from my configuration):
```
xset r 66
# xset r rate 200 100
# xset r rate 150 150
# xset r rate 170 130
# This was my default for a long time
#xset r rate 170 120
# 200.250 are good for typing but too slow for actual use
#xset r rate 250 120
xset r rate 200 120
```
I'll try changing the constant tomorrow.

**Comment by nicm** [comment] 2020-06-04 22:13
1/120 is ~8 milliseconds so setting WINDOW_COPY_SEARCH_REPEAT to anything much below 10 you might find you can still build up a big backlog of keys for tmux to work through if you hold it down for a long time. But I suspect if may mean holding down the key for longer than realistically anyone will actually do - I don't really care if you have to wait for a few seconds for tmux to catch up after you hold `n` for 10+ seconds. If it isn't a problem in normal use now, we can remove the timeout, searching just the visible text is pretty fast.

**Comment by balta2ar** [comment] 2020-06-05 06:06
I tried setting WINDOW_COPY_SEARCH_REPEAT to 10, 5 and 1. 1 was most comfortable and it did build up a queue of keys, tmux was still responsive after I released `n` (this is of course only a single machine and a single use-case).

> If it isn't a problem in normal use now

It's hard to say in advance, I'll need to live with that for a while and see how it goes.

By the way, why is there a slight delay when I cross over the screen when searching with `n`?

**Comment by nicm** [comment] 2020-06-05 07:44
I don't think many other people will have a key repeat this fast so I'm going to remove the limit on how fast we can process `n`. If you find it is a problem then we can add it back, but you will have to choose between tmux limiting how fast it will process `n` so it can't build up a queue of keys, or living with a delay when you release `n` - I don't see any other choice.

I don't see any difference in time when a search moves off the screen and has to scroll.

**Comment by balta2ar** [comment] 2020-06-05 07:48
> I don't see any difference in time when a search moves off the screen and has to scroll

I'm trying search on a different machine and I can't reproduce it either. Must be something local to my home machine. Let's leave it.

**Comment by nicm** [comment] 2020-06-05 09:36
OK I am going to close this, let me know if you still see any problems.

**Closed by nicm** 2020-06-05 09:36 UTC
