### ISSUE TITLE
substitution of quotes in expansion

### ISSUE THREAD

**Issue by unphased** [tmux/tmux#1449] opened 2018-08-23 04:11 UTC
I have a bind that looks like this: 

```
bind -n C-j if-shell "discriminator '#{pane_title}' '#{pane_current_command}' '#{pane_pid}' C-j '#{window_panes}' '#{window_zoomed_flag}'" "select-pane -D" "send-keys C-j"
```

The problem that this encounters is if the `pane_current_command` contains single-quotes (e.g. it is `ssh user@host 'complex single quoted command'`), it messes up the argument parsing of my `discriminator` program. 

I attempted to modify this binding to something like this to try to leverage the substitution feature as described in `FORMATS` in the manpage: 

```
bind -n C-j if-shell "discriminator '#{pane_title}' '#{s/'/"/:pane_current_command}' '#{pane_pid}' C-j '#{window_panes}' '#{window_zoomed_flag}'" "select-pane -D" "send-keys C-j"
```

However this binding is not accepted/parsed by tmux, whether or not I prepend that single-quote with one or two backslashes. Indeed I suspect that I cannot be using any escapes. This is definitely going to be tricky.

I wonder if there is a way to deal with this somehow. Am open to creative hacks.

**Comment by unphased** [comment] 2018-08-23 04:17
Sorry, the pane_title is the variable that I'm actually in need of munging.

**Comment by unphased** [comment] 2018-08-23 04:47
No, my last message was simply incorrect. It just reverses the problem.

**Comment by unphased** [comment] 2018-08-23 05:49
I'm trying to figure out if [this](https://unix.stackexchange.com/a/23349/12497) could be leveraged here somehow. But can't think of how.

**Comment by nicm** [comment] 2018-08-23 07:39
There is no automatic way to escape special characters when expanding #{}, although it has been mooted before and now it would not be particularly hard to implement.

In the meantime, you will need to get the title inside the script:

bind -n C-j if '/path/to/myscript #{pane_id}' ...

Then in your script do something like:

title=$(tmux display -pt$1 '#{pane_title}')

**Comment by nicm** [comment] 2018-08-23 08:41
Alternatively, please try this 
[x.diff.txt](https://github.com/tmux/tmux/files/2313620/x.diff.txt)

Then try #{q:pane_title} as the argument eg if "sh myscript #{q:pane_title}" ...

**Comment by nicm** [comment] 2018-08-23 08:55
Or this has all the shell special characters: [y.diff.txt](https://github.com/tmux/tmux/files/2313677/y.diff.txt)

**Comment by unphased** [comment] 2018-08-24 22:26
OK, I've been testing y.diff.txt, thanks for that. 

However some behavior is a bit confusing: 

```
24 18:24 ~/util ❯❯❯ tmux display-message -p "#{q:pane_title}"                                           
tmux\ display-message\ -p\ \"\#{q:pane_title}\"
24 18:24 ~/util ❯❯❯ tmux display-message -p "#{q:pane_title}'"                                          
tmux\ display-message\ -p\ \"\#{q:pane_title}\'\"'
24 18:24 ~/util ❯❯❯ tmux display-message -p "#{q:pane_title}\'"                                         
tmux\ display-message\ -p\ \"\#{q:pane_title}\\\\\'\"\'
24 18:26 ~/util ❯❯❯ tmux display-message -p '#{q:pane_title}'                                 
tmux\ display-message\ -p\ \'\#{q:pane_title}\'
24 18:26 ~/util ❯❯❯ tmux display-message -p '#{q:pane_title}"'                             
tmux\ display-message\ -p\ \'\#{q:pane_title}\"\'"

```

spurious quote seems to get added at the end. also backslashes seem to get blown out to more copies than make sense to me.

**Comment by nicm** [comment] 2018-08-24 22:36
This output means nothing to me, 
please show me one example that doesn't work together with what is actually in pane_title when printed without q:.

**Comment by unphased** [comment] 2018-08-24 23:26
I think the issue here is evidenced by 

```
$ tmux display-message -p '\''
>
```

where it is a parse failure for the shell. Consistent with what is seen above. 

In shell we cannot have an escaped single quote in a single quoted string... I reckon this will function as intended once I swap the quotes again as I did up near the OP.

**Comment by unphased** [comment] 2018-08-24 23:28
What would your guidance be on the `q` flag for the expansion? Is it reasonable at all to have this be such a hardcoded expansion that targets shell? The shell will be different on different environments too. /bin/sh could be many different shells on different systems.

**Comment by nicm** [comment] 2018-08-25 08:49
POSIX specifies the /bin/sh special characters, so they are the same no matter what implementation /bin/sh is (see http://pubs.opengroup.org/onlinepubs/009604499/utilities/xcu_chap02.html).

However, I think actually it is a bit silly to escape them all, we should escape only those needed for using the value inside one of " or '. The problem is that when using ", some things are context-dependent, for example:
~~~~
$ echo "$"
$
$ echo "$x"

$ echo "\$x"
$x
~~~~
So if we are to escape suitable for single quotes, we need to escape " and \ and `, but only escape $ if it is followed by a valid variable name character. I wonder if there some existing free (acceptably licensed) code that does this already, maybe in OpenSSH or somewhere...

**Comment by nicm** [comment] 2018-08-25 08:50
(We can't realistically escape for ', because there is no way to escape ' itself inside 's, so it needs to be ".)

**Comment by unphased** [comment] 2018-08-25 15:25
Well, as you mention, targeting `"` is complex due to context sensitivity. 

I feel like we can absolutely target `'`, we just need to escape them by inserting `'\''` instead of just a single backslash. This should avoid all the `$` shenanigans, I think

**Comment by nicm** [comment] 2018-08-25 15:30
I think " is much more useful.

**Comment by unphased** [comment] 2018-08-25 15:32
Orthogonal to this, do you think it’s worth having an analogue to if-shell which directly spawns a program rather than a shell? This would allow us to sidestep the shell’s string syntax intricacies and enhance performance and security

**Comment by krader1961** [comment] 2018-08-25 15:53
FWIW, the fish `string escape` command side-steps the quirks of escaping single and double quotes by backslash escaping both types of quote chars plus spaces and other meta chars. For example,

```
$ string escape "'a\" b \$;'c"
\'a\"\ b\ \$\;\'c
```

It's verbose and not pretty but it is a straightforward solution to the problem.

**Comment by nicm** [comment] 2018-08-25 16:13
Yes this is what my last diff does. I'm actually thinking it is OK now:

~~~~
$ cat x.sh
echo $1
$ tmux set @xyz 'abc$ foo$xx[]'
$ tmux run "sh x.sh #{q:@xyz}"
abc$ foo$xx[]
$
~~~~
So you need to use no quotes, but it works.

**Comment by nicm** [comment] 2018-08-25 16:18
@unphased that would be OK for run-shell where there is one argument and it could use -- like new-window etc but not for if-shell where tmux would have to split the argument and then there is the same issue with escaping spaces.

**Comment by unphased** [comment] 2018-08-25 16:59
Ah, this is a clever development. It feels "dangerous", but as far as I can tell it should be correct!

I also like that it makes the `q:` remain a simple and easily understood transformation.

**Comment by unphased** [comment] 2018-08-25 17:01
@nicm I'd love it if you could comment on the question of something like `if-fork` in addition to `if-shell` so we can spawn and predicate on the return value of an independent program, so that we can skip the shell processing. If you think that'd be a good idea i'll work on a PR

**Comment by nicm** [comment] 2018-08-25 17:02
No new commands please, but if you can do it as an extension to if-shell and run-shell then go for it.

**Comment by unphased** [comment] 2018-08-25 17:07
OK, the concern would be that it's explicitly to avoid spawning a shell and seems wrong to be under it

**Comment by nicm** [comment] 2018-08-25 17:14
We're not adding two new commands just to avoid a minor problem with the names. You can add command-alias entries if you care about it.

It shouldn't be too hard to do this but you will need to at least do this:

- add a variant form of job_run that takes an argv/argc and uses execvp - it would be best not to copy the whole thing, add a common function or something;
- it will need to set PATH etc and call cmd_copy_argv, take a look at window_pane_spawn;
- change run-shell and if-shell to accept any number of arguments (max = -1) like new-window;
- if some flag is set (dunno, '-N' for no shell?), then use execvp instead of execl.

It would be nice to automatically detect this like neww and new do (eg if there is >1 argument then use execvp) but I think it is impractical for if-shell because the "false" argument is optional so there is no way to tell if "if-shell a b c" means if-shell "/bin/sh a" "b" "c" or if-shell "a b" "c".

**Comment by nicm** [comment] 2018-08-26 09:29
I have applied the q: change to OpenBSD now, it will be in GitHub later. Thanks!

**Closed by nicm** 2018-08-26 09:29 UTC

**Comment by unphased** [comment] 2018-08-27 19:28
Thank you!
