### ISSUE TITLE
Symbols not showing up inside tmux 

### ISSUE THREAD

**Issue by cHoco** [tmux/tmux#328] opened 2016-03-10 22:23 UTC
Hi, not sure when started but some symbols don't show up inside tmux (work well outside and on 2.1)

Steps to reproduce:
`
printf '\u2b06\n'
`
It doesn't print anything inside, prints upper arrow outside

Here's the log output: https://gist.github.com/ef5f65c4979090727d3f

**Comment by jasonij** [comment] 2016-03-11 02:34
Seeing this too with Neomake symbols not showing up; fine outside of tmux.

**Comment by nicm** [comment] 2016-03-16 10:39
Apparently this character is not valid on your platform. Try this diff

[x.txt](https://github.com/tmux/tmux/files/175737/x.txt)

and show me the same log (only the server one is needed) and we can see which function is failing.

**Comment by cHoco** [comment] 2016-03-16 11:12
Here's the new log: https://gist.github.com/930238fddf14ee02be1e

**Comment by nicm** [comment] 2016-03-16 11:16
Although mbtowc() correctly converts UTF-8 into Unicode for 2b06, wcwidth() returns -1 so tmux cannot correctly draw the character. This is a problem with your system locale implementation.

**Comment by cHoco** [comment] 2016-03-16 12:00
Since all OS X versions seems to be affected, do you plan on using a non-system provided `wcwidth()` implementation on mac in the mean time? At least until Apple fixes this :(

**Comment by nicm** [comment] 2016-03-16 12:26
I don't think so, the point of using system wcwidth() is to avoid having to carry around UTF-8 information in tmux itself.

**Comment by nicm** [comment] 2016-03-19 08:47
If you can come up with a (semi)complete list of the symbols OS X gets wrong, perhaps we can have an error correction table. But I don't think I want to add just one table.

Or maybe Apple have an update? Have you opened a bug report with them?

**Comment by nicm** [comment] 2016-03-19 08:47
Er, add a table just for one symbol.

**Comment by nicm** [comment] 2016-03-19 08:57
You should be able to use this test program: [test2b06.c.txt](https://github.com/tmux/tmux/files/180731/test2b06.c.txt)

**Comment by cHoco** [comment] 2016-03-19 21:15
Yeah I submitted a bug report, and was waiting for the response before writing here again.
I did already test what characters `wcwidth` didn't support and it seems every character after `U+2B00` (included) returns `-1` :disappointed:

**Comment by nicm** [comment] 2016-03-22 09:13
It looks to me like 2b06 has been around since Unicode 4.0, so I guess Apple have just screwed up their tables. I am going to close this but please comment anyway if you get a fix.

**Closed by nicm** 2016-03-22 09:13 UTC

**Comment by deiwin** [comment] 2016-03-31 13:24
Any ideas for a workaround while waiting for OS X fix?

**Comment by cHoco** [comment] 2016-04-04 15:52
I haven't even received a confirmation of the bug report, so I wouldn't hope for a quick fix. Personally I'm using the `wcwidth` function provided by this library https://github.com/JuliaLang/utf8proc as a drop-in replacement.

**Comment by deiwin** [comment] 2016-04-04 17:26
I guess I'll do that as well. Thanks.

For anyone else happening onto this, this is the diff that I'm using (note that I'm not really using it as a drop-in replacement, because that broke my powerline-ish shell theme. So I'm just doing some error correction instead and this seems to work fine):
```diff
diff --git a/utf8.c b/utf8.c
index c040757..01d0402 100644
--- a/utf8.c
+++ b/utf8.c
@@ -21,6 +21,7 @@
 #include <stdlib.h>
 #include <string.h>
 #include <wchar.h>
+#include <utf8proc.h>
 
 #include "tmux.h"
 
@@ -115,6 +116,11 @@ utf8_width(wchar_t wc)
 	int	width;
 
 	width = wcwidth(wc);
+	if (width < 0) {
+		int confirmation_width = utf8proc_charwidth(wc);
+		if (confirmation_width > 0)
+			width = confirmation_width;
+	}
 	if (width < 0 || width > 0xff)
 		return (-1);
 	return (width);
```

And this is the diff of my `tmux.rb` brew formula:
```diff
diff --git a/Library/Formula/tmux.rb b/Library/Formula/tmux.rb
index 9922c5c..8700372 100644
--- a/Library/Formula/tmux.rb
+++ b/Library/Formula/tmux.rb
@@ -39,11 +39,15 @@ class Tmux < Formula
 
   depends_on "pkg-config" => :build
   depends_on "libevent"
+  depends_on "utf8proc"
+
+  patch :DATA
 
   def install
     system "sh", "autogen.sh" if build.head?
 
     ENV.append "LDFLAGS", "-lresolv"
+    ENV.append "LDFLAGS", "-lutf8proc"
     system "./configure", "--disable-dependency-tracking",
                           "--prefix=#{prefix}",
                           "--sysconfdir=#{etc}"
@@ -68,3 +72,30 @@ class Tmux < Formula
     system "#{bin}/tmux", "-V"
   end
 end
+
+__END__
+diff --git a/utf8.c b/utf8.c
+index c040757..01d0402 100644
+--- a/utf8.c
++++ b/utf8.c
+@@ -21,6 +21,7 @@
+ #include <stdlib.h>
+ #include <string.h>
+ #include <wchar.h>
++#include <utf8proc.h>
+ 
+ #include "tmux.h"
+ 
+@@ -115,6 +116,11 @@ utf8_width(wchar_t wc)
+ 	int	width;
+ 
+ 	width = wcwidth(wc);
++	if (width < 0) {
++		int confirmation_width = utf8proc_charwidth(wc);
++		if (confirmation_width > 0)
++			width = confirmation_width;
++	}
+ 	if (width < 0 || width > 0xff)
+ 		return (-1);
+ 	return (width);
+
```

**Comment by bruno-** [comment] 2016-04-11 14:45
@cHoco can you please paste a link to where is this bug opened with Apple se we can see if there's progress.

@deiwin thank you for the detailed explanation how to get it working. What's the chance the diff above would be accepted by homebrew for the official tmux formula?

**Comment by deiwin** [comment] 2016-04-11 14:48
> What's the chance the diff above would be accepted by homebrew for the official tmux formula?

Not sure. You can try opening an issue for them and pushing for this, linking here.

**Comment by cHoco** [comment] 2016-04-11 14:54
@bruno- Unfortunately it isn't possible because Apple doesn't use a public issue tracker, issues are "private" to a user, and if another user reports the same issue the new one is closed as duplicate of the other issue, without letting you track the original one. (yeah it's pretty shitty...) The good thing is that since I was probably the first to report the issue, my submission wasn't closed as duplicated, so if there's any news I will be able to report here immediately.

**Comment by deiwin** [comment] 2016-04-12 07:58
@bruno-, [looks like](https://github.com/Homebrew/homebrew-core/pull/240#issuecomment-208761283) this won't be accepted into the official homebrew tmux formula unless there's some indication that it'll get merged into upstream, i.e. the tmux project, eventually.

@nicm, do you think you'd be willing to accept something like the patch above into the project? If yes, I can open a PR and we can continue the discussion there.

**Comment by nicm** [comment] 2016-04-12 08:04
Possibly but it is not ok to change utf8.c, it will need to go in compat/ and have some configure magic to enable it (for example, add BROKEN_WCWIDTH, like BROKEN_CMSG_FIRSTHDR).

**Comment by deiwin** [comment] 2016-05-04 09:46
@nicm, can you confirm that https://github.com/tmux/tmux/commit/65e4c57d3a554940ed5cada6dfeff403ae8d9572 took care of this issue?

**Comment by nicm** [comment] 2016-05-04 10:11
It might. I don't use OS X.

**Comment by nicm** [comment] 2016-05-04 10:12
It was intended to anyway :_).

**Comment by Atcold** [comment] 2016-09-30 21:11
I'm having a similar issue, and I'm not sure I understood how to solve it.
This is a snippet from a file I'm editing
```lua
       <E2><8E><A7>  1, if x >  1
f(x) = <E2><8E><A8> -1, if x < -1
       <E2><8E><A9>  x, otherwise
```
which `cat`s just fine as
```lua
       ⎧  1, if x >  1
f(x) = ⎨ -1, if x < -1
       ⎩  x, otherwise
```
But, in `tmux`, I see
```lua
       _  1, if x >  1
f(x) = _ -1, if x < -1
       _  x, otherwise
```

**Comment by Atcold** [comment] 2016-09-30 23:30
Hmm... On my Mac that I have home everything looks just fine, and they share the same configuration. Can anyone suggest what could have been gone wrong?

Thank you.

**Comment by cHoco** [comment] 2016-10-01 17:30
I haven't had this issue anymore. Is it a fresh installation? If not have
you restarted the tmux server after upgrading?
And finally have you tried the new option --enable-utf8proc when building?
It's not included in homebrew so either have to edit the formula or build
by hand.
Also is it possible that the font configured in the machine doesn't have
that character?
-- 
Enrico Ghirardi

**Comment by Atcold** [comment] 2016-10-05 21:38
Just removed and reinstalled `tmux` via `brew`. *unicode* characters are not shown properly.
I'm trying now the other points you mentioned.

**Comment by nicm** [comment] 2016-10-05 21:52
If you are seeing _ instead of UTF-8 then you are not telling tmux that the terminal supports UTF-8, either with LANG/LC_ALL or -u.

**Comment by Atcold** [comment] 2016-10-06 04:57
> with LANG/LC_ALL or -u

Where exactly?

**Comment by Atcold** [comment] 2016-10-06 14:49
Yay! That worked.
```
$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```
and after
```
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8
```
`tmux` is correctly visualising the unicode. I'm wondering where these two `export`s are performed on the older machine. Were they set by default and later on removed, in newer versions of MacOS?
How would someone know to set these two environmental variables?
