### ISSUE TITLE
random crashes

### ISSUE THREAD

**Issue by JESii** [tmux/tmux#1313] opened 2018-04-14 13:43 UTC
**description**: tmux is randomly, but regularly crashing during my normal workflow. Only happens after a long time (1-2 days) running. Things will be working fine and then I return to a terminal window which had tmux running, the screen looks as if tmux is there, but there's a `[lost server]` message and I'm back to a native terminal window. 

I've tried to identify some cause/effect relationship but been unable to do so because of the long time between failures.

I've also updated to the latest HEAD through brew several times with the same result. I'll try building from the latest git master but don't have high hopes for that.

I'm hoping that the logs will provide some clues as to the issue and/or some things for me to try -- working without my usual configs for a day or two would be challenging to say the least...

Thanks.

**tmux version**: HEAD-336beeb, installed through brew
**system**:  macOS 10.12.6
**$TERM** (inside and outside tmux): xterm-256color
**uname -sp && tmux -V && echo $TERM**: 
Darwin i386
tmux master
xterm-256color
**running iTerm2**: Build 3.1.5
**config & logs**: https://snippets.cacher.io/snippet/af9f9724ec06515e8428

[tmux-client-6481.log](https://github.com/tmux/tmux/files/1911219/tmux-client-6481.log)
[tmux-client-8519.log](https://github.com/tmux/tmux/files/1911220/tmux-client-8519.log)
[tmux-server-6513-part1.log](https://github.com/tmux/tmux/files/1911239/tmux-server-6513-part1.log)
[First 5000 lines of the server log; 27Meg]
[tmux-out-6513.log](https://github.com/tmux/tmux/files/1911222/tmux-out-6513.log)

bash version/settings: In case it makes any difference, I'm using brew's bash:
`GNU bash, version 4.4.19(1)-release (x86_64-apple-darwin16.7.0)`
and have modified my default shell with `chsh` to point to that version.
**screenshot** 
<img width="1440" alt="2018-04-14_0549_tmux-lost-server" src="https://user-images.githubusercontent.com/486/38768864-ceb1b420-3fae-11e8-9cde-8ead74343499.png">

**Comment by nicm** [comment] 2018-04-14 19:29
I can't view these logs, please attach them to the issue.

**Comment by JESii** [comment] 2018-04-14 22:17
@nicm done

**Comment by nicm** [comment] 2018-04-14 23:25
Please show the entire log file, it should compress well.

**Comment by nicm** [comment] 2018-04-14 23:26
Entire server log file.

Or the last few 1000 lines would do for a start actually.

**Comment by JESii** [comment] 2018-04-16 12:50
OK; I'll get the last 25000 lines; the entire file is too big to attach.

[tmux-server-6513.part-aj.log](https://github.com/tmux/tmux/files/1915298/tmux-server-6513.part-aj.log)

**Comment by JESii** [comment] 2018-04-16 12:56
FWIW, I have other server & client logs from previous crashes if that would help. Thanks much!

**Comment by nicm** [comment] 2018-04-16 14:47
Please make sure you are running master, 336beeb is almost a year old.

If you can still reproduce please do two things:

- apply this diff [x.diff.txt](https://github.com/tmux/tmux/files/1915797/x.diff.txt) and reproduce and show me the server log;

- see if tmux generates a core file, you may need to do "ulimit -c unlimited" in the shell before starting tmux for the first time (make sure it is not running at all); if it does then load the core into gdb with something like gdb $(which tmux) /path/to/core then do "bt full" and show me the output.

**Comment by JESii** [comment] 2018-04-16 15:22
Will do; thanks...

**Comment by JESii** [comment] 2018-04-19 20:31
So far, so good. Moving to a newer machine at work so will keep the logs on in case there are other issues.

**Comment by nicm** [comment] 2018-04-23 09:41
OK please comment again if you still have problems.

**Comment by JESii** [comment] 2018-04-23 16:44
Yep; just crashed again Friday; sorry I couldn't post sooner. So I'll apply the diff you suggested and see what happens.

**Comment by nicm** [comment] 2018-04-23 16:47
I've already applied it, it just adds logging so if you rebuild from latest
master and generate the logs.

**Comment by JESii** [comment] 2018-04-30 15:45
OK; Another crash this morning around 8:30am, PDT; here are the logs:

[tmux-client-6433.log](https://github.com/tmux/tmux/files/1961201/tmux-client-6433.log)

[tmux-client-7772.log](https://github.com/tmux/tmux/files/1961204/tmux-client-7772.log)

Used `split` on the next two files as they were too large to post directly. These should be the last entries.

[tmux-out-6435.logaj.log](https://github.com/tmux/tmux/files/1961216/tmux-out-6435.logaj.log)

[tmux-server-6435.logbx.log](https://github.com/tmux/tmux/files/1961232/tmux-server-6435.logbx.log)

**Comment by nicm** [comment] 2018-04-30 16:03
The client log doesn't matter, please compress the server log with gzip and then post it, then you should be able to paste the entire thing.

**Comment by nicm** [comment] 2018-04-30 16:06
If it is still too big, please just do tail -10000 mylog>newfile instead of using split, then gzip the result. This doesn't look like the end of the log, or at least it doesn't match the previous error.

**Comment by nicm** [comment] 2018-04-30 20:11
OK that's weird because it is nothing like your previous log. Does tmux leave a core? You may need to run "ulimit -cunlimited" before you start it for the first time.

**Comment by JESii** [comment] 2018-05-01 16:46
You mean a core dump? Where would I find that>

**Comment by nicm** [comment] 2018-05-02 08:38
Yes a core file, normally it will be in the directory where you started tmux for the first time.

**Comment by JESii** [comment] 2018-05-03 16:01
Sorry for the delay; end of iteration and switching to a new machine.

Don't see anything like that; I looked in the directory where tmux is started (where the tmux logs are) and there's nothing there like `*cores*`. And I looked in the `/cores` directory and nothing there either.

**Comment by JESii** [comment] 2018-05-13 03:39
Sorry for the slow response; been spinning up that new machine and on different assignments; I expect I will be able to return to this next week. Thanks for your patience.

**Comment by BEFH** [comment] 2018-05-17 16:13
I've been having the same issues on my work cluster login nodes. They're on CentOS 6. I've had the issue with multiple versions of tmux including the latest release (2.7). I thought it was due to a problem with the cluster, but maybe not.

There are no core dumps.

**Comment by BEFH** [comment] 2018-05-23 17:57
Yes

**Comment by nicm** [comment] 2018-05-23 18:00
Please show your logs as well Bryan.

**Comment by nicm** [comment] 2018-06-03 10:20
Please try master now and let me know with all the usual information if you continue to see this and I will reopen the issue.

**Closed by nicm** 2018-06-03 10:20 UTC

**Comment by JESii** [comment] 2018-06-04 00:52
Will do; thanks.

**Comment by BEFH** [comment] 2018-06-08 01:10
I compiled Master and turned on logging, and I've just had another crash. The server log is 16 GB, though.

**Comment by nicm** [comment] 2018-06-08 06:29
Show me the first and last 10000 lines?

**Comment by nicm** [comment] 2018-06-08 20:42
This link doesn't work.

**Comment by BEFH** [comment] 2018-06-08 23:37
Sorry. I accidentally made it one-time-use.

https://file.io/whdjhH should work.

**Comment by nicm** [comment] 2018-06-09 07:46
Doesn't show anything useful, at least no fatal errors, so it must be crashing, please try to get a core file and then get a backtrace from that.
