### ISSUE TITLE
Feature request: interpret ANSI escape codes in the 'show-buffer' view

### ISSUE THREAD

**Issue by hariseldon78** [tmux/tmux#3401] opened 2022-12-01 15:00 UTC
tmux version: 3.3a
Platform: Linux
$TERM: tmux-256color

I tried capturing a pane to a buffer with 'capture-pane -e -S 22000', but when I want to display it with 'show-buffer' all the escape codes are printed as is, instead of being used to display color. So the only way to see the colors seems to be saving the buffer to a file and using 'less -R'.

It would be handy to be able to read the buffer and do some searches with colors activated.

**Comment by nicm** [comment] 2022-12-06 14:31
Try this please: [showb.diff.txt](https://github.com/tmux/tmux/files/10167302/showb.diff.txt)

**Comment by bfrg** [comment] 2022-12-06 15:20
I think the line with `#include <vis.h>` needs to be removed. It gives me a compile error because the file doesn't exist. When I remove it, it compiles and seems to work as intended.

**Comment by nicm** [comment] 2022-12-07 09:44
Applied to OpenBSD now, will be in GitHub later. Thanks!

**Closed by nicm** 2022-12-07 09:44 UTC

**Comment by jmeurin** [comment] 2023-01-03 19:18
This seems to break https://github.com/RTBHOUSE/tmux-picker, as it now shows the escape codes instead of highlighting:

`
cmd-kill-session.o     cmd-show-prompt-history.c  \033[30m\033[48;5;202m\033[1ms\033[m\017\033[30m\033[43m\033[1mdoc2\033[m\017man.awk       tty.o
`

It works at 1536b7e2 and fails at 70ff8cfe.

tmux-picker uses `swap-pane` (https://github.com/RTBHOUSE/tmux-picker/blob/master/hint_mode.sh#L48), I'm guessing that could be the issue?

tmux version: top of tree (70ff8cf)
Platform: Linux
$TERM: tmux-256color

Thanks.
