### ISSUE TITLE
searching is broken

### ISSUE THREAD

**Issue by benoit-pierre** [tmux/tmux#3864] opened 2024-02-29 12:40 UTC
### Issue description

43e5e80343185e69a1b864fc48095ede0b898180 broke search for wrapped lines: when the pattern occurs before the wrap, it's correctly highlighted, but ignored by the search.

Example, execute the following command:
```bash
▸ a=haystack b=needle; for n in $(seq 5); do printf '%*s%*s%*s\n' $((COLUMNS/2)) $a $((COLUMNS/2)) $b $((COLUMNS/2)) $a; echo; t=$a a=$b b=$t; done
```
Then try a backward search for `needle`: on lines that wrap, matches that occur before the wrap are ignored (even if correctly highlighted).

Reverting 43e5e80343185e69a1b864fc48095ede0b898180 fix the issue.

### Required information

* tmux version: `3.4`.
* Platform: Arch Linux.
* `$TERM` inside and outside of tmux: `tmux-256color` / `alacritty`.

**Comment by yan12125** [comment] 2024-03-02 05:44
Thank you for the investigation! I also get fully-working search back after reverting that commit.

As a short-term workaround, I propose to revert that commit in Arch Linux package: https://gitlab.archlinux.org/archlinux/packaging/packages/tmux/-/issues/2

**Comment by moralground** [comment] 2024-03-18 18:02
@ThomasAdam @nicm Any update on this?

**Comment by ThomasAdam** [comment] 2024-03-18 18:03
@moralground -- No, and like all other issues, patience is a virtue.  When there's an update, you'll know.

**Comment by yan12125** [comment] 2024-04-16 15:28
I took a look, and it seems 43e5e80343185e69a1b864fc48095ede0b898180 is not doing as intended.

In `window_copy_search_jump` function, grid lines with the flag `GRID_LINE_WRAPPED` are skipped. In a wrapped line, all grid lines other than the last one have this flag, so only the last grid line is passed to `window_copy_search_rl_regex` or a similar function. As a result, only the last grid line is searched.

I assume the intention was to passing the first grid line to `window_copy_search_rl_regex` or a similar function, so that the inner loop will search from the first grid line to the end of a wrapped line. I'm not sure how to fix it, as I didn't find a special flag to identify the first grid line.

**Comment by nicm** [comment] 2024-05-14 09:33
Yes, this was intended to skip lines that are already being visited as part of a wrapped line. So it needs to skip all wrapped lines except the first instead of skipping all but the last. I don't have time to get this to work as intended so I have reverted this part of the change for the moment. This will be in GitHub later on.

**Closed by nicm** 2024-05-14 09:33 UTC
