### ISSUE TITLE
[bug] capture-pane -S / -E does not work in >=3.3 with ubuntu > 18

### ISSUE THREAD

**Issue by rockandska** [tmux/tmux#3425] opened 2023-01-06 17:17 UTC
Hi,

Before posting I create a reproducible case to let people see the difference depending on :
- the version
- the ubuntu version used

You could try the reproducible case (docker required) with :
```
$ git clone -b tmux/capture-pane-bug https://github.com/rockandska/repro-issues.git /tmp/tmux_issue
$ cd /tmp/tmux_issue
/tmp/tmux_issue $ ./run-test.sh
```

If needed, you could run `DEBUG=1 ./run-test.sh` instead to increase verbosity (see docker images creations, set -x in for tests log )

The script test `capture-pane -S` /  `capture-pane -E` with a matrix of :

- tmux
  - 3.2
  - 3.2a
  - 3.3
  - 3.3a
  - master
- ubuntu
  - 18.04
  - 22.04
  - 24.04

It should print something similar to
```
ubuntu:18.04 in use
Building docker image : test-tmux:ubuntu_18_04
sha256:b503eeae1a589886dcd8b42c7966203ee930f6d18368d4bdd8f1dedb18a26da7
Starting container test-tmux-ubuntu_18_04
370cd7267de041cb0c9c670f4ccd03e1d74e208e39f16d1a4aabc2d7fa718a4d

Starting test with version 3.2
3.2 and test-tmux:ubuntu_18_04 -> OK (status: 0)
Log: /tmp/tmux_issue/tmp/cache/test-tmux-ubuntu_18_04/log-3.2

Starting test with version 3.2a
3.2a and test-tmux:ubuntu_18_04 -> OK (status: 0)
Log: /tmp/tmux_issue/tmp/cache/test-tmux-ubuntu_18_04/log-3.2a

Starting test with version 3.3
3.3 and test-tmux:ubuntu_18_04 -> OK (status: 0)
Log: /tmp/tmux_issue/tmp/cache/test-tmux-ubuntu_18_04/log-3.3

Starting test with version 3.3a
3.3a and test-tmux:ubuntu_18_04 -> OK (status: 0)
Log: /tmp/tmux_issue/tmp/cache/test-tmux-ubuntu_18_04/log-3.3a

Starting test with version master
master and test-tmux:ubuntu_18_04 -> ERR (status: 1)
Log: /tmp/tmux_issue/tmp/cache/test-tmux-ubuntu_18_04/log-master
....
```

The home of the docker user will be cached in `$PWD/tmp/cache/test-tmux-ubuntu_XX_XX`
The containers are not deleted after a run to be able to analyze.

To summarize :

|              | 3.2 | 3.2a | 3.3 | 3.3a | master |
|--------------|-----|------|-----|------|--------|
| Ubuntu 18.04 | OK  | OK   | OK  | OK   | NOK    |
| Ubuntu 20.04 | OK  | OK   | NOK   | NOK    | NOK       |
| Ubuntu 22.04 | OK  | OK   | NOK   | NOK    |  NOK      |

So it seems, there is something in the build dependencies who change how `capture-pane` behave since it works in 18.04 but not after

Not took the time to add bisect to the test case to find the culprit but it will be easy to do I think

The last update in `master` seems to totally avoid negative arguments for `-S` / `-E`
```
 /tmp/tmux_issue $ tail /tmp/tmux_issue/tmp/cache/test-tmux-ubuntu_18_04/log-master
Sending "tput clear" C-m
Comparing expected vs output
----------------------------
$								$
----------------------------
Comparing expected vs output with -S -2
----------------------------
command capture-pane: unknown flag -2			      |	$ printf '%s'
							      >	$ tput clear
							      >	$

```

In the others cases, it prints not all the expected lines
```
/tmp/tmux_issue $ tail /tmp/tmux_issue/tmp/cache/test-tmux-ubuntu_20_04/log-3.3a
Sending "tput clear" C-m
Comparing expected vs output
----------------------------
$								$
----------------------------
Comparing expected vs output with -S -2
----------------------------
							      >	$ printf '%s'
							      >	$ tput clear
$								$
```

Regards,

**Comment by nicm** [comment] 2023-01-06 17:31
Please attach the test script to this issue.

**Comment by rockandska** [comment] 2023-01-06 17:44
It is already in the issue with a procedure

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nicm** [comment] 2023-01-06 17:46
I already looked in your repo and I can't see it.

**Comment by nicm** [comment] 2023-01-06 18:04
OK GitHub did not list the branch for some reason.

It is not clear to me exactly what is failing here. You have three `capture-pane` commands. Which one is the problem? All of them?

I tried the same commands in your script and do not see any problems on macOS or OpenBSD. I do not have any Linux boxes at the moment.

Can you please show me a stripped down script with just the two or three tmux commands necessary to reproduce, so we can be sure we are both doing the same thing? Also please show two files with the bad and good output and preferably the corresponding tmux server logs (run tmux with `-vv`).

**Comment by nicm** [comment] 2023-01-06 18:13
I wonder if this is related to https://github.com/tmux/tmux/commit/9cc8e40aa08ff91bc1c5d0211c1d2cef02f2c7a2. I can't remember when the original change was made that this commit reverted but these are the only recent `capture-pane` changes I can remember. Although it seems unlikely the same version would behave differently...

**Comment by rockandska** [comment] 2023-01-06 18:18
> It is not clear to me exactly what is failing here. You have three capture-pane commands. Which one is the problem? All of them?

The capture pane with `-S -2` and I'm sure it will be the same for `-E -`

> I tried the same commands in your script and do not see any problems on macOS or OpenBSD. I do not have any Linux boxes at the moment.

Not possible to create a VM to run completely the reproducible case and have all the logs needed directly ?

> Can you please show me a stripped down script with just the two or three tmux commands necessary to reproduce, so we can be sure we are both doing the same thing? Also please show two files with the bad and good output and preferably the corresponding tmux server logs (run tmux with -vv).

I will in a few hours

> I wonder if this is related to https://github.com/tmux/tmux/commit/9cc8e40aa08ff91bc1c5d0211c1d2cef02f2c7a2. I can't remember when the original change was made that this commit reverted but these are the only recent capture-pane changes I can remember. Although it seems unlikely the same version would behave differently...

Too recent, the bug seems to appeared after 3.2a and will try a `git bisect` to point the culprit

**Comment by nicm** [comment] 2023-01-06 18:26
I tried this and variations and I get exactly what I expect:
~~~~
tmux -Ltest kill-server
tmux -Ltest new -d \; run -d1 \; send "printf '%s'" C-m
tmux -Ltest capturep -pS-2
~~~~
Perhaps I am missing something you are doing however.

I'll take another look when you can confirm script and show actual/expected output.

Thanks

**Comment by nicm** [comment] 2023-01-06 18:45
I wonder if the problem is that you are using `tput clear` which IIRC changed sometime in the last few years to send `E3` which clears the history. Are you using a `TERM` inside tmux which has `E3` (check with `infocmp`)? Does it make any difference if you use `clear -x` instead?

**Comment by nicm** [comment] 2023-01-06 19:30
You will get `E3` by default for `TERM=tmux` since ncurses 6.0 patch 20180121 and since tmux 3.3 we will use `TERM=tmux` by default if it exists on the build system.

I suspect perhaps Ubuntu moved to ncurses 6.1 after version 18.4 - or didn't upgrade their terminfo so there was no `tmux` - which is why the 3.3 behaviour is unchanged. And older tmux versions still use `TERM=screen` so `clear` does not send `E3`.

I'm not sure why master would be different on Ubuntu 18 however...

In any case, if you want to reliably reach into the history after `clear`, you will need to use `clear -x` or `tput -x clear`.

**Comment by nicm** [comment] 2023-01-06 19:36
There was also a fix to`clear` (by me, that I'd forgotten until now) in ncurses 6.1 patch 20180804 which may be why Ubuntu 18.4 works even if they did move to ncurses 6.1 by then.

For the record, `-x` was added in ncurses 6.0 patch 20170819, `clear` started sending `E3` in ncurses 5.9 patch 20130622 and `tput clear` started sending it as well in ncurses 6.0 patch 20161022.

Anyway, that's enough hoking through ncurses, let's see if using `clear -x` fixes your problem...

**Comment by rockandska** [comment] 2023-01-07 00:10
> Anyway, that's enough hoking through ncurses, let's see if using clear -x fixes your problem...

It solved almost all the problems, well done !

But `master` is still broken and not related to this issue

Running `tmux capture-pane -p -S -2` fail with `command capture-pane: unknown flag -2`

**Comment by systemmonkey42** [comment] 2023-01-07 23:51
I've just hit this as well.  I have a macro which which calls

     tmux capture-pane -J -e -S - -E - -p -t %7

for example, and it now returns

    command capture-pane: too many arguments (need at most 0)

Simply typing `tmux capture-pane -S -` also fails.

**Comment by nicm** [comment] 2023-01-08 22:17
Try this please: 
[z.diff.txt](https://github.com/tmux/tmux/files/10369636/z.diff.txt)

**Comment by systemmonkey42** [comment] 2023-01-08 22:24
No, go..

I get the same error:

       tmux capture-pane -S -
       command capture-pane: too many arguments (need at most 0)

```
1673216453.297903 client started (2846231): version next-3.4, socket /tmp/tmux-0/default, protocol 8
1673216453.297914 on Linux 5.15.0-57-generic #63~20.04.1-Ubuntu SMP Wed Nov 30 13:40:16 UTC 2022
1673216453.297918 using libevent 2.1.11-stable (poll); ncurses 6.2
1673216453.297925 flags are 0x10000
1673216453.297927 socket is /tmp/tmux-0/default
1673216453.297933 trying connect
1673216453.297974 add peer 0x55d056dc8e40: 6 ((nil))
1673216453.298741 cmd_pack_argv: argv[0]=capture-pane
1673216453.298744 cmd_pack_argv: argv[1]=-S
1673216453.298745 cmd_pack_argv: argv[2]=-
1673216453.298749 client loop enter
1673216453.299005 peer 0x55d056dc8e40 message 303
1673216453.299008 open write file 2 -
1673216453.299015 write check file 2
1673216453.299069 peer 0x55d056dc8e40 message 304
1673216453.299071 write 58 to file 2
1673216453.299073 peer 0x55d056dc8e40 message 203
1673216453.299074 file 2 58 bytes left
1673216453.299084 write check file 2
1673216453.299085 client loop exit
```

**Comment by nicm** [comment] 2023-01-08 22:57
Are you sure you restarted tmux entirely and ran your newly built binary?

**Comment by systemmonkey42** [comment] 2023-01-08 23:33
> Are you sure you restarted tmux entirely and ran your newly built binary?

So, apparently I didn't do this.  AFter restarting tmux properly, it is now working.

Thanks

**Comment by nicm** [comment] 2023-01-08 23:35
Great, applied now, will be in GitHub later on. Thanks!

**Closed by nicm** 2023-01-08 23:35 UTC
