### ISSUE TITLE
Erratic behavior when exiting copy-mode

### ISSUE THREAD

**Issue by ajh17** [tmux/tmux#1454] opened 2018-08-29 01:57 UTC
Hi, I'm running tmux master (18b611b at the time of this writing) and I'm noticing a curious issue when I exit copy mode. 

When I enter copy mode and select some lines using visual selection, and then hit Escape, tmux will either exit copy mode and leave a line visually selected, as shown below:

<img width="902" alt="screen shot 2018-08-28 at 18 44 05" src="https://user-images.githubusercontent.com/1159146/44760309-16bc1580-aaf3-11e8-83ab-222fd631a633.png">

or it will continue copy mode and I can't cancel the selection unless I exit out of copy-mode entirely. This is shown in the screenshot below where the upper right denotes that 0/6 lines are selected but you can see there's many more:

<img width="902" alt="screen shot 2018-08-28 at 18 44 13" src="https://user-images.githubusercontent.com/1159146/44760354-4d922b80-aaf3-11e8-9df6-5e4182ba57a5.png">

When reporting issues:

Please also include:

- Platform: Mac
- No tmux config file is required to reproduce this issue
- Terminal: iTerm and Terminal both exhibit this issue.
- TERM outside tmux: xterm-256color
- TERM inside tmux: screen OR screen-256color (both exhibit this issue)

Output of `uname -sp && tmux -V && echo $TERM`:

Darwin i386
tmux master
xterm-256color

I'm compiling tmux with:

`./configure --disable-debug --prefix=/Users/ajh/build`

Logs:

[tmux-server-32166.log](https://github.com/tmux/tmux/files/2330409/tmux-server-32166.log)
[tmux-out-32166.log](https://github.com/tmux/tmux/files/2330410/tmux-out-32166.log)
[tmux-client-32164.log](https://github.com/tmux/tmux/files/2330411/tmux-client-32164.log)

**Comment by ajh17** [comment] 2018-08-29 02:07
I can confirm that I am not able to reproduce when compiled at commit 8a81993a (tag 2.7).

I *am* able to reproduce it on commit aa6e6fa0 (tag 2.8-rc) and on 18b611b (master).

I haven't ran a bisect yet, but I'll update once I have done so.

**Comment by nicm** [comment] 2018-08-29 10:55
This still happens without a config?

**Comment by ajh17** [comment] 2018-08-29 17:27
@nicm: Yes it does. v2.7 doesn’t exhibit this behavior with or without any tmux.conf file, but I can always reproduce it from v2.8 onwards with, or without any tmux.conf.

**Comment by nicm** [comment] 2018-08-29 17:30
I can't reproduce, please tell me exactly what keys you are pressing to reproduce, starting with:

VISUAL=vim tmux -Ltest -f/dev/null new

**Comment by ajh17** [comment] 2018-08-29 18:11
@nicm: Here are my key presses:

1. cat ~/.vimrc
2. Ctrl+b [
3. k V k k k k
4. Escape

After step 4 is when I see the issue described. Basically, all I’m doing is entering copy mode, selecting some lines and then clearing the selection by hitting Escape. After I hit Escape though, I see that one line of selection doesn’t clear properly (as seen in the attached screenshot above —notice the cursor location and the selected line) or that I can’t seem to clear the selection at all despite pressing Escape multiple times.

Again, this is reproducible in all the terminals I’ve tried (namely Terminal.app, kitty, iTerm), with any TERM set.

Oh and I’m running macOS 10.13.5.

**Comment by ajh17** [comment] 2018-08-29 18:41
@nicm: Yep! That seems to have fixed it. Thank you!

**Comment by nicm** [comment] 2018-08-29 18:54
Great - applied to OpenBSD now, will be in GitHub later. Thanks!

**Closed by nicm** 2018-08-29 18:54 UTC
