### ISSUE TITLE
Initial pane isn't receiving focus event, after 'set-hook -g pane-focus-in' command.

### ISSUE THREAD

**Issue by vbauerster** [tmux/tmux#2966] opened 2021-11-02 12:42 UTC
* tmux version (`tmux -V`): tmux next-3.4 (7d330c19e822c09164264eebfddad32bb1194a6d)
* Platform (`uname -sp`): Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`): inside `tmux-256color`, outside `xterm-256color`

To reproduce:
```
$ tmux splitw
$ tmux set-hook -g pane-focus-in 'set -p window-style bg=red'
$ exit # expected bg change inside initial pane, but it didn't
$ tmux neww # bg changed
```

[![asciicast](https://asciinema.org/a/I4WZc9zgyJaVH77S0HTeaEEPn.svg)](https://asciinema.org/a/I4WZc9zgyJaVH77S0HTeaEEPn)

If above commands are entered inside `tmux 3.2a`, bg changes instantly inside initial pane after `exit` command.

Related: https://github.com/tmux/tmux/issues/2880#issuecomment-953254426

**Comment by reportaman** [comment] 2021-11-22 07:59
Tmux's hooks currently have more precise meaning, and there are hooks to cover both cases: 1) if focus of pane changed (``pane-focus-in``), 2) if pane exited (``pane-exited``), 3) idk there might be more. Depending on what you want to do, you can assign this behavior to both or just ``pane-exited`` hook.

 So, this should work:
```bash
$ tmux splitw
$ tmux set-hook -g pane-exited 'set -p window-style bg=red'
$ exit
```

**Comment by systemmonkey42** [comment] 2021-12-02 00:13
Hi I came for a similar reason,  With tmux 'focus-events on', tmux issues focus events to terminal applications both on pane changes, and when the terminal itself receives/loses focu.

However, if I close a pane, resulting in the active pane changing, the newly activated pane doesn't get focus events.

@reportaman 

I'm not sure *how* a pane gets focus is relevent here.  TMUX used to do this.

Any time TMUX returns focus to the pane running my application, it should get a focus notification, regardless if it was because of a command, hotkey, mouse-click, or the current pane being closed.

Currently I have to click away from my terminal, then click back into my terminal to ensure the pane gets the focus event it wants.

@nicm  - Should I start a separate thread for focus events rather than hooks?  I believe its the same issue.

**Comment by reportaman** [comment] 2021-12-02 00:28
@systemmonkey42 Did you try the 2nd listing in my comment? It would resolve the problem faced by the author of this ticket. There is no "receiver" of these events, are you saying if you have an app like nvim/vim running in the final pane and that it doesn't trigger its FocusGained autocommand??

**Comment by systemmonkey42** [comment] 2021-12-02 00:31
@reportaman No.  I'm not using or interested in pane-focus events, just application notifications (yes, like vim, but not vim). As I said it used to work as expected, and hasn't since I upgraded to a more recent build.

**Comment by systemmonkey42** [comment] 2021-12-02 00:50
Ignoring specific applications, a super simple test is to run (in your shell);
```
echo $'\e[?1004h';cat -v
```
Now as you move focus into and away from the pane, you will see `^[[I` and `^[[O` escape codes being displayed.

When you "split" the pane, you see `^[[O` as focus moves to the new pane.  When you exit the new pane, focus returns to the original pane without printing anything.

If you revert change 2bb0b9d6 and repeat the test, you will see `^[[I` displayed as the focus returns to the original pane after closing the second.

You can then disable notifications with;
```
echo $'\e[?1004l'
```

**Comment by reportaman** [comment] 2021-12-02 03:14
I confirm this is reproducible. I tried this: exit a pane such that the focus moves to a pane with nvim. It does not trigger the FocusGained autocommand, surprisingly it does not even trigger FocusLost autocommand when focus is then moved outside of nvim for the first time.

**Comment by vbauerster** [comment] 2021-12-02 10:43
> Did you try the 2nd listing in my comment? It would resolve the problem faced by the author of this ticket.

Actually I've discovered broken behavior in external application `kakoune`, which I suppose relies on focus events. I'm not interested in changing background of a pane, those commands with bg change were provided with sole purpose to reproduce the problem without any external application like vim, nvim or kak.

Here is broken behavior in kakoune editor (top bar color suppose to change on receiving focus):

https://user-images.githubusercontent.com/2206533/144406278-fd3d98d3-6fc7-4638-af3d-90566e62204f.mp4

And here is how it was in tmux 3.2a:

https://user-images.githubusercontent.com/2206533/144406642-35d3d13b-1bfa-4ada-8277-b26ab4e97ca8.mp4

**Comment by systemmonkey42** [comment] 2021-12-03 21:47
> surprisingly it does not even trigger FocusLost autocommand when focus is then moved outside of nvim for the first time.

I've never seen this.  Any chance you have found a bug in nvim?

Use the 
```
echo $'\e[?1004h';cat -v
```
and verify that
(a) - a focus event is triggerred immediately when you echo the control characters, (You should see `^[[I`)
and 
(b), the first focus lost event is triggered when you change focus (you should see `^[[O`).

If you don't get (a), that would be the reason, and that is a bug in your terminal.
If you see (a) and (b), but neovim doesn't react then its a neovim bug.

It might be worth testing the behaviour inside and outside tmux as well.

**Comment by nicm** [comment] 2022-02-03 07:39
I've made this change:
~~~~
Index: window.c
===================================================================
--- window.c    7 Oct 2021 07:52:13 -0000       1.277
+++ window.c    3 Feb 2022 07:38:17 -0000       1.278
@@ -754,6 +754,7 @@ window_lost_pane(struct window *w, struc
                if (w->active != NULL) {
                        w->active->flags |= PANE_CHANGED;
                        notify_window("window-pane-changed", w);
+                       window_update_focus(w);
                }
        } else if (wp == w->last)
                w->last = NULL;
~~~~
Which seems to fix this for me, please try this again after it syncs to GitHub and let me know if this is still a problem. Thanks!

**Closed by nicm** 2022-02-03 07:39 UTC

**Comment by vbauerster** [comment] 2022-02-03 09:18
I confirm this patch fixes the issue.
