### ISSUE TITLE
Some race condition messes up nvim buffer when restoring a tmux session

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2981] opened 2021-11-21 01:04 UTC
### Issue description

This might not turn out to be a tmux issue per se, but you would be the best to answer.

While using tmux-resurrect, if one of panes being restored has ``nvim <filename>``, the opened nvim buffer is messed up (as you will see in the comparison videos below). Among other symptoms that occur, the one that occurs the most is: the lines in tmux buffer are off by 1, and user cannot scroll up to first line of the file. If one is to close nvim, and run the command ``nvim <filename>`` manually in the same pane again, the problem does not occur. It makes me think there is some kind of race condition that occurs when nvim is launching in one pane, and tmux is doing some of its own setup for pane, but I don't know for sure.

This behavior of nvim does not always happen on one of my machines, and seems to depend on the size of terminal & phase of the moon. Luckily it happens all the time on my other machine when tmux status line is enabled and does not if its disabled, so it was easy to produce the log files.

Log files, and videos: I have two set of log files and related videos. 

1. With problem: (if status line is enabled)

Log files:
[withstatus.zip](https://github.com/tmux/tmux/files/7575593/withstatus.zip)

Video:

https://user-images.githubusercontent.com/71736629/142745313-95cb0450-5443-49f3-8e6d-b50caa144581.mp4

2. Without problem: (if status line is disabled)

Log files: 
[withoutstatus.zip](https://github.com/tmux/tmux/files/7575594/withoutstatus.zip)

Video:

https://user-images.githubusercontent.com/71736629/142745318-e4f21c32-fab1-405d-a61b-a36d5ea8b3a8.mp4

### Required information

Please provide the following information:

* tmux version: tmux next-3.4.
* Platform: Darwin arm64.
* $TERM: xterm-256color outside, tmux-256color inside.
* Logs (attached above).

**Comment by bfrg** [comment] 2021-11-22 23:49
I don't use tmux-resurrect myself but I had a similar issue with vim in the past. I solved it by setting the correct width (with `-x`) and height (with `-y`) in `new-session`. This seems to be necessary when creating detached sessions.

It looks like [tmux-resurrect](https://github.com/tmux-plugins/tmux-resurrect/blob/6be2f34b5f06c8a6a23dc3dc835e69c132d58a18/scripts/restore.sh#L149-L151) doesn't set the width or height.

FWIW, this is what my tmux session scripts look like (very simplified):
```bash
#!/bin/sh

# $1 = lines, $2 = columns (don't quote the sub-command!)
# shellcheck disable=SC2046
set -- $(stty size)

# Create new session 'test-session' with two windows
tmux new-session -d -x "$2" -y "$1" -s 'test-session' -n 'testwin'  \; send-keys 'vim main.c' 'C-m'
tmux new-window -n 'myproject' -c ~/path/to/some/project

# Go to first window
tmux select-window -t ':1'

# Open session
exec tmux attach-session -t '=test-session'
```

Instead of `set -- $(stty size)` you could also use `-x $(tput cols)` and `-y $(tput lines)` in `new-session`.

**Comment by reportaman** [comment] 2021-11-23 00:54
@bfrg I am already doing that, it does not work. I even tried modifying my local tmux resurrect to run ``set -- $(stty size)`` in every pane before it runs the command it runs in the pane. IMO it worked for you because you got lucky, in my testing the problem is is not easy to reproduce, and depends on many factors:

1. Size of terminal
2. Size and arrangement of panes
3. Pane in which nvim is launched
4. Pane in which cursor rests after restoration script completes
5. Phase of the moon (i.e its not always reproducible on one machine, is always on another if certain constant combination of 1-4)

One possibility, given it depends on the status bar being enabled at launch or not, is that when window arrangement is being restored, the appearance of status bar causes a redraw that interferes with nvim. Though I am shooting in the dark... Let's wait for @nicm's review.

**Comment by bfrg** [comment] 2021-11-23 01:15
> I even tried modifying my local tmux resurrect to run `set -- $(stty size)` in every pane before it runs the command in the panes.

I don't quite understand what the point is to run `set -- $(stty size)` in every pane. What exactly did you do?

`stty size` will print the number of lines and column in the current terminal window. When running `set -- foo bar`, `foo` will be assigned to `$1` and `bar` to `$2`. If you don't use `$1` or `$2` anywhere in the script, the `set -- $(stty size)` command is useless. Be careful when doing this in a function since you're modifying the positional parameters.

**Comment by reportaman** [comment] 2021-11-23 02:18
@bfrg Ok got it how that stty command works. I already was passing ``tput cols/rows`` while new session is created, it still didn't work. I changed the restore script of tmux-resurrect to have ``-x "$(tput cols)" -y "$(tput rows)" `` arguments for every new-session command, but still the same story.

**Comment by nicm** [comment] 2021-11-29 11:25
If you send SIGWINCH to the vim process after it has started instead of killing it and restarting it does it work out the right size?

Probably tmux is resizing a couple of times quickly and vim is notoriously bad at handling this.

**Comment by reportaman** [comment] 2021-11-29 19:37
@nicm Yes SIGWINCH resolves it!!! I tried this multiple times, and each time it gets fixed with SIGWINCH. What should be the next course of action?

**Comment by reportaman** [comment] 2021-11-30 05:30
As a workaround for now, I am detecting that a session is being created using tmux resurrect, and performing a 1 time operation ``killall -WINCH nvim`` in hooks ``client-session-changed``, and ``client-attached``. It seems to always work, though not sure if the solution is susceptible to another race (i.e. I am just feeling good because I am delaying the problem and it will occur again in future). Look forward to your review of that idea...

**Comment by nicm** [comment] 2021-12-01 09:33
Can you reproduce this without a .tmux.conf by writing a simple shell script that starts tmux running vim?

There is too much going on in your log to see anything.

This is almost certainly a problem with vim ignoring SIGWINCH but perhaps tmux can avoid resizing.

**Closed** 2021-12-21 14:58 UTC
