### ISSUE TITLE
Tmux `run-shell`/`if-shell` is slow for some computers.

### ISSUE THREAD

**Issue by Xeite** [tmux/tmux#2306] opened 2020-07-13 08:31 UTC
### Issue description

This issue is directly related to #1603, and my observations was exactly same. I used `vim-tmux-navigator` and when I changed to new machine, tmux pane switch suddenly slow down. 

What I found is that it's not only related to `if-shell` but also `run-shell`. Even simple `run-shell` command such as `tmux run-shell 'echo hello'` seems to be slow which takes 0.3 seconds at least.

I tried to find out the cause but now does not have any clues, so I really appreciate if you helps me how to find the corrections.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
tmux 3.1b

* Platform (`uname -sp`).
Darwin i386

* $TERM inside and outside of tmux (`echo $TERM`).
tmux-256color

* Logs from tmux (`tmux kill-server; tmux -vv new`).

```
tmux -vv run-shell 'echo hello'
```
or even noticeable with 
```
for _ in {1..100}; do tmux -vv run-shell 'echo hello'; done
```

Abbreviated Server log: https://pastebin.com/XGSBQ8QX
Abbreviated Client log:
```
....
1594628682.880626 sending message 106 to peer 0x10f1d0000 (0 bytes)
1594628682.880657 cmd_pack_argv: argv[0]=new
1594628682.880700 sending message 200 to peer 0x10f1d0000 (8 bytes)
1594628682.880739 client loop enter
1594628683.173368 peer 0x10f1d0000 message 207
1594628683.173413 sending message 208 to peer 0x10f1d0000 (0 bytes)

1594628691.968709 peer 0x10f1d0000 message 203
1594628691.968842 sending message 205 to peer 0x10f1d0000 (0 bytes)
1594628691.969502 peer 0x10f1d0000 message 204
1594628691.969550 client loop exit
```

Note that client logs has some time duration between `sending message` and `peer 0x10f1d000 message 203` .

I have another OSX machine which almost exactly same spec / config and it works fine without those duration above.

Any hint to fix this problem would be appreciated.

**Comment by nicm** [comment] 2020-07-13 10:21
If you go to osdep-darwin.c and comment out the two setenv lines in osdep_event_init, then rebuild and completely restart the tmux server (`tmux kill-server`), does it make any difference?

**Comment by Xeite** [comment] 2020-07-17 20:54
Sorry, I'm late.

I deleted those two lines and test again
```
	/* setenv("EVENT_NOKQUEUE", "1", 1); */
	/* setenv("EVENT_NOPOLL", "1", 1); */
```

But it looks same.

**Comment by krader1961** [comment] 2020-07-18 05:23
Running `tmux -vv run-shell 'echo hello'` on my macOS server takes ~20 ms. Running the equivalent `time $SHELL -c 'echo yes'` to bypass tmux completes in ~15 ms. How fast is that latter command for you, @Xeite? In other words, how do we know the problem isn't your shell rather than tmux?

Also, did you actually build a new tmux binary and kill any existing tmux server when testing the effect of commenting out those `setenv()` statements? I ask this because a common mistake is to test a change to the tmux server behavior without restarting the tmux server.

P.S., I'm using tmux built from commit 9ffdcc76 merged 2020-06-06; i.e., a tmux I built from head a month ago.

**Comment by Xeite** [comment] 2020-07-18 11:45
@krader1961 because I deleted shell env files and ran test. Shell itself looks fine for me though, I'm not sure shell loads silently something that I'm not aware of (and it's looks most promising I think as well)

```
tmux$ time $SHELL -c 'echo yes'
yes
$SHELL -c 'echo yes'  0.00s user 0.01s system 62% cpu 0.016 total
```

I built current HEAD and `kill-server`.

**Comment by nicm** [comment] 2020-07-24 07:13
Show me the full server look from reproducing please.

**Comment by Xeite** [comment] 2020-07-25 15:48
@nicm 
Log for
```
tmux -vvv new
tmux -vvv run-shell "echo hello" 
```

https://gist.github.com/Xeite/43094d1a97dc94bab45f035ac52909ca

**Comment by nicm** [comment] 2020-07-27 08:06
This looks OK to me:
~~~~
1595687129.218625 job_run: cmd=echo hello, cwd=/Users/yyouseok/codes
1595687129.219123 run job 0x7fadab515de0: echo hello, pid 30806
1595687129.219369 job write 0x7fadab515de0: echo hello, pid 30806, output left 0
1595687129.444576 job error 0x7fadab515de0: echo hello, pid 30806
1595687129.444660 job died 0x7fadab515de0: echo hello, pid 30806
1595687129.444797 free job 0x7fadab515de0: echo hello
~~~~
So it is ~226 milliseconds between the process being run and tmux being told it has exited, which doesn't seem that bad.

**Comment by Xeite** [comment] 2020-07-27 13:52
I'm not quite sure the metric is wrong or not, but what I measure in different OSX has quite different metric,

```

**Comment by nicm** [comment] 2020-07-27 14:03
Can you get a trace of the system calls in the tmux server when reproducing without logging? I don't know how to do this now since Apple have apparently completely changed ktrace but on *BSD it is usually ktrace/kdump and on Linux strace.

**Comment by Xeite** [comment] 2020-07-27 14:10
```
tmux$ sudo dtruss tmux run-shell "echo hello"
Password:
dtrace: system integrity protection is on, some features will not be available

SYSCALL(args)            = return
error connecting to /tmp//tmux-0/default (No such file or directory)
open("/dev/dtracehelper\0", 0x2, 0xFFFFFFFFE8EAAFE0)             = 3 0
ioctl(0x3, 0x80086804, 0x7FFEE8EAADF0)           = 0 0
close(0x3)               = 0 0
access("/AppleInternal/XBS/.isChrooted\0", 0x0, 0x0)             = -1 Err#2
bsdthread_register(0x7FFF6319C400, 0x7FFF6319C3F0, 0x2000)               = 1073742047 0
sysctlbyname(kern.bootargs, 0xD, 0x7FFEE8EAA140, 0x7FFEE8EAA130, 0x0)            = 0 0
issetugid(0x0, 0x0, 0x0)                 = 0 0
ioctl(0x2, 0x4004667A, 0x7FFEE8EA9884)           = 0 0
mprotect(0x106EC6000, 0x1000, 0x0)               = 0 0
mprotect(0x106ECD000, 0x1000, 0x0)               = 0 0
mprotect(0x106ECE000, 0x1000, 0x0)               = 0 0
mprotect(0x106ED5000, 0x1000, 0x0)               = 0 0
mprotect(0x106EC4000, 0x90, 0x1)                 = 0 0
mprotect(0x106E37000, 0x1000, 0x1)               = 0 0
mprotect(0x106EC4000, 0x90, 0x3)                 = 0 0
mprotect(0x106EC4000, 0x90, 0x1)                 = 0 0
getentropy(0x7FFEE8EA99D0, 0x20, 0x0)            = 0 0
getpid(0x0, 0x0, 0x0)            = 54928 0
stat64("/AppleInternal\0", 0x7FFEE8EAA5B0, 0x0)          = -1 Err#2
csops(0xD690, 0x7, 0x7FFEE8EAA0E0)               = -1 Err#22
proc_info(0x2, 0xD690, 0xD)              = 64 0
csops(0xD690, 0x7, 0x7FFEE8EA9920)               = -1 Err#22
open_nocancel("/usr/share/locale/en_US.UTF-8/LC_CTYPE\0", 0x0, 0x5)              = 3 0
fcntl_nocancel(0x3, 0x3, 0x0)            = 0 0
getrlimit(0x1008, 0x7FFEE8EAAF30, 0x0)           = 0 0
fstat64(0x3, 0x7FFEE8EAAFA8, 0x0)                = 0 0
fstat64(0x3, 0x7FFEE8EAADA8, 0x0)                = 0 0
lseek(0x3, 0x0, 0x1)             = 0 0
lseek(0x3, 0x0, 0x0)             = 0 0
dtrace: error on enabled probe ID 2175 (ID 947: syscall::read_nocancel:return): invalid kernel access in action #12 at DIF offset 68
dtrace: error on enabled probe ID 2175 (ID 947: syscall::read_nocancel:return): invalid kernel access in action #12 at DIF offset 68
dtrace: error on enabled probe ID 2175 (ID 947: syscall::read_nocancel:return): invalid kernel access in action #12 at DIF offset 68
dtrace: error on enabled probe ID 2175 (ID 947: syscall::read_nocancel:return): invalid kernel access in action #12 at DIF offset 68
dtrace: error on enabled probe ID 2175 (ID 947: syscall::read_nocancel:return): invalid kernel access in action #12 at DIF offset 68
dtrace: error on enabled probe ID 2175 (ID 947: syscall::read_nocancel:return): invalid kernel access in action #12 at DIF offset 68
dtrace: error on enabled probe ID 2175 (ID 947: syscall::read_nocancel:return): invalid kernel access in action #12 at DIF offset 68
dtrace: error on enabled probe ID 2175 (ID 947: syscall::read_nocancel:return): invalid kernel access in action #12 at DIF offset 68
close_nocancel(0x3)              = 0 0
access("/etc/localtime\0", 0x4, 0x0)             = 0 0
open_nocancel("/etc/localtime\0", 0x0, 0x0)              = 3 0
fstat64(0x3, 0x7FFEE8EAAFB8, 0x0)                = 0 0
dtrace: error on enabled probe ID 2175 (ID 947: syscall::read_nocancel:return): invalid kernel access in action #12 at DIF offset 68
close_nocancel(0x3)              = 0 0
issetugid(0x0, 0x0, 0x0)                 = 0 0
open_nocancel("/var/db/timezone/zoneinfo/posixrules\0", 0x0, 0x0)                = 3 0
fstat64(0x3, 0x7FFEE8EAADE8, 0x0)                = 0 0
dtrace: error on enabled probe ID 2175 (ID 947: syscall::read_nocancel:return): invalid kernel access in action #12 at DIF offset 68
close_nocancel(0x3)              = 0 0
madvise(0x106EFC000, 0xB000, 0x9)                = 0 0
madvise(0x106EF1000, 0xB000, 0x9)                = 0 0
shm_open(0x7FFF6318FCD8, 0x0, 0x0)               = 3 0
mmap(0x0, 0x1000, 0x1, 0x1, 0x3, 0x0)            = 0x106F07000 0
close_nocancel(0x3)              = 0 0
open_nocancel(".\0", 0x0, 0x1)           = 3 0
fstat64(0x3, 0x7FFEE8EAAAF0, 0x0)                = 0 0
fcntl_nocancel(0x3, 0x32, 0x106DCFE20)           = 0 0
close_nocancel(0x3)              = 0 0
stat64("/Users/yyouseok/codes/c/tmux\0", 0x7FFEE8EAAA60, 0x0)            = 0 0
stat64("/\0", 0x7FFEE8EA8F38, 0x0)               = 0 0
getattrlist("/Users\0", 0x7FFF63075964, 0x7FFEE8EAA890)          = 0 0
getattrlist("/Users/yyouseok\0", 0x7FFF63075964, 0x7FFEE8EAA890)                 = 0 0
getattrlist("/Users/yyouseok/codes\0", 0x7FFF63075964, 0x7FFEE8EAA890)           = 0 0
getattrlist("/Users/yyouseok/codes/c\0", 0x7FFF63075964, 0x7FFEE8EAA890)                 = 0 0
getattrlist("/Users/yyouseok/codes/c/tmux\0", 0x7FFF63075964, 0x7FFEE8EAA890)            = 0 0
getattrlist("/Users\0", 0x7FFF63075964, 0x7FFEE8EAA890)          = 0 0
getattrlist("/Users/yyouseok\0", 0x7FFF63075964, 0x7FFEE8EAA890)                 = 0 0
getattrlist("/Users/yyouseok/codes\0", 0x7FFF63075964, 0x7FFEE8EAA890)           = 0 0
getattrlist("/Users/yyouseok/codes/c\0", 0x7FFF63075964, 0x7FFEE8EAA890)                 = 0 0
getattrlist("/Users/yyouseok/codes/c/tmux\0", 0x7FFF63075964, 0x7FFEE8EAA890)            = 0 0
access("/bin/sh\0", 0x1, 0x0)            = 0 0
getuid(0x0, 0x0, 0x0)            = 0 0
getattrlist("/tmp\0", 0x7FFF63075964, 0x7FFEE8EAB0C0)            = 0 0
readlink("/tmp\0", 0x7FFEE8EAA4C0, 0x400)                = 11 0
getattrlist("/private\0", 0x7FFF63075964, 0x7FFEE8EAB0C0)                = 0 0
getattrlist("/private/tmp\0", 0x7FFF63075964, 0x7FFEE8EAB0C0)            = 0 0
getattrlist("/private/tmp/tmux-0\0", 0x7FFF63075964, 0x7FFEE8EAB0C0)             = -1 Err#2
mkdir("/tmp//tmux-0\0", 0x1C0, 0x0)              = 0 0
lstat64("/tmp//tmux-0\0", 0x7FFEE8EAB928, 0x0)           = 0 0
issetugid(0x0, 0x0, 0x0)                 = 0 0
issetugid(0x0, 0x0, 0x0)                 = 0 0
issetugid(0x0, 0x0, 0x0)                 = 0 0
issetugid(0x0, 0x0, 0x0)                 = 0 0
pipe(0x0, 0x0, 0x0)              = 3 0
fcntl(0x3, 0x4, 0x4)             = 0 0
fcntl(0x4, 0x4, 0x4)             = 0 0
fcntl(0x3, 0x2, 0x1)             = 0 0
fcntl(0x4, 0x2, 0x1)             = 0 0
issetugid(0x0, 0x0, 0x0)                 = 0 0
sigaction(0x14, 0x7FFEE8EAB3A8, 0x7FFEE8EAB3D0)          = 0 0
dtrace: error on enabled probe ID 2198 (ID 559: syscall::sysctl:return): invalid kernel access in action #10 at DIF offset 28
dtrace: error on enabled probe ID 2198 (ID 559: syscall::sysctl:return): invalid kernel access in action #10 at DIF offset 28
dtrace: error on enabled probe ID 2198 (ID 559: syscall::sysctl:return): invalid kernel access in action #10 at DIF offset 28
dtrace: error on enabled probe ID 2198 (ID 559: syscall::sysctl:return): invalid kernel access in action #10 at DIF offset 28
dtrace: error on enabled probe ID 2198 (ID 559: syscall::sysctl:return): invalid kernel access in action #10 at DIF offset 28
sigaction(0x2, 0x7FFEE8EAB398, 0x0)              = 0 0
sigaction(0xD, 0x7FFEE8EAB398, 0x0)              = 0 0
sigaction(0x12, 0x7FFEE8EAB398, 0x0)             = 0 0
sigaction(0x1, 0x7FFEE8EAB268, 0x7FB8BA6001B0)           = 0 0
sigaction(0x14, 0x7FFEE8EAB268, 0x7FB8BA600340)          = 0 0
sigaction(0x13, 0x7FFEE8EAB268, 0x7FB8BA6001E0)          = 0 0
sigaction(0xF, 0x7FFEE8EAB268, 0x7FB8BA600200)           = 0 0
sigaction(0x1E, 0x7FFEE8EAB268, 0x7FB8BA600220)          = 0 0
sigaction(0x1F, 0x7FFEE8EAB268, 0x7FB8BA600240)          = 0 0
sigaction(0x1C, 0x7FFEE8EAB268, 0x7FB8BA600260)          = 0 0
socket(0x1, 0x1, 0x0)            = 5 0
connect(0x5, 0x7FFEE8EAB470, 0x6A)               = -1 Err#2
close(0x5)               = 0 0
dtrace: error on enabled probe ID 2173 (ID 949: syscall::write_nocancel:return): invalid kernel access in action #12 at DIF offset 68

```

Does it helps you?

I also noticed abnormal server log has many `format-expand`, `format-replace` or something compared to normal one which has nothing between `run` and `die`. Do you have any idea to dig it more? I am willing to dig by myself if you can guide a little.

**Comment by nicm** [comment] 2020-07-27 14:18
We need the server not the client, because we need to see the actual time between tmux server forking the job (`echo hello`) and getting an EOF on its stdout and a `SIGCHLD` so it knows it is finished. So you need to kill the server and start it under dtruss and also ask for timestamps. So do something like this:
~~~~
tmux kill-server
tmux new -d
dtruss -p `tmux display -p '#{pid}'` -a -d >dtruss.log
~~~~
Then `tmux attach` from another terminal and reproduce and show me the dtruss.log.

**Comment by nicm** [comment] 2020-07-27 14:23
The format stuff in your log is tmux redrawing the status line, but this only takes 16 milliseconds. The time is in other places, for example between these two log lines:
~~~~
1595687129.269040 cmdq_append <global>: [notify_callback/0x7fadab4116e0]
1595687129.427844 cmdq_next <global>: enter
~~~~
When tmux is asleep for 150 milliseconds waiting for something to wake it up again.

This seems like either a problem with the kernel or with libevent.

**Comment by Xeite** [comment] 2020-08-03 07:04
@nicm 
Sorry nicm, I was late again. [Here](https://pastebin.com/tW26W2nQ) is server log from `dtruss -p `tmux display -p '#{pid}'` -a -d >dtruss.log`. 

I compared the log with my different OSX, but could not find noticeable difference. Please take a look at it if you have some time.

**Comment by nicm** [comment] 2020-08-03 10:22
Can you do the same but add `-f` as well and also show me the corresponding tmux server log (start the tmux server with `-vv`)?

**Comment by Xeite** [comment] 2020-08-03 11:55
@nicm 
[Here](https://gist.github.com/Xeite/5f95b3b57f3eeeca9260edb04a234888) is dstruss log with `-f` and
[Here](https://gist.github.com/Xeite/8aa94a4c3fa6b4bc76bceb7e5ea825bb) is server log

**Comment by nicm** [comment] 2020-08-03 13:02
OK this doesn't really tell us much unfortunately because dtruss is apparently showing process-time rather than real-time, so there is no way to tell how much time there actually was between the child process starting and exiting.

I don't see any reason to believe this is in tmux though. Are you sure you are using the same OS version, the same libevent version and the same tmux version on both machines?

**Comment by Xeite** [comment] 2020-08-03 15:23
@nicm I tried several tmux versions including exactly same. 
The other environment was slightly different like
```
OS: Catalina vs Mojave
Llibvent: 2.1.11 vs 2.1.12
```
But I matched all the same, and the problem still exist. 

I myself do not believe this is only from tmux problem, but I don't know how to solve it so I am looking forward to help.

**Comment by nicm** [comment] 2020-08-04 13:49
I am not sure what else you can try. You could try profiling it with instruments and see if you can see what is taking the time.

**Closed** 2020-08-19 06:27 UTC
