### ISSUE TITLE
Sending non-ASCII chars via send-keys results in wrong output

### ISSUE THREAD

**Issue by lifepillar** [tmux/tmux#686] opened 2016-12-06 10:58 UTC
Using tmux 2.3 in macOS Sierra, I have the following problem (tested in Terminal.app and iTerm2): start a session and make a split pane. Then, send some non-ASCII characters from one pane to the other, e.g.,

```
tmux -u -l send-keys -t 1 àèì
```

The received output is `Ã Ã¨Ã¬` instead of `àèì`. Am I missing something?

**Comment by nicm** [comment] 2016-12-07 09:19
Does this still happen in master?

If so please include some logs (look at the CONTRIBUTING file for how).

**Comment by lifepillar** [comment] 2016-12-07 15:28
Yes, it happens in master, too.

[tmux-server-50505.txt](https://github.com/tmux/tmux/files/636961/tmux-server-50505.txt)

**Comment by nicm** [comment] 2016-12-07 17:38
Yes, this is caused by changing to support Unicode keys. We need to translate the UTF-8 that you enter into Unicode so that window_pane_key can turn it back into UTF-8 correctly. Please try this: [x.diff.txt](https://github.com/tmux/tmux/files/637318/x.diff.txt)

**Comment by lifepillar** [comment] 2016-12-08 20:46
I'm afraid that patch is not enough: I'm still having the same issue.

**Comment by nicm** [comment] 2016-12-08 20:51
Are you sure you restarted tmux entirely after rebuilding?

**Comment by lifepillar** [comment] 2016-12-08 20:56
Argh, I did `kill-session` instead of `kill-server`…

After restarting `tmux`, it works perfectly. Thanks!

**Comment by nicm** [comment] 2016-12-08 22:16
Applied now, will be in GitHub soon. Thanks!

**Closed by nicm** 2016-12-08 22:16 UTC
