### ISSUE TITLE
copy & paste broken

### ISSUE THREAD

**Issue by octoploid** [tmux/tmux#790] opened 2017-02-20 14:19 UTC
tmux master
xterm-256color

When I enter copy-mode and select e.g. a multi line gcc command
and the paste the copied buffer with ] the text appears garbled.
(Only the last character of each line is shown, the rest is whitespace.)

![shot](https://cloud.githubusercontent.com/assets/327746/23128584/be94bdee-f77f-11e6-94b7-8a787e67e2ee.png)

I can execute the pasted command just fine. Only the rendering is broken.
When I switch to a different pane and then back again, the full command is rendered correctly.

**Comment by nicm** [comment] 2017-02-20 15:17
Can't reproduce this. Logs?

**Comment by octoploid** [comment] 2017-02-20 16:07
```
markus@x4 ~ % cat tmux-client-17398.log
1487606474.677201 client started (17398): version master, socket /home/markus/tmp/tmp/tmux-1000/test, protocol 8
1487606474.677228 on Linux 4.10.0 #113 SMP Mon Feb 20 10:05:18 CET 2017; libevent 2.1.8-stable (poll)
1487606474.677250 socket is /home/markus/tmp/tmp/tmux-1000/test
1487606474.677260 trying connect
1487606474.677321 add peer 0x832b30: 6 ((nil))
1487606474.677365 sending message 100 to peer 0x832b30 (4 bytes)
1487606474.677373 sending message 101 to peer 0x832b30 (15 bytes)
1487606474.677379 sending message 102 to peer 0x832b30 (12 bytes)
1487606474.677383 sending message 108 to peer 0x832b30 (13 bytes)
1487606474.677389 sending message 104 to peer 0x832b30 (0 bytes)
1487606474.677394 sending message 107 to peer 0x832b30 (4 bytes)
1487606474.677398 sending message 105 to peer 0x832b30 (18 bytes)
1487606474.677403 sending message 105 to peer 0x832b30 (18 bytes)
1487606474.677407 sending message 105 to peer 0x832b30 (27 bytes)
1487606474.677411 sending message 105 to peer 0x832b30 (16 bytes)
1487606474.677416 sending message 105 to peer 0x832b30 (159 bytes)
1487606474.677422 sending message 105 to peer 0x832b30 (8 bytes)
1487606474.677426 sending message 105 to peer 0x832b30 (20 bytes)
1487606474.677431 sending message 105 to peer 0x832b30 (38 bytes)
1487606474.677435 sending message 105 to peer 0x832b30 (14 bytes)
1487606474.677439 sending message 105 to peer 0x832b30 (31 bytes)
1487606474.677443 sending message 105 to peer 0x832b30 (25 bytes)
1487606474.677447 sending message 105 to peer 0x832b30 (26 bytes)
1487606474.677451 sending message 105 to peer 0x832b30 (107 bytes)
1487606474.677455 sending message 105 to peer 0x832b30 (64 bytes)
1487606474.677459 sending message 105 to peer 0x832b30 (36 bytes)
1487606474.677463 sending message 105 to peer 0x832b30 (11 bytes)
1487606474.677467 sending message 105 to peer 0x832b30 (46 bytes)
1487606474.677471 sending message 105 to peer 0x832b30 (25 bytes)
1487606474.677475 sending message 105 to peer 0x832b30 (22 bytes)
1487606474.677479 sending message 105 to peer 0x832b30 (18 bytes)
1487606474.677483 sending message 105 to peer 0x832b30 (13 bytes)
1487606474.677487 sending message 105 to peer 0x832b30 (11 bytes)
1487606474.677491 sending message 105 to peer 0x832b30 (22 bytes)
1487606474.677495 sending message 105 to peer 0x832b30 (30 bytes)
1487606474.677499 sending message 105 to peer 0x832b30 (15 bytes)
1487606474.677503 sending message 105 to peer 0x832b30 (10 bytes)
1487606474.677507 sending message 105 to peer 0x832b30 (33 bytes)
1487606474.677511 sending message 105 to peer 0x832b30 (12 bytes)
1487606474.677516 sending message 105 to peer 0x832b30 (22 bytes)
1487606474.677520 sending message 105 to peer 0x832b30 (184 bytes)
1487606474.677524 sending message 105 to peer 0x832b30 (199 bytes)
1487606474.677528 sending message 105 to peer 0x832b30 (21 bytes)
1487606474.677532 sending message 105 to peer 0x832b30 (148 bytes)
1487606474.677536 sending message 105 to peer 0x832b30 (17 bytes)
1487606474.677540 sending message 105 to peer 0x832b30 (50 bytes)
1487606474.677544 sending message 105 to peer 0x832b30 (18 bytes)
1487606474.677548 sending message 105 to peer 0x832b30 (42 bytes)
1487606474.677552 sending message 105 to peer 0x832b30 (11 bytes)
1487606474.677556 sending message 105 to peer 0x832b30 (27 bytes)
1487606474.677560 sending message 105 to peer 0x832b30 (19 bytes)
1487606474.677564 sending message 105 to peer 0x832b30 (16 bytes)
1487606474.677568 sending message 105 to peer 0x832b30 (16 bytes)
1487606474.677572 sending message 105 to peer 0x832b30 (24 bytes)
1487606474.677576 sending message 105 to peer 0x832b30 (17 bytes)
1487606474.677580 sending message 105 to peer 0x832b30 (24 bytes)
1487606474.677584 sending message 105 to peer 0x832b30 (20 bytes)
1487606474.677588 sending message 105 to peer 0x832b30 (15 bytes)
1487606474.677594 sending message 105 to peer 0x832b30 (15 bytes)
1487606474.677598 sending message 105 to peer 0x832b30 (13 bytes)
1487606474.677602 sending message 105 to peer 0x832b30 (11 bytes)
1487606474.677606 sending message 105 to peer 0x832b30 (27 bytes)
1487606474.677614 sending message 105 to peer 0x832b30 (27 bytes)
1487606474.677618 sending message 105 to peer 0x832b30 (16 bytes)
1487606474.677623 sending message 106 to peer 0x832b30 (0 bytes)
1487606474.677628 sending message 200 to peer 0x832b30 (8 bytes)
1487606474.677632 client loop enter
1487606474.687713 peer 0x832b30 message 207
1487606474.687735 sending message 208 to peer 0x832b30 (0 bytes)
1487606619.178385 peer 0x832b30 message 203
1487606619.178408 sending message 205 to peer 0x832b30 (0 bytes)
1487606619.179044 peer 0x832b30 message 204
1487606619.179050 client loop exit
```

**Comment by octoploid** [comment] 2017-02-20 16:13
screen capture:
[capture_smaller.mkv.zip](https://github.com/tmux/tmux/files/787980/capture_smaller.mkv.zip)

**Comment by nicm** [comment] 2017-02-20 17:15
I need the server log.

**Comment by octoploid** [comment] 2017-02-20 17:23
Sorry:
[log.tar.zip](https://github.com/tmux/tmux/files/788133/log.tar.zip)

**Comment by octoploid** [comment] 2017-02-20 17:29
git bisect doesn't work unfortunately.
This is what I came up with:

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
13a0b6bb3fe05454cace81f5ec7624f6fd9021a5
d4b006b9faf001de41560db2e8fb890c654598e2
7475165cd87d443da34da11298e638d3d17f43e9
e09625e38b361b8ce0b8fa88851f447144f1a718
e100d465daefd20da0bb5eea87c4b4896badff16
05802a6fe309e3b4559286ca5ce3c51f7367d661
ac1f294bb930a0c05f96197b6a53b883ebc483f2
96b66f8fc32867899653dd898f53285741ab8c83
713f3b05f3f0579c4ccbba2d93affaf672a3a473
9af5f3ff812044a157a120ba7e2c70283b3b36dd
130b77edc737fcd113964fd77123285d78dfe3f9
```

**Comment by nicm** [comment] 2017-02-21 08:48
If you press C-b r (refresh-client) after pasting, does the text appear?

**Comment by octoploid** [comment] 2017-02-21 08:51
Yes.

**Comment by nicm** [comment] 2017-02-21 09:13
Instead of reproducing with a load of compiler output, can you please make a single file which reproduces the problem (take the last line of the compiler output, for example, or create a file full of 'aaaaaaaaaaaaaaa'). Then send me that file and the server log from copying and pasting the file.

**Comment by nicm** [comment] 2017-02-21 09:19
Actually I think I might have fixed this already but the GitHub sync has not caught up. See if this fixes it:

~~~~
Index: tty.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/tty.c,v
retrieving revision 1.248
retrieving revision 1.249
diff -u -p -r1.248 -r1.249
--- tty.c	15 Feb 2017 11:22:13 -0000	1.248
+++ tty.c	16 Feb 2017 12:56:01 -0000	1.249
@@ -1321,7 +1321,7 @@ tty_region(struct tty *tty, u_int rupper
 		tty_cursor(tty, 0, tty->cy);
 
 	tty_putcode2(tty, TTYC_CSR, tty->rupper, tty->rlower);
-	tty->cx = tty->cy = 0;
+	tty->cx = tty->cy = UINT_MAX;
 }
 
 /* Turn off margin. */
@@ -1359,7 +1359,7 @@ tty_margin(struct tty *tty, u_int rleft,
 	else
 		snprintf(s, sizeof s, "\033[%u;%us", rleft + 1, rright + 1);
 	tty_puts(tty, s);
-	tty->cx = tty->cy = 0;
+	tty->cx = tty->cy = UINT_MAX;
 }
 
 /* Move cursor inside pane. */

**Comment by octoploid** [comment] 2017-02-21 09:25
Your patch doesn't fix the issue.
Here are your requested files: 
[log.tar.zip](https://github.com/tmux/tmux/files/789641/log.tar.zip)

**Comment by nicm** [comment] 2017-02-21 09:29
Are you sure these logs are from a tmux with the patch applied? If so it should not be using relative movement escape sequences after CSR, are you sure you tested with the right tmux binary?

**Comment by octoploid** [comment] 2017-02-21 09:29
the logs were taken before the patch was applied. But the patch doesn't help.

**Comment by octoploid** [comment] 2017-02-21 09:32
Here's a log with your patch applied: 
[log.tar.zip](https://github.com/tmux/tmux/files/789663/log.tar.zip)

**Comment by nicm** [comment] 2017-02-21 09:34
What terminal are you using and if it isn't xterm, does the same happen in xterm?

**Comment by octoploid** [comment] 2017-02-21 09:35
Konsole. And yes, it also happens in xterm.

**Comment by nicm** [comment] 2017-02-21 09:35
It looks to me like tmux is writing everything it should be, at least it is writing more than you see, which means the cursor positioning or something must be off. Can you do the same logs from a smaller terminal (80x24 or so, at least <100x100)?

**Comment by octoploid** [comment] 2017-02-21 09:41
size 89x64: 
[log.tar.zip](https://github.com/tmux/tmux/files/789679/log.tar.zip)

**Comment by nicm** [comment] 2017-02-21 10:05
Apply this please 
[x.diff.txt](https://github.com/tmux/tmux/files/789738/x.diff.txt)
then do the same thing (logs with smaller terminal), thanks

**Comment by octoploid** [comment] 2017-02-21 10:11
[log_with_debug_patch.tar.zip](https://github.com/tmux/tmux/files/789751/log_with_debug_patch.tar.zip)

**Comment by nicm** [comment] 2017-02-21 10:22
Try this please:  
[y.diff.txt](https://github.com/tmux/tmux/files/789772/y.diff.txt)

**Comment by nicm** [comment] 2017-02-21 10:24
Actually this is probably better 
[z.diff.txt](https://github.com/tmux/tmux/files/789779/z.diff.txt)

**Comment by octoploid** [comment] 2017-02-21 10:26
y.diff.txt fixes the issue. Many thanks.

**Comment by nicm** [comment] 2017-02-21 10:27
Does the z one fix it as well?

**Comment by octoploid** [comment] 2017-02-21 10:28
Yes. z.diff.txt is fine, too.

**Comment by nicm** [comment] 2017-02-21 10:30
Great, applied to OpenBSD, will be in GitHub soonish. Thanks!

**Closed by nicm** 2017-02-21 10:30 UTC
