### ISSUE TITLE
[Bug Report] Cursor in neovim stops blinking after upgrading tmux from 3.2a to 3.3-rc

### ISSUE THREAD

**Issue by laggardkernel** [tmux/tmux#2891] opened 2021-09-17 02:09 UTC
### Issue description

Cursor stops blinking within nvim (iTerm2 + tmux) after upgrading tmux from 3.2a to 3.3-rc.

- Neovim cursor blinks outside tmux
- Neovim cursor blinks inside tmux when using tmux 3.2a but not 3.3-rc
- Neovim cursor even stops blinking after quitting neovim (still within tmux)
- Only affects neovim but not vim

### Required information

(All following info are included in the log archiver.)

Environments

- tmux: next-3.4, 409e121, installed with `brew install --HEAD tmux`
- OS: macOS 10.14.6
- Terminal: iTerm2 3.4.10
- TERM:
  - xterm-256color outside tmux
  - tmux-256color  inside  tmux
- Vim: Neovim v0.5.0
- Logs from tmux (`tmux kill-server; tmux -vv new`): [tmux-no-cursor-blink-in-nvim.tar.gz](https://github.com/tmux/tmux/files/7182058/tmux-no-cursor-blink-in-nvim.tar.gz)

I have also tried with neovim nightly, and switched to terminal kitty. Still the same problem.

Log archiver structure

```
❯ tree
.
├── info.txt
├── infocmp-dump-tmux-256color.txt
├── infocmp-dump-xterm-256color.txt
├── init.vim
├── tmux-client-36996.log
├── tmux-out-36998.log
├── tmux-server-36998.log
└── tmux.conf

0 directories, 8 files
```

Log generation steps

```sh
# start tmux server
tmux -vv -f ./tmux.conf -S ./tmux.socket

# after enter tmux
nvim
# insert some char in nvim, and quit with q!
```

Minimal tmux conf

```conf
set-option -s escape-time 25
set-option -gs default-terminal "tmux-256color"
set-option -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[5 q'
```

Minimal neovim conf

```vim
set guicursor=n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20,a:blinkwait10-blinkon400-blikoff300
```

**Comment by nicm** [comment] 2021-09-17 06:09
vim is setting the cursor style, but then it is sending `cnorm` which turns off blinking, for example:
~~~~
\033[1 q\033[H\033[34h\033\[?25h
^^^^^^^^      ^^^^^^^^

This is the same behaviour as xterm (although it uses a different escape sequence to turn blinking off).

Does vim blinking work in xterm?

**Comment by laggardkernel** [comment] 2021-09-17 09:15
Tested with above minimal conf in xterm 367 (the xterm is bundled in XQuartz). `vim -u init.vim` (init.vim is the minimal conf I pasted above)

- outside tmux: cursor in neovim blinks
- inside tmux: cursor blinking in neovim is turned off

This happened with both tmux 3.2a and tmux 3.3-rc.

**Comment by nicm** [comment] 2021-09-17 09:25
Run vim in script in xterm but outside tmux and show me the typescript file please.

**Comment by laggardkernel** [comment] 2021-09-18 05:26
@nicm  Do you mean the log generated by XTerm's "Log to file" function?

[Xterm-nvim-outside-tmux.log](https://github.com/tmux/tmux/files/7189305/Xterm-nvim-outside-tmux.log)

Log generated with

- XTerm **without** `~/.Xresources`, shell defaults `/bin/sh`.
- `nvim -u minimal.vim` (conf pasted above)

**Comment by nicm** [comment] 2021-09-21 08:00
vim is not asking xterm to turn the cursor off again, which means it must be sending `cnorm` inside tmux but not outside tmux. You should probably ask the vim developers why it is doing this?

**Comment by laggardkernel** [comment] 2021-09-25 08:00
terminfo `tmux-256color` has `cnorm=\E[34h\E[?25h,` as the default cnorm value. Changing it to `cnorm=\E[?12h\E[?25h,` seems to be a temporary solution for me.

**Comment by ThomasDickey** [comment] 2021-09-25 20:21
That (`cnorm=\E[34h\E[?25h`) is from screen, as seen in version 3.7.1 (1995).  The only older version I have is 2.1, which doesn't have that feature.  Looking at the ncurses terminal database, I'd say that the screen developers copied the feature from one of the Wyse terminals.  There's no source archive, of course.

ECMA-48 doesn't define the ***34*** code (it goes up to 22), so you're unlikely to find a more definitive usage.

If tmux is going to rely upon using screen's terminal description, it should map that code into its own.

**Comment by nicm** [comment] 2021-09-25 20:38
The effect of cnorm is the same as xterm however (cursor on, blink off), it
just uses different escape sequences to do it.

**Comment by nicm** [comment] 2021-09-25 20:44
Note that screen's SM 34 code is the wrong way round - SM 34 turns blinking *off* and RM *on*.

**Comment by ThomasDickey** [comment] 2021-09-25 20:49
fwiw, http://www.nic.funet.fi/index/gnu/funet/historical-funet-gnu-area-from-early-1990s/ has some older versions, lacking this detail.

This entry https://invisible-island.net/ncurses/terminfo.src.html#tic-wy185 uses the same definition.  Whether it's correct or not actually depends on how the Wyse terminal was documented.  [Bitsavers](https://invisible-island.net/ncurses/terminfo.src.html#tic-wy185) doesn't have a suitable manual for this one.

**Comment by ThomasDickey** [comment] 2021-09-25 21:16
If you look on page 2-8 of the Wyse-370 programmer's reference, you'll see that mode 34 switches between underline (reset) and block (set) cursor.  The screen developer decided that a block cursor was "normal".   (I seem to recall having a different result when I developed terminal descriptions).

Private mode 25 does turn blinking on/off, but that's a DEC VT220 feature -- screen borrowed bits and pieces from different places without documenting the origin of each.

**Comment by nicm** [comment] 2021-09-25 21:17
34 is just the same as ?12 in tmux and screen except SM/RM are reversed, it is not really relevant. The problem is that vim is sending cnorm inside tmux causing it to (correctly) turn off blinking, when in fact vim wants blinking to remain on. The same would happen in xterm except vim chooses not to send cnorm and instead only sends SM ?25.

**Comment by nicm** [comment] 2021-09-25 21:30
You can see this in xterm, these will both turn off blinking:
~~~~
printf '\033[1 q\033[?12l'
printf '\033[1 q'; tput cnorm
~~~~
And all three of these in tmux 3.3-rc or master:
~~~~
printf '\033[1 q\033[?12l'
printf '\033[1 q\033[34h'
printf '\033[1 q'; tput cnorm
~~~~
The reason for this issue is because I fixed tmux to behave like xterm, so there is one blinking flag for both of DECSCUSR and SM/RM ?12/34.

Since tmux and xterm behave the same with regards to `cnorm`, it appears that vim should not be using `cnorm` inside tmux in the same way as it does not use it in xterm.

**Comment by ThomasDickey** [comment] 2021-09-25 23:02
xterm ignores `\033[34h'; it only responds to `\033[?12h` (and the `"h"` versus `"l" of course). 

vim doesn't necessarily follow the termcap exactly (it tries to find what terminal is actually used).
Because xterm ***XOR***s the different settings for cursor-blink, vim could be confused.
I added a control in [patch #331](https://invisible-island.net/xterm/xterm.log.html#xterm_331) to help it guess better, but it may not be using that:

>add private modes 13 and 14, as well as resource cursorBlinkXOR to allow better control over the cursor-blinking state (discussion with Bram Moolenaar).

(I should know the difference between `\E[?12h` and `\E[?25h` offhand...)

**Comment by nicm** [comment] 2021-09-26 05:58
Correct me if I'm wrong, but cursorBlinkXOR only XORs the menu option/resource and the flag set by both escape sequences (SM ?12 or DECSCUSR). There is only one combined flag for the escape sequences that they both change. That is the problem here.

I think if vim wants to use DECSCUSR it either cannot use `cnorm` or it must resend DECSCUSR after using `cnorm`, otherwise it will not work correctly in any terminal which behaves like xterm.

**Comment by ThomasDickey** [comment] 2021-09-26 08:33
The [SM?12](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h4-Functions-using-CSI-_-ordered-by-the-final-character-lparen-s-rparen:CSI-?-Pm-h:Ps-=-1-2.1EC0) and [DECSCUSR](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h4-Functions-using-CSI-_-ordered-by-the-final-character-lparen-s-rparen:CSI-Ps-SP-q.1D81) are private controls from different terminals, different manufacturers (AT&T and DEC), and their interaction is as they say "unspecified" in any hardware terminal.  In xterm, they interact by xor (since [patch #193](https://invisible-island.net/xterm/xterm.log.html#xterm_193)).

**Comment by ThomasDickey** [comment] 2021-09-26 08:43
As I recall it, Bram's concern about xor was that the user may have set the menu entry while vim enables blinking by one method or another.  So I added [SM?14](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h4-Functions-using-CSI-_-ordered-by-the-final-character-lparen-s-rparen:CSI-?-Pm-h:Ps-=-1-4.1EC2) to help.  But an application ought to choose how it wants to enable/disable blinking and not mix the different schemes, since that will never be fully specified.

**Comment by nicm** [comment] 2021-09-26 09:22
I'm not too worried about the menu option because tmux currently has no equivalent and if user's change xterm's that is their own concern. I'm only really interested in how DECSCUSR and SM/RM ?12 interact.

I'm not sure we are thinking the same thing when you say that the two escape sequences "interact by xor" - as far as I can tell from testing the latest snapshot, xterm's default behaviour is that the blink state is set by the most recent escape sequence, and (although perhaps I am missing something) from the code it seems like they share a flag, `screen->cursor_blink_esc`:
~~~~
    case CASE_DECSCUSR:
    ...
            case BLINK_BLOCK:
            blinks = True;
            screen->cursor_shape = CURSOR_BLOCK;
            break;
    ...
	    screen->cursor_blink_esc = blinks;
	    UpdateCursorBlink(xw);
~~~~
And for SM/RM ?12:
~~~~
    case srm_ATT610_BLINK:  /* AT&T 610: Start/stop blinking cursor */
        if (SettableCursorBlink(screen)) {
        set_bool_mode(screen->cursor_blink_esc);
        UpdateCursorBlink(xw);
        }
	break;
~~~~
The menu option is indeed XORd, but it is a separate flag (`screen->cursor_blink`).

I think vim should straighten out how they want to control cursor blinking because I would prefer that tmux follows how xterm works here, it is simpler to have one blink flag for both escape sequences.

**Comment by ThomasDickey** [comment] 2021-09-26 21:49
hmm - actually that's "Neovim v0.5.0", whose developers don't generally ask my opinion.  For vim, I see that Bram's made some changes mostly a couple of years ago (but don't see it using the extra private modes that I added in patch #331 -- it's using `DECRQM` with mode 12).

However, in tmux, I think that warts-and-all, screen's use of SM34 was intended to change the cursor appearance (`screen_set_cursor_style`) rather than enabling/disabling blink (`MODE_BLINK`).  This is what screen's source has:
 `   civis=\E[?25l, cnorm=\E[34h\E[?25h, cvvis=\E[34l,`

When correcting its terminfo, for ncurses, I didn't notice the SM34.  Making `cvvis` an underline cursor seems odd.  While I'm looking at it, `cvvis` probably wasn't used a lot, because going directly from `civis` to `cvvis` will leave the cursor hidden.  Someone would have noticed that.

screen utimately maps SM34 into this chunk:

`void    `                                                                        
`CursorVisibility(v) `
`int v; `
`{ `
`  if (display && D_curvis != v)`
`    {`
`      if (D_curvis) `
`        AddCStr(D_VE);          /* do this always, just to be safe */     `      
`      D_curvis = 0;`
`      if (v == -1 && D_VI) `
`        AddCStr(D_VI);`
`      else if (v == 1 && D_VS)`
`        AddCStr(D_VS);`
`      else`
`        return;`
`      D_curvis = v;`
`    }`
`}`

(no blinking in that function).

**Comment by ThomasDickey** [comment] 2021-09-26 23:56
Here's the steps it follows to reach that point:

- https://git.savannah.gnu.org/cgit/screen.git/tree/src/ansi.c#n1692 calls LCursorVisibility
- https://git.savannah.gnu.org/cgit/screen.git/tree/src/layer.c#n618 calls CursorVisibility
- https://git.savannah.gnu.org/cgit/screen.git/tree/src/display.c#n559

The `D_xxx` are the outer terminal's capabilities (which are hard to grep for in screen, due to the way the source is constructed).  They have the obvious meanings for termcap.

**Comment by nicm** [comment] 2021-09-27 02:19
Not sure what you mean, the effect of vs (cvvis) is blinking so 34 does indeed turn it on (I know it doesn't have to be but it is in xterm)? The effect of ve (cnorm) is to turn blinking off, so it will turn blinking off.

You may be right that 34 is intended to turn the cursor on as well (ie always send cnorm), but I don't know if that would make any difference here since it is the blinking state we are concerned with. I'll try it in screen and see what happens tomorrow.

**Comment by nicm** [comment] 2021-09-27 02:35
Maybe I should split ?12 (blinking) from 34 (vvis) but I would still need to sort out the interaction of that with DECSCUSR. And the fact is that it appears cnorm *should* disable blinking (that's what it does in xterm) which means that 34 has to do it  even in the presence of DECSCUSR.

**Comment by nicm** [comment] 2021-09-27 07:27
Screen version 4.00.03 (FAU) 23-Oct-06 (only one I have at hand) in xterm:
~~~~
tput cvvis # \E[34l <-- cursor blinking
tput cnorm # \E[34h\E[?25h <-- cursor not blinking (and on, if it were off)
tput civis; tput cvvis # \E[?25l\E[34l <-- cursor off
~~~~
So it appears at least in this screen version, SM/RM 34 only affects blinking and not visibility. Screen does not support DECSCUSR so there is nothing to say how it should interact, but I don't see any reason that it should behave differently than SM/RM ?12, at least for terminals where cvvis is blinking (so any that use TERM=xterm).

FWIW these all behave the same in tmux in xterm.

**Comment by ThomasDickey** [comment] 2021-09-28 00:16
cvvis doesn't always turn on blinking (I did that in xterm -- in [1996](https://invisible-island.net/xterm/xterm.log.html#xterm_22) -- because I implemented a blinking cursor). But the Wyse terminal didn't do that -- as I mentioned, it switched between block-cursor and underline-cursor.

There're 95 occurrences of cvvis in ncurses terminal database.  A small minority of those use SM?12 (about a dozen, counting uses via a building block -- which would make that about 100 occurrences).  Whether the others use different cursor appearance (including bold or color) or blinking, I'm not sure (categorizing all 95 isn't on my to-do list).

**Comment by nicm** [comment] 2021-09-28 05:53
Yes I know, but tmux has used cvvis for 34 and ?12 for 10 years and so far nobody has complained that it is not correct on their terminal. It is almost certain that any terminal on which tmux will use DECSCUSR will use xterm or some equivalent terminfo entry which does have cvvis as blinking. If the terminal doesn't have DECSCUSR of the application in tmux doesn't use it, it doesn't really matter if cvvis is blinking or something else.

If it does ever becomes a problem, I shall do something like make tmux use ?12 directly for blinking, make it only use DECSCUSR if supported, or have it try to work out if cvvis is blinking. But I don't think this is worth doing right now.

**Comment by nicm** [comment] 2021-09-28 05:56
Maybe it is a mistake to try and follow xterm in this and I should return to using separate flags for DECSCUSR blinking and ?12/34 blinking...

**Comment by nicm** [comment] 2021-09-28 07:03
TBH the choices are somewhat limited if I wanted to make sure blinking was actually blinking:

1. I could make tmux support some extension capabilities which are explicitly to set/reset cursor blinking, but any terminal where tmux can detect them automatically it will be detecting DECSCUSR anyway, so it would rely on the user setting them in other cases, and realisitically hardly anyone is going to do that. And anywhere it couldn't detect it would probably need to fall back to cvvis anyway.

2. I could use DECSCUSR for blinking. But it is tricky to figure out what the "default" does. I added the `Se` extension capability for "reset to the default cursor style", but tmux doesn't actually know what that default is (that is, does it blink or not), and the query sequence to find out is not widely supported.

As for what tmux itself can do:

1. I can leave it as it is, which means it behaves the same as xterm when cvvis is blinking and without DECSCUSR the same as it did before when cvvis is not, but mixing DECSCUSR and cvvis on terminals where cvvis is not blinking will be incorrect.

2. I could separate 34 (cvvis) and ?12 (blinking) and only support the latter on terminals where tmux can actually figure out if blinking is supported, but that would require tmux to detect if blinking is supported and I am certain that for almost all users it will just end up falling back to cvvis anyway.

3. I could return to separating DECSCUSR blinking from ?12/34 cvvis, but that moves away from cnorm resetting blinking. That wasn't the main point of the change but it seems like that is how it should work.

I'm not really adverse to doing (3) since that is how some non-xterm terminals work, but it seemed better to do the same as xterm...

That would also not need vim to change, even though it seems it does behave strangely.

**Comment by ThomasDickey** [comment] 2021-09-29 00:33
_SM34_ is only used within the internal terminal emulation, and only means whatever "normal" and "very visible" might mean (not explicitly blinking).  `DECSCUSR` is closer to the original intent for this, and doesn't have to do blinking (and because of that, it can be decoupled from _SM?12_).

An application is presumably able to send _SM?12_ and have tmux interpret that, but _SM34_ equates to whatever the outer terminal description says.

If tmux analyzes the outer terminal's `cnorm`/`cvvis` and notices blinking there, that's something to keep track of.

**Comment by nicm** [comment] 2021-10-01 09:30
OK after thinking about it I am going to leave DECSCUSR and ?12 blinking with the same flag, but change 34 to a different flag. So:

- If an application uses DECSCUSR and the outer terminal supports it, tmux will use it. SM ?12 will swap between blinking and not, so between style 1 and 2 or 3 and 4.

- If an application uses DECSCUSR and the outer terminal doesn't support DECSCUSR, tmux will send `cvvis` for blinking styles.

- RM 34 will do nothing while DECSCUSR is active.

- If the application doesn't use DECSCUSR, if *either* of SM ?12 or RM 34 has been used, tmux will send `cvvis`.

I don't see any point in trying to track if the outer terminal actually supports blinking because if it doesn't, tmux would need to fall back to `cvvis` anyway, so it might as well just use `cvvis`.

**Comment by nicm** [comment] 2021-10-01 09:39
@laggardkernel can you try this please? [tmux-cursor.diff.txt](https://github.com/tmux/tmux/files/7265967/tmux-cursor.diff.txt)

**Comment by laggardkernel** [comment] 2021-10-01 10:06
@nicm Thanks, this patch fixes my problem. 

And I'm sure I did the test with the minimal conf carefully

- reverted modification on terminfo tmux-256color
- made a comparison with tmux compiled without above patch

**Comment by nicm** [comment] 2021-10-01 10:58
OK I will apply this later.

**Comment by nicm** [comment] 2021-10-01 10:58
Thanks

**Comment by nicm** [comment] 2021-10-05 12:46
Applied to OpenBSD now, will be in GitHub later. Thanks!

**Closed by nicm** 2021-10-05 12:46 UTC
