### ISSUE TITLE
Can't create a new pane by horizontal split

### ISSUE THREAD

**Issue by norio13** [tmux/tmux#1153] opened 2017-11-09 08:31 UTC
hello,

## Step to reproduce

1. Draw UTF-8 character at the position where the border of the pane is drawn.
2. Try horizontal split.
3. Pane was not created. CPU is 100% used. Memory and swap are high usage.

$ cat sample.bash
```bash
#!/bin/bash
n="$(($(tput cols)/2-1))"
s=''
for ((i=0; i<"$n"; i++)); do s="${s}a"; done
echo "${s}あ"
tmux split-window -h
```

```
$ tmux -Ltest kill-server
$ tmux -vv -Ltest -f/dev/null new
$ bash sample.bash
```
## Environment

OS: Linux Debian stretch 9.2 64bit
tmux version: master(6f3b6c8)
terminal: xterm 327-2, xfce4-terminal 0.8.3-1, gnome-terminal 3.22.2-1
TERM: screen-256color

[tmux-server-1017.log](https://github.com/tmux/tmux/files/1456833/tmux-server-1017.log)

The size of the original log file was about 400 MB over.
The content after line 2079 is duplicated.
I will upload the log file with a smaller size.

best regards,

**Comment by nicm** [comment] 2017-11-09 08:42
Can't reproduce but this will probably fix it: [x.diff.txt](https://github.com/tmux/tmux/files/1456919/x.diff.txt)

**Comment by nicm** [comment] 2017-11-09 08:50
Or this might be better 
[y.diff.txt](https://github.com/tmux/tmux/files/1456947/y.diff.txt)

**Comment by norio13** [comment] 2017-11-09 13:35
Thank you for the patches.
Patches are good.

However, there are UTF-8 characters on the boundary.

![a](https://user-images.githubusercontent.com/18260849/32607579-d2b055fe-c59c-11e7-8ad0-3db52a26b9fe.png)

**Comment by norio13** [comment] 2017-11-11 10:53
Thank you for the new patch.
I think it's a good thing except that double width characters at end of the line are hidden.
I hope that it will be improved in the future.
At the moment, x.diff.txt or y.diff.txt may be good.

use y.diff.txt:
![y](https://user-images.githubusercontent.com/18260849/32688683-110687f6-c719-11e7-97db-f3b4635db50a.png)

use z.diff.txt:
![z](https://user-images.githubusercontent.com/18260849/32688689-1854e638-c719-11e7-8176-02383ad3d06b.png)

**Comment by nicm** [comment] 2017-11-11 12:10
There is no choice but to hide them or let them write over the border.
Hiding them is better because sometimes we redraw only the borders and if
would be very complicated to keep the wide characters visible.

**Comment by nicm** [comment] 2017-11-11 12:12
Actually they should probably be wrapped onto the next line by the reflow
code, will take a look.

**Comment by nicm** [comment] 2017-11-11 12:54
Reflow does not properly support double width characters and it will need some work to fix it. I'll probably apply the last change in the meantime.

**Comment by nicm** [comment] 2017-11-12 19:54
Please try this which changes the reflow code to support wide characters: [tmux-new-reflow.diff.txt](https://github.com/tmux/tmux/files/1465045/tmux-new-reflow.diff.txt)

**Comment by nicm** [comment] 2017-11-12 20:27
Here is an updated diff with no logging and some optimizations which mean it should be about the same performance as the previous code: [tmux-new-reflow2.diff.txt](https://github.com/tmux/tmux/files/1465078/tmux-new-reflow2.diff.txt)

**Comment by norio13** [comment] 2017-11-13 08:31
Perfect!
Thank you for your great work.

**Comment by nicm** [comment] 2017-11-13 09:47
I found a bug, here is a fixed version: [tmux-new-reflow3.diff.txt](https://github.com/tmux/tmux/files/1466297/tmux-new-reflow3.diff.txt)

I will probably test this for a few more days before I do anything else with it.

**Comment by nicm** [comment] 2017-11-15 19:23
I have applied these changes to OpenBSD now, they will be in GitHub later. Please let me know if you see any further issues. Thanks.

**Closed by nicm** 2017-11-15 19:23 UTC
