### ISSUE TITLE
Additional bottom pane status line e.g. `┴┴┴┴┴┴`  on multiple clients and `window-size smallest`

### ISSUE THREAD

**Issue by michalpokusa** [tmux/tmux#3943] opened 2024-04-14 23:03 UTC
### Issue description

Tested on latest build from GitHub and older releases first noticed on 3.2a but more than likely appears on even older builds.

The issue is, that when connected to same tmux window with multiple client with diffrent size of terminal window, an additional line with e.g. "┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴┴" appears. From my testing this is only the case when a custom `pane-border-format` is present and pane status is placed at the bottom.

Setting pane status format to anything other tahn empty string does not solve the issue, it simply displays the defined status line and then still displays the additional one.

![image](https://github.com/tmux/tmux/assets/72110769/78645905-ee32-4ba6-9e75-14909ad35dba)
![image](https://github.com/tmux/tmux/assets/72110769/e4f858f0-52b1-4d89-a529-76d8185107d8)

### Steps to reproduce

1. Install tmux
2. Create a `.tmux.conf` with configuration provided below
3. Start new session
4. Attach one client and resize terminal to small window size (not tmux window, the Desktop app window like Windows Terminal etc.)
5. Attach second client and resize terminal window to larger size than first one

### Minimal `.tmux.conf`

```
set-option -g window-size smallest
set-option -g pane-border-status bottom
set-option -g pane-border-format ""
```
### Required information

* tmux version (`tmux -V`).
tmux 3.4
* Platform (`uname -sp`).
Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
tmux-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).
I am not sure what I should provide here

**Comment by nicm** [comment] 2024-10-05 07:34
The issue is that with `bottom` the total height used for the window is different. You can see this by switching between `top`, `bottom` and `off` - `off` and `top` have the same size (the status line is taken as part of the pane with `off`) but `bottom` will actually make the window smaller. `window_find_string` and `window_pane_find_up` and `window_pane_find_down` account for this, but `screen-redraw.c` does not seem to.

I'm not sure why it works this way and we don't simply treat `bottom` like `top` and put the extra line as part of the pane...

**Comment by nicm** [comment] 2024-10-05 07:41
Ah, of course - when the window takes up the full terminal we do need to add an extra line for the pane status line, so the window size needs to be smaller...

**Comment by nicm** [comment] 2024-10-05 08:25
This fixes it for me: [bottom.diff.txt](https://github.com/user-attachments/files/17265552/bottom.diff.txt)

**Comment by michalpokusa** [comment] 2024-10-05 21:36
Thank you very much for looking into it!

I compiled tmux with your changes and it does in fact seem to solve the issue of additional line.
Unfortunately as a side effect the `pane-border-format` option seems to not work correctly.

Both screenshots with the same config file.

No changes:
![image](https://github.com/user-attachments/assets/18747688-0525-4787-93a7-12b33252fd6d)

After changes:
![image](https://github.com/user-attachments/assets/d8ac0a62-9533-4c90-8553-22075436b0b5)

When `set-option -g pane-border-status top`, it seems to work correctly.

![image](https://github.com/user-attachments/assets/0efcdf63-47dd-4a7a-8fa1-5a5dde754620)

**Comment by nicm** [comment] 2024-10-05 21:54
Hmm OK thanks I'll have to take another look.

**Comment by nicm** [comment] 2024-10-07 11:14
Please try this instead: [y.diff.txt](https://github.com/user-attachments/files/17277509/y.diff.txt)

**Comment by michalpokusa** [comment] 2024-10-07 20:32
> Please try this instead: [y.diff.txt](https://github.com/user-attachments/files/17277509/y.diff.txt)

I tried this change, with multiple `pane-border-format`, `pane-border-lines` and other configurations, and this one seems to work fine.

Thank you very much for looking into it.

**Comment by nicm** [comment] 2024-10-08 09:41
I have applied this to OpenBSD now, will be in GitHub later. Let me know if you see any other problems. Thanks!

**Closed by nicm** 2024-10-08 09:41 UTC
