### ISSUE TITLE
Mouse scrolling broken in nested tmux sessions

### ISSUE THREAD

**Issue by ltning** [tmux/tmux#2721] opened 2021-05-27 19:13 UTC
### Issue description

After upgrading from 3.1c to 3.2, mouse handling seems broken in my use case, which involves nesting (two levels) of tmux.
Mouse events (scrolling, in particular) are passed to the outermost tmux only, whereas previously they would be passed to whichever pane had focus.
I've tried to read the changelog (to the point that my eyes are now running ;), but apart from the "it's a lot", nothing obvious stands out.

TERM seems to be set to `screen` inside tmux. This is not something I'm doing in login/profile/tmux conf files. If I override this inside the outer tmux, and set xterm-256color, mouse seems to work (from a brief test), but as has always been the case, this breaks any number of other things so it's not really a solution.

Tested on same OS release and same tmux conf etc., but 3.1c, and confirmed it works there.

### Required information
tmux 3.2
FreeBSD 13.0-RELEASE-p1 amd64
Inside: TERM=screen
Outside: TERM=xterm-256color

Logs attached.
[tmux-server-63888.log](https://github.com/tmux/tmux/files/6556160/tmux-server-63888.log)
[tmux-client-63886.log](https://github.com/tmux/tmux/files/6556161/tmux-client-63886.log)
[tmux-out-63888.log](https://github.com/tmux/tmux/files/6556162/tmux-out-63888.log)

**Comment by topcat001** [comment] 2021-05-27 22:35
I tested this on my OpenBSD machine, in xterm. tmux built from git master in a nested session. I can use the mouse in both the outer and inner instances. `DECSET 1000+1006` also correctly reports coordinates in both cases. Can you please try git master and see if you are able to reproduce this?

**Comment by ltning** [comment] 2021-05-27 22:52
Built from master, tested in xterm and xfce4-terminal - same problem, still.
And confirmed (again) it works with the previous version.

**Comment by nicm** [comment] 2021-05-28 09:16
You do not appear to have the mouse enabled in this log, are you sure you reproduced the problem using the inner tmux server?

**Comment by ltning** [comment] 2021-05-28 10:36
I do indeed, and yes I did -- at least I thought I did.
Attached are more logs, from inside xterm - I explicitly did `set mouse on` in both parent and child (although my configuration takes care of that, normally). I did notice the `-f /dev/null`, which means I *may* have failed to actually enable the mouse in the inner one - but it makes no difference. See logs:

[tmux-client-11719.log](https://github.com/tmux/tmux/files/6560283/tmux-client-11719.log)
[tmux-out-11721.log](https://github.com/tmux/tmux/files/6560284/tmux-out-11721.log)
[tmux-server-11721.log](https://github.com/tmux/tmux/files/6560285/tmux-server-11721.log)

**Comment by nicm** [comment] 2021-05-28 10:58
Your `screen` terminfo entry does not have `kmous` (it must be very old), so tmux will not enable the mouse. Try doing this:
~~~~
set -as terminal-overrides 'screen*:kmous=\E[M'

**Comment by ThomasDickey** [comment] 2021-05-30 13:10
no - it can't be that **_old_**, because it's been part of ncurses for more than 20 years, and this is an issue reported in FreeBSD 13 (this year).  In that release, unless the ncurses port is installed, the system uses the termcap database, which has no setting for **`Km`** (the termcap equivalent to **`kmous`**).

On other systems, I'd suppose this could happen if some packager decided to install the [terminfo](https://git.savannah.gnu.org/cgit/screen.git/tree/src/terminfo/screeninfo.src) which is part of screen's sources (also lacking in the ["next" branch](https://git.savannah.gnu.org/cgit/screen.git/log/src/terminfo/screeninfo.src?h=next)), but don't recall anyone doing that for **_screen_** (just other programs whose developers rely upon alternate-facts).

**Comment by ltning** [comment] 2021-05-31 10:30
> set -as terminal-overrides 'screen*:kmous=\E[M'

Sorry for my late reply. Where should I do this? Outer or inner tmux? Before doing `set mouse on`? I've tried, but doesn't seem to be making a difference - though I'm not certain I'm doing it in the right place/time.

**Comment by nicm** [comment] 2021-05-31 12:07
Inner tmux. Make sure you are restarting tmux entirely after changing .tmux.conf.

**Comment by ltning** [comment] 2021-05-31 15:52
Adding that to .tmux.conf seems to have done the trick.
Is this something I can safely add to the default config that is pushed to all our systems, no matter which tmux version they're currently at?
Also, would this be considered a breaking change - especially if one can arrive at which change actually caused this? As stated by @ThomasDickey FreeBSD 13 is hardly old, and it's the new tmux - not new OS - that caused this to surface (not saying where the root cause is, as I imagine that could turn into a philosophical discussion).

**Comment by nicm** [comment] 2021-06-01 08:08
Yes, you can safely do this even on systems with a modern terminfo implementation.

**Comment by ltning** [comment] 2021-06-01 10:08
I'm confused - why close this issue? It's not something one can expect users to know/understand, and it's clearly an unintended side-effect of some other change in 3.2. It certainly won't affect only me; granted Linux owns the world these days but FreeBSD is neither obsolete nor irrelevant, I would think?

I'm just a user of tmux, and a quite simple one at that. Hence I have a hard time going from changelogs to having any idea what *might* have caused this, as I know painfully little about what's going on under the hood. But if there's anything I can realistically do to track down the root cause, please do let me know.

**Comment by nicm** [comment] 2021-06-01 10:13
tmux has always checked for the `kmous` capability before enabling the mouse. Are you sure you tested 3.1c and 3.2 on the same FreeBSD version and that both were linked against libtermcap (and not, for example, libncurses or libterminfo from ports?

**Comment by nicm** [comment] 2021-06-01 10:22
IIRC if you build tmux from ports after installing ncurses, it will use the ports ncurses rather than the system ncurses (even though the ports ncurses is not a dependency). Or if you build tmux from source yourself with ports ncurses installed it should pick it up.

I reported this to the tmux port maintainer a year or so ago but they didn't reply.

**Comment by ltning** [comment] 2021-06-01 14:53
> tmux has always checked for the `kmous` capability before enabling the mouse. Are you sure you tested 3.1c and 3.2 on the same FreeBSD version and that both were linked against libtermcap (and not, for example, libncurses or libterminfo from ports?

What's a good way of checking this? On the computer I'm writing this I'm running 13, and I have both 3.1c and 3.2 packages from upstream. I've tested both, including running `ldd $(which tmux)`, and output looks the same from both versions. Both are using libncurses, and the same version of it too. The difference is that 3.1c has working mouse in the child session, 3.2 does not.

Note that between the tests (logs attached) *no* other changes than the tmux version were made; no other packages/libraries were touched.

The only change to FreeBSD-specific build-time options since October 2020 happened on the same day the port was updated to 3.2: [Remove obsolete BACKSPACE option](https://cgit.freebsd.org/ports/commit/?id=fb0ec579e3d385d75a18df8ea8b8f2162606c484). I fail to see how this could be relevant. The upgrade to 3.2 itself only changed the version number; nothing else was changed (dependencies etc.)

[tmux-3.1c-log.zip](https://github.com/tmux/tmux/files/6577169/tmux-3.1c-log.zip)
[tmux-3.2-log.zip](https://github.com/tmux/tmux/files/6577171/tmux-3.2-log.zip)

**Comment by nicm** [comment] 2021-06-01 16:20
I'll have to look, maybe the check was broken in 3.1. In any case you are best to link tmux against the ports ncurses.

**Comment by ltning** [comment] 2021-06-02 21:31
> I'll have to look, maybe the check was broken in 3.1. In any case you are best to link tmux against the ports ncurses.

That is, unfortunately, not an option - and it feels wrong to pull in a library that already exists in base. Can you tell me a bit more about what would need to change in base for this to work out of the box - assuming the bug was in fact in 3.1 and was merely "fixed" in 3.2?

**Comment by nicm** [comment] 2021-06-03 08:53
It is still using the termcap database which was superseded by terminfo in the mid-1980s. termcap cannot express the full range of capabilities available in terminfo, and one of those is `kmous` which tmux uses to work out if the terminal supports the mouse sequences. This is how it is intended to be used, per curs_mouse(3):
~~~~
       Because there are no standard terminal responses that would serve to
       identify terminals which support the xterm mouse protocol, ncurses
       assumes that if your $TERM environment variable contains "xterm", or
       kmous is defined in the terminal description, then the terminal may
       send mouse events.
~~~~
It looks like tmux 3.1c incorrectly only checked `kmous` when tmux exits (to disable the mouse again) and not while tmux was running, this was fixed in 3.2 (in 37b7a29cc).

I'm not really inclined to change to ignore `kmous`, because it is working as intended at the moment, although it is unfortunate it does not work properly on FreeBSD. 

tmux knows it is running inside another tmux, so an option would be to force `kmous` on when that is the case, which would do no harm, although it would be good if this was straightened out on FreeBSD instead.

**Comment by nicm** [comment] 2021-06-03 09:00
You can try this to have tmux force `kmous` on when running in a terminal that it knows supports it, even if terminfo is incorrect: [tmux-kmous.diff.txt](https://github.com/tmux/tmux/files/6590310/tmux-kmous.diff.txt)

Don't forget to remove the `terminal-overrides` from `.tmux.conf`.

**Comment by derekschrock** [comment] 2021-06-08 00:31
I can confirm rebuilding tmux 3.2 from FreeBSD ports with tmux-kmous.diff does enable mouse support without the terminal-override.

**Comment by nicm** [comment] 2021-06-08 09:50
I have applied this now, thanks!

**Closed by nicm** 2021-06-08 09:50 UTC
