### ISSUE TITLE
[bug] server exits unexpectedly after running `tmux display-popup -h`

### ISSUE THREAD

**Issue by alexzanderr** [tmux/tmux#3281] opened 2022-07-28 16:02 UTC
### Issue description

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.
\> i tried to print some help for this command: `tmux display-popup -h`, but after running this command, server crashed.
```shell
❱  tmux display-popup -h
[server exited unexpectedly]
[0][#A]   [1]:zsh           %                                            

 [~]
      user:(...)
                         cmd:(took[2m 31s])
                                            ✘ exit:(code[1])
                                                            ❱
```
and also my prompt is destroyed.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.
\> well. on your changelog the latest is 3.3a, so im sure that on the latest

### Required information

Please provide the following information:

* tmux version (`tmux -V`). `tmux 3.3a`
* Platform (`uname -sp`). `Linux unknown`
* $TERM inside and outside of tmux (`echo $TERM`). `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`). `no logs`
* neofetch
```shell
❱  neofetch --json
{
    "OS": "Manjaro Linux x86_64",
    "Host": "GL553VD 1.0",
    "Kernel": "5.15.55-1-MANJARO",
    "Uptime": "43 mins",
    "Packages": "2082 (pacman)",
    "Shell": "zsh 5.9",
    "Resolution": "1920x1080",
    "DE": "Xfce 4.16",
    "WM": "Xfwm4",
    "WM Theme": "borderless-windows",
    "Theme": "Matcha-dark-aliz [GTK2], Adwaita [GTK3]",
    "Icons": "Papirus-Dark [GTK2], Adwaita [GTK3]",
    "Terminal": "alacritty",
    "CPU": "Intel i7-7700HQ (8) @ 3.800GHz",
    "GPU": "Intel  HD Graphics 630",
    "GPU": "NVIDIA GeForce GTX 1050 Mobile",
    "GPU": "NVIDIA GeForce GTX 1050 Mobile",
    "Memory": "6027MiB / 15886MiB",
    "GPU Driver": "ASUSTeK Computer Inc. Device [1043:15e0]",
    "CPU Usage": "14%",
    "Disk (/)": "135G / 213G (67%)",
    "Disk": "135G / 213G (67%)",
    "Battery0": "100% [Full]",
    "Battery": "100% [Full]",
    "Version": "7.1.0"
}
```

**Comment by Boodleboy** [comment] 2022-08-01 19:23
Reproduced. 
The -h option to `tmux display-popup` isn't help/usage, it's the height of the popup window. Passing the option without an argument seems to be causing a crash rather than an error. This crash also happens with the -w option, but not the -x, -y, -b, or any other of the options listed on the man page under display-popup

**Comment by alexzanderr** [comment] 2022-08-01 20:01
nice. thank you for investigating

**Comment by nicm** [comment] 2022-08-02 09:23
This should be fixed in OpenBSD now and will be in GitHub next time it syncs up (probably later today). Thanks!

**Closed by nicm** 2022-08-02 09:23 UTC
