### ISSUE TITLE
Hook `client-resized` strange resizing

### ISSUE THREAD

**Issue by finkandreas** [tmux/tmux#2995] opened 2021-12-04 14:29 UTC
I observe a strange behaviour for a hook that I have setup. I have 5 panes, three in the top row, two in the bottom row. And I have this hook in `tmux.conf`.
```
set-hook -g client-resized 'resize-pane -t progs.0 -x 100; resize-pane -t progs.2 -x 80'
```
progs.0 is the top-left pane, progs.2 is the top-middle pane. What I try to achieve is to have these two panes having a fixed width, while the top-right pane should grow/shrink.

When I resize slowly the hook works as expected, but resizing in large steps does not work correctly. A jump could be for instance maximizing the window, but also using `xdotool`
```
xdotool search --class XTerm windowsize 900 800 
xdotool search --class XTerm windowsize 1900 800 # incorrect resized panes
xdotool search --class XTerm windowsize 1920 800 # looks good
xdotool search --class XTerm windowsize 910 800 # incorrect
xdotool search --class XTerm windowsize 890 800 # looks good
```

It used to work with tmux-3.1, with 3.2 I had to change the hook slightly (I think it was a session hook before, but I'm not sure anymore what exactly I had to change) and since then it misbehaves.

The outer `$TERM` is either `xterm` or `alacritty`, same behaviour with both terminals. The windowmanager is openbox. Other system information:
```
anfink@anfink-laptop ~ $ tmux -V
tmux 3.2a
anfink@anfink-laptop ~ $ uname -sp
Linux Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
anfink@anfink-laptop ~ $ echo $TERM
tmux-256color

```

**Comment by nicm** [comment] 2022-02-03 07:52
What does "resizing in large steps does not work correctly" mean? Do the panes get the wrong size or do they not resize at all?

Please show server log from a single incorrect resize.

**Comment by finkandreas** [comment] 2022-02-03 08:41
I have created a video of the incorrect resizing. It starts with the layout that I want to have. Top-left is 100 characters wide, top middle is 80 characters wide, top-right is the rest.
First resize is reducing the window width in half. Top-left is clearly not 100 chars wide, top middle almost gone, top right kept its size.
Second resize is reducing the window height in half (width stays the same). Now top left is correctly 100 chars wide, top-middle is 80 chars wide, and top-right is the rest (not much left, but this is what I would expect)
Third resize is again full width. Clearly top-left is > 100 chars, top-middle > 80 chars and top-right still almost nothing.
Fourth resize is back to full height. Now we are back to the expected sizes.

https://user-images.githubusercontent.com/15714790/152307770-5adffc8a-e5e7-4443-9f6c-f914b8eb77ca.mp4

All further resizes are just for fun.

To answer your question: The panes get resized but they have sometimes the wrong sizes.
Regarding the server log. I tried sending SIGUSR2 to the running server, but no log was created. I will start it next time with the `-v` flag and come back when I have a log.

**Comment by finkandreas** [comment] 2022-02-15 10:49
Here is the log file when I resize by reducing the width from 2560px to 1280px 
[tmux-server-3414.log](https://github.com/tmux/tmux/files/8068417/tmux-server-3414.log)

**Comment by nicm** [comment] 2022-02-16 11:59
I cannot see the video (it says it is corrupt).

But from the log, it looks like the problem is that your hook is firing when the client resize is received, but the window resize is queued until later, so your `resize-pane` commands are taking place before the window is resized rather than after.

Please try applying this diff which adds a `window-resized` hook you can use instead: [x.diff.txt](https://github.com/tmux/tmux/files/8079674/x.diff.txt)

You will probably want to which window is being resized, something like:
~~~~
set-hook -g window-resized {
    if -F '#{==:#{window_name},progs}' {
        resize-pane -t progs.0 -x 100
        resize-pane -t progs.2 -x 80
    }
}

**Comment by finkandreas** [comment] 2022-02-16 19:30
Thanks for the patch, I'll give it a try. Regarding the video, I get corrupt video in firefox, a working one in chromium. Also right-clicking in firefox and copying the video link and playing it e.g. with mpv works fine: 
```
mpv https://user-images.githubusercontent.com/15714790/152309249-2b2efb0e-c7e7-40ed-a579-15482309bbf4.mp4
```

**Comment by nicm** [comment] 2022-02-17 09:58
Great, applied to OpenBSD now, will be in GitHub later. Thanks!

**Closed by nicm** 2022-02-17 09:58 UTC
