### ISSUE TITLE
Showing pane numbers when pressing prefix key stopped working

### ISSUE THREAD

**Issue by purpleP** [tmux/tmux#2473] opened 2020-11-21 02:29 UTC
You taught me the trick on how to show pane numbers when pressing prefix key.
@nicm 
```
set -g prefix none
bind -n C-Space display-panes -b "select-pane -t '%%'; switchc -Troot"\; switchc -Tprefix
```
It stopped working for me on the latest master (I was experimenting with popup windows and they are awesome!).
I've bisected the issue to this commits.

When this trick is active first press of `n` or `w` isn't registered (next window and choose-tree).

```
$ git bisect visualize
commit a0fee328bf7d2cefe047f3911e7e29955f14a75a (refs/bisect/bad)
Merge: b895ffbf 60860ace
Author: Thomas Adam <thomas@xteddy.org>
Date:   Tue Sep 1 12:01

    Merge branch 'obsd-master'

commit 60860aced8d424ef6c1d527b63842a0ea0f452ad (HEAD)
Author: nicm <nicm>
Date:   Tue Sep 1 09:19

    Add -F to set-environment and source-file; GitHub issue 2359.

commit b2a262e35357228d01f93f81ab57df204fdbaef0
Author: nicm <nicm>
Date:   Tue Sep 1 08:50

    Only print below number when there is enough space.
```
Unfortunately on `60860` I can't build tmux to bisect further.

Hope you can restore this trick as I like it very much!

PS
By the way it stops working for the second or the third time already, maybe this can be done in a more general way if you would add hook to pressing prefix key so that users would be able to see the clock or whatever they want automatically?

**Comment by nicm** [comment] 2020-11-23 08:31
This still works OK for me? Show logs?

**Comment by purpleP** [comment] 2020-11-24 20:01
> This still works OK for me? Show logs?

I can reproduce the issue even with this tmux config

```
set -g prefix none

unbind C-b
bind -n C-Space display-panes -b "select-pane -t '%%'; switchc -Troot"\; switchc -Tprefix
```

I've probably haven't been clear enough. When I press `C-space` I see pane numbers, but when I press `w` after that I don't see window tree. When I press `w` second time I see it.

**Comment by nicm** [comment] 2020-11-24 20:36
Hmm yes I think I see, I'll take a look.

**Comment by nicm** [comment] 2020-11-25 08:32
Ah, the problem is that we added [a-z] keys to display-panes to switch to windows 0-9. Can you try this which adds a -N flag to disable keys in display-panes: [tmux-display-panes-N.diff.txt](https://github.com/tmux/tmux/files/5595337/tmux-display-panes-N.diff.txt)
 
Then you can add -N:
~~~~
set -g prefix none
bind -n C-b display-panes -Nb "select-pane -t '%%'; switchc -Troot"\; switchc -Tprefix

**Comment by purpleP** [comment] 2020-11-25 20:14
> Ah, the problem is that we added [a-z] keys to display-panes to switch to windows 0-9. Can you try this which adds a -N flag to disable keys in display-panes: [tmux-display-panes-N.diff.txt](https://github.com/tmux/tmux/files/5595337/tmux-display-panes-N.diff.txt)
> 
> Then you can add -N:
> 
> ```
> set -g prefix none
> bind -n C-b display-panes -Nb "select-pane -t '%%'; switchc -Troot"\; switchc -Tprefix
> ```

Yep, that fixes it for me! You're the best!

**Comment by nicm** [comment] 2020-11-26 09:19
Applied to OpenBSD now, will be in GitHub later. Thanks!

**Closed by nicm** 2020-11-26 09:19 UTC
