### ISSUE TITLE
Memory leak since 46f642b0

### ISSUE THREAD

**Issue by avih** [tmux/tmux#1660] opened 2019-03-29 07:54 UTC
I noticed that after some time the tmux server process was using lots of memory (~50M compared to ~5M usually). I bisected it a bit and narrowed it down to the following key commits:

52cb7a63 : (current master): BAD

320237fd : OK

46f642b0 : BAD, which means the offending commit is "8b74e959 Include window-status-style and window-status-current style in the format". This is weird because there's no actual code change at this commit, so I suspect it just triggers an existing but unexposed issue.

bff957a4 : BAD. This is after "458b8715 Do not leak ranges on error" so either it didn't fix it correctly or there are still more/new fixes to be done.

Steps to notice the leak fast-ish, by retriggering redraws of the status line:

Use this config:
```
set -g status-left ""
set -g status-right ""
set -g status-interval 1
```

Then start tmux and run the following loop from shell in a pane:
```sh
 while : ; do path/to/tmux set -g status-interval 15; done
```

And notice that with 320237fd the server process memory doesn't increase, while with all the BAD commits it does increase.

**Comment by nicm** [comment] 2019-03-29 08:02
Reproduce in valgrind please and show me the "out" file after exiting tmux:
~~~~
valgrind --leak-check=yes --log-file=out --trace-children=yes --trace-children-skip=\*sh tmux -Ltest new

**Comment by avih** [comment] 2019-03-29 08:04
Sorry, I don't have a valgrind setup.

**Comment by nicm** [comment] 2019-03-29 08:07
Show tmux logs please.

**Comment by avih** [comment] 2019-03-29 08:15
I'll upload client/server logs soon after I remove private date in them.

Should I understand that you cannot reproduce the leak at 46f642b ?

**Comment by nicm** [comment] 2019-03-29 08:17
I can't reproduce but I may be missing something obvious.

**Comment by avih** [comment] 2019-03-29 08:34
This was observed on cygwin. If you can't find anything then I'll try to reproduce it elsewhere.

These logs are with the same config and procedure described above, the loop running about 10s, with tmux master.
[tmux-leak-52cb7a63.zip](https://github.com/tmux/tmux/files/3021733/tmux-leak-52cb7a63.zip)

**Comment by nicm** [comment] 2019-03-29 09:29
Turns out I was running the wrong binary, I can see it now.

**Comment by nicm** [comment] 2019-03-29 09:33
This is the fix:
~~~~
diff --git a/format.c b/format.c
index e6354b5a..a5c61d68 100644
--- a/format.c
+++ b/format.c
@@ -1041,7 +1041,9 @@ format_choose(struct format_tree *ft, const char *s, char **left, char **right,
 
 	if (expand) {
 		*left = format_expand(ft, left0);
+		free(left0);
 		*right = format_expand(ft, right0);
+		free(right0);
 	} else {
 		*left = left0;
 		*right = right0;

**Comment by nicm** [comment] 2019-03-29 09:44
Applied to OpenBSD now, will be in GitHub later. Thanks!

**Closed by nicm** 2019-03-29 09:44 UTC

**Comment by avih** [comment] 2019-03-29 10:19
Confirmed fixed by that patch. Thanks.
