### ISSUE TITLE
Commit 2f854969 messes shell prompt

### ISSUE THREAD

**Issue by amosbird** [tmux/tmux#768] opened 2017-02-09 08:59 UTC
It messes shell prompt by one line ![](https://ptpb.pw/UuSo.jpg)

```
centos 6.8
gcc 6.3
ncurses 6.0
libevent 2.1.8
fish shell 2.5.0
```

**Comment by nicm** [comment] 2017-02-09 09:04
... TERM? Logs? Content of the prompt?

**Comment by nicm** [comment] 2017-02-09 09:06
And terminal also.

**Comment by amosbird** [comment] 2017-02-09 09:39
```
inside tmux  TERM = tmux-256color
outside tmux TERM = xterm-256color
fish prompt = " ❯ "
fish right prompt = last command duration
terminal  =  urxvt
```
fish prompt functions are [here](https://ptpb.pw/bifF)

tmux server logs are [here](https://ptpb.pw/U1VZ)

**Comment by nicm** [comment] 2017-02-09 09:52
Looks like your prompt has UTF-8 in it, I just committed a change to OpenBSD which may fix this, please wait until it appears in GitHub (commit message is "When an ordinary (not collected) cell is received, we need to flush any delayed scrolling before drawing it.")

**Comment by amosbird** [comment] 2017-02-09 10:18
thanks, it works.

**Comment by amosbird** [comment] 2017-02-09 15:21
well, another issue surfaced.  Here is the [screencast](https://asciinema.org/a/3jcp07w8p3tfe0z08ri7igrz9)

**Comment by nicm** [comment] 2017-02-09 15:38
Logs.....

**Comment by amosbird** [comment] 2017-02-09 16:16
Weird, `tmux -vvvv -Ltest -f/dev/null new` has no such problem. Sorry for the noise I've made. Next time I'll make sure it's reproducable before firing bugs :smiley:

**Comment by amosbird** [comment] 2017-02-12 15:22
This issue recurs. [Here is the server log](https://ptpb.pw/YAzB)

**Comment by nicm** [comment] 2017-02-12 17:26
Can you reproduce this?

If so, please do it inside tmux and also inside script(1), then give me the matching tmux-server*.log, tmux-out*.log and typescript files.

**Comment by nicm** [comment] 2017-02-12 17:27
That is, do this:

tmux -Ltest -vvvv new
script
<output that reproduces problem>
exit
exit

Then give me the three files.

**Closed** 2017-02-15 10:28 UTC

**Comment by hattya** [comment] 2017-02-16 11:45
I've encountered same issue.

The issue is introduced in commit 6ea36af, and it seems that following patch fixes the issue.
```diff
--- a/tty.c
+++ b/tty.c
@@ -1321,7 +1321,7 @@ tty_region(struct tty *tty, u_int rupper, u_int rlower)
 		tty_cursor(tty, 0, tty->cy);
 
 	tty_putcode2(tty, TTYC_CSR, tty->rupper, tty->rlower);
-	tty->cx = tty->cy = 0;
+	tty_cursor(tty, 0, 0);
 }
 
 /* Turn off margin. */
```

**Comment by nicm** [comment] 2017-02-16 11:48
What terminal?

**Comment by hattya** [comment] 2017-02-16 12:31
I'm using [RLogin](http://nanno.dip.jp/softlib/man/rlogin/). (in Japanese)

**Comment by nicm** [comment] 2017-02-16 12:41
I don't think it is the same problem, since rxvt-unicode seems to return
the cursor to 0,0 after CSR and I am guessing your terminal does not
(which is a bug in the terminal). But I think this is a better
workaround in tmux, can you try this instead?


Index: tty.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/tty.c,v
retrieving revision 1.248
diff -u -p -r1.248 tty.c
--- tty.c	15 Feb 2017 11:22:13 -0000	1.248
+++ tty.c	16 Feb 2017 11:49:28 -0000
@@ -1321,7 +1321,7 @@ tty_region(struct tty *tty, u_int rupper
 		tty_cursor(tty, 0, tty->cy);
 
 	tty_putcode2(tty, TTYC_CSR, tty->rupper, tty->rlower);
-	tty->cx = tty->cy = 0;
+	tty->cx = tty->cy = UINT_MAX;
 }
 
 /* Turn off margin. */
@@ -1359,7 +1359,7 @@ tty_margin(struct tty *tty, u_int rleft,
 	else
 		snprintf(s, sizeof s, "\033[%u;%us", rleft + 1, rright + 1);
 	tty_puts(tty, s);
-	tty->cx = tty->cy = 0;
+	tty->cx = tty->cy = UINT_MAX;
 }
 
 /* Move cursor inside pane. */

**Comment by hattya** [comment] 2017-02-16 12:53
It works, thank you!

**Comment by nicm** [comment] 2017-02-16 12:57
Applied, thanks!
