### ISSUE TITLE
Mouse scrolling in tmux 2.1 on OSX no longer auto-starts

### ISSUE THREAD

**Issue by victorhooi** [tmux/tmux#145] opened 2015-10-19 04:50 UTC
I have installed `tmux` via Homebrew on OSX.

I have just upgraded from tmux 2.0 to 2.1.

I read the changelog, which mentioned the mouse options changed, so my `~/.tmux.conf` file now has:
``
set-option -g mouse on
```

Previously I was able to start scrolling immediately - that is, scrolling upwards would go into copy-mode automatically, and then if I scrolled back to the bottom it exited automatically.

However, apparently in 2.1 this feature was removed (although it wasn't mentioned in the changelog) - I read it here:

http://www.davidverhasselt.com/better-mouse-scrolling-in-tmux/

My question is - would it be possible to add the auto-start to scrolling, and auto-exit back in?

**Comment by victorhooi** [comment] 2015-10-19 04:52
Also, I should mention that the workaround on that page:
```bind -n WheelUpPane copy-mode
```
does not work for me - all it seems to do is break mouse scrolling, so that even if I try to enter in copy-mode, it doesn't even work there when this option is enabled.

**Comment by NHDaly** [comment] 2015-10-19 09:13
I've gotten it to work with this command ([link to the commit in my dotfiles](https://github.com/NHDaly/nhdaly_dotfiles/commit/030d82c15cc6c12971f59b2bf14497da5ca01459)):

```
# Start copy mode when scrolling up and exit when scrolling down to bottom.
# The "#{mouse_any_flag}" check just sends scrolls to any program running that
# has mouse support (like vim).
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -    e'"
```

**Comment by apriendeau** [comment] 2015-10-19 17:52
@victorhooi @NHDaly 's plugin returns this to normal behavior for me.

**Comment by jlowgren** [comment] 2015-10-20 09:11
Having issues with this after upgrading to 2.1. Any hints on how to get the same behavior as before would be great.

**Comment by adamk33n3r** [comment] 2015-10-20 14:28
@jlowgren Very odd. It seems @NHDaly is no longer an account on github. He had a repository that had a plugin which brought back the behavior. Luckily I cloned the repo before this happened. I've pushed it up here: https://github.com/adamk33n3r/tmux-scroll-copy-mode

**Comment by mdibaiee** [comment] 2015-10-20 20:19
Same problem here, @NHDaly's plugin works like a charm. Probably we can get this merged to tmux?

**Comment by ThomasAdam** [comment] 2015-10-20 20:29
No,

There's nothing to merge in here.  Tmux is meant to be scriptable.  Enjoy!

Thomas Adam

**Closed by ThomasAdam** 2015-10-20 20:29 UTC

**Comment by victorhooi** [comment] 2015-10-20 22:17
I understand that it's scriptable - and that is awesome.

However, it seems like a lot of people were quite used to, or preferred the old behaviour in Tmux 2.0 and before.

Is there any chance this could simply be added as an option?

Or are there technical or UI reasons why the new behaviour (needing to explicitly call Ctrl + B + ] to scroll) is superior? I'm assuming there was a reason for the change, just curious why.

**Comment by nicm** [comment] 2015-10-20 22:28
Show me the key bindings you are using now.

The old behaviour changed around because the few people who cared about
it could never agree on whether it should scroll 1 line or 3 lines or 10
lines or just inside copy mode or outside or what. So now you can
configure it yourself.

But I might add a default binding if it looks sensible.

**Comment by adamk33n3r** [comment] 2015-10-20 22:31
@nicm speaking of number of lines scrolled, is there a config option for that? I couldn't find anything on the subject.

**Comment by nicm** [comment] 2015-10-20 22:48
No, I had something but nobody asked for it so it was dropped. I think this was it http://pastebin.ca/raw/3209063, it should still work.

**Comment by NHDaly** [comment] 2015-10-20 23:20
@nicm: I think the default key binding would be:

bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"

**Comment by nicm** [comment] 2015-10-21 11:14
Yes this is reasonable, I've added it.

**Comment by victorhooi** [comment] 2015-10-22 00:56
@ncim @NHDaly Just to clarify - the above keybinding is only for *entering* copy mode, right?

As in, do we need a second one to exit out of copy-mode, when you scroll back down to the bottom? (I believe 2.0 did this).

**Comment by NHDaly** [comment] 2015-10-22 02:20
No, it's both -- the `-e` on `copy-mode -e` sets it to exit when scrolling
down to bottom.

**Comment by builtinnya** [comment] 2015-10-24 01:59
@NHDaly 's solution works for me. Thanks a lot!
```
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"
```

**Comment by milosivanovic** [comment] 2015-10-26 09:14
Am I missing something? I've added:

```
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"
```

to my .tmux.conf, and I am not able to get the old behaviour back. I'm running commit e95df0bc, HEAD at this point.

**Comment by milosivanovic** [comment] 2015-10-26 09:53
Ah, sorry, I had a previous instance of tmux running which caused it to not use the updated settings even though I was starting a fresh instance of tmux.

With everything working right it seems like all that's missing is specifying how many lines to skip. Previously on my configuration it was 5, but now it's only skipping 1 line. Is this currently possible?

**Comment by milosivanovic** [comment] 2015-10-26 09:57
I've also noticed that with the proposed workaround, one scroll is required to enter copy mode, whereas before, the initial scroll entered copy mode *and* scrolled 5 lines in one go. Will this be possible to configure with the new version as well? I am just trying to get everything exactly back to the way it was before.

**Comment by milosivanovic** [comment] 2015-10-26 10:53
I was able to get the original functionality with a small change to @NHDaly's bind configuration. I kindly ask @nicm that you include this in the official default for backwards-compatibility's sake (replacing what @NHDaly had).

```
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e; send-keys -M'"
```

The difference is the addition of `send-keys -M` at the end.

There is one last difference I noticed, and that's if you left-click-and-hold inside the tmux session while in copy mode, it no longer highlights the character at the cursor, and when you let go, it no longer exits copy mode. You now have to highlight more than one character. I have become accustomed to exiting copy mode by just doing a single click, so it would be ideal to have this function the same as version 2.0 for backwards-compatibility reasons. If there is an argument against this then at least a way to configure it manually would be much appreciated.

**Comment by milosivanovic** [comment] 2015-10-26 12:09
I've unfortunately encountered another regression. I'm not sure I should just open a bug listing them all, since they all seem to be related to automatic mouse scrolling, which this bug addresses.

The latest regression stops users from scrolling the pane that the mouse is currently hovering over. Prior to version 2.1, with the help of mouse-select-pane, it was possible to hover over any pane of your choice and scroll up or down to automatically initiate copy mode without having to click into the pane (or select it using the keyboard.) You now have to select each pane manually before scrolling.

You can see all of these regressions impact one's productivity. I think it goes without question that if you, and I quote, specify:

```
Mouse-mode has been rewritten.  There's now no longer options for:
	- mouse-resize-pane
	- mouse-select-pane
	- mouse-select-window
	- mode-mouse

  Instead there is just one option:  'mouse' which turns on mouse support
  entirely.
```
(from https://raw.githubusercontent.com/tmux/tmux/e95df0bc3982ef7367b48236837069013642be14/CHANGES)

then this new mode 'mouse' is, by definition, meant to do exactly the same as all of the previous options had done by default, which it is not. This breaks all common sense rules about backwards compatibility. It goes without saying that all of these issues need to be addressed and resolved to fully restore backwards compatibility with earlier versions. The given reason that initiated all of these changes ("whether it should scroll 1 line or 3 lines or 10
lines or just inside copy mode or outside") does not in any way make it acceptable to break backwards compatibility.

If you would like me to open a new issue listing mouse-related regressions, I'm more than happy to do so.

**Comment by milosivanovic** [comment] 2015-10-26 12:52
I managed to find the required configuration to allow selecting the pane with the mouse wheel, thanks to Thomas Sattler (https://groups.google.com/d/msg/tmux-users/TRwPgEOVqho/Ck_oth_SDgAJ):

```
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M
```

This should be the built-in default.

I was not able to find the configuration to enter and exit copy mode on single click, which is the only outstanding regression. If someone is aware of what it is, it would be great to add that as a default as well for reasons previously mentioned.

**Comment by brentvatne** [comment] 2015-10-27 05:40
@milosivanovic - that fix works great :smile: agreed, this should be the default.

**Comment by tlhunter** [comment] 2015-10-28 00:51
:+1: @milosivanovic

**Comment by yan12125** [comment] 2015-10-28 03:11
@NHDaly's plugin works for me, too - tested on Arch Linux x86_64 with tmux 2.1-1. :+1:

**Comment by ppiekarczyk** [comment] 2015-10-29 03:15
:tada: I'm so happy I found this

**Comment by wiserfirst** [comment] 2015-10-29 11:19
@milosivanovic Thank you very much! After adding the two lines in tmux config, mouse scrolling works just as before :tada:

**Comment by builtinnya** [comment] 2015-10-29 11:21
@milosivanovic :tada: working perfectly!

**Comment by siphiuel** [comment] 2015-10-29 11:24
@milosivanovic - confirmed:) Thanks so much!

**Comment by grandfatha** [comment] 2015-11-01 17:28
@milosivanovic thx bruh was already going crazy af fam

**Comment by Dalvenjia** [comment] 2015-11-03 21:07
Works great, but one line scrolling is a PITA.
Add after @milosivanovic solution to scroll half a page:

    bind -t vi-copy WheelUpPane halfpage-up
    bind -t vi-copy WheelDownPane halfpage-down

change vi-copy to emacs-copy if you're using emacs mode

Credit to John Whitley @ the official mailing-list: https://groups.google.com/forum/#!topic/tmux-users/LNjtjCrVO0A

**Comment by dragonxlwang** [comment] 2015-11-13 16:47
@milosivanovic 's approach set it to 5 ln AFAIK

**Comment by moeabdol** [comment] 2015-11-29 15:20
:+1: @milosivanovic @Dalvenjia

**Comment by jedahan** [comment] 2015-11-30 16:43
@milosivanovic :astonished: that works perfectly, thank you!

**Comment by flov** [comment] 2015-12-01 16:03
@milosivanovic AWESOME! Thank you, it took me ages to fix this.

**Comment by amaltson** [comment] 2015-12-21 12:45
@milosivanovic thank you so much! Was afraid I just lost my mouse support!

**Comment by riesebie** [comment] 2015-12-21 20:17
* Arthur Maltson <notifications@github.com> [2015-12-21 04:45 -0800]:

> @milosivanovic thank you so much! Was afraid I just lost my mouse support!

Which won't be a drama ;-)

Elimar
-- 
 "Talking much about oneself can also
   be a means to conceal oneself."
         -Friedrich Nietzsche

**Comment by genexp** [comment] 2016-01-03 14:52
Thank you @milosivanovic!

**Comment by grandfatha** [comment] 2016-01-10 15:03
The change really saddens me. I love this tool to switch between different working environments. I use tmuxinator to start up a specific proejct setup and virtual environments. It helps me a lot. But lately the ease of use has been reduced because I can no longer scroll back as much as I want and


What is the configuration I need to add to allow me to

- easily select and copy text from specific panes
- allow me to easily resize any pane
- allow me to scroll back as much as i want without switching modes and without using a shortcut that requires the "[" key as that does not work right on german keyboards (at least in IntelliJ or PyCharm)
- reset the output / clear a single pane without destroying the layout


Thanks a lot for your help!

**Comment by nh2** [comment] 2016-01-13 12:48
@milosivanovic's solution doesn't seem to work in mosh (it does it in SSH), does anybody know what might be going on?

**Comment by nh2** [comment] 2016-01-13 12:57
Ah, upgrading from mosh 1.2.4 to 1.2.5 fixed it (https://github.com/mobile-shell/mosh/issues/101#issuecomment-165936476).

**Comment by tclh123** [comment] 2016-01-13 13:09
Conclusion:

```
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M
bind -n C-WheelUpPane select-pane -t= \; copy-mode -e \; send-keys -M
bind -t vi-copy    C-WheelUpPane   halfpage-up
bind -t vi-copy    C-WheelDownPane halfpage-down
bind -t emacs-copy C-WheelUpPane   halfpage-up
bind -t emacs-copy C-WheelDownPane halfpage-down
```

**Comment by dimosz** [comment] 2016-01-14 10:41
@milosivanovic thanks.

**Comment by amartins** [comment] 2016-01-14 22:16
Thanks @tclh123!

**Comment by loliee** [comment] 2016-01-20 14:21
Thanks @milosivanovic !

**Comment by bdossantos** [comment] 2016-01-20 14:23
:+1:

**Comment by Spitfire988** [comment] 2016-01-21 17:04
If there a way I can update the .conf file to scroll more then whats visible? I'm on version 2.2 now and have added @milosivanovic code.

**Comment by dragonxlwang** [comment] 2016-01-21 17:28
@Spitfire988: 
```
# Once in copy-mode, mouse wheel scrolls scrolls by half pages
bind -temacs-copy WheelUpPane   halfpage-up
bind -temacs-copy WheelDownPane halfpage-down
```

**Comment by casperklein** [comment] 2016-01-24 19:22
I've just used tclh123's conclusion. That works for me, except two things:

Before version 2.1, I could exit "scrolling" by just clicking the left mouse button somewhere in the pane. Now I have to press the ESC key.

I also noticed, that its not possible anymore, placing the mouse at the status bar and using the scroll wheel to select a window.

**Comment by dragonxlwang** [comment] 2016-01-24 19:34
for the 2nd, you might bind "WheelUpStatus" with "next-window"

**Comment by casperklein** [comment] 2016-01-24 19:57
@dragonxlwang thanks for the hint. I tried adding the following to my .tmux.conf:

    bind -n WheelUpStatus next-window
    bind -n WheelDownStatus previous-window

But that didn't work.

**Comment by michahell** [comment] 2016-01-26 17:54
Tried some proposed solutions for Tmux 2.1 on OSX 10.10.5, but they don't work :-1: 
I really like tmux but at the same time... Sorry tmux, scrolling is really better using a scroll wheel or touchpad. Hence, their invention. You can make it hard or impossible for new users to configure tmux to work with a mouse or touchpad but that won't change this fact :)

**Comment by whitlockjc** [comment] 2016-02-13 18:08
I have the same issue as @michahell.  I tried a few different options, like the one from @milosivanovic, and none of it seems to work.  Maybe I have the wrong expectation but from what I understand, the following configuration should make it so that using my mouse wheel or trackpad in a pane to scroll should enter/exit copy mode automatically and scroll appropriately:

```
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M
```

If my expectations are wrong, let me know but just in case I'm not, here are my environment details:

* OS X 10.10.5
* Terminal.app 2.5.3
* tmux 2.1
* zsh 5.2

Also, scrolling works just fine if I enter/exit copy-mode manually so maybe my expectations are just wrong.

**Comment by jdalt** [comment] 2016-02-16 03:07
I applied @milosivanovic changes and that improved the situation, but I have the same issue outlined in https://github.com/tmux/tmux/issues/145#issuecomment-174332645 by @casperklein: I can no longer exit with a click.

I'm only able to exit copy mode by hinting enter which is extremely annoying since the enter key is typically used by my right hand.

Any way to get the *exact* behavior of tmux 1.9a would be greatly appreciated.

**Comment by dragonxlwang** [comment] 2016-02-16 03:23
@jdalt : per your specific concern, you can actually use "q" instead of "enter" to exit which should be easily reached by your left palm

**Comment by DeepAnchor** [comment] 2016-02-17 01:31
unfortunately this seems to be broken yet again with osx 10.11.3 update even with milosivanovic's patch

**Comment by gtmax** [comment] 2016-02-23 15:41
What about the case of alt- (or option- on Mac) + left mouse click and subsequent scroll to copy? This works when scrolling up, but not when scrolling down (scrolling simply doesn't happen). Any way to fix this?

**Comment by romeovs** [comment] 2016-02-28 22:52
I got scrolling to work using:

```
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M
bind -n C-WheelUpPane select-pane -t= \; copy-mode -e \; send-keys -M
bind -t vi-copy    C-WheelUpPane   halfpage-up
bind -t vi-copy    C-WheelDownPane halfpage-down
bind -t emacs-copy C-WheelUpPane   halfpage-up
bind -t emacs-copy C-WheelDownPane halfpage-down
```

yet it seems to only work once. I can scroll up once (as far as I want) and when I scroll down, tmux leaves copy-mode. After that scrolling does not work anymore.

**Comment by subfuzion** [comment] 2016-03-25 05:35
@milosivanovic You're [fix](https://github.com/tmux/tmux/issues/145#issuecomment-151098708) just saved my evening. Thank you!

**Comment by xapple** [comment] 2016-03-27 16:34
The scrolling speed with only one line at the line is much too slow. But the half-page fix proposed here is much too fast and destroyes the impression of scrolling by replacing it with only the sensation of jumping. To make the scroll go at a custom speed you can add several `send-keys` commands like this:

    # Scrolling in tmux
     set -g mouse on
     bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M; send-keys -M; send-keys -M; send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M; send-keys -M; send-keys -M; send-keys -M' 'copy-mode -e; send-keys -M; send-keys -M; send-keys -M; send-keys -M'"
    bind -n WheelDownPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M; send-keys -M; send-keys -M; send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M; send-keys -M; send-keys -M; send-keys -M' 'copy-mode -e; send-keys -M; send-keys -M; send-keys -M; send-keys -M'"

**Comment by mamiu** [comment] 2016-03-27 18:07
@xapple Thanks that's awesome! :+1:

**Comment by mamiu** [comment] 2016-03-27 18:39
@NHDaly's plugin works like a charm! Thanks a lot :+1: 

https://github.com/tmux/tmux/issues/145#issuecomment-149153883

**Comment by giddie** [comment] 2016-03-29 11:46
Has anyone yet found a way to permit scrolling in `less` (i.e. sending key events when in alternate buffer that doesn't support mouse interaction) with tmux 2.1?

**Comment by xapple** [comment] 2016-03-29 12:08
Well if you use iTerm2 you can activate the option "Scroll wheel sends arrow keys when in alternate screen mode". But turning that on will make it incompatible with the tmux fix here.

**Comment by NHDaly** [comment] 2016-03-29 16:19
The latest version of my plugin [NHDaly/tmux-scroll-copy-mode](http://github.com/NHDaly/tmux-scroll-copy-mode) has an option to disable the scroll-wheel while in alternate screen mode: NHDaly/tmux-scroll-copy-mode#6.

It's `off` by default but you can turn it on like this:
`set -g @prevent-scroll-for-fullscreen-alternate-buffer 'on'`

It shouldn't be too hard to modify that option to instead just send the arrow keys instead of sending nothing, but I haven't gotten around to it yet. Feel free to send me a pull request or open an issue! :)

**Comment by giddie** [comment] 2016-03-30 07:53
Thanks @NHDaly. I've already enabled that option in your plugin. I'll take a look at the code to see if I can modify it to send arrow keys. Pull request coming up :)

**Comment by lpender** [comment] 2016-04-29 16:21
I really enjoy tmux but how is that the talented developers behind it do not respect [semver](http://semver.org/)?

> 1. MAJOR version when you make incompatible API changes,

This change to the API should have been tmux 3.0, not 2.1, *or* they should have supported-but-deprecated the previous API.

**Comment by nicm** [comment] 2016-04-29 16:49
I disagree - as the founder and Head Bossy Boots of the newly created _Campaign For Version Numbering That I Like, If You Please, Thank You Very Much_ (CFVNTILIYPTYVM), I contend that the correct way to number releases is 1, 2, 3, 3.1, 95, 98, 2000, XP, Vista, 7, 8, 8.1, 10. I shall be contacting Mozilla, Google and Apple to demand that they comply with this - clearly superior - scheme forthwith. Naturally I expect they will comply, at which point I plan to release tmux Vista Snow Lion 2016.

**Comment by lpender** [comment] 2016-04-29 17:23
Lol 

Might as well make it 3016 and future proof it

**Comment by dave-kennedy** [comment] 2016-05-04 04:22
I use st and openbox, and for some reason @milosivanovic's bindings cause the terminal to close. The following accomplishes what I want: scroll pane under cursor on mouse up and enter copy mode:

```
set-option -g mouse on
bind-key -T root WheelUpPane select-pane -t =\; copy-mode -e\; send-keys -M
```

**Comment by geoherna** [comment] 2016-06-27 18:19
@NHDaly's solution worked perfectly for using scroll to enter copy mode. Excellent work.

**Comment by chellberg** [comment] 2016-09-14 17:56
The above solutions worked for me for a while, and then something somewhere updated (either os x or iterm or tmux) and then none of them worked.

Fix:

`set-option -g mouse on` (I don't appear to need the Bindwheel stuff now)
`brew reinstall --HEAD tmux`

**Comment by whitlockjc** [comment] 2016-09-14 18:55
I've come to the conclusion that the issue is `Terminal.app`.  I'm on OS X `10.10.x` and with `Terminal.app`, mouse mode of any kind fails to work.  Using `iTerm.app`, the same configuration works as expected.  I hear newer versions of `Terminal.app` have mouse reporting but the one I'm using, and likely versions before it, do not.

**Comment by jeremyjjbrown** [comment] 2016-09-22 04:19
@chellberg Your solution worked for me as well. Thanks.

**Comment by tommyjcarpenter** [comment] 2016-12-18 18:19
I'm using 

```
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M
```

but when I start scrolling, it always scrolls the leftmost pane, and not whatever pane I currently have selected. How do I configure it to scroll the pane I'm in?

**Comment by ar0ra1** [comment] 2017-10-11 19:10
I tried all, the scrolling works fine until i start use vi 
it no longer scrolls in vi 
any solution to that ?

**Comment by leehambley** [comment] 2017-10-11 19:25
Not even sure it's possible to get him to scroll with a mouse in the
terminal with or without tmux.

**Comment by ar0ra1** [comment] 2017-10-11 19:34
@leehambley 
if i remove the binding and set option from the tmux.conf
i can scroll in vim
with or without tmux, it works fine.

but not when using `set -g mouse on`

**Comment by ar0ra1** [comment] 2017-10-12 06:01
Found the solution,
For tmux 2.1 +
in `tmux.conf`
 > set -g mouse on

And in `.vimrc`

> set mouse=a

**Comment by tommyjcarpenter** [comment] 2017-10-12 15:16
@ar0ra1 solution seems to work for me, with the caveat that, in TMUX, scrolling the mouse scrolls up the commands as if you pressed the up arrow key many times. It does not automatically enter the "ctrl-b [" mode where you scroll up in the terminal itself. I was hoping for a way for mouse to automatically enter the "ctrl-b [" mode. 

However @ar0ra1's solution definitely fixes my vim so that it has the behavior I desire where it scrolls in the terminal itself (like up in the source file).

**Comment by ar0ra1** [comment] 2017-10-12 19:23
@tommyjcarpenter it actually requires you to scroll two times, first time to initiate `C-b [` 
then second time is your natural scrolling 

the problem I next faced was eventually of the default copy paste operation, since tmux doesn't actually copy it to the OS's clipboards, instead to its copy buffer. 

But then, holding down the shift key for selecting and right clicking fixed that.
