### ISSUE TITLE
Pass through C-j, C-m and C-i in extended-keys mode

### ISSUE THREAD

**Issue by vbauerster** [tmux/tmux#2708] opened 2021-05-12 11:30 UTC
With `extended-keys on` option I'm able to bind `C-j`, `C-m` and `C-i` with `bind-key` command. But if not bound, tmux is not sending these combinations down to application running inside tmux. I use kakoune editor inside tmux which is [requesting](https://github.com/mawww/kakoune/commit/47c0d2038807757207cde3b3e00fbc1ca9448178) extended-keys mode and is capable to handle `C-j`, `C-m` and `C-i`.

Can you please make a change so `C-j`, `C-m` and `C-i` are passed through if not bound by tmux itself and extended-keys mode (`printf '\033[>4;1m'`) requested by application?

Other combos like `C-1` for example are passed through if not bound by tmux itself.

**Comment by nicm** [comment] 2021-05-12 11:31
This is a) a shit issue and b) a duplicate of https://github.com/tmux/tmux/issues/2705.

**Closed by nicm** 2021-05-12 11:31 UTC
