### ISSUE TITLE
[Feature Request] help strings in bind-key and list-keys commands

### ISSUE THREAD

**Issue by alextremblay** [tmux/tmux#2000] opened 2019-12-03 16:25 UTC
## Premise

tmux is an incredibly flexible tool, with commands that can be combined with other commands or embedded in other commands like building blocks to create complex and powerful macros.

This is awesome, but it presents a problem for people just starting out learning tmux.

Often times, the first key sequence a new user learns is how to trigger list-keys so they can look up all the key sequences they haven't memorized. 

When looking at key bindings in list-keys, when the bound command is simple, like `select-window -t :=1`, it's pretty easy to figure out what that key binding does. When the bound command is more complicated, like `command-prompt -i -I "#{pane_search_string}" -p "(search up)" "send -X search-backward-incremental \"%%%\""`, it can be much more difficult for a new user, not familiar with the intricacies of the tmux command system, to figure out.

## Proposal

- Add an option to the `bind-key` command to annotate the binding with a string, a desription of what the bound command does
- Add an option to the 'list-keys` command to show key binding descriptions (instead of, or alongside the bound command

maybe for example:
```
bind-key -h "Send mouse wheel up event to pane, scroll up if in copy mode" -T root WheelUpPane       if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= \"#{pane_in_mode}\" \"send-keys -M\" \"copy-mode -et=\""
```

Thoughts?

**Comment by nicm** [comment] 2019-12-03 16:58
I like this idea a lot.

One problem is that list-keys should be valid if copied into a config file and it will become very cluttered if it has a long help string as one of the arguments, although I suppose there is no avoiding that.

What I would suggest is that the flag to list-keys should print an entirely different output form which shows only the key and the help string. This could look a little like the "default keys" table in the manual and be the default for the ? binding. The only problem with this is how to deal with key tables - it would be nice if prefix table keys were printed as eg "C-b x" but what about other key tables, how are they shown?

I think I would probably call this a "note" rather than "help", firstly because it would be intended as an aide memoire rather than detailed help, and secondly because the place for help text is in the manual.

**Comment by alextremblay** [comment] 2019-12-03 18:16
Yes, I agree with all of that. 

I also don't know how to deal with key tables. As far as I know, there is no easy, reliable way to look up the key bound to a given `switch-client -T {key-table}` command

and yes, this would be more of an 'annotation which could be used as a help / hint string' feature than a specifically help-string-focused feature

**Comment by nicm** [comment] 2019-12-03 19:03
It would probably be enough to make it that list-keys -h (or whatever flag it is) just checks prefix/root table and ignores keys in other tables. Even if we could find out what keys were bound to switch-client, what if there are more than one? Or if they are somewhere inside an if-shell... it's pretty impossible.

Are you going to work on this? If you wanted to write descriptions for each key it would be helpful, if you look at key-string.c:key_bindings_init there is a table with all the default bind commands, I'd suggest changing each one to put the note on the first line and the binding on the second, something like:
~~~~
                 "bind -N 'Send the prefix key to the current pane'"
                     "C-b "send-prefix",

**Comment by ThomasAdam** [comment] 2019-12-03 19:19
Hi,

If no one picks this up, I don't mind doing it.  Just let me know.

Kindly,
Thomas

**Comment by alextremblay** [comment] 2019-12-04 18:38
That would be great!

I barely know enough Clang to be able to read it, so i wouldn't know where to start

**Comment by nicm** [comment] 2019-12-04 22:44
OK @ThomasAdam if you want to do it that'd be great

**Comment by ThomasAdam** [comment] 2019-12-04 22:45
Okey dokey! Let's try and get this in before the new year!

**Comment by nicm** [comment] 2020-01-05 22:03
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/4024098/x.diff.txt)

This ignores mouse keys and only looks at the root and prefix tables. I also changed lsk to accept a key argument, so you can do:
~~~~
$ tmux lsk -N C-o
C-b C-o Rotate through the panes
~~~~
If we extended `command-prompt -1` to have a flag which passed the string form of a key for its key press, we could have something a bit like `M-x describe-key` in emacs.

**Comment by nicm** [comment] 2020-01-08 14:19
Same but with with a binding C-b \\ to prompt for a key and show only its note: [y.diff.txt](https://github.com/tmux/tmux/files/4035674/y.diff.txt)

**Comment by alextremblay** [comment] 2020-01-11 04:10
Oh this looks awesome!

I've never applied a patch or compiled tmux from source before, but I'll try and give it a shot on monday.

Thank you for doing this!

**Comment by lacygoill** [comment] 2020-01-14 15:04
> I've never applied a patch or compiled tmux from source before, but I'll try and give it a shot on monday.

Clone the repo:

    git clone https://github.com/tmux/tmux

Enter the repo:

    cd tmux

Download the patch:

    curl -LOs https://github.com/tmux/tmux/files/4035674/y.diff.txt

Apply the patch:

    patch <./y.diff.txt

At the moment, one hunk fails, but it doesn't seem to contain code, only a comment.

Compile:

    make clean; make distclean; sh autogen.sh && ./configure && make ; tput bel

You can now try the binary without installing it; it should be at the root of the repo.
To try it with your usual config, run:

    ./tmux -Lx

To try it without config, run:

    ./tmux -Lx -f/dev/null

**Comment by lacygoill** [comment] 2020-01-14 15:05
I only tested the patch for a short time, but this is what I've noticed.

It seems the patch introduces:

   - the new arguments `key`, `-N` and `-1` for the `list-keys` command
   - the new argument `-1` for the `command-prompt` command
   - a new `\` key binding in the prefix table which can be reinstalled with this shell command:

          $ tmux bind -T prefix '\' command-prompt -k -p key 'list-keys -1N "%%%"'

---

You can now annotate any key binding in the prefix table:

    $ tmux bind -N 'display "a" in the status line' a 'display a'

    $ tmux lsk -N a
    C-b a display the character in the status line

and in the root table:

    $ tmux bind -Troot -N 'display "C-a" in the status line' C-a 'display C-a'

    $ tmux lsk -N C-a
        C-a display "C-a" in the status line
    ^^^^
    these spaces are probably there to position `C-a` in the second column of keys
    in the output of `$ tmux lsk -N`; the first column usually contains `C-b `

---

I know this is working as intended, but just document as much as possible the new annotation feature, you can annotate a key binding in an ad-hoc table:

    $ tmux bind b switchc -T buffer

    $ tmux bind -N 'copy clipboard into Tmux buffer' -T buffer '>' run 'tmux setb -- "$(xsel -ob)"' \\\; display 'clipboard copied into tmux buffer'
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    $ tmux bind -N 'copy Tmux buffer into clipboard' -T buffer '<' choose-buffer -F '#{buffer_sample}' { run 'tmux showb -b "%%%" | xsel -ib' ; display 'tmux buffer copied into clipboard' }
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

But you can't make `lsk` display it:

    $ tmux lsk -N '>'
    unknown key: >

    $ tmux lsk -N '<'
    unknown key: <

The key binding must be in the root or prefix table to query its annotation.

---

You can query an annotation interactively with the default key binding `C-b \`.
Or – if you want to use another key sequence, e.g. prefix + `M-h` – you can source this line in your tmux.conf:

    bind M-h command-prompt -k -p key { lsk -1N '%%%' }
         ^^^

If you don't want having to press the prefix key, use `-Troot`:

    bind -Troot M-h command-prompt -k -p key { lsk -1N '%%%' }
         ^^^^^^

---

I think there is an error on the line 531 of the last patch:

    +-Fl h ) .
     ^
     shouldn't this be a dot?

Because the manpage displays this:

     attaches a note to the key (shown with list-keys -Fl h ) .
                                                      ^^^^^

While I think it should just display:

     attaches a note to the key (shown with list-keys).

---

In the manpage, the `-1` argument of the `lsk` command is described as restricting the output to the first matching key and note.  But it also has a secondary effect; it redirects the output from the terminal (in copy mode if invoked from a key binding) to Tmux status line.

For example, this command:

    $ tmux lsk -N '?'

outputs this message on the terminal:

    C-b ? List key bindings

While this command:

    $ tmux lsk -1N '?'

outputs the same message on Tmux status line.

---

Anyway this will be a very useful addition to Tmux; thank you for your work on this feature @nicm.

**Comment by nicm** [comment] 2020-01-14 15:08
Thanks, I meant to reply with build instructions actually but I forgot to do it. I'll fix the -Fl h.

**Comment by nicm** [comment] 2020-01-14 15:09
Yes -1 is meant to go to the status line, because I didn't want C-b \ to enter view mode. I might change it to C-b / actually since that is usually above the ?.

**Comment by alextremblay** [comment] 2020-01-14 15:43
Hi @lacygoill, thanks for the detailed build instructions. 
Thanks to you, I was able to successfully compile tmux 🎉 

So far it looks great! I really like the "describe-key" feature. As an added bonus, it makes it much easier for me to find unbound keys to map new actions to :)

**Comment by nicm** [comment] 2020-01-14 15:54
Here is an updated diff  [tmux-key-notes.diff.txt](https://github.com/tmux/tmux/files/4060067/tmux-key-notes.diff.txt)with a few changes:
- change describe key binding to `/` rather than `\`;
- make list-keys show any keys with notes in a custom key table if -T is given;
- add -P to list-keys to add a custom prefix printed before each key, this works with and without -T but is only really of any use with -T;
- fix some typos.

This means that if someone makes a custom key table bound to say C-x and they put notes on the keys they can do something like this to get output similar to the default C-b ? for their key table:
~~~~
tmux lsk -Tmytable -P 'C-x ' -N
~~~~

**Comment by lacygoill** [comment] 2020-01-14 17:14
With the latest patch, you can now query the annotation of any key binding, regardless of its table.

    $ tmux -Lx -f<(cat <<'EOF'
    bind b switchc -T buffer
    bind -T buffer -N 'copy clipboard into tmux buffer' > run 'tmux setb -- "$(xsel -ob)"' \; display 'clipboard copied into tmux buffer'
    bind -T buffer -N 'tmux buffer copied into clipboard' < choose-buffer -F '#{buffer_sample}' \
        { run 'tmux showb -b "%%%" | xsel -ib' ; display 'tmux buffer copied into clipboard' }
    EOF
    )

    $ tmux lsk -N -T buffer '>'
    > copy clipboard into tmux buffer

---

For anyone interested in getting a description for a key binding triggered by 2 keypresses instead of a single one, try this:

         replace with whatever key you want
         vvv
    bind '\' command-prompt -1p 'key1,key2' \
        { run "tmux lsk | awk '/-T prefix\s+%1\s+/ { print \$NF }' | xargs -I {} tmux lsk -T {} -1N '%2'" }

To test it:

    $ tmux -Lx -f<(cat <<'EOF'
    bind b switchc -T buffer
    bind -T buffer -N 'copy clipboard into tmux buffer' > run 'tmux setb -- "$(xsel -ob)"' \; display 'clipboard copied into tmux buffer'
    bind -T buffer -N 'tmux buffer copied into clipboard' < choose-buffer -F '#{buffer_sample}' \
        { run 'tmux showb -b "%%%" | xsel -ib' ; display 'tmux buffer copied into clipboard' }
    bind '\' command-prompt -1p 'key1,key2' \
        { run "tmux lsk | awk '/-T prefix\s+%1\s+/ { print \$NF }' | xargs -I {} tmux lsk -T {} -1N '%2'" }
    EOF
    )
    # press:  C-b \ b >
    # Tmux should display:  > copy clipboard into tmux buffer

It could probably be adapted to support more keypresses, but I suspect the key binding would quickly become unwieldy.

**Comment by nicm** [comment] 2020-01-27 08:53
Applied to OpenBSD now, will be in GitHub later. Thanks!

**Closed by nicm** 2020-01-27 08:53 UTC
