### ISSUE TITLE
[Feature Request] "before" flag for new-/link-/move-window

### ISSUE THREAD

**Issue by bchallenor** [tmux/tmux#2261] opened 2020-06-06 13:49 UTC
`new-window`/`link-window`/`move-window` all support the `-a` flag to mean "the index after the target window". It would be useful to have an analogous flag to mean "the index before the target window".

I suggest `-b`, as it is used for a similar purpose in `join-pane` and `split-window`.

It is possible to emulate this feature using `-a` followed by `swap-window` but it's surprisingly hard to do so in a way that correctly preserves the session stack, and particularly so in combination with `-t`.

**Comment by nicm** [comment] 2020-06-06 14:26
Yes, that's a good idea.

It would also be easier to do with `swap-window` if there was a builtin way to express "left/right of window x" rather than just "left of current window".

**Comment by bchallenor** [comment] 2020-06-06 16:28
Yes, it would be nice if `+`/`-`/`+N`/`-N` after any valid `target-window` (or `target-pane`) resulted in another valid `target-window` (or `target-pane`). For example, `:foo` -> `:foo-1` or `:^` -> `:^+3`. But I'm not sure how you would deal with resulting ambiguity - is `:foo-1` the window called "foo-1" or the window before "foo"?

The complexity of the `swap-window` workaround (at least one that tries to preserve the session stack) makes me think that the "before" flag is still preferable though. e.g. to represent `new-window -b -t:^` I think you'd need something like `new-window -a -t:^ -d ; swap-window -d -s:^+1 -t:^ ; select-window -t:^`.

**Comment by nicm** [comment] 2020-06-09 13:42
Try this please: [tmux-b.diff.txt](https://github.com/tmux/tmux/files/4752477/tmux-b.diff.txt)

**Comment by nicm** [comment] 2020-06-09 13:49
Missed some flags, also tmux.1: [tmux-b2.diff.txt](https://github.com/tmux/tmux/files/4752504/tmux-b2.diff.txt)

**Comment by nicm** [comment] 2020-06-11 11:00
Yes, something is up with move-window...

**Comment by nicm** [comment] 2020-06-11 11:19
The problem is that shuffling windows up frees the winlinks and makes new ones, but there may still be pointers to them. But I don't see any need to do that. Please try this: [tmux-b3.diff.txt](https://github.com/tmux/tmux/files/4764383/tmux-b3.diff.txt)

**Comment by bchallenor** [comment] 2020-06-13 08:51
That does fix it, thanks.

It also fixes a separate issue with `-a` that I had noticed, in that this patch better preserves the session stack.

4000052:
```
+ tmux -Ltest -f/dev/null new-session -d -n w0
+ tmux -Ltest new-window -n w1
+ tmux -Ltest list-windows
0: w0- (1 panes) [80x24] [layout b25d,80x24,0,0,0] @0
1: w1* (1 panes) [80x24] [layout b25e,80x24,0,0,1] @1 (active)
+ tmux -Ltest new-window -n w0a -t :w0 -a
+ tmux -Ltest list-windows
0: w0- (1 panes) [80x24] [layout b25d,80x24,0,0,0] @0
1: w0a* (1 panes) [80x24] [layout b25f,80x24,0,0,2] @2 (active)
2: w1 (1 panes) [80x24] [layout b25e,80x24,0,0,1] @1
```

4000052 with this patch:
```
+ tmux -Ltest -f/dev/null new-session -d -n w0
+ tmux -Ltest new-window -n w1
+ tmux -Ltest list-windows
0: w0- (1 panes) [80x24] [layout b25d,80x24,0,0,0] @0
1: w1* (1 panes) [80x24] [layout b25e,80x24,0,0,1] @1 (active)
+ tmux -Ltest new-window -n w0a -t :w0 -a
+ tmux -Ltest list-windows
0: w0 (1 panes) [80x24] [layout b25d,80x24,0,0,0] @0
1: w0a* (1 panes) [80x24] [layout b25f,80x24,0,0,2] @2 (active)
2: w1- (1 panes) [80x24] [layout b25e,80x24,0,0,1] @1
```

Note that the latter correctly shows `w1-` rather than `w0-`.

**Comment by nicm** [comment] 2020-06-13 09:06
Great stuff, applied to OpenBSD now, will be in GitHub later. Thanks!

**Closed by nicm** 2020-06-13 09:06 UTC
