### ISSUE TITLE
Mouse scrolling broken in nested tmux sessions - again

### ISSUE THREAD

**Issue by ltning** [tmux/tmux#3513] opened 2023-03-30 13:16 UTC
Hi,

this is a follow-up to issue #2721 - Mouse scrolling broken in nested tmux sessions.

This problem, exhibited in exactly the same way, is happening again in 3.3. The workaround suggested for 3.2 however, does not work. Installing 3.2a and adding
  `set -as terminal-overrides 'screen*:kmous=\E[M'`
to my .tmux.conf works.

Is it possible the fix which was committed to 3.2 was not brought forward to 3.3? Did something else break in the meantime?

tmux version: 3.3a (works in 3.2a with workaround described above)
term (outside): TERM=xterm-256color
term (inside): TERM=tmux-256color
os: FreeBSD 13.1

Logs for tmux-server and outer client:
[tmux-server-11615.log](https://github.com/tmux/tmux/files/11111931/tmux-server-11615.log)
[tmux-out-11615.log](https://github.com/tmux/tmux/files/11111933/tmux-out-11615.log)
[tmux-client-11613.log](https://github.com/tmux/tmux/files/11111935/tmux-client-11613.log)

Logs for inner client:
[tmux-client-15559.log](https://github.com/tmux/tmux/files/11111934/tmux-client-15559.log)

**Comment by nicm** [comment] 2023-03-30 16:46
Show server log from inner tmux please. I assume mouse is working in the outer tmux itself, for example you can change or resize panes with the mouse?

**Comment by ltning** [comment] 2023-03-30 17:09
I was a bit confused - I never got a server log inside. What did I do wrong? Would it end up in a different path?

**Comment by nicm** [comment] 2023-03-30 17:39
Did you make sure to kill the tmux server (`tmux kill-server`) before running with `-vv`, or use a different socket with `-L`?

**Comment by ltning** [comment] 2023-03-30 17:51
Yes - prior to running the external one. I presume I can/should not do that before invoking the inner one. I also verified (`ps ax`) that no tmux processes were running as my user prior to the first invocation.
I've never (had to) use different sockets for outer/inner.

**Comment by nicm** [comment] 2023-03-30 17:54
You need to kill the inner one too if you want logs from it.

**Comment by nicm** [comment] 2023-03-30 17:54
Oh is inner and outer the same tmux? Then you'll only have one log yes. I'll take a look later.

**Comment by ltning** [comment] 2023-03-30 17:55
...but there are none running at all, until I start the outer one. At which point there is one server. And ... yes, same tmux, same host. :)

**Comment by nicm** [comment] 2023-04-03 08:18
Outer tmux is recognizing the mouse but it is not writing it to the inner tmux, it must be failing one of the checks in `input_key_pane` or `input_key_mouse`. Please apply this, rebuild and then do the same and show me the log: [x.diff.txt](https://github.com/tmux/tmux/files/11136206/x.diff.txt)

**Comment by ltning** [comment] 2023-04-17 17:55
Sorry, I missed your comment. You still need me to test?

**Comment by nicm** [comment] 2023-04-17 17:56
Yes please test and show me the log so we can see where it is failing.

**Comment by nicm** [comment] 2023-04-24 14:28
Does this fix it?
~~~~
--- a/tty.c
+++ b/tty.c
@@ -484,6 +484,8 @@ tty_update_features(struct tty *tty)
                tty_puts(tty, tty_term_string(tty->term, TTYC_ENFCS));
        if (tty->term->flags & TERM_VT100LIKE)
                tty_puts(tty, "\033[?7727h");
+
+       tty_invalidate(tty);
 }

 void

**Comment by ltning** [comment] 2023-04-24 14:40
It does indeed!
Need more logs?

**Comment by nicm** [comment] 2023-04-24 14:53
No, it's OK I know what the problem is. I think this fix will do, I'll apply it tomorrow.

**Comment by nicm** [comment] 2023-04-25 09:32
Applied to OpenBSD now, will be in GitHub later. Thanks!

**Closed by nicm** 2023-04-25 09:32 UTC

**Comment by nicm** [comment] 2023-04-25 09:38
Yes there will be.
