### ISSUE TITLE
tmux can't use triple click to select line. add \33[12;1H \33[13;1H between long text in one line

### ISSUE THREAD

**Issue by ask-github** [tmux/tmux#2537] opened 2021-01-17 12:21 UTC
i use bash to print one lone text in a line. i can't use triple click to select the whole line
i use strace to record the writev of tmux server and found tmux add \33[12;1H \33[13;1H between long text in one line

like this
1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\33[11;1H111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\33[12;1H111

in win10 os, and xshell app

details is in gif
![1](https://user-images.githubusercontent.com/72971953/104841859-781df280-5901-11eb-8106-26a39114d733.gif)

**Comment by nicm** [comment] 2021-01-17 12:39
Am I meant to guess the tmux version?

**Comment by ask-github** [comment] 2021-01-17 12:49
> Am I meant to guess the tmux version?

$tmux -V
tmux 3.2-rc3

**Comment by nicm** [comment] 2021-01-17 12:58
Can you run with -vv and show me the server log please?

**Comment by ask-github** [comment] 2021-01-17 13:05
the log of tmux -vv a -t one

  1 1610888614.875792 client started (3509124): version 3.2-rc3, socket /tmp/tmux-0/default, protocol 8
  2 1610888614.875813 on Linux 5.4.0-s1 #41 SMP Fri Jan 3 22:10:15 CST 2020
  3 1610888614.875817 using libevent 2.1.8-stable (poll); ncurses 6.1
  4 1610888614.875834 flags are 0x18010000
  5 1610888614.875836 socket is /tmp/tmux-0/default
  6 1610888614.875848 trying connect
  7 1610888614.875915 add peer 0x21490e0: 6 ((nil))
  8 1610888614.875965 sending message 100 to peer 0x21490e0 (4 bytes)
  9 1610888614.875970 sending message 111 to peer 0x21490e0 (8 bytes)
 10 1610888614.875973 sending message 101 to peer 0x21490e0 (6 bytes)
 11 1610888614.875975 sending message 109 to peer 0x21490e0 (4 bytes)
 12 1610888614.875977 sending message 102 to peer 0x21490e0 (11 bytes)
 13 1610888614.875979 sending message 108 to peer 0x21490e0 (6 bytes)
 14 1610888614.875981 sending message 104 to peer 0x21490e0 (0 bytes)
 15 1610888614.875984 sending message 110 to peer 0x21490e0 (0 bytes)
 16 1610888614.875986 sending message 107 to peer 0x21490e0 (4 bytes)
 17 1610888614.875989 sending message 105 to peer 0x21490e0 (1515 bytes)
 18 1610888614.875996 sending message 105 to peer 0x21490e0 (54 bytes)
 19 1610888614.875998 sending message 105 to peer 0x21490e0 (17 bytes)
 20 1610888614.876000 sending message 105 to peer 0x21490e0 (23 bytes)
 21 1610888614.876002 sending message 105 to peer 0x21490e0 (24 bytes)
 22 1610888614.876004 sending message 105 to peer 0x21490e0 (37 bytes)
 23 1610888614.876006 sending message 105 to peer 0x21490e0 (11 bytes)
 24 1610888614.876008 sending message 105 to peer 0x21490e0 (24 bytes)
 25 1610888614.876010 sending message 105 to peer 0x21490e0 (14 bytes)
 26 1610888614.876012 sending message 105 to peer 0x21490e0 (19 bytes)
 27 1610888614.876014 sending message 105 to peer 0x21490e0 (10 bytes)
 28 1610888614.876017 sending message 105 to peer 0x21490e0 (45 bytes)
 29 1610888614.876018 sending message 105 to peer 0x21490e0 (18 bytes)
 30 1610888614.876020 sending message 105 to peer 0x21490e0 (10 bytes)
 31 1610888614.876022 sending message 105 to peer 0x21490e0 (11 bytes)
 32 1610888614.876024 sending message 105 to peer 0x21490e0 (35 bytes)
 33 1610888614.876026 sending message 105 to peer 0x21490e0 (114 bytes)
 34 1610888614.876029 sending message 105 to peer 0x21490e0 (19 bytes)
 35 1610888614.876031 sending message 105 to peer 0x21490e0 (26 bytes)
 36 1610888614.876033 sending message 105 to peer 0x21490e0 (11 bytes)
 37 1610888614.876035 sending message 105 to peer 0x21490e0 (16 bytes)
 38 1610888614.876037 sending message 105 to peer 0x21490e0 (8 bytes)
 39 1610888614.876039 sending message 105 to peer 0x21490e0 (26 bytes)
 40 1610888614.876041 sending message 105 to peer 0x21490e0 (13 bytes)
 41 1610888614.876043 sending message 105 to peer 0x21490e0 (51 bytes)
 42 1610888614.876045 sending message 105 to peer 0x21490e0 (28 bytes)
 43 1610888614.876047 sending message 105 to peer 0x21490e0 (107 bytes)
 44 1610888614.876049 sending message 105 to peer 0x21490e0 (23 bytes)
 45 1610888614.876051 sending message 105 to peer 0x21490e0 (14 bytes)
 46 1610888614.876053 sending message 105 to peer 0x21490e0 (35 bytes)
 47 1610888614.876055 sending message 105 to peer 0x21490e0 (22 bytes)
 48 1610888614.876057 sending message 106 to peer 0x21490e0 (0 bytes)
 49 1610888614.876060 cmd_pack_argv: argv[0]=a
 50 1610888614.876061 cmd_pack_argv: argv[1]=-t
 51 1610888614.876063 cmd_pack_argv: argv[2]=one
 52 1610888614.876065 sending message 200 to peer 0x21490e0 (13 bytes)
 53 1610888614.876067 client loop enter
 54 1610888614.878064 peer 0x21490e0 message 207
 55 1610888614.878070 sending message 208 to peer 0x21490e0 (0 bytes)
 56 1610888619.440497 peer 0x21490e0 message 201
 57 1610888619.440524 sending message 205 to peer 0x21490e0 (0 bytes)
 58 1610888619.441625 peer 0x21490e0 message 204
 59 1610888619.441630 client loop exit

**Comment by nicm** [comment] 2021-01-17 13:06
This is the client not the server log, you need to kill tmux entirely and run with -vv. Also please attach it to the issue rather than pasting it into a comment.

**Comment by ask-github** [comment] 2021-01-17 13:11
> This is the client not the server log, you need to kill tmux entirely and run with -vv. Also please attach it to the issue rather than pasting it into a comment.

it is not very easy to reproduce

**Comment by ask-github** [comment] 2021-01-17 13:15
[tmux-server-20959.log](https://github.com/tmux/tmux/files/5826135/tmux-server-20959.log)
this is the log of the server. it reproduce

**Comment by ask-github** [comment] 2021-01-17 13:18
in the log. is this place. the tmux server split the long text on a line

1610889135.959714 /dev/pts/0: 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
1610889135.959719 tty_clear_pane_line: /dev/pts/0, 212 at 0,46
1610889135.959723 tty_clear_line: /dev/pts/0, 212 at 0,46
1610889135.959725 /dev/pts/0: \033[47;1H
1610889135.959730 /dev/pts/0: \033[K
1610889135.959735 /dev/pts/0: 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
1610889135.959739 tty_clear_pane_line: /dev/pts/0, 212 at 0,47
1610889135.959741 tty_clear_line: /dev/pts/0, 212 at 0,47
1610889135.959744 /dev/pts/0: \033[48;1H
1610889135.959747 /dev/pts/0: \033[K
1610889135.959751 /dev/pts/0: 1111111111

**Comment by nicm** [comment] 2021-01-17 13:20
OK I will look during the week.

**Comment by nicm** [comment] 2021-01-17 17:50
tmux has to clear the line, and that means moving the cursor. But I don't think we need to clear immediately if the new text is going to overwrite at 0 anyway. Does this make any difference? [x.diff.txt](https://github.com/tmux/tmux/files/5826546/x.diff.txt)

**Comment by ask-github** [comment] 2021-01-18 02:14
> tmux has to clear the line, and that means moving the cursor. But I don't think we need to clear immediately if the new text is going to overwrite at 0 anyway. Does this make any difference? [x.diff.txt](https://github.com/tmux/tmux/files/5826546/x.diff.txt)

still has this problem. make sure the patch has compiled

strings  /proc/3571487/exe |grep 'clearing at'
clearing at %u
<img width="1280" alt="1" src="https://user-images.githubusercontent.com/72971953/104865086-fae09500-5975-11eb-94d9-1cd56c17513a.png">

**Comment by ask-github** [comment] 2021-01-18 02:40
use tmux to scrool up cursor to show the history of the screen, can easy reproduce this bug

**Comment by nicm** [comment] 2021-01-18 06:20
Oh in copy mode it doesn't really worry about it at all, it isn't really expected to work.

**Comment by nicm** [comment] 2021-01-18 06:21
Show me a log from reproducing with the patch applied please, not using copy mode.

**Comment by tty5** [comment] 2021-01-18 06:26
> Show me a log from reproducing with the patch applied please, not using copy mode.

i use patched tmux. after using half working day. has not beed reproduce this problem

do u need log that havn't reproduce. so the log is not useful

**Comment by nicm** [comment] 2021-01-18 06:31
No only show log if you can still reproduce outside copy mode.

**Comment by tty5** [comment] 2021-01-18 06:44
> No only show log if you can still reproduce outside copy mode.

ok.
thanks a lot for resolve this problem

**Comment by tty5** [comment] 2021-01-18 06:46
> No only show log if you can still reproduce outside copy mode.

so i think that tmux show a long text in one line in copy mode still has problem.

will it be fixed in the furture?

**Comment by nicm** [comment] 2021-01-18 06:49
Maybe, I will have a look and see if it can. But I am not too worried about this TBH because it will never work with multiple panes, it is better to focus on making tmux's own mouse support work better.

**Comment by ask-github** [comment] 2021-01-18 07:02
i think tmux's own mouse only can be used in tmux. paste in tmux. can't copy out

there are many scenario that use ssh client to connect linux in windows os. like win10

so need copy some lines of the histroy of a pane out to windows app is a frequent ops.

if use the multiple panes. the tmux resize command can make a pane max window size. 

if the bug still in the copy mode. programmer can't copy the lines out to other app. or the copyed text is wrong

thanks

**Comment by nicm** [comment] 2021-01-18 07:03
You can copy out if you use a terminal which supports OSC 52.

**Comment by ask-github** [comment] 2021-01-18 07:07
it limits tmux's world wide used

help tmux better, it is a very useful tool. it will be used by many ten years

**Comment by nicm** [comment] 2021-01-18 10:28
I have applied a modified version of this diff to fix some problems with it, it  will be in GitHub later on when it syncs. Please let me know if you see any problems.

**Comment by ask-github** [comment] 2021-01-18 14:08
i tested the master branch. and the copy mode is still can't work. is it expect?

the normal mode can work fine

**Comment by nicm** [comment] 2021-01-18 14:11
Yes no changes to copy mode yet, I will look at it later sometime.

**Comment by ask-github** [comment] 2021-01-18 14:18
thanks u very much

it make my work easier.

**Comment by nicm** [comment] 2021-01-18 15:48
I think that because of how copy mode works it is not practical to change this without major work to how it redraws. I will put it on the todo list but I don't expect it to happen soon, sorry.

**Comment by nicm** [comment] 2021-01-23 10:33
I had to revert the previous change because it wasn't working, however here is an updated change which should achieve the same thing (still not copy mode). Please test if possible: [tmux-screen-write-trim4-freelist.diff.txt](https://github.com/tmux/tmux/files/5860039/tmux-screen-write-trim4-freelist.diff.txt)

**Comment by tty5** [comment] 2021-01-25 08:46
now, i use commit 82423975, which include your patch
91d112bf There is no need to clear every line entirely before drawing to it, this means moving the cursor and messes up wrapping. Better to just clear the sections that aren't written over. GitHub issue 2537.

it is work fine.
so if i can help test. is patch tmux-screen-write-trim4-freelist.diff.txt on 82423975?
or use the branch master to compile tmux and run it

**Comment by nicm** [comment] 2021-01-25 08:50
https://github.com/tmux/tmux/commit/91d112bf12789da07e25ed001f7961b1d6bd7a76 causes tmux to freeze for some people so I reverted it.

Please pull master and then apply the new patch and try it instead.

**Comment by ask-github** [comment] 2021-01-26 03:19
> [91d112b](https://github.com/tmux/tmux/commit/91d112bf12789da07e25ed001f7961b1d6bd7a76) causes tmux to freeze for some people so I reverted it.
> 
> Please pull master and then apply the new patch and try it instead.

i test master branch and patch tmux-screen-write-trim4-freelist.diff.txt, it is also work fine.

**Comment by nicm** [comment] 2021-01-26 07:49
Great stuff, let me know if you see any problems. I shall probably apply
this in a few days.

**Comment by ask-github** [comment] 2021-01-27 08:59
i use vim to open file and use triple click to select long txt. 

can't select the whole line.

so maybe there are some problem on patch tmux-screen-write-trim4-freelist.diff.txt

the log need send later

**Comment by nicm** [comment] 2021-01-27 09:49
I see this too but it seems like a problem with vim:
~~~~
$ perl -e 'print "x" x 1000' >~/xx
$ rm *.log;./tmux -vvLtest new 'vim ~/xx' \; run -d 1 \; send :q Enter
~~~~
Shows:
~~~~
1611740720.370086 input_parse_buffer: %0 ground, 1982 bytes: \033[1;1Hxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\033[2;1Hxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\033[3;1H...
~~~~
So vim is moving the cursor at the end of each line which means it does not wrap.

**Comment by nicm** [comment] 2021-01-27 10:02
vim is actually drawing quite strangely, it doesn't move the cursor at the end of the line but instead it draws one more character than the line length, then moves the cursor back:
~~~~
1611741403.230266 screen_write_collect_end: 107 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx (at 0,0)
~~~~
^--- 107 characters is full terminal width.
~~~~
1611741403.230291 screen_write_collect_add: wrapped at 107,0
1611741403.230329 screen_write_linefeed: at 107,0 (region 0-81)
1611741403.230352 screen_write_collect_end: 1 x (at 0,1)
~~~~
^--- It wraps,but then vim sends an additional `x`.
~~~~
1611741403.230374 input_csi_dispatch: 'H' "" "2;1"
1611741403.230393 parameter 0: number 2
1611741403.230411 parameter 1: number 1
1611741403.230437 screen_write_cursormove: from 1,1 to 0,1
~~~~
^--- The cursor is now at 1,1, but vim moves it back to 0,1.
~~~~
1611741403.230467 screen_write_collect_trim: 0xc3e6b116200 0-0 inside 0-106
~~~~
^--- tmux discards the stray `x` because it will be overwrriten by the next line of `xxxxx...`.

**Comment by nicm** [comment] 2021-01-27 10:05
It does the same with `TERM=xterm` so it is not something lacking in the `screen` or `tmux` terminfo entry. Maybe it is an attempt to deal with non-`am` terminals...

Anyway I guess you will need to talk to vim about this, or try neovim and see if it is better.

**Comment by ask-github** [comment] 2021-01-28 03:00
but run vim in normal shell, not in tmux. the triple click can select the whole line.

the previous patch also can use triple click to select whole line in vim as run in tmux

**Comment by nicm** [comment] 2021-01-28 06:27
Hmm you're right, that's weird. I'll take a look.

**Comment by nicm** [comment] 2021-01-28 06:41
Try this instead please: [tmux-screen-write-trim5.diff.txt](https://github.com/tmux/tmux/files/5885292/tmux-screen-write-trim5.diff.txt)

**Comment by ask-github** [comment] 2021-01-29 03:15
> Try this instead please: [tmux-screen-write-trim5.diff.txt](https://github.com/tmux/tmux/files/5885292/tmux-screen-write-trim5.diff.txt)

tmux-screen-write-trim5.diff.txt is work fine for run vim in tmux

thanks

**Comment by nicm** [comment] 2021-01-29 09:49
OK great, let me know if you see any further problems. It will be applied soon.

**Closed by nicm** 2021-01-29 09:49 UTC
