### ISSUE TITLE
feature: simple way to move pane from other session into new window

### ISSUE THREAD

**Issue by azrdev** [tmux/tmux#2176] opened 2020-04-22 15:14 UTC
### Issue description
I'm using tmux as the shell for my graphical terminal emulator, frequently having multiple instances (= X windows) of it running and later on deciding to rearrange the tmux windows and panes between them (e.g. from yakuake to konsole and back). So, I use a single tmux server with a multitude of sessions, windows, and panes.

I can already move a pane to a different tmux session by first marking it (`ctrl-b m`), then switching to the target session, open a new window (`ctrl-b c`) and then pulling the pane with the `join-pane` command. This however results in the new window being split between the pulled pane and the "default pane" created with the window, i.e. after `join-pane` I have to switch panes and terminate that pane with the idle shell.
I'd like to get rid of those extra keystrokes, therefore propose:
1. a version of `join-pane` (or `move-pane`? they apparently are similar, but move-pane seems to ignore the marked pane) which creates a new window to move the pulled pane into. a parameter to the command is maybe a better idea
2. a default shortcut for that version of `join-pane`
3. a way to get rid of first marking the to-be-pulled pane, so all I had to do was press the "pull" shortcut in the designated target session, and tmux let me (probably like `choose-tree`) select any pane on the current tmux server to pull to me.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). `tmux 2.9a`
* Platform (`uname -sp`). `Linux x86_64` / Fedora 31

**Comment by nicm** [comment] 2020-04-22 16:12
Yes, moving and joining panes in tmux can be a bit clumsy although it is a lot better than it was.

(1) `move-pane` and `join-pane` are the same except `join-pane` does not allow you to move a pane to the window it is currently in.

What you want is more like `break-pane` than `join-pane`, except:

- `break-pane` won't do anything if the source pane is the only pane in its window;
- It has no `-a` flag like `move-window` so you get a window at the end;
- It doesn't use the marked pane.

So you can almost do it with `break-pane -s'{marked}'` but not quite :-).

You could script it but it would be a little bit of a fiddle since there is no `-a` flag to `break-pane` - you would need to do `neww -a`/`swap-pane`/`kill-pane`.

I think we should make a few changes:

- `join-pane` and `move-pane` should be the same commands in truth, the extra checks are unnessary.
- `break-pane` should have `-a` to create a new window like `move-window`.
- `break-pane` should behave like `move-window` if there is only one pane in the source window, rather than failing.

That would mean you could just do `break-pane -a -s'{marked}'`.

(2) I don't want any default bindings where you need to mark the pane first.

(3a) You can already bind keys to have `choose-tree` "ask" for a pane. For example try this: `bind J choose-tree 'join-pane -s "%%"'`. I had half forgotten you could do this until you asked, I have always been thinking more of what you could do inside tree mode rather than using it as  prompt. Perhaps we could make it nicer (for example add a "Choose a target for join-pane" prompt at the top).

(3b) In theory you should be able to do stuff using the `:` prompt from inside tree mode, but it doesn't really work. The problem is if you tag a pane and use the `:` prompt, the tagged pane becomes both the target and the source so commands like `join-pane` become useless. Ideally the tagged pane should be the used as the source and the selected pane the target, so you could just tag the pane to join and select the target pane and do `: join-pane`. But this is not trivial to implement either. If this *was* changed to work, I'd like it that the marked pane was automatically tagged when you entered tree mode.

**Comment by nicm** [comment] 2020-04-22 16:27
OK (1) is pretty simple. Please try this: [tmux-break-pane-a.diff.txt](https://github.com/tmux/tmux/files/4517490/tmux-break-pane-a.diff.txt)

**Comment by nicm** [comment] 2020-04-22 16:44
Here is a slightly improved version: [tmux-break-pane-a-2.diff.txt](https://github.com/tmux/tmux/files/4517638/tmux-break-pane-a-2.diff.txt)

**Comment by nicm** [comment] 2020-04-22 17:20
Just realised you didn't actually say you wanted `-a` so all you really need is a `break-pane` that works if the source window only has one pane. The last diff does that anyway so you can just do `break-pane -s'#{marked}'` or `break-pane -as'#{marked}'` to move the marked pane to a new window in the attached session.

**Comment by nicm** [comment] 2020-04-22 18:03
Here is another diff with additional changes which makes it a bit easier to work with the marked pane in tree mode: [break-pane-and-window-tree.diff.txt](https://github.com/tmux/tmux/files/4518139/break-pane-and-window-tree.diff.txt)

- Highlight the marked pane and the window containing it in reverse.
- Show an M on the pane as well as the window.
- Add `m` and `M` keys to set and clear the marked pane.
- Add an `H` key to jump back to the pane where you entered tree mode.

This means to join a pane you can just enter tree mode, move to the pane you want to join, press `m` then `H` then do `:join-pane` (not `C-b :`, just `:`).

Unfortunately it doesn't work quite so well for `break-pane` and I don't think it is a good idea to make `break-pane` default to the marked pane. You need to do `:break-pane -s~` instead.

I might add default keys for with `swap-pane`, `join-pane`, `break-pane` in tree mode.

I don't think it is a good idea to try and make it so that you can do the same with tags, the idea of tags is that the `:` command or the key press is applied to each one separately. Trying to make it so that sometimes the tag means the source and sometimes the target would just make it confusing.

**Comment by nicm** [comment] 2020-04-22 21:24
I have applied these bits now, they should be in GitHub when it syncs in a few hours. Please build from master and test.

You will probably want something like:
~~~~
bind B choose-tree 'break-pane -as "%%"'
~~~~
Which will move the pane you choose in tree mode to a new window after the current window.

Alternatively you can do this: `C-b w` and scroll to the pane you want to move, then press `m` to mark it, then `H` to go back to the original pane, then `:` and type `break-pane -as~`.

I am not sure about adding default key bindings for any of this, I liked the idea of being able to do it completely in tree mode but when I tried it was kind of confusing to move stuff about.

**Comment by nicm** [comment] 2020-04-24 08:56
I'm going to close this because I think your original requests are solved by the changes to `break-pane` and using `choose-tree` with a command argument. Let me know if you have any further suggestions.

**Closed by nicm** 2020-04-24 08:56 UTC

**Comment by azrdev** [comment] 2020-04-28 19:35
Hey @nicm thank you very much for considering my request and even doing something about it so quickly! I'm afraid I cannot test the changes now, but I'm looking forward to better usability once I see them in my distros packages

**Comment by azrdev** [comment] 2020-05-08 20:43
For the record, this seem to be commits 
- 899b3d2 and 4b21fd2  indicating the marked pane in choose mode
- 950af33 and e46cf86 changing join-pane,move-pane,break-pane
