### ISSUE TITLE
Server exited unexpectedly using neovim 0.10.0 over SSH with Alacritty

### ISSUE THREAD

**Issue by prurigro** [tmux/tmux#3983] opened 2024-05-17 15:52 UTC
### Issue description

Running tmux in Alacritty then SSHing into a client and running neovim 0.10.0 will crash the tmux server.

* Running tmux in urxvt and doing the same does not cause the issue.
* SSHing into a server with neovim 0.9.5 and doing the same does not cause the issue.
* I've tested both with my personal tmux config as well as vanilla (logs below are using my personal config, let me know if you need vanilla)

In case this was due to the new osc52 support for copy/paste, I tried disabling osc52 in the alacritty config but there was no difference. I also attempted to prevent osc52 copy/paste in neovim by forcing unnamedplus (which the documentation says prevents the feature from loading) but still hit the issue.

Describe the problem and the steps to reproduce:

1. Start tmux in Alacritty
2. SSH into a box with neovim 0.10
3. Run `nvim -u NORC` (to load without any config)
4. Observe `[server exited unexpectedly]`

### Required information

Please provide the following information:

* tmux version: 3.4 (from the Archlinux repos)
* Platform: Linux unknown (Archlinux)
* Inside tmux: tmux-256color -- Outside tmux: alacritty
* Logs:
    [tmux-client-607371.log](https://github.com/tmux/tmux/files/15353857/tmux-client-607371.log)
    [tmux-out-607375.log](https://github.com/tmux/tmux/files/15353858/tmux-out-607375.log)
    [tmux-server-607375.log](https://github.com/tmux/tmux/files/15353859/tmux-server-607375.log)

Let me know if you need additional information and I'd be happy to provide it. Also, thanks for maintaining tmux :)

**Comment by Cnly** [comment] 2024-05-17 16:10
That was fast! I was about to submit the same bug report when I saw this, so I'll add my report here.

My steps to reproduce

1. `tmux -vv -f /dev/null -L test new`
2. ssh onto a remote machine with neovim 0.10 (`NVIM v0.10.0` from linuxbrew)
3. Start neovim with no custom config: `nvim -u NONE`

I've tested this with both the following setups:

* (to test on a mac) tmux on my mac → ssh onto linux server A → start nvim → local tmux crashes
* (to test on a linux) ssh onto linux server J → start tmux → ssh onto linux server A → start nvim → tmux on server J crashes

### Required information

* tmux version (`tmux -V`): `tmux 3.4` on both my mac and linux server J
* Platform (`uname -sp`). `Darwin arm` and `Linux x86_64`
* $TERM inside and outside of tmux (`echo $TERM`).
  * on my mac: `screen-256color` inside and `xterm-256color` outside
  * on linux server J: `tmux-256color` inside and `xterm-256color` outside

The last few lines of tmux server logs look like this:

```
1715960621.245436 screen_redraw_draw_pane: /dev/ttys023 %0 line 0,52 at 0,52, width 92
1715960621.245444 tty_draw_line: px=0 py=52 nx=92 atx=0 aty=52
1715960621.245451 tty_draw_line: defaults: fg=8, bg=8
1715960621.245458 tty_draw_line: 92 to end of line (0 cleared)
1715960621.245465 tty_clear_line: /dev/ttys023, 92 at 0,52
1715960621.245471 /dev/ttys023: \r
1715960621.245484 /dev/ttys023: \n
1715960621.245496 /dev/ttys023: \033[K
1715960621.245510 tty_cmd_sixelimage: image is 1x1
1715960621.245518 tty_cmd_sixelimage: clamping to 0,0-1,1
1715960621.245549 fatal: xcalloc: zero size
```

Looks like it's related to sixel?

**Comment by prurigro** [comment] 2024-05-17 16:13
True, I should have mentioned that I patched sixel support into the latest Alacritty release. It would be odd if neovim was triggering a sixel-related bug on that note.

**Comment by Cnly** [comment] 2024-05-17 16:20
Found this issue following the sixel lead: https://github.com/neovim/neovim/issues/28082. Unfortunately iTerm2 seems to have no way to disable sixel so I can't test without it...

**Comment by nicm** [comment] 2024-05-17 16:35
Does this still happen with master?

**Comment by prurigro** [comment] 2024-05-17 16:42
@nicm: I just tested in master and the issue does not occur there

**Comment by nicm** [comment] 2024-05-18 08:33
Great stuff. I expect it was fixed by aa17f0e0c1c8b3f1d6fc8617613c74f07de66fae.

**Closed by nicm** 2024-05-18 08:33 UTC

**Comment by marcomayer** [comment] 2024-05-18 18:54
Nice, will there be a new release soon? 👀

**Comment by jby** [comment] 2024-05-23 07:58
I just came here to report the same thing, with iTerm, but apparently it's known already - nice.
Awaiting a new release so I can go back to using iTerm

**Comment by Cnly** [comment] 2024-05-23 08:04
@jby for now a workaround would be `brew install tmux --HEAD`

**Comment by jby** [comment] 2024-05-23 09:09
Oh, and related to the OP - for me there's no problem in Alacritty, even with 3.4...

**Comment by jby** [comment] 2024-05-23 11:04
> > @jby for now a workaround would be `brew install tmux --HEAD`
> 
> It still happens with `tmux next-3.5`

Hmm, it didn't crash on a second try, so I'm hopeful...

**Comment by prurigro** [comment] 2024-05-27 22:14
@jby the reason it was happening for me with alacritty is because I have sixel support patched in. I've edited the title so it describes the issue better in case others are looking here in the future.

Try building git master and the issue should be gone.

**Comment by cynicaljoy** [comment] 2024-05-28 09:55
> Hmm, it didn't crash on a second try, so I'm hopeful...

witnessed the same behavior. first time launching neovim I saw an error like "server unexpected quit" (though tmux didn't wholesale crash this time), launched neovim again and it's running seemingly fine now.

**Comment by cocoliliace** [comment] 2024-05-29 08:26
This behaviour is reproducible on foot, when running neovim as a different user as the one that launched tmux. For example, this crashes the tmux server with the same error log (xcalloc: zero size)
```
tmux
doas nvim
```
but this works
```
doas tmux
nvim
```
and this doesn't
```
doas tmux
doas -u myuser nvim
```

**Comment by MarkusZoppelt** [comment] 2024-05-31 11:02
Also happening to me with tmux 3.4 + nvim 0.10.0 over ssh on macOS.

**Comment by lennartack** [comment] 2024-06-06 10:08
This was also happening for me locally when `$TMUX` is not set, for example after running `su -`.

**Comment by ryad-eldajani** [comment] 2024-06-07 07:55
Observe the same behavior when opening a file in neovim via sudo in a tmux session:

```sh
$ tmux
$ touch file.txt
$ sudo nvim file.txt
[server exited unexpectedly]
```

However, can confirm that the workaround suggested by @lennartack does not crash tmux:
```sh
$ tmux
$ sudo -E TMUX=$TMUX nvim file.txt
```

**Comment by sainttttt** [comment] 2024-06-10 04:02
Yeah setting TMUX to anything like `export TMUX=meow` on the remote machine that I'm ssh'ing into stops the crash from happening. Without it, it still crashes for me on tmux-HEAD on macOS

**Comment by blacklight** [comment] 2024-06-19 18:42
`export TMUX=foobar` on the remote machine does the trick, but it's still a very dirty workaround. I'm still in the situation where i SSH into a box, type nvim forgetting to export TMUX, and my whole session crashes.

Are there any plans for a new tmux release that includes the fix? The latest release was made in February and the version that comes on Arch and any derived distros is currently impacted.

**Comment by sainttttt** [comment] 2024-06-21 09:28
So I'm having another issue with neovim and TMUX. If on my host machine I run tmux, and ssh into a server, and then on that remote machine I start a tmux instance (nested tmux) and open vim in there, it crashes everything (crashes my host machine tmux instance). I have `$TMUX` set on both remote and host machines. Latest nvim running on remote machine and latest TMUX on both host and remote machines. Any idea how to get around this?

Thanks!

**Comment by blacklight** [comment] 2024-06-21 09:42
@sainttttt setting `TMUX` on the remote machine is a workaround that gets things to work in case of single tmux sessions, but I'm not sure how to get it to work with nested sessions, since each will have its own `TMUX` variable.

I think that nested tmux sessions are not advised in general, and the crash around the remote neovim session may just be one of the many issues you may encounter.

Maybe you could try another non-conflicting terminal multiplexer like screen on the remote machine?

**Comment by sainttttt** [comment] 2024-06-21 09:51
@blacklight Thanks for the reply! Actually I noticed that my host tmux was not on HEAD (it was on 3.4). Upgrading it to HEAD fixed the nested issue! I did test out doing nested zellij instances and it worked, however I can't stand zellij as it has a bunch of UI clutter etc, and would have to figure out how to configure it to be more minimal like tmux. Yeah screen is an option I guess as a last resort, but I'm glad it's working now atm. Thanks!

**Comment by ChristophSonnleitner** [comment] 2024-06-22 19:37
The TMUX=meow fix worked for me, but caused that clipboard in neovim did not work anymore.
What worked for was opening another tmux session on the server I ssh-ed into (one tmux session on the client, one tmux-session on the server). After that nvim didn't crash anymore and I could use the clipboard still (using wezterm, if relevant)

**Comment by lennartack** [comment] 2024-06-23 18:58
@ChristophSonnleitner instead of `TMUX=meow` you could try to set it to the value it has locally within tmux.

**Comment by joaospinto** [comment] 2024-06-28 21:00
`brew install tmux --HEAD` didn't solve it for me.
Setting $TMUX to anything works if I'm launching `neovim` inside `tmux -> ssh`.
However, if I launch it inside `tmux -> ssh -> tmux`, $TMUX is already set, and when I launch `neovim` the local (but not the remote) tmux server crashes.
Using iTerm2.

**Comment by sainttttt** [comment] 2024-06-28 21:09
@joaospinto So first of all tmux --HEAD should be newer than 3.4_1 - try uninstalling tmux and then reinstalling it. Secondly, this similar issue was happening to me but I didn't update the tmux on the remote server. See if that fixes it. I have `tmux next-3.5` on both client and server

**Comment by dmitridb** [comment] 2024-06-28 22:20
> @sainttttt setting `TMUX` on the remote machine is a workaround that gets things to work in case of single tmux sessions, but I'm not sure how to get it to work with nested sessions, since each will have its own `TMUX` variable.
> 
> I think that nested tmux sessions are not advised in general, and the crash around the remote neovim session may just be one of the many issues you may encounter.
> 
> Maybe you could try another non-conflicting terminal multiplexer like screen on the remote machine?

this is happening outside of nested sessions for me though...

in fact since a nested session seems to set $TMUX for me simply doing this prevents neovim from crashing!

and single-level nested sessions have worked fine for me for 15 years plus now so i don't think that's related here (always figured ctrl+b was default mapped for remote session purposes so you didnt have to remap ctrl+a to ctrl+b in nested sessions like i have to in nested screen, which has also worked just fine since ancient times when we discovered this)

iterm2 3.5.2
tmux 3.4
neovim 0.10.0 in a remote debian shell

**Comment by dmitridb** [comment] 2024-06-28 23:01
I'm finding tmux 3.5 also fixes things just fine for me

**Comment by histamineblkr** [comment] 2024-07-08 20:50
# Issue
Similar to everyone's stated issue of tmux server unexpectedly exiting, but slightly different variables and setup.

## Setup and Versions
Local Tmux: 3.4 on Manjaro
Remote Tmux: 3.4 on Ubuntu
Remote Nvim:
```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
```
I also have fairly developed `.ssh/configs` and `.tmux.conf` files, but I do not think those affect anything relevant (of course, I could be mistaken).

## Scenarios
### The Crash/Exit
The setup that gave me the exit is a tmux server locally and then a ssh to a GCP instance. From there, I ran `nvim` and it crashes/exits.
In the local tmux, the `$TMUX` var is pointed to the file you'd expect. After ssh-ing to the remote instance, `$TMUX` is empty. Setting it to an arbitrary value doesn't prevent the crash/exit.

### Preventing Crash/Exit and Strange Output
 If I create a tmux session locally and then ssh to my remote instance and then run `nvim -V` I get repeating output:
```
...
chdir(vim/)                                                                                                                                                                                 
chdir(/home/user)                                                                                                                                               
chdir(/home/user)                                                                                                                                               
chdir(vim/)                                                                                                                                                                                 
chdir(/home/user)                                                                                                                                               
chdir(/home/user)                                                                                                                                               
chdir(/home/user/apps/nvim-linux64/share/nvim/runtime/lua/vim/)                                                                                                 
chdir(/home/user)                                                                                                                                               
chdir(/home/user)                                                                                                                                               
chdir(vim/)                                                                                                                                                                                 
-- More --[server exited unexpectedly]
```
where it eventually exits after scrolling some number of lines (~40ish).

More interestingly, I can prevent the exit/crash by running this:
```
nvim -V | less
```
less doesn't really work correctly, but captures some of the output. I can then exit less where I am still stuck in the nvim command (I think) and then can Ctrl-C out of the command with my tmux session still intact. A return code of 0 is given:
```
❯ echo $?
0
```
Also `nvim | less` produces the same behavior.

### No Crash/Exit
What if I nest tmux sessions so the `$TMUX` variable is set on the remote machine?:
```
ssh work-bastion -t tmux new -t work -s work
```
It works (mostly). I can run nvim on a file or just plainly, but the interesting part is when I use `nvim -V`. I get the strange output as above, except I make it all the way to the very end of output:
```
...
chdir(/home/user)                                                                                                                                               
chdir(/home/user/apps/nvim-linux64/share/nvim/runtime/plugin/)                                                                                                  
chdir(/home/user)                                                                                                                                               
finished sourcing /home/user/apps/nvim-linux64/share/nvim/runtime/plugin/tohtml.lua                                                                             
not found in 'packpath': "pack/*/start/*"                                                                                                                                                   
not found in 'packpath': "start/*"                                                                                                                                                          
not found in runtime path: "plugin/**/*"                                                                                                                                                    
Executing BufWinEnter Autocommands for "*"                                                                                                                                                  
autocommand autocmd SafeState * ++once call s:Highlight_Matching_Pair()                                                                                                                     
Executing BufEnter Autocommands for "*"                                                                                                                                                     
autocommand sil call s:LocalBrowse(expand("<amatch>"))                                                                                                                                      
Executing VimEnter Autocommands for "*"                                                                                                                                                     
Press ENTER or type command to continue                                                                                                                                                     
autocommand sil call s:VimEnter(expand("<amatch>"))                                                                                                                                         
Press ENTER or type command to continue                                                                                                                                                     
Press ENTER or type command to continue
```
If I hit `e` I enter nvim edit mode? Or at least I enter nvim's main page and can then exit if I press the right keys, which is some weird mix of nvim commands and whatever the hell command line mode I am in above.

**Comment by sainttttt** [comment] 2024-07-08 21:22
@histamineblkr Upgrade both tmux's to 3.5 (head) and set $TMUX=foo(whatever you want) on both machines as well and see if you have the issue. This fixed it for me

**Comment by histamineblkr** [comment] 2024-07-09 18:01
The `nvim -V` bug is still present in nvim `3.5`. I kept it simple with a single tmux server (no nesting) and then sshing to the remote instance.

Newest tmux version:
![tmux-3 5](https://github.com/tmux/tmux/assets/5628330/9afac525-a781-4402-b16a-a6f3a1665994)

Ssh to instance:
![ssh-thru-tmux](https://github.com/tmux/tmux/assets/5628330/25e88057-b009-4370-8197-842cada7c0b8)

nvim -V bug:
![tmux-3 5-nvim-V-bug](https://github.com/tmux/tmux/assets/5628330/5c2be31d-fed8-4392-a5bf-6de2bcc704aa)

**Comment by histamineblkr** [comment] 2024-07-09 18:03
Should I report a new bug?

**Comment by sainttttt** [comment] 2024-07-09 18:29
@histamineblkr Oh you're right, I didn't catch the part you posted about `nvim -V` - I have the same bug too. Maybe a new issue might be good, cause I'm not sure they're related.

**Comment by histamineblkr** [comment] 2024-07-09 19:00
Wait, I am dumb... This isn't a problem with tmux it is a problem with nvim. Duh :expressionless: . I will open an issue in the proper project. :laughing:

**Comment by sainttttt** [comment] 2024-07-09 19:37
@histamineblkr Haha you're right

**Comment by swahpy** [comment] 2024-07-11 03:29
> Also happening to me inside of WezTerm with tmux 3.4 + nvim 0.10.0 over ssh on macOS. Using Alacritty instead of WezTerm works.

having the exactly same issue here. setting $TMUX=hello works for me.

**Comment by AlexAlbright** [comment] 2024-07-12 04:30
I'm also having this issue with iTerm2 with tmux 3.4 + neovim v0.11.0-dev over ssh on macOS. Attempting open neovim causes iTerm2 to crash entirely. 

Setting `TMUX=foo` on my Ubuntu host seems to fix this issue, however copy/pasting doesn't work. I get an error in neovim when attempting to yank text that `clipboard: error invoking tmux: error connecting to foo (No such file or directory)`

I'm guessing this is the error @ChristophSonnleitner was seeing, but his fix of one tmux session open on the client and one on the host doesn't work for me. What is odd is it clearly sets a `TMUX=` env var on the host, and it has a value, but still crashes...

**Comment by mdentremont** [comment] 2024-07-19 18:42
Hey folks, thanks for much for this thread - `brew install tmux --HEAD` fixed the issue for me (3.4 did not)

**Comment by easystartup-io** [comment] 2024-08-10 14:25
I've spent the past week diving deep into Neovim and Tmux, and dang I hit a snag with a basic use case. When I SSH into hetzner machine using Tmux within Tmux, everything crashed. Neovim is an incredible tool, but it's frustrating because I lost all my sessions when the Mac session crashed while trying to use Neovim on a remote Ubuntu host. Let me check if above workarounds work where I update tmux to latest head.

**Comment by prurigro** [comment] 2024-08-13 01:24
Assuming 3.5 is still a ways out, would it be worth a 3.4.1 point release with just https://github.com/tmux/tmux/commit/aa17f0e0c1c8b3f1d6fc8617613c74f07de66fae applied in the mean time so distros update to a fixed version?

**Comment by floriskruisselbrink** [comment] 2024-09-01 18:40
> Hey folks, thanks for much for this thread - `brew install tmux --HEAD` fixed the issue for me (3.4 did not)

This doesn't work for me. Has something changed in the meantime? It seems the last version is still 3.4 and that version crashes.

When I execute above command the result is this:
```
$ brew install tmux --HEAD
==> Downloading https://formulae.brew.sh/api/formula.jws.json
############################################################################################################################################################################################################################ 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
############################################################################################################################################################################################################################ 100.0%
Error: tmux 3.4_1 is already installed
To install HEAD_1, first run:
  brew unlink tmux
$
```

**Comment by sainttttt** [comment] 2024-09-01 18:46
@floriskruisselbrink Yeah you have to run brew unlink tmux first to install the head version. Literally says in the output you printed. If that doesn't work then do `brew uninstall tmux` and then `brew install tmux --HEAD` that should sort it out.

**Comment by floriskruisselbrink** [comment] 2024-09-02 06:56
@sainttttt sorry, you are right. I was confused as I thought brew told me I already had tmux 3.4.1 installed, but the _1 is of course not a tmux version suffix but a packaging suffix from homebrew.
Unlinking first works fine. Was just user error on my side.
