### ISSUE TITLE
Repeating escape sequences

### ISSUE THREAD

**Issue by lemnos** [tmux/tmux#2998] opened 2021-12-05 01:17 UTC
It seems that tmux is sending multiple copies of the passthrough sequences the the terminal. The following

printf '\033Ptmux;\033\033]11;?\007\033\\'

Elicits multiple response sequences on my machine when running tmux in kitty. Am I doing something wrong?

Version: 3.2a

**Comment by systemmonkey42** [comment] 2021-12-06 00:31
> Elicits multiple response sequences on my machine when running tmux in kitty. Am I doing something wrong?

Which Kitty?  PC (PuTTY clone) or Mac? (https://github.com/kovidgoyal/kitty)

**Comment by rvaiya** [comment] 2021-12-06 04:07
The modern GPU accelerated one written in python. Though I oddly can't seem to reproduce this anymore. My code was broken in other ways so I might have been mistaken. Out of curiosity does libevent make any guarantees about the order of events?

**Comment by rvaiya** [comment] 2021-12-06 04:50
Ah, I figured it out. It seems that when multiple terminals are attached to the same tmux session it will send escaped codes to all attached sessions and process the responses. 

From the application's perspective this causes pandemonium since it is not expecting interleaved responses from multiple terminals. 

Is this by design, or is it a bug? It seems a reasonable thing to do would be to process responses (and possibly only send requests) exclusively from the last active terminal.

**Comment by systemmonkey42** [comment] 2021-12-06 05:03
I would say by design.  Each connected client will send the mentioned escape codes to its local terminal and receive a response.  Identifying a single response is technically impossible, but if your application/script was tmux-aware you could use
```
tmux list-clients -t $TMUX_PANE -F '#{clients}'
```
to list the connected client ttys for example, or 
```
tmux display-message -p '#{window_active_clients}'
```
to list how many clients are viewing the current window (and will react to control characters sent to the current pane)

What I have done in the past is use the 'list-clients', select a tty (usually the first), and send the control to only one.  At that point you get a single response.

**Comment by rvaiya** [comment] 2021-12-06 05:14
> Identifying a single response is technically impossible

Why can't tmux just send requests to a single client? If the program is sending escaped sequences it is presumably tmux aware and is trying to solicit information from 'the controlling terminal'.

> What I have done in the past is use the 'list-clients'..

Thanks, this should work nicely. Is there a way to identify the client which executed the program?

**Comment by systemmonkey42** [comment] 2021-12-06 05:19
>  Is there a way to identify the client which executed the program?

No, because the program being executed is attached to the server.   The clients are mostly indistinguishable.

In fact, your script could even discover that there are no clients attached, and the escape code goes unanswered.

You can find out which client you are typing into (ie, which is "active") by using
```
tmux display-message -p '#{client_tty}'
```
but really there is no guarantee because the same window could be active in two clients on two separate ssh-sessions, from two different machines.

**Comment by rvaiya** [comment] 2021-12-06 05:23
> No, because the program being executed is attached to the server. The clients are mostly indistinguishable.

Yes, but the server could theoretically keep track of the last client which fed it input and only send the escaped sequences to that client.

> In fact, your script could even discover that there are no clients attached, and the escape code goes unanswered.

True, but this is unlikely to happen given that most sequences of interest are sent in response to some user action.

**Comment by rvaiya** [comment] 2021-12-06 05:27
> The server could theoretically keep track of the last client which fed it input and only send the escaped sequences to that client.

From my preliminary experiments this seems to be what `client_tty` actually corresponds to in practice. So it solves my problem :).

**Comment by nicm** [comment] 2021-12-06 07:21
tmux does not know what the passthrough escape sequence does, there is no way for it to know you only want to send it to one client.

Similarly, it does not know the responses and passthrough escape sequence are connected, for all it knows they could be key presses.

**Comment by rvaiya** [comment] 2021-12-06 09:44
Perhaps it could inspect them for sequences which require a response and
send those to a single client to avoid placing the burden of disaggregating
the multiple escape codes on the application. The particular use case I
have in mind is querying the current terminal colors using OSC sequences,
though I am sure there are other instances in which it might be desirable
to query the underlying terminal directly.

**Comment by nicm** [comment] 2021-12-06 09:48
No, passthrough is just that, tmux should not inspect them. The alternative
is to add support to tmux itself.

**Comment by nicm** [comment] 2021-12-06 09:56
We could make it so you could specify a client to send the escape sequence do so instead of `tmux;` you would do `tmux:/dev/ptyp0` or similar. Not sure how difficult this would be.

But I'm not convinced we should encourage use of the passthrough sequence.

**Comment by rvaiya** [comment] 2021-12-06 10:12
> No, passthrough is just that, tmux should not inspect them. 

Most programs assume they are running in a single terminal. It would seem natural to extend this to passthrough sequences. The sequences would still be sent unaltered to the terminal, they just wouldn't elicit multiple responses (which the application can't properly distinguish amongst on its own). I agree that that it makes sense for unidirectional sequences to be sent to all terminals.

> The alternative is to add support to tmux itself.

You would still be left with the problem of deciding which terminal to forward the sequences to. Though it would indeed be nice if tmux could handle OSC 11/12/10/4* query sequences without explicit escapes :P.

> We could make it so you could specify a client to send the escape sequence do so instead of tmux.

If the program knows which terminal it wants to write to it can just do so directly. This is the approach I am currently taking.

**Comment by nicm** [comment] 2021-12-06 10:24
They are running in a single terminal. The terminal is tmux. The passthrough sequence is explicitly for use when you know you are running in tmux. I do not want to extend it in complicated ways, it is meant for stuff that tmux has no reason or ability to support (like notifications), or where you know there will only be one terminal or don't mind sending to them all.

tmux has supported OSC 11 queries since f08bfa7cd13f605396ac7e2810b8fa516f8e11bd but it is not able to respond unless the colour has been set by the user. Anything else runs into the same problem you are having - which terminal's colour should tmux use?

**Comment by lemnos** [comment] 2021-12-06 18:16
> They are running in a single terminal. The terminal is tmux.

I meant for code which wants to access the underlying terminal. I agree that this should not generally be done, but when it is necessary it makes sense to provide the application with a single terminal model. Tmux already does this in the case of non escaped sequences (e.g if multiple terminals are attached the size of the currently active one is provided to the program). It would be easier for programs which need to access the underlying terminal to be able to just wrap the existing logic in an escape rather than having to account for the fact that they may receive multiple responses. 

> The passthrough sequence is explicitly for use when you know you are running in tmux. I do not want to extend it in complicated ways, it is meant for stuff that tmux has no reason or ability to support (like notifications), or where you know there will only be one terminal or don't mind sending to them all.

I agree that this makes sense for things which do are not response driven (like notifications, cursor position etc), but for queries which are attempting to obtain information from the terminal it makes sense to return a single response. E.G If you run an OSC 11 query then multiple terminals will send a result and it is impossible for the program to distinguish between them.

> tmux has supported OSC 11 queries since f08bfa7 but it is not able to respond unless the colour has been set by the user.

My apologies, I am running a slightly older version :P. Would it not be possible to read colors from the underlying terminal and respond with those in the event that they have not explicitly been set by the user?

**Comment by nicm** [comment] 2021-12-07 07:12
OK, well I will accept a change to allow the client (or currenc client) to be specified as part of the passthrough sequence prefix, but I don't think any other changes are appropriate.

**Comment by rvaiya** [comment] 2021-12-07 07:59
I understand your position on escaped sequences in general, but permit me to make a final case for querying the underlying terminal in the case of OSC color sequences one more time (I am here referring to unescaped OSC sequences).

Lets suppose for a moment that the user is running an editor which queries the background color of the terminal to determine what colours it should use. There are four possibilities:

1. A single terminal is attached and tmux reports nothing: 

    - The user is left with potentially ugly fallback colours.

2. A single terminal is attached and tmux reports the background color obtained from querying the underlying terminal:

    - The user sees what they would expect if they had run the program outside of tmux.

3. Multiple terminals are attached (and viewing the same pane) and tmux does nothing:

   - Both users are left with ugly fallback colours.

4. Multiple terminals are attached and tmux responds with the colors obtained from querying the most recently active terminal

   - User 1 sees what they would expect if they ran the editor locally (outside of a tmux session).
   - User 2 is left with potentially ugly fallback colours (if using a different/incompatible theme).

 In most cases multiple users are unlikely to be using the same pane at the same time, but even in the event that they are pairing on the same editor, 4 is not necessarily a worse outcome than 3 (imo). In the more common use case of a single user attached to a session, 2 is almost certainly more desirable than 1.

**Comment by nicm** [comment] 2021-12-07 08:50
OK, do it and I will review it. Possibly it should be initially controlled by an option (off = current behaviour), because I am concerned with applications being left with incorrect information as soon as the user reattaches. But we can decide that once the basics work.

**Comment by nicm** [comment] 2021-12-10 12:47
I'll close this for the moment but if you have any questions feel free to ask them or to open a PR or another issue. Thanks!

**Closed by nicm** 2021-12-10 12:47 UTC
