### ISSUE TITLE
OSC11 query caches response until client is changed 

### ISSUE THREAD

**Issue by Baspar** [tmux/tmux#3582] opened 2023-05-31 12:53 UTC
### Issue description

Following commit a41a92744188ec5c8a8d4ddc100ec15b52d04603, the OSC 11 sequence correctly returns the background color, but doesn't reflect any change in background color until client is detached/attached 

### How to reproduce:

`~/osc11.bash`
```bash
#!/usr/bin/env bash
read -rs -d \\ -p $'\e]11;?\e\\' BG
echo "$BG" \
    | xxd -c 64 \
    | grep -o -E "rgb:.{4}/.{4}/.{4}"
```
1. Clean existing tmux `tmux kill-server`
2. Start a new session `tmux new`
3. `bash  ~/osc11.bash` => `rgb:fbfb/f1f1/c8c8`
4. Update the background from the terminal (In my case, Change from OS light mode to dark mode)
5. `bash  ~/osc11.bash` => `rgb:fbfb/f1f1/c8c8` **Still shows the previous background color**
6. Detach session `C-b d`
7. Re-attach `tmux attach`
8. `bash  ~/osc11.bash` => `rgb:2020/2020/2020` **Shows the new background color**

### Required information
* tmux version: `tmux next-3.4` @ 0eb5d2545367c4d051861c33452d33f25b427e89
* Platform: `Darwin arm`
* $TERM inside tmux: `xterm-256color`
* $TERM outside tmux: `xterm-256color`
* Terminal: Wezterm

**Comment by nicm** [comment] 2023-05-31 23:17
There is no mechanism for the terminal to tell tmux the colour has changed and polling for the background colour is silly. If you change the background colour outside tmux you need to detach and reattach.

**Comment by Baspar** [comment] 2023-06-01 07:54
Isn't a41a92744188ec5c8a8d4ddc100ec15b52d04603 simply relaying the OSC11 `?` request to the terminal in case the default background colour isn't set ?
In which case, it should print the updated background in step `5.`, since that's how it behaves when I run those steps outside of Tmux

**Comment by nicm** [comment] 2023-06-01 08:06
Good point, but no, it doesn't, it reads the default value on attach and uses that if you haven't set a background inside tmux.

**Comment by vimpostor** [comment] 2023-07-07 10:07
> polling for the background colour would be silly

Zellij queries for the bg/fg colour on every `SIGWINCH` (in addition to on attach: https://github.com/zellij-org/zellij/pull/1358

Maybe this could help here, but it looks like not many terminals send `SIGWINCH` when their colorscheme changes (I only know of [iTerm that does this](https://gitlab.com/gnachman/iterm2/-/commit/f61c3ee01ceb69b083c017de7de781bd47c9f973), but it might be something worth implementing in other terminal emulators).

**Comment by nicm** [comment] 2023-09-02 15:52
Try this please which will do it on WINCH but at most once every 30 seconds: [tmux-fgbg-winch.diff.txt](https://github.com/tmux/tmux/files/12504273/tmux-fgbg-winch.diff.txt)

**Comment by vimpostor** [comment] 2023-09-02 19:44
@nicm I can confirm the patch is working.

Tested with starting vim inside tmux (which sets `background` according to OSC11 response), as well as with a manual `printf '\e]11;?\a'`.

The only problem with this implementation is that tmux may miss a colorscheme change, if the user resizes the window and then changes the colorscheme within the next 30 seconds. But still, it's better than nothing.

**Comment by nicm** [comment] 2023-09-02 20:08
Great, I have applied this to OpenBSD now, it will be in GitHub later. Thanks!

**Closed by nicm** 2023-09-02 20:08 UTC
