### ISSUE TITLE
2.4 breaks end of line

### ISSUE THREAD

**Issue by patrickSpaceSurfer** [tmux/tmux#1318] opened 2018-04-16 23:11 UTC
I am using FreeBSD 11.1 with rxvt-unicode-9.22 (TERM=rxvt) and bash-4.4.19. As of tmux version 2.4 (built from github source code as well as FreeBSD ports) there are issues with how tmux handles the end of a line. Once the tmux terminal fills all rows, the ends of a line are displayed with spaces filling all remaining columns instead of a new line. So if I were to cut and paste the output of ls -latrh into an editor then each line would have extra spaces on the end. Note that this only happens once the tmux terminal fills all rows. If I detach the tmux terminal and re-attach, then the end of lines are correct until I add a new line to the terminal.
tmux 2.3 (build from github source code as well as FreeBSD downgraded ports) works fine.

**Comment by patrickSpaceSurfer** [comment] 2018-04-16 23:43
This break seems to have happened in commit
aace1ead1e711412e4be0287972a389248583ad6
on the the 18th of Apr 2017

**Comment by nicm** [comment] 2018-04-17 05:47
Does this happen with master?

**Comment by patrickSpaceSurfer** [comment] 2018-04-17 21:17
yes, master is broken. However, strangely, if I revert commit aace1ead1e711412e4be0287972a389248583ad6, master is still broken.

If I checkout tag 2.4 and revert aace1ead1e711412e4be0287972a389248583ad6, then it works

**Comment by patrickSpaceSurfer** [comment] 2018-04-17 21:39
All lines are affected, but only when the terminal has at least as many lines as there are rows in the x window. I build tmux in a standard rxvt terminal, run
./tmux -L test9
run
ls -latrh
in the tmux terminal. Copy and paste a few lines into emacs (any line will do, no need to scroll). The lines in emacs have extra spaces (to fill all the columns in my tmux terminal). Note that the ls output has sufficient entries to fill more rows than there are in my terminal x window. If I do the ls in a directory with only a few files (say ls ../), so that there are insufficient entries to fill all the rows in my tmux window, then when I cut and paste a few lines into emacs they do not have extra spaces on the end.

To be clear, my tmux terminal has 71 lines and 223 columns
ls -latrh lists 284 files/directories
ls ../ lists 41 files/directories

**Comment by nicm** [comment] 2018-04-17 21:40
Show tmux logs from reproducing with master please.

**Comment by nicm** [comment] 2018-04-17 21:44
Also I don't think you understood my question.

It only happens when the terminal scrolls, right? If you have a terminal of
71 lines and you start at line 0 and output 284 lines, then the terminal
will scroll. If you output 41 it will not.

But what I am asking is: what happens if you output 73 lines? Do all 71
lines now have spaces, or only the bottom 2 lines that were scrolled on?

**Comment by patrickSpaceSurfer** [comment] 2018-04-17 22:06
ok, I get what you mean now.

I have attached the logs for ./tmux -vvv

If I scroll up to the first few lines of the ls command, they do indeed paste correctly, the problem does seem to start from line 72, hence pasting 70-74 will have some good lines and some bad lines.

[tmux-out-16339.log](https://github.com/tmux/tmux/files/1921722/tmux-out-16339.log)
[tmux-server-16339.log](https://github.com/tmux/tmux/files/1921723/tmux-server-16339.log)
[tmux-client-16337.log](https://github.com/tmux/tmux/files/1921724/tmux-client-16337.log)

**Comment by patrickSpaceSurfer** [comment] 2018-04-17 22:08
If I tun a bash script to echo 1 to 100 on each line and run it when I first start tmux, the problem starts at number 68, but my bash prompt outputs 3 lines before I can run the command. So it looks like the first line with a problem is the one that first scrolled.

**Comment by nicm** [comment] 2018-04-17 22:13
I do not see tmux sending any extra spaces here. Does this also happen with
xterm?

**Comment by patrickSpaceSurfer** [comment] 2018-04-17 22:17
Seems to work fine for xterm

**Comment by nicm** [comment] 2018-04-17 22:25
You said some good lines and some bad lines? Can you show me a log and tell
me exactly what is on the bad line so I know I am looking at the right one?

**Comment by patrickSpaceSurfer** [comment] 2018-04-17 22:36
So xterm always works, no matter what the TERM value and rxvt always fails.
Also, xterm is much slower than rxvt, but only when I run the command from in tmux, if I run the command in the xterm without tmux its similar to rxvt. rxvt is always fast.

This time I can the 1-100 bash script, I pasted lines with numbers 64-73. 64-67 are ok, 68 to 73 are broken.

[tmux-out-17940.log](https://github.com/tmux/tmux/files/1921837/tmux-out-17940.log)
[tmux-server-17940.log](https://github.com/tmux/tmux/files/1921838/tmux-server-17940.log)
[tmux-client-17938.log](https://github.com/tmux/tmux/files/1921839/tmux-client-17938.log)

**Comment by nicm** [comment] 2018-04-18 05:45
There is no difference between what tmux sends for any of lines 64-73 that
I can see. This looks like a bug in rxvt-unicode.

**Comment by nicm** [comment] 2018-04-18 05:46
I'll send an example you can test without tmux later in the day.

**Comment by nicm** [comment] 2018-04-18 09:14
Oh I know what the problem is, when tmux is scrolling it is scrolling from the last column which apparently causes rxvt-unicode to create lines filled with spaces rather than empty. This is a bit weird, but we can probably deal with it OK.

**Comment by nicm** [comment] 2018-04-18 09:32
Oh it does, but I was testing with TERM=rxvt-unicode and it does the same for INDN as well. Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/1923301/x.diff.txt)

**Comment by nicm** [comment] 2018-04-23 07:41
Applied to OpenBSD now, will be in GitHub later. Thanks!

**Closed by nicm** 2018-04-23 07:41 UTC
