### ISSUE TITLE
3.4 questions and comments

### ISSUE THREAD

**Issue by nicm** [tmux/tmux#3836] opened 2024-02-13 09:16 UTC
### Ask or discuss any quick questions about 3.4 here please.

**Do not use this issue for bug reports,** please open a new issue with full information, see [CONTRIBUTING](https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md).

**[The 3.4 CHANGES file is here](https://raw.githubusercontent.com/tmux/tmux/3.4/CHANGES).**

As always, thanks to the many people who contributed to both this and to previous releases.

**Comment by ngocphamm** [comment] 2024-02-13 13:25
Just updated to tmux 3.4 on my mac 14.3.1, and it seems like the `tmux-mem-cpu-load` plugin stops rendering. Running it directly still prints out the values.

This is my config for it

`set -g status-left '#[fg=green]#(whoami)@#h :: #[fg=blue]#($TMUX_PLUGIN_MANAGER_PATH/tmux-mem-cpu-load/tmux-mem-cpu-load --interval 5)#[default]'`

**Comment by kevinkirkup** [comment] 2024-02-13 13:56
On my mac when I try to split windows with `-p` option, I'm getting "Size missing" warning and the split fails.
Full commands:
```
new-window -n tmux-dev -c ${HOME}
split-window -h -p 50 -t 0
split-window -v -p 50 -t 1
```

**Comment by creaktive** [comment] 2024-02-13 15:05
> Just updated to tmux 3.4 on my mac 14.3.1, and it seems like the `tmux-mem-cpu-load` plugin stops rendering. Running it directly still prints out the values.
> 
> This is my config for it
> 
> `set -g status-left '#[fg=green]#(whoami)@#h :: #[fg=blue]#($TMUX_PLUGIN_MANAGER_PATH/tmux-mem-cpu-load/tmux-mem-cpu-load --interval 5)#[default]'`

Out of curiosity, does [rainbarf](https://github.com/creaktive/rainbarf) work for you?

**Comment by ffernand** [comment] 2024-02-13 15:08
Upgrading to 3.4 and my terminal (rxvt-unicode) spits out what looks like color control sequences...
```
10;rgb:ff00/ff00/ff00]11;rgb:2000/1000/1000
```

I've tried to widdle down my tmux config, but in the end I can reproduce with an empty tmux config and the system bash from `/etc/skel/bashrc`, but only for rxvt-unicode shell (ie. urxvt).

I cannot reproduce with either Alacritty or xterm, though neither of these are my preferred shell.

As far as I can tell (and I'm not certain about this), it's related to commit https://github.com/tmux/tmux/commit/a41a92744188ec5c8a8d4ddc100ec15b52d04603.  But I couldn't revert to test if this was the case as the revert wasn't clean and I'm a little out of my depth at resolving those merge conflicts for tmux.

**Comment by ngocphamm** [comment] 2024-02-13 15:11
> > Just updated to tmux 3.4 on my mac 14.3.1, and it seems like the `tmux-mem-cpu-load` plugin stops rendering. Running it directly still prints out the values.
> > This is my config for it
> > `set -g status-left '#[fg=green]#(whoami)@#h :: #[fg=blue]#($TMUX_PLUGIN_MANAGER_PATH/tmux-mem-cpu-load/tmux-mem-cpu-load --interval 5)#[default]'`
> 
> @ngocphamm out of curiosity, does [rainbarf](https://github.com/creaktive/rainbarf) work for you?

I didn't know what that is and right now I don't really have time to try it out. Maybe later 😁

**Comment by H4ckint0sh** [comment] 2024-02-13 15:33
> On my mac when I try to split windows with `-p` option, I'm getting "Size missing" warning and the split fails. Full commands:
> 
> ```
> new-window -n tmux-dev -c ${HOME}
> split-window -h -p 50 -t 0
> split-window -v -p 50 -t 1
> ```

Found this in changelog.

 Note the -p and -l options to split-window are now gone, these may reappear
  once I think them through again.

**Comment by ffernand** [comment] 2024-02-13 16:07
> Upgrading to 3.4 and my terminal (rxvt-unicode) spits out what looks like color control sequences...
> 
>    10;rgb:ff00/ff00/ff00]11;rgb:2000/1000/1000

😩 nvm.  It just occurred to me to check closed issues for tmux where the issue was reported here https://github.com/tmux/tmux/issues/3470.

After apply the patch to rxvt-unicode referenced by @nicm in the issue, the terminal with tmux no longer spits out control sequences.  It's a bug in rxvt-unicode on the handling of OSC commands for color sequences.

**Comment by michal-piekarski** [comment] 2024-02-13 16:31
[Wiki page](https://github.com/tmux/tmux/wiki) still links to version `3.3a`
<img width="913" alt="image" src="https://github.com/tmux/tmux/assets/60774954/b51bd853-3da3-4711-8eea-fbc584a3c6ab">

**Comment by afh** [comment] 2024-02-14 05:18
Thanks for reporting, @michal-piekarski; the wiki home page has been updated.

**Comment by vbauerster** [comment] 2024-02-14 08:13
I cannot paste any preset buffer (with default <kbd>=</kbd>) until I copy something explicitly.
By preset buffer I mean following line in my config:

```
set-buffer -b mail my@gmail.com
```

If there are several preset buffers I cannot even navigate them with arrows or `j/k` again until I copy something interactively.
Is it expected?

**Comment by ngocphamm** [comment] 2024-02-14 12:00
> > Just updated to tmux 3.4 on my mac 14.3.1, and it seems like the `tmux-mem-cpu-load` plugin stops rendering. Running it directly still prints out the values.
> > This is my config for it
> > `set -g status-left '#[fg=green]#(whoami)@#h :: #[fg=blue]#($TMUX_PLUGIN_MANAGER_PATH/tmux-mem-cpu-load/tmux-mem-cpu-load --interval 5)#[default]'`
> 
> @ngocphamm out of curiosity, does [rainbarf](https://github.com/creaktive/rainbarf) work for you?

It does not seem to work for me `brew install rainbarf`.

`rainbarf --tmux --width 40 --no-battery` prints out `#[fg=green,bg=green]▁#[fg=red,bg=red]▁▁▁#[fg=yellow,bg=yellow]▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁#[fg=blue,bg=blue]▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▂#[fg=default,bg=default]`

But with tmux config like this, it shows nothing there.
`set -g status-left '#[fg=green]#(whoami)@#h :: #($rainbarf --tmux --width 40 --no-battery)'`

**Comment by godeater** [comment] 2024-02-14 23:40
> > On my mac when I try to split windows with `-p` option, I'm getting "Size missing" warning and the split fails. Full commands:
> > ```
> > new-window -n tmux-dev -c ${HOME}
> > split-window -h -p 50 -t 0
> > split-window -v -p 50 -t 1
> > ```
> 
> Found this in changelog.
> 
> "Note the -p and -l options to split-window are now gone, these may reappear once I think them through again."
> 
> use -l option instead.

That comment in the change log is from 2009, and refers to tmux 0.6 😁

I think there's a small bug that's been introduced into the cmd-split-window.c on line 98:

` size = args_strtonum_and_expand(args, 'l', 0, 100, item,`

Which I think should be:

` size = args_strtonum_and_expand(args, 'p', 0, 100, item,`

I rebuilt a local copy of tmux with that alteration and that seems to have fixed the issue for me.

**Comment by iamralch** [comment] 2024-02-15 05:19
Do you have any links to the previous release 3.3a? Everything stopped working with 3.4 on my machine.

**Comment by krader1961** [comment] 2024-02-15 05:24
> Do you have any links to the previous release 3.3a? Everything stopped working with 3.4 on my machine.

@iamralch Really? Everything? Tmux itself stopped working? Reverting to an older version is fine until whatever regression was introduced has been fixed. But that is rarely a long term strategy. Also, if you have found regressions introduced by a newer version it will help everyone using Tmux if you tell us what the new version broke.

**Comment by kuntau** [comment] 2024-02-17 08:25
> I think there's a small bug that's been introduced into the cmd-split-window.c on line 98:
> 
> ` size = args_strtonum_and_expand(args, 'l', 0, 100, item,`
> 
> Which I think should be:
> 
> ` size = args_strtonum_and_expand(args, 'p', 0, 100, item,`
> 
> I rebuilt a local copy of tmux with that alteration and that seems to have fixed the issue for me.
> 
> I've also raised a PR with this small fix in it.

Thank you!!

I've been pulling my hair since 3.4-next why `fzf` split window cause tmux hang. Made this change on my local copy and :chef_kiss:

**Comment by rfrancoise** [comment] 2024-02-17 14:40
> edit: Those changes ([c07d582](https://github.com/tmux/tmux/commit/c07d582e2476db075252998388305f11302a8b23)) have been in the code base for 2 years. I wonder why it only cause problems now?

The previous version (3.3/3.3a) was released in June 2022 but before that lived in a branch for some time. It doesn't have this commit.

**Comment by pqwy** [comment] 2024-02-19 16:28
I used

    bind-key -n MouseDrag1Status swap-window -d -t=

to reorder windows by dragging, but it stopped working. Any ideas?

**Comment by nnovzver** [comment] 2024-02-19 17:22
Search in copy mode seems broken in 3.4. I create a file with a long line repeating "lorem ipsum" 100 times, then
```
cat lorem
prefix + [
ctrl+r lorem
and n to jump next keyword doesn't work as expected
```

**Comment by DovieW** [comment] 2024-02-21 23:37
I can't seem to get hyperlinks working.
Some of my config:
```
set-option -g default-shell $SHELL
set -ga terminal-features "*:hyperlinks"
set -g mouse on
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
set-environment -g COLORTERM "truecolor"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
set-environment -g COLORTERM "truecolor"
```

**Comment by DovieW** [comment] 2024-02-21 23:44
Nevermind it is working. Though not in Alacritty. Only in Gnome Terminal.

Hyperlinks work in Alacritty when not using Tmux.

**Comment by afh** [comment] 2024-02-22 07:00
Just a wild guess @DovieW:
If I'm not mistaken alacritty has its own way of recognizing and interacting with links (and other terminal text matching a pattern) through hints (see section HINTS in [alacritty(5)](https://alacritty.org/config-alacritty.html)). For hints mod-keys, like `Shift`, can be specified as well as `hyperlinks`, which includes "all OSC 8 escape sequence hyperlinks […] in the hints". Could it be that alacritty's hints get in the way of tmux?

**Comment by detroyejr** [comment] 2024-02-22 14:42
The oh-my-zsh plugin has an alias "ta" which maps to `tmux attach-session -t`. Tmux version 3.3a allowed passing `-t` without any arguments, but no longer does in 3.4. In order to make a fix that works for users of 3.3a and 3.4, I would propose just calling `tmux attach-session` without any flags. `tmux attach-session` and `tmux attach-session -t` seem to do identical things and works with both versions. Could anyone here confirm if that is correct?

**Comment by pepoluan** [comment] 2024-02-24 04:10
> Edit: Amending this to say that my assumption was not correct. Aliasing `tmux attach-session -t` is better since it allows you to pass a session name. So, `ta SESSION` would no longer work if we can't pass an empty flag. New question then: is there a good way to just run the alias without needing to pass a session name as before?

I don't think it's doable with a simple alias. It needs to be turned into a function, like so:

```zsh
function ta() {
    tmux attach-session ${1:+-t}$1
}
```

**Comment by detroyejr** [comment] 2024-02-24 04:28
> I don't think it's doable with a simple alias. It needs to be turned into a function, like so:
> 
> ```shell
> function ta() {
>     tmux attach-session ${1:+-t }$1
> }
> ```

Amazing, thank you @pepoluan! That's so clean, too.

**Comment by casperklein** [comment] 2024-02-24 11:16
I've this in my `~/.inputrc`:

```
"\e[11~": "uptime\n"
"\e[12~": "hop\n"
```

This allows me, to get the uptime / start htop, when pressing F1 / F2. Starting with tmux 3.4, this does not work anymore (inside tmux). Does anyone have an idea, how to get this working again? Thanks.

**Comment by ViBiOh** [comment] 2024-02-24 13:38
I have some shifts with some unicode text since the new version.

<details>
<summary>This picture is on Alacrity terminal, in bash 5.2, without tmux. Everything seems ok</summary>

<img width="665" alt="Screenshot 2024-02-24 at 2 25 16 PM" src="https://github.com/tmux/tmux/assets/2349470/2abc2dac-087e-46a9-888a-76f84f312916">
</details>

<details>
<summary>The same request with it a tmux (same bash, same terminal). You can notice that there is a row which is not aligned.</summary>

<img width="662" alt="Screenshot 2024-02-24 at 2 24 49 PM" src="https://github.com/tmux/tmux/assets/2349470/a9e48eb5-5009-41c5-a356-507591ae9f25">
</details>

I also have a strange character in the right column when I scroll back (mouse on). And the `>` at the beginning of my prompt is disappearing.

<img width="906" alt="Screenshot 2024-02-24 at 2 33 42 PM" src="https://github.com/tmux/tmux/assets/2349470/b2200499-38ab-4364-aae7-6a628b0c0d0a">

I don't know if it's related to the OSC 133 support. How can I disable it to test?

### Configuration

```bash
> echo $PS1
\033[0;34m\u\033[0m@\033[0;31m\h\033[0m \033[0;32m\w\033[0m\033[33m$(__git_ps1)\033[0m\033[0;34m$(__kube_ps1)\033[0m\033[35m$(__terraform_ps1)\033[0m $(_ps1_previous_status)\n>
> echo $TERM
xterm-256color
> echo $LANG
en_US.UTF-8
```

My tmux.conf [is here](https://github.com/ViBiOh/dotfiles/blob/main/symlinks/tmux.conf). I don't think I have exotic stuff.

**Comment by druckdev** [comment] 2024-02-28 15:35
DId the parsing of arguments change?

Following breaks for me in 3.4:

```tmux
bind c neww -a -c "#{pane_current_path}" -t #{active_window_index}
```

with:

```
command new-window: -t expects an argument
```

If I add double quotes around `#{active_window_index}` the config is sourced successfully, but when executing the binding I get:

```
Can't find window: #{active_window_index}
```

which surprised me since the double quotes work around `pane_current_path`. Do I miss something?

**Comment by vladislavbailovic** [comment] 2024-03-03 16:10
> > > On my mac when I try to split windows with `-p` option, I'm getting "Size missing" warning and the split fails. Full commands:
> > > ```
> > > new-window -n tmux-dev -c ${HOME}
> > > split-window -h -p 50 -t 0
> > > split-window -v -p 50 -t 1
> > > ```
> > 
> > 
> > Found this in changelog.
> > "Note the -p and -l options to split-window are now gone, these may reappear once I think them through again."
> > use -l option instead.
> 
> That comment in the change log is from 2009, and refers to tmux 0.6 😁
> 
> I think there's a small bug that's been introduced into the cmd-split-window.c on line 98:
> 
> ` size = args_strtonum_and_expand(args, 'l', 0, 100, item,`
> 
> Which I think should be:
> 
> ` size = args_strtonum_and_expand(args, 'p', 0, 100, item,`
> 
> I rebuilt a local copy of tmux with that alteration and that seems to have fixed the issue for me.
> 
> I've also raised a PR with this small fix in it.

So, apparently, `-p` has been deprecated, as per `CHANGES`:

> Add support for percentage sizes for resize-pane ("-x 10%"). Also change
>  split-window and join-pane -l to accept similar percentages and deprecate the
> -p flag.

Just replacing `-p 15` with `-l 15%` in my script worked for me.

**Comment by godeater** [comment] 2024-03-03 20:50
> So, apparently, `-p` has been deprecated, as per `CHANGES`:
> 
> > Add support for percentage sizes for resize-pane ("-x 10%"). Also change
> > split-window and join-pane -l to accept similar percentages and deprecate the
> > -p flag.

That line in the CHANGES file is from the 'CHANGES FROM 3.0a TO 3.1' section. Not from 'CHANGES FROM 3.3a to 3.4'. 

Clearly -p wasn't deprecated as it was working fine in version 3.3a.

**Comment by L1Q** [comment] 2024-03-06 23:24
Any plans for improving compatibility with Nerd Fonts? They are all displayed as underscores tmux 3.4

**Comment by godeater** [comment] 2024-03-06 23:27
> Any plans for improving compatibility with Nerd Fonts? All the custom characters are displayed as underscores tmux 3.4

Absolutely nothing wrong with Tmux's support for Nerd Fonts for simply ages, Tmux 3.4 included:
![image](https://github.com/tmux/tmux/assets/1461/a017da6a-77a7-4322-94cf-44de12b9cf4e)

My prompt features many nerd font characters.

**Comment by systemmonkey42** [comment] 2024-03-06 23:38
Nerdfonts -

![image](https://github.com/tmux/tmux/assets/2985620/f04edcbe-cdef-4f64-bce4-775dfe06021d)

tmux -V
`tmux next-3.5`

Do you have a specific issue?

**Comment by L1Q** [comment] 2024-03-06 23:49
Yes, unpdated arch with kde6, maybe not entirely tmux fault.
``Konsole 24.02.0``
``tmux tmux next-3.5``
``FiraCode Nerd Font Mono 12pt``
no tmux:

![image](https://github.com/tmux/tmux/assets/6942070/4dbb3872-a1f8-47a7-9104-a00c335d131f)

tmux
![image](https://github.com/tmux/tmux/assets/6942070/777ddb52-de7c-4c64-bae7-79faa9b77529)

better open a proper issue I guess

**Comment by systemmonkey42** [comment] 2024-03-07 00:15
As a quick test- run 'tmux -u' to force "utf-8" mode.

**Comment by L1Q** [comment] 2024-03-07 00:17
> As a quick test- run 'tmux -u' to force "utf-8" mode.

that helped, thank you!

**Comment by smprather** [comment] 2024-03-08 20:39
> I cannot reproduce with either Alacritty or xterm, though neither of these are my preferred shell.

Please please please forgive me for being pedantic, but I'm trying to preserve "the culture". Alacritty/xterm/gnome-terminal/konsole/rxvt/kitty/etc/etc are terminals, not shells. Bash/zsh/sh/csh/ksh/fish/etc/etc are shells that send their stdout/err to be rendered by a terminal (and receive stdin from them). I'm only making this comment due to some young co-workers of mine making the same mistake.

**Comment by Akhil-CM** [comment] 2024-03-16 19:52
> I figured that `#(echo $HOME)` doesn't even work here (just prints out `$HOME`), then realized I was using single quotes for the config (as can see above). Changing that to double quotes works!!!
> 
> However, it still doesn't seem to work with `$TMUX_PLUGIN_MANAGER_PATH`, so instead I have to use `$HOME/.tmux/plugins/...`.

I don't know whether it's similar issue and whether I have to report it as a new bug. I cannot get plugins to work when specifying `TMUX_PLUGIN_MANAGER_PATH` with single quotes. But it works with double quotes.
Having the following in `tmux.conf` doesn't work:
```sh
...
set-environment -g TMUX_PLUGIN_MANAGER_PATH '$HOME/.config/tmux/plugins'
...
``` 
But this works
```sh
...
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.config/tmux/plugins"
...
```

**Comment by GrzegorzKozub** [comment] 2024-03-23 09:54
Used to be able to copy text to clipboard by just selecting it with the left mouse button or just double clicking a word. Now it's rather random.

Copying by selecting with the mouse seems to work only when I select more lines, but it's not consistent. Copying by a double click seems to work at random as well.

Any clues, friends? Pretty sure this has changed since 3.4 for me.

I'm on linux using tmux with kitty.

**Comment by afh** [comment] 2024-04-01 06:39
Adding a `menu-border-lines` type of `none` is the purpose of PR #3666. At the time I didn't get it to the finish line as the menu would be misplaced/misaligned. There have been several [other PRs](https://github.com/tmux/tmux/pulls?q=is%3Apr+is%3Aclosed+border-style) related to border-style. Maybe these could provide some inspiration in case you'd like to add a `none` type to the `pane-border-lines` setting.

I image it being difficult to distinguish where one pane ends and begins without a dividing line. How to you plan to do that? Using `window-active-style`?

**Comment by elidhu** [comment] 2024-04-24 03:05
I am having an issue with `-l` it is splitting but ignoring the perrcentage, it is always even.

```
tmux split-window -h -l "10%"
```

MacOS tmux 3.4 from brew

**Comment by afh** [comment] 2024-04-24 14:48
@elidhu Could it be something in your local `.tmux.conf` that overrides the layout?
Using the command you sent I can split a window horizontally with varying widths.

**Comment by elidhu** [comment] 2024-04-25 04:31
Okay so this is what I have found, while using an **empty** `.tmux.conf`:

- If I attach to the session, then detach and then split - it get's it correct.
- If I create a session and immediately detach with say `tmux new -d` it splits, but gets the size wrong. 

I have no idea how this works, but it must think the terminal is a different size (or something) until I actually attach?

@afh

**Comment by afh** [comment] 2024-04-25 06:08
Thanks for digging deeper and refining your initial report, @elidhu. I'm still not able to reproduce and the commands given in the example could use an existing session or otherwise be affected by the environment.

Here's my take on the example commands to ensure no existing session is used and no empty `.tmux.conf` is needed:

```sh
export TMUX_TMPDIR=$(mktemp -d)
tmux -vv -f/dev/null new
tmux -vv -f/dev/null split-window -h -l 90% # run from shell created within the tmux session
tmux display-message -p '#{client_width}x#{client_height}: #{window_layout}'
80x24: 0e73,80x23,0,0{7x23,0,0,0,72x23,8,0,1}
```

```sh
export TMUX_TMPDIR=$(mktemp -d)
tmux -vv -f/dev/null new -d \
&& tmux -vv -f/dev/null split-window -h -l 90% \
&& tmux -f/dev/null attach
tmux display-message -p '#{client_width}x#{client_height}: #{window_layout}' # run from shell created within the tmux session
80x24: 0e73,80x23,0,0{7x23,0,0,0,72x23,8,0,1}
```

**Comment by elidhu** [comment] 2024-04-25 06:28
Thanks for getting back to me - with your commands I get the same behaviour I was seeing before:

First (worked): 184x32: 2938,184x31,0,0{18x31,0,0,0,165x31,19,0,1}
Second (didn't work): 184x32: f7d7,184x31,0,0{59x31,0,0,0,124x31,60,0,1}

<img width="1653" alt="Screenshot 2024-04-25 at 2 22 37 PM" src="https://github.com/tmux/tmux/assets/22187575/d3104900-a9e5-4cb6-9834-3f957f7b248f">
<img width="1653" alt="Screenshot 2024-04-25 at 2 23 23 PM" src="https://github.com/tmux/tmux/assets/22187575/600d7512-4526-441f-b9e2-7464f0ce9be2">

**Comment by nicm** [comment] 2024-04-25 06:43
Detached windows start at 80x24, you need to use -x and -y (or -x- -y-) to use a different size.

**Comment by elidhu** [comment] 2024-04-25 09:28
@nicm Yep, you're totally right - that was it!

Thank you as well @afh

**Comment by gabrielso** [comment] 2024-05-02 12:10
Since upgrading to 3.4, mouse (MacBook touchpad) events are ignored. I can scroll through the terminal history (meaning I see the terminal lines before I start tmux) but not within the tmux pane scrollback anymore.

Also can't set the active pane by clicking on it anymore.

My config have the following lines:

```
set -g mouse on
unbind -n MouseDrag1Pane
unbind -Tcopy-mode MouseDrag1Pane
```

Tried enabling mouse directly from the command prompt (`C-<prefix>:`) and sourcing the config file directly but nothing works.

Anyone with the same problem? Using Mac Terminal, Mac OS 14.4.1, trackpad.

**Comment by multi-io** [comment] 2024-05-02 21:21
Ummm the following .tmux.conf works as it should under 3.2a (macOs brew, Ubuntu 22.04), while in 3.4 (Ubuntu 24.04) I'm getting `.tmux.conf:2: command list-sessions: unknown flag -l`.

```
# cat ~/.tmux.conf
run {
  ls -l
}
#
```

So it looks like tmux 3.4 no longer understands the { } generalized quotes, so that instead of passing the "ls -l" as an argument to "run", it tries to interpret it as a tmux command (list-sessions in this case)??

**Comment by multi-io** [comment] 2024-05-02 21:31
https://github.com/tmux/tmux/issues/3836#issuecomment-2091678394

Just found this in the changelog:

> * Change so that {} is converted to tmux commands immediately when parsed. This
  means it must contain valid tmux commands. For commands which expand %% and
  %%%, this now only happens within string arguments. Use of nested aliases
  inside {} is now forbidden. Processing of commands given in quotes remains
  the same.

Umm what? Why?? It was a generalized "", used to encode arbitrary strings to be sent to and interpreted by arbitrary commands such as "run", which interprets it as a shell command obviously. It's still documented as such in the 3.4 manpage. 

And now all of a sudden it can only be used for tmux commands? What sense does that make??

**Comment by msly** [comment] 2024-05-29 07:05
Issue with Panel Splitting in tmux 3.4

Description
In tmux version 3.4, I encountered an issue where the first script evenly splits the window into 8 panels, but the second script does not. However, both scripts work correctly in tmux version 2.3, evenly splitting the window into 8 panels.

Script 1
This script splits the window evenly into 8 panels in both tmux 2.3 and 3.4:
```
tmux new -s ttt -d
tmux splitw -v -l 50% -t ttt:0.0
tmux splitw -h -l 75% -t ttt:0.0
tmux splitw -h -l 66% -t ttt:0.1
tmux splitw -h -l 50% -t ttt:0.2
tmux splitw -h -l 75% -t ttt:0.4
tmux splitw -h -l 66% -t ttt:0.5
tmux splitw -h -l 50% -t ttt:0.6
tmux attach -t ttt
```

Script 2
This script splits the window evenly into 8 panels in tmux 2.3, but not in tmux 3.4:
```
tmux new -s ttt -d
tmux splitw -h -l 50% -t ttt:0.0
tmux splitw -v -l 50% -t ttt:0.1
tmux splitw -v -l 50% -t ttt:0.0
tmux splitw -h -l 50% -t ttt:0.3
tmux splitw -h -l 50% -t ttt:0.2
tmux splitw -h -l 50% -t ttt:0.1
tmux splitw -h -l 50% -t ttt:0.0
tmux attach -t ttt
```
Steps to Reproduce
Run the scripts in tmux 3.4 and tmux 2.3 respectively.
Observe the panel distribution and verify if they are split evenly into 8 panels.

Expected Behavior
Both scripts should split the window evenly into 8 panels in tmux 3.4, just as they do in tmux 2.3.

Actual Behavior
In tmux 3.4, Script 1 splits the window evenly into 8 panels, but Script 2 does not.

Environment
tmux version: 3.4 (issue present)
tmux version: 2.3 (no issue)

Please investigate this inconsistency between tmux versions.

Thank you!

**Comment by morfikov** [comment] 2024-06-04 11:06
I noticed that when starting a new tmux window/pane, the following message is generated in the system logs:

```systemd[3083]: Started tmux-spawn-3fb77461-07bc-49d7-888b-574c631b7b07.scope - tmux child pane 266522 launched by process 3390.```

Is there a way to forbid creating `tmux-spawn-*.scope`? The reason is a problem with cgroupsv2. For instance, when I run the `ssh` or `ping` command in the shell inside of a tmux session, the internet packets sometimes are dropped, because (I think) of the wrong cgroup process assignment (I have a different cgroup for internet apps, and I'm filtering OUTPUT of all the internet accessing apps). When the drops  happen, I can fix the situation by reloading the tmux config (`bind r source-file /etc/tmux.conf`). After reloading the configuration, everything works well for some time, till it happens again.

**Comment by panzacoder** [comment] 2024-07-26 16:38
Was running into the `Size missing` issue today after restarting my computer (I didn't `at least intentionally` update anything) and was very confused.

No clear explanation, ran a brew upgrade and nothing changed.

Updated my `tmux.conf`  from:
```
# splitting panes
bind t split-window
bind T split-window -h -l 
bind E split-window -h -l 80
```

to 
```
# splitting panes
bind t split-window
bind T split-window -h -l 80 
```

Still not entirely sure why this stopped working suddenly, but it's working now!

> Disclaimer: I am not really a tmux/nvim tinkerer, someone else provided these dotfiles for me at a previous job (thanks @jondkinney), I only update them when something breaks 🙃

**Comment by ipstone** [comment] 2024-08-21 17:16
OSC52 escape sequence stopped working for me in tmux 3.4 version (I tried tmux both in miniconda packages system, and nix); but 3.2a version worked well for me in linux installed through miniconda (yes, it's ancient, but what I am using).

Is there something changed between 3.2a and 3.4 that affects the functionality of OSC52? I am mostly using it to copy file path to the host system (such as using mac, iterm2, connect to remote linux server, within the tmux session on the linux server that I would like to copy filepath to the host system - mac's clipboard, using command line tool such as: https://github.com/skaji/remote-pbcopy-iterm2 )

Ideas and suggestions? Thanks in advance!

**Comment by Archdsenna** [comment] 2024-09-01 08:45
How to cancel the top-right timeline display in tmux 3.4 copy mode

![image](https://github.com/user-attachments/assets/5f24d6ac-1138-48c4-9bde-05b249c85ceb)
As shown in the picture above, how to cancel the time display in the top-right?

**Comment by andrew-cybsafe** [comment] 2024-09-18 21:02
It seems we can no longer successfully run `tmux send-keys -t1 q C-u` when the target pane is in copy mode.

    $ tmux send-keys -t1 q C-u
    not in a mode

This is used by the [preservim/vimux](https://github.com/preservim/vimux) vim plugin. See their issue here: https://github.com/preservim/vimux/issues/230

**Comment by afh** [comment] 2024-09-22 09:08
If I understand the code in [`window-copy.c:4267ff`](https://github.com/tmux/tmux/blob/master/window-copy.c#L4267-L4275) correctly, @Archdsenna, it seems that it is hard-coded and not possible to "cancel the time display in the top-right".

**Closed** 2024-09-27 07:59 UTC
