### ISSUE TITLE
On a bare tty, the mouse no longer works in weechat running inside tmux

### ISSUE THREAD

**Issue by JustAnotherHumanBeing** [tmux/tmux#3020] opened 2021-12-28 03:19 UTC
I run FreeBSD and before tmux-3.2 came out, I was able to do this on a bare tty: "tmux new weechat". Then I do ctrl+b+c and type "elinks". After loading elinks, I do ctrl+b+n and the mouse starts working in weechat. It means I am able to click on different channel windows in weechat. Then I do ctrl+b+c (it has to be done from the weechat tmux window), type "tmux set-option -g mouse on", and gain the ability to click on tmux window panes. After I do this whole procedure, the mouse works just fine on a bare tty in tmux. There is no need to load either x11 or wayland. But after tmux-3.2 came out, this procedure no longer works for me. Can you please fix this, so the mouse could start working again on a bare tty?

**Comment by nicm** [comment] 2021-12-28 08:15
Logs?

**Comment by JustAnotherHumanBeing** [comment] 2021-12-28 21:35
Tmux logging doesn't show any info about how the mouse works. It simply shows text about what's going on in a particular tmux window. So, ctrl+b+shift+alt+p didn't log any useful info.
Why can't I compile tmux with any of the patches that were added to it between the time it was tagged as 3.1c and the time it was tagged as 3.2? There is no autogen.sh available for that time window. If I were able to compile tmux using any of the patches that were added to it during that time window, I would be able to find out which patch broke the functionality that I described in the first post.

**Comment by nicm** [comment] 2021-12-28 22:40
Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md, particularly the last section.

**Comment by JustAnotherHumanBeing** [comment] 2021-12-29 00:53
Okay, these are the log files for tmux-3.1c:
[tmux-client-81856.log](https://github.com/tmux/tmux/files/7786868/tmux-client-81856.log)
[tmux-out-81858.log](https://github.com/tmux/tmux/files/7786870/tmux-out-81858.log)
[tmux-server-81858.log](https://github.com/tmux/tmux/files/7786871/tmux-server-81858.log)

These are the log files for tmux-3.2a:
[tmux-client-84557.log](https://github.com/tmux/tmux/files/7786873/tmux-client-84557.log)
[tmux-out-84559.log](https://github.com/tmux/tmux/files/7786874/tmux-out-84559.log)
[tmux-server-84559.log](https://github.com/tmux/tmux/files/7786875/tmux-server-84559.log)

**Comment by nicm** [comment] 2021-12-29 11:37
I don't see any evidence of you clicking the mouse on pane 0 (weechat), so it is difficult to tell why it may not be receiving it. I only see you clicking twice on pane 1 (elinks).

Can you please do exactly this:
~~~~~
tmux kill-server
tmux -vv -f/dev/null set -g mouse on \; new weechat
~~~~
Then click a couple of times in the weechat pane, then `C-b : kill-server` and send me the server log.

**Comment by JustAnotherHumanBeing** [comment] 2021-12-29 13:24
But the procedure that I described in the first post will never work even in tmux-3.1c if I have mouse set to on before starting weechat in tmux. As I said earlier, on a bare tty (no x11 or Wayland loaded) and with tmux-3.1c I could do this: "tmux new weechat". At this point, I won't be able to use my mouse to click on channel windows in weechat. So, I do "Ctrl+b+c" to open pane 1 and type there "elinks". The mouse immediately starts working in elinks (unless I have "set -g mouse on" in my tmux.conf). This will happen in both tmux-3.1c and tmux-3.2a. However, this will only happen in tmux-3.1c: after starting elinks and typing Ctrl+b+n, the mouse will start working in weechat. I'll be able to click on different channel windows in weechat, different nicknames in irc channels, or etc. Then (and for this to work it has to be done inside the weechat pane), I could do "Ctrl+b" and then :"set -g mouse on" and I'll be able to click on "1: elinks" and then back on "0:weechat".

**Comment by nicm** [comment] 2021-12-29 13:37
I'm only really interested in why the mouse isn't working in weechat if it requests it, not why this complicated procedure you have come up with doesn't work anymore. elinks is not a tool meant to turn the mouse on in other programs and if it no longer does that is probably a bug fixed.

**Comment by JustAnotherHumanBeing** [comment] 2021-12-29 14:08
You mean, it's probably a bug fixed in tmux, not in elinks?.. Okay, here's the server log for tmux-3.2a. I typed the command that you told me to type and attempted to click (without success) on channel windows in weechat.
[tmux-server-31461.log](https://github.com/tmux/tmux/files/7789187/tmux-server-31461.log)

**Comment by nicm** [comment] 2021-12-29 14:41
Do you have `moused` running?

**Comment by JustAnotherHumanBeing** [comment] 2021-12-29 14:47
No. I have a USB mouse and as far as I know, the moused service is useless for a USB mouse.

**Comment by nicm** [comment] 2021-12-29 14:51
Does it make any difference if you start it before doing `tmux new weechat`?

tmux is asking the terminal for the mouse but it is not sending it, but it must support it because elinks is turning it on somehow. I don't see anything in the elinks code for mapping the escape sequences so it must be just one of the flags it is setting.

So I wonder if moused will turn it on instead.

**Comment by nicm** [comment] 2021-12-29 15:01
Can you try saving this file then doing: [x.c.txt](https://github.com/tmux/tmux/files/7789492/x.c.txt)
~~~~
mv x.c.txt x.c
make x
~~~~
If `make` gives any errors, let me know what they are.

If it doesn't give any errors, then before running tmux:
~~~~
./x
tmux new weechat
~~~~
And see if the mouse works.

**Comment by JustAnotherHumanBeing** [comment] 2021-12-29 15:13
I had this error: 
x.c:15:11: error: use of undeclared identifier 'STDOUT_FILENO'
    ioctl(STDOUT_FILENO, CONS_MOUSECTL, &mi);

Speaking of moused, I will never be able to start it because I only have a USB mouse.

**Comment by nicm** [comment] 2021-12-29 15:18
Change `STDOUT_FILENO` to 1 please and try again.

According to ums(4), `moused` should work for at least some USB mice.

**Comment by JustAnotherHumanBeing** [comment] 2021-12-29 15:39
Now I received no compilation errors, but after running "/.x" and "tmux new weechat", the mouse doesn't work in weechat (and it doesn't matter if I have set-option -g mouse on or off in my .tmux.conf).
If moused works with USB mice, then I don't know how to start it. It looks for /dev/psm0 device which I don't have.

**Comment by nicm** [comment] 2021-12-29 15:47
OK, let me look again.

Try `moused -t /dev/ums0`?

**Comment by nicm** [comment] 2021-12-29 15:47
`moused -p /dev/ums0` not `-t`.

**Comment by nicm** [comment] 2021-12-29 15:51
What version of elinks do you have?

**Comment by JustAnotherHumanBeing** [comment] 2021-12-29 16:04
Moused complains that the /dev/ums0 device is busy. I have elinks-0.11.7_13. The mouse will always work for the tmux/elinks combination on a bare tty unless set-option for the mouse is set to on in .tmux.conf. If x11/wayland is loaded, then it doesn't matter if set-option for the mouse is on or off because the mouse will work in elinks (or weechat) in either case.

**Comment by nicm** [comment] 2021-12-29 16:30
elinks must be doing something to turn the mouse on in the way tmux expects but I can't see what it is doing, I will probably need to try it on FreeBSD.

**Comment by JustAnotherHumanBeing** [comment] 2021-12-29 16:35
The FreeBSD port for elinks offers the "Mouse" compilation option that can be turned either on or off. The port for weechat offers no such option. "/mouse enable" is the standard way to turn a mouse on inside weechat. I did run "/mouse enable" before I opened this github issue.

**Comment by nicm** [comment] 2021-12-29 16:37
Aye but weechat and tmux will use the standard escape sequences to turn the mouse on which the console ignores, but it must be able to generate the right escape sequences because it works sometimes. So it is just a matter of figuring out what elinks is doing to get it started.

**Comment by nicm** [comment] 2021-12-29 17:49
Can you do this outside tmux (where the mouse in elinks works):
~~~~
ktrace elinks
~~~~
Then exit elinks and do `kdump >kdump.out` and show me the kdump.out file.

**Comment by nicm** [comment] 2021-12-29 18:17
Hah the problem is that FreeBSD does not support anything except the most basic mouse mode, but tmux ends up always asking for the more complex ones.

elinks is triggering tmux to send the basic escape sequence, that's why it makes it work, the sysmouse stuff it does is a red herring.

Please try this against master: [x.diff.txt](https://github.com/tmux/tmux/files/7790106/x.diff.txt)

This works for me on FreeBSD if I do:
~~~~
moused -p /dev/psm0
vidcontrol -m on
tmux set -g mouse on \; new
~~~~
I suspect you already have `moused` running though so probably the last step alone is all you need to try.

**Comment by JustAnotherHumanBeing** [comment] 2021-12-29 18:35
I have to try it against the latest tmux master, not against earlier versions of tmux?

**Comment by nicm** [comment] 2021-12-29 19:16
You can see if it applies to older tmux but I have a feeling it won't.

**Comment by JustAnotherHumanBeing** [comment] 2021-12-29 20:46
I applied this patch to version 3.2a and it works! Now the mouse works for the tmux/weechat combination on a bare console. Thank you for fixing this issue. So, will you apply this patch to both head and earlier versions?

**Comment by nicm** [comment] 2021-12-29 20:50
No, earlier releases are done, it will be in 3.3.

**Comment by JustAnotherHumanBeing** [comment] 2021-12-29 21:05
I don't know why no one reported this issue earlier, given the fact that making the mouse work in tmux on a bare console is quite a useful thing.

**Comment by nicm** [comment] 2021-12-29 21:10
I expect hardly anyone uses consoles for more than occasional
setup/troubleshooting.

**Comment by JustAnotherHumanBeing** [comment] 2021-12-29 21:11
Yeah...

**Comment by nicm** [comment] 2021-12-31 11:36
This is applied to OpenBSD now, will be in GitHub later. Thanks!

**Closed by nicm** 2021-12-31 11:36 UTC
