### ISSUE TITLE
3.3 questions and comments

### ISSUE THREAD

**Issue by nicm** [tmux/tmux#3203] opened 2022-06-01 07:32 UTC
### Ask or discuss any quick questions about 3.3 here please.

Bug reports please open a new issue with full information, see [CONTRIBUTING](https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md).

**[The 3.3 CHANGES file is here](https://raw.githubusercontent.com/tmux/tmux/3.3/CHANGES).**

As always, thanks to the many people who contributed to both this and to previous releases.

---

Here are some of the notable changes for the 3.3 release, for more see the CHANGES file:

- When building on macOS, `--enable-utf8proc` or `--disable-utf8proc` must be explicitly given to `configure` (the former is recommended).

- The default value for `default-terminal` is now chosen by `configure` from those available on the build system (force with `--with-TERM=tmux-256color`).

- There is now an ACL list to control users permitted to attach to a tmux socket (file system permissions must still be set manually); see the `server-access` command.

- The passthrough escape sequence is now controlled by an option (`allow-passthrough`), default is off (recommended).

- Various other new options: `remain-on-exit-format`, `fill-character`, `scroll-on-clear`, `pane-border-indicators`, `cursor-style`, `cursor-colour`, `popup-border-lines`, `popup-border-style`, `popup-style`, `pane-colours`.

- On Linux, tmux now supports getting the socket from systemd (socket activation), if built with `--enable-systemd`.

- There is now a menu when button 3 is pressed outside a popup border with a few items including the ability to convert a popup into a pane.

**Comment by krader1961** [comment] 2022-06-02 01:21
I can reproduce this by using `set-buffer` to create two named buffers ("a" and "b") then running `delete-buffer -b x` silently deleted buffer "b". Oops! I concur this a bug and agree with your analysis of the code. Note the documentation says "or the most recently added automatically named buffer if not specified." It seems to me there is another bug with this code assuming the documentation describes the desired behavior. If there are no automatically named buffers and I create two named buffers then do `delete-buffer` it deletes the most recently named buffer. Which the documentation says shouldn't happen.

**Comment by systemmonkey42** [comment] 2022-06-02 01:53
> It seems to me there is another bug with this code assuming the documentation describes the desired behavior.

I would have to agree there.  The paste buffer data structures clearly have a "automatic" flag (0 or 1) which is not checked when selecting a buffer to delete.

**Comment by kujohn** [comment] 2022-06-02 18:03
With this new release, I am seeing crashes like [this](https://github.com/laishulu/emacs-tmux-pane/issues/3) and strange behaviors like:

```
> clear
terminals database is inaccessible
```
```
> git diff
WARNING: terminal is not fully functional
```

I had `3.2a` running previously working fine.

**Comment by krader1961** [comment] 2022-06-02 18:25
@kujohn, What does `echo $TERM` output? Do you have a `TERMINFO` env var? Did you recently modify your *~/.tmux.conf* file? I just built tmux from the latest commit and don't see any of the problems you're reporting. It seems likely you've changed your tmux or shell config and that's the source of your problems.

**Comment by kujohn** [comment] 2022-06-02 19:31
@krader1961 thanks for the advice. I can confirm something changed with the `TERM` that caused this issue.

**Comment by pakabah** [comment] 2022-06-02 21:07
Is there a way to resolve this or we'd have to wait for a fix? Currently having 
`terminal database is inaccessible`

**Comment by nicm** [comment] 2022-06-02 21:12
> Bug reports please open a new issue with full information, see [CONTRIBUTING](https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md).

**Comment by nicm** [comment] 2022-06-02 21:16
tmux will now autodetect `TERM` with `configure` so I expect they built tmux against a different ncurses from the one used by `clear`/`git` etc.

**Comment by nicm** [comment] 2022-06-02 21:59
See this comment and the subsequent one: https://github.com/Homebrew/homebrew-core/issues/102748#issuecomment-1145378599

**Comment by slimbiosys** [comment] 2022-06-03 02:04
I've noticed an issue in tmux 3.3 with `display-menu -O` not allowing the mouse to select menu items or highlighting selections when the mouse hovers over them.  Keyboard navigation works as expected in the menu, but it does not register any mouse activity other than closing the popup on a mouse click. 

`display-menu` works correctly and as expected with both mouse and keyboard without the -O flag.

**Comment by nicm** [comment] 2022-06-03 03:58
Are you running `display-menu -O` from a mouse key binding? The mouse will only work in menus opened from mouse key bindings.

**Comment by slimbiosys** [comment] 2022-06-03 04:36
Yes, they are mouse key bindings.  To test that it wasn't my configuration I have started a new session with:
tmux -Ltest -f/dev/null

Then I have changed the default binding for any of the default display-menu bindings adding the -O flag, ie. MouseDown3StatusLeft

the binding for MouseDown3StatusLeft after modification is:
display-menu -O -T "#[align=centre]#{session_name}" -t = -x M -y W Next n { switch-client -n } Previous p { switch-client -p } '' Renumber N { move-window -r } Rename n { command-prompt -I "#S" { rename-session "%%" } } '' "New Session" s { new-session } "New Window" w { new-window }

**Comment by nicm** [comment] 2022-06-03 08:07
This is an error in how tmux sends the mouse sequences, this should fix it:
~~~~
--- a/tty.c
+++ b/tty.c
@@ -814,7 +814,7 @@ tty_update_mode(struct tty *tty, int mode, struct screen *s)
                        tty_puts(tty, "\033[?1006h");
                if (mode & MODE_MOUSE_ALL)
                        tty_puts(tty, "\033[?1000h\033[?1002h\033[?1003h");
-               if (mode & MODE_MOUSE_BUTTON)
+               else if (mode & MODE_MOUSE_BUTTON)
                        tty_puts(tty, "\033[?1000h\033[?1002h");
                else if (mode & MODE_MOUSE_STANDARD)
                        tty_puts(tty, "\033[?1000h");

**Comment by slimbiosys** [comment] 2022-06-03 08:31
That fixes it, thank you!

Appreciate your quick response and rectification of the issue, nicm.  Kudos !

**Comment by narinor** [comment] 2022-06-05 10:09
Just upgraded and found that when starting the tmux server, `run-shell` in my `tmux.conf` now crashes the server with `server exited unexpectedly` if the command does not exist. I can't find this change in the changelog, is it intended?

In my case, I tried loading `tmux-plugin-manager` when it wasn't installed (`run-shell '/usr/share/tmux-plugin-manager/tpm'`). I solved it by using `run '/usr/share/tmux-plugin-manager/tpm || true'` instead to always return a 0 exit code.

**Comment by imomaliev** [comment] 2022-06-05 16:06
After update `window-linked` hook does not see environment variables set by `set-environment`

**Comment by cujomalainey** [comment] 2022-06-06 06:28
> Just upgraded and found that when starting the tmux server, `run-shell` in my `tmux.conf` now crashes the server with `server exited unexpectedly` if the command does not exist. I can't find this change in the changelog, is it intended?
> 
> In my case, I tried loading `tmux-plugin-manager` when it wasn't installed (`run-shell '/usr/share/tmux-plugin-manager/tpm'`). I solved it by using `run '/usr/share/tmux-plugin-manager/tpm || true'` instead to always return a 0 exit code.

Not sure if its the same crash, but something I have noticed is that when using gpakosz/.tmux and tpm together the server crashes and my plugins directory gets wiped out.

**Comment by elanorigby** [comment] 2022-06-06 17:13
I also too as well was getting "server exited unexpectedly" when attempting to run tmux after to updating to 3.3. The issue seems to be that `~/.tmux/plugins` no longer existed, so re-installing the plugins with `prefix + I` solved it. 

Sadly, I can't say for sure if the plugins directory (actually the whole `~/.tmux/` dir) got blown away as part of my initial attempt to upgrade tmux or if there was something else causing the "server exited unexpectedly" error and the directory only disappeared when I uninstalled tmux altogether in trying to solve it. I am not using [gpakosz/.tmux](https://github.com/gpakosz/.tmux), just bash and vim, and I manage tmux with homebrew.

In any case, if you've come here because you're seeing "server exited unexpectedly" check on your plugins they might be RIP.

**Comment by RobertMenke** [comment] 2022-06-06 20:44
I was able to fix the 

> With this new release, I am seeing crashes like [this](https://github.com/laishulu/emacs-tmux-pane/issues/3) and strange behaviors like:
> 
> ```
> > clear
> terminals database is inaccessible
> ```
> 
> ```
> > git diff
> WARNING: terminal is not fully functional
> ```
> 
> I had `3.2a` running previously working fine.

I was able to fix this issue by explicitly exporting `TERM`. 

```bash
export TERM=xterm-256color
```

**Comment by narinor** [comment] 2022-06-06 23:05
> Just upgraded and found that when starting the tmux server, `run-shell` in my `tmux.conf` now crashes the server with `server exited unexpectedly` if the command does not exist. I can't find this change in the changelog, is it intended?
> 
> In my case, I tried loading `tmux-plugin-manager` when it wasn't installed (`run-shell '/usr/share/tmux-plugin-manager/tpm'`). I solved it by using `run-shell '/usr/share/tmux-plugin-manager/tpm || true'` instead to always return a 0 exit code.

While attempting to bisect the issue, I found that it was already fixed by commit 18838fb (which was made after the 3.3 release).

**Comment by nicm** [comment] 2022-06-07 07:38
I will make a patch release with this change in a while.

**Comment by sgleizes** [comment] 2022-06-07 14:40
Hello, on my end the migration to 3.3 introduced a change of behavior when using `run-shell` in `#()` embedded shell commands.

I am basically defining tmux command aliases using `run-shell` to output the different parts of my status-bar, then using these aliases in embedded shell commands. Something like:
```
tmux set "command-alias[100]" status-hostname="run '/path/to/status.zsh hostname'"
tmux set -g @themepack-status-right-area-left-format '#(tmux status-hostname)'
```

The idea was to provide an additional level of abstraction by using the command aliases. This used to work fine in previous versions, but with 3.3 the shell command output is sent to the current pane instead of the status bar.

Of course the workaround is to execute the shell function directly from the format string, as in:
```
set -g @themepack-status-right-area-left-format '#(/path/to/status.zsh hostname)'
```

For reference here are the relevant part of this config (before fixing this) :
- [Command import](https://github.com/sgleizes/dotfiles/blob/653c9947c1fea27ad5d5bbbf251d315111f86553/.config/tmux/main.tmux#L90)
- [Alias definitions](https://github.com/sgleizes/dotfiles/blob/653c9947c1fea27ad5d5bbbf251d315111f86553/.config/tmux/command/status.zsh#L8)
- [Theme format commands](https://github.com/sgleizes/dotfiles/blob/653c9947c1fea27ad5d5bbbf251d315111f86553/.config/tmux/theme.tmux#L42)

This use case is quite a stretch and has a performance cost, but it kind of made sense for me that the output of a run-shell command in the context of `#()` would be captured instead of displayed in the current pane.

However the documentation of `run-shell` is pretty clear about how it deals with output, so this new behavior is consistent with the doc and I understand if you prefer to keep it this way. Otherwise I can create a separate issue if you think the previous behavior should be restored.

**Comment by nicm** [comment] 2022-06-07 18:51
This is a feature of `clear`, try `clear -x`.

**Comment by milosivanovic** [comment] 2022-06-08 17:18
> > With this new release, I am seeing crashes like [this](https://github.com/laishulu/emacs-tmux-pane/issues/3) and strange behaviors like:
> > ```
> > > clear
> > terminals database is inaccessible
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > > git diff
> > WARNING: terminal is not fully functional
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I had `3.2a` running previously working fine.
> 
> I was able to fix this issue by explicitly exporting `TERM`.
> 
> ```shell
> export TERM=xterm-256color
> ```

@nicm do you know why this is necessary as of 3.3? I needed to add `export TERM=xterm-256color` to my `~/.bash_profile`to fix the following issues, among others:

```
milos@pro:~$ clear
terminals database is inaccessible
milos@pro:~$ reset
reset: can't initialize terminal type tmux-256color (error -1)
Terminal type? ^D
```

**Closed** 2022-06-09 11:38 UTC
