### ISSUE TITLE
tmux session killed when ssh being disconnected

### ISSUE THREAD

**Issue by rvu95** [tmux/tmux#271] opened 2016-01-17 08:27 UTC
I have tmux installed on an Debian jessie system. When I start a tmux session I can detach from it and then attach again while the ssh session is active. But if I end my ssh session then the tmux session gets killed. Is this always happen in the system with systemd? As i know i'm using it in different system and it was ok, thanks.

**Comment by jungle-boogie** [comment] 2016-01-17 08:34
I can't reproduce this. What tmux version do you have?

**Comment by rvu95** [comment] 2016-01-17 10:33
tmux 1.9, i'm running it on debian jessie

**Comment by nicm** [comment] 2016-01-19 12:30
Sounds like something on your system is broken. How is tmux being killed? Run "tmux -vvvv" new then reproduce and show me the tmux-server-*.log file.

**Comment by sekrause** [comment] 2016-01-27 07:25
Are you using systemd's socket activation? It's definitely not a tmux problem, but a problem with your systemd configuration. See http://unix.stackexchange.com/a/176292/8755 for more information,

**Comment by sekrause** [comment] 2016-01-27 07:35
On Debian the problem can be easily fixed by installing the package `libpam-systemd`: http://thread.gmane.org/gmane.comp.sysutils.systemd.devel/2379/focus=2391

**Comment by rvu95** [comment] 2016-01-27 12:17
Okay, thanks for the solution

**Closed** 2016-01-29 10:51 UTC
