### ISSUE TITLE
RFC/discussion around feature request around lazy pane width history reflow

### ISSUE THREAD

**Issue by unphased** [tmux/tmux#1269] opened 2018-02-22 17:39 UTC
Here is the situation: When resizing a tmux pane, the history of the pane is reflowed with width changes. This consumes a lot of CPU when the panes affected have a lot of history (with long lines). 

This can be further compounded by the fact that a resizing action can affect any number of panes, e.g. a layout like this which is rather common in the layouts I end up building:

    ┌────┐
    ├─┬──┤
    │ ├──┤
    │ ├──┤
    └─┴──┘

When you adjust the vertical division on the bottom there, you are horizontally resizing 4 panes, and if they all have a bunch of history, then up to [max buffer lines] * [no. of panes] lines would be reflowed when resizing that. I suppose if most of the lines are not very long, it wont be much overhead, but I've recently discovered that this can make resizing extremely slow for certain types of log output.

Now I like to have lots of history buffer, you know, _just in case_ a long running command I run turns out to be an important one, so I'd been thinking about increasing my history buffer line limit from 100k to an even higher value, but it seems like it might be a bad idea given this situation.

So what I would like to consider is the possibility of having lazy reflow: Only reflow history lines into current width when we scroll up to them, instead of immediately upon resize. 

Failing that, perhaps the reflow could at least be deferred until the initial scroll up in copy mode, or failing that, upon entering copy mode. The main point is that as things are now, resizing a particular column divider potentially causes a lot of immediate computation, and it should be deferrable, and limiting buffer size as a tradeoff is unappealing.

**Comment by nicm** [comment] 2018-02-22 18:13
Yes, I have mentioned this before, it could reflow the active pane or the (current window) and then do others either on demand or in the background.

**Comment by unphased** [comment] 2018-02-22 18:19
The active pane probably only needs visible content reflowed, instead of all of its history reflowed. Even one pane (if it has the right kind of history) could be slow to reflow. 

And to tack on to my estimate from above, theres really no limit to how much computation is involved in reflow because you can have arbitrarily long lines that all have to wrap.

**Comment by nicm** [comment] 2018-02-22 18:29
True, but then you are doing two things that are largely separate: partial reflow (of only the visible content), and lazy reflow (reflowing nonvisible panes on demand rather than immediately). The second is probably easier than the first, and the maximum number of panes per window is smaller than the maximum number of panes per session.

I would suggest first implementing lazy reflow and then seeing how much of an improvement it makes for most cases.

**Comment by unphased** [comment] 2018-02-22 21:48
Your intuition here is invaluable as it will inform what kind of approach might be the most practical. 

What you said is interesting. What I observe (I'm running master which i compiled about a week ago) is this: Only when *horizontally* resizing panes that affect panes that have large histories of long lines cause CPU-spiking sluggish resizes. Neither vertical resizing anywhere nor horizontal resizes of other (non heavily laden) panes lead to sluggish resizes. So I'm not sure what exactly you describe (w.r.t. doing something different on nonvisible panes) because in order to move a vertical border means that pane is already visible... Of course, I could be misunderstanding what you mean by "visible".

But I think it also does make sense to consider even allowing a pane to remain un-reflowed even in its visible section, and to allow that reflow to either occur in the background or deferred until the pane is focused, if it is a challenging thing to go for partial reflow, as you describe. Mainly I think the deferment is quite desired because it saves a lot of CPU (and hence battery power when running locally) because when you resize you do it in multiple steps and during this whole time, eager reflowing pegs CPU. If deferred, we can allow the reflow to happen just once, after the user has (hopefully) finished adjusting sizes.

**Comment by nicm** [comment] 2018-02-22 21:54
You can resize a terminal window in both directions and every pane in the attached session will be resized. Horizontal resize will always be slower than vertical.

**Comment by nicm** [comment] 2018-02-22 21:59
I think it won't be OK not to reflow visible lines. All visible parts of visible panes must be reflowed immediately. Invisible panes can be left until they become visible (or are otherwise needed), and the hidden parts of any pane's history can be left until it is needed (so copy mode, capture-pane, or a subsequent resize that would make it visible).

**Comment by nicm** [comment] 2018-02-22 22:08
No. If you move a pane border inside tmux, only the affected panes are resized. If you change the size of the terminal containing tmux, or attach tmux to a new terminal, then everything is resized.

**Comment by nicm** [comment] 2018-02-22 22:09
Reflowing only visible history would help with the first and second. Reflowing only visible panes only with the second.

**Comment by nicm** [comment] 2018-02-22 22:10
No new options please. This needs to be an optimization that works for everyone and doesn't change any behaviour the user can see.

**Comment by unphased** [comment] 2018-02-22 22:14
Great, excellent notes, and you're reminding me of more context around tmux's capabilities that I wasn't considering such as host terminal size. I think we're on the same page now! Yep, a new option seems super hacky for something like this.

I now also notice that if I have one heavily laden pane, resizing it smaller often takes quite a bit longer than expanding it. This makes sense too. As far as resizing the host terminal I personally do this less often than resizing, which is why I didn't even think about it.

**Comment by nicm** [comment] 2018-02-22 22:17
It sounds like you care more about resizing panes inside tmux than resizing the terminal, so if I was you I would look at resizing only the visible parts of panes.

I don't know how difficult it actually will be to do. You will need to make sure that you reflow enough - it isn't enough to reflow just the new height because if the width grew lines may be joined. Also of course there will be several places it will need to do a full reflow.

**Comment by ThomasAdam** [comment] 2018-02-22 22:18
On Thu, Feb 22, 2018 at 10:14:05PM +0000, Steven Lu wrote:
> I now also notice that if I have one heavily laden pane, resizing it smaller
> often takes quite a bit longer than expanding it. This makes sense too. As
> far as resizing the host terminal I personally do this less often than
> resizing, which is why I didn't even think about it.

Look at `recalculate_sizes()` for inspiration.

**Comment by nicm** [comment] 2018-02-22 22:20
I don't think it will be that hard to tell grid_reflow to only stop or start at a certain point. The problem is that it works top to bottom and the visible part is at the bottom. Also I don't know how you will work out how many lines you need to actually reflow cheaply.

**Comment by unphased** [comment] 2018-02-22 22:25
What happens when history is cleared or empty and a pane becomes wider is that the lines taken up shrinks. Maybe this can serve to avoid needing to reflow backwards, though it would change behavior (only cosmetically, imo). How acceptable might that be? 

I'll need to familiarize myself with the codebase... Thanks

**Comment by nicm** [comment] 2018-02-23 08:33
If content that should be visible after resize is not visible, it will look like a bug. We do not have to reflow backwards, it is just how it is implemented now. I suggest you go and look at grid_reflow.

One possible option instead of trying to reflow only part of the existing grid is to create a new partially reflowed grid that is just the visible size of the pane and set it as the pane's grid, storing the existing, full non-reflowed grid for later. Then when needed the previous grid could be reflowed and swapped back. This would mean writing an additional function that could generate a smaller visible-only reflowed grid instead of modifying grid_resize to make it able to do only the visible portion. But I don't know which is the easier option.

**Comment by unphased** [comment] 2018-02-23 19:44
Makes sense!

This discussion leads me to think about a tangentially related topic: history management. I'll make a new issue to discuss that.

**Comment by nicm** [comment] 2018-07-04 07:36
Can you show me a diff please or open a PR so I can get a diff from it?

**Comment by nicm** [comment] 2018-07-04 07:37
Never mind apparently I can get it from https://github.com/tmux/tmux/compare/master...da-x:lazy-reflow.diff

**Comment by da-x** [comment] 2018-07-04 08:16
@nicm Thanks for looking into it! BTW, the division to commits in the branch may make the changes clearer.

**Comment by nicm** [comment] 2018-07-04 09:39
OK this looks reasonable so far.

I like the accessor for linedata so I might apply that which would make it simpler.

You are using access to the linedata as a trigger for the reflow which is not what I'd thought of (I thought we would do it when then pane became active or something) but this way makes sense and is probably better.

I do wonder if it is overkill to split the grid into N blocks. On the one hand it does mean that the reflow will be bounded to 1000-odd lines at a time, but on the other maybe it would be simpler just to split it into two: history and non-history? Then there would be no need for a list of blocks, just a flag to say "does the history need to be reflowed?" It would need to make sure not to reflow the history unnecessarily of course, eg when resizing only part of it is going to become non-history. This would probably be simpler to implement but not as fast for some cases.

I would like to get the cursor positioning fixed too but I'm not sure when I will have time to do that, I'm not getting very far. So if you fancy having a look a that instead then go for it ;-).

**Comment by nicm** [comment] 2018-07-04 09:44
OK I applied the accessors but called them grid_get_line and grid_adjust_lines.

**Comment by da-x** [comment] 2018-07-04 10:00
I took the N blocks approach, figuring the 2-blocks approach (non-history and history) would need a similar amount of changes anyway. Also I had in mind that the N blocks approach is more conducive to packing of large unaccessed histories into smaller space in order to save memory (if we want to, in future changes), and also to avoid the large realloc of the lines array (2MB for a 250,000 lines history). But I see why the exact approach taken here is not really important to get this fix going.

BTW regarding accessors - the access as trigger for full reflowing is potentially a bit buggy in places where the accessor computes 'gd->sy + gd->hsize' before trying to access. Maybe add an accessor for that too? Need to look at all the accessors to see whether fixes are needed.

I also noticed while developing this feature, an existing bug - resizing panes while in copy mode does not keep the copy mode cursor in sync due to reflow, so we really have three markers that need syncing, and not just two. We may be able to get this fixed on the way :)

**Comment by nicm** [comment] 2018-07-04 10:02
OK it does allow more flexibility.

**Comment by da-x** [comment] 2018-07-05 08:01
Fixed some stability issues: https://github.com/da-x/tmux/compare/lazy-reflow-0...lazy-reflow.diff

Cursor still needs fixing though.

**Comment by da-x** [comment] 2018-07-10 21:02
Sure, rebased my `lazy-reflow` branch now.

**Comment by nicm** [comment] 2018-07-10 22:13
I think the general idea here is mostly fine, most of my comments would be style.

I think looping through the blocks in grid_get_block is a problem. It is called from grid_set_cell and grid_set_cells via grid_get_line and those functions are used a lot, so I don't think we can be looping over the blocks every time.

It's a pity each block couldn't be a fixed size and then you could go directly to blocks[line / 1000].

Perhaps the cache could be stored as part of the grid as well, so when you lookup line 10 you store the block at blocks[0], 2551 you store the gb at blocks[2] and so on. You would need each block to know its own start line number though to adjust py which might be a pain to keep up-to-date though.

**Comment by nicm** [comment] 2018-07-11 07:05
Here are some trivial changes to branch, as it is now. I have applied one (add grid_trim_history) already so probably want to patch before git pull: [r1.diff.txt](https://github.com/tmux/tmux/files/2183284/r1.diff.txt)

- Move grid_block into grid.c
- Use the existing flags member instead of gd->reflowing
- grid_trim_head -> grid_trim_history
- grid_append_empty_block -> grid_block_append
- Use xcalloc where appropriate
- Add or edit some function header comments
- Use int for boolean members not u_int

**Comment by nicm** [comment] 2018-07-11 07:19
There is a typo:
~~~~
@@ -397,7 +397,7 @@ grid_free_lines(struct grid *gd, u_int py, u_int ny)
        }
 }

-/* Resize the grid. Thus does not update gd->hsize and gd->sy. */
+/* Resize the grid. This does not update gd->hsize and gd->sy. */
 void
 grid_adjust_lines(struct grid *gd, u_int lines)
 {

**Comment by da-x** [comment] 2018-07-16 06:38
Updated the branch with your changes.

BTW, I noticed a crash in window-copy.c, due to the assumption that the backing grid history size does not change behind the scense. `screen_hsize(data->backing) + data->cy - data->oy` produces negative numbers that are provided to `grid_get_line`. Reproducible by creating a large history, resizing the pane, entering copy mode, going to the beginning of the history, and trying to resize again. Didn't have time to investigate further, though.

I did notice that it's somewhat slower to fill the history with all these changes together, consistent with your thoughts regarding `grid_get_block`. Perhaps caching the list lookup to an array would fix it. Or, instead of using a list, maintain an array of pointers to grid blocks indexed by their offsets for quick lookup.

**Comment by nicm** [comment] 2018-07-30 10:17
So where is this now? There are still bugs?

**Comment by da-x** [comment] 2018-07-30 10:47
Yes, it requires more work, but I have more urgent things right now.

As for the code, I'm inclining more toward not automatically re-flowing in `grid_get_line`, but instead calling to perform full reflow explicitly at various places. Perhaps it would be easier to tackle remaining instabilities that way.

**Comment by nicm** [comment] 2018-07-30 11:05
OK cool, I will leave it for the moment until you get back to it.

**Comment by nicm** [comment] 2018-08-31 08:58
Please comment when you are working on this again and I'll reopen it.

**Closed by nicm** 2018-08-31 08:58 UTC

**Comment by unphased** [comment] 2018-09-24 03:53
Thanks so much for contributing!! @da-x
