### ISSUE TITLE
tmux hangs when killing a session after swapping windows

### ISSUE THREAD

**Issue by serban** [tmux/tmux#3676] opened 2023-08-29 11:11 UTC
## Environment

| Software | Version                    |
|----------|----------------------------|
| macOS    | Ventura 13.5               |
| Debian   | Bookworm 12.1              |
| tmux     | 071849f8 from Aug 23, 2023 |

## Problem

Hey, Nicholas. This bug has eluded me for quite some time, but I finally managed to reproduce it.

tmux gets jammed up after swapping windows in a session belonging to a session group and then subsequently killing that session.

## Steps To Reproduce

```fish
tmux -L test -f /dev/null -v start-server ';' set-option exit-empty off
tmux -L test new-session  -s  session-00     -n window-00      -d
tmux -L test new-window   -t  session-00     -n window-01
tmux -L test new-session  -t =session-00     -s session-00-a   -d
tmux -L test swap-window  -s  session-00-a:0 -t session-00-a:1
tmux -L test kill-session -t =session-00
```

## Sample Reproduction

```
━━━━━━  2023-08-23 18:09:28  ━━━━━━
» tmux -L test -f /dev/null -v start-server ';' set-option exit-empty off
› tmux -L test display-message -p '#{pid}'
→ pid = 262667 → tmux-server-262667.log
» tmux -L test new-session -s session-00 -n window-00 -d
» tmux -L test new-window -t session-00 -n window-01
» tmux -L test new-session -t =session-00 -s session-00-a -d
» tmux -L test list-sessions
  session-00: 2 windows (created Wed Aug 23 18:09:29 2023) (group session-00)
  session-00-a: 2 windows (created Wed Aug 23 18:09:30 2023) (group session-00)
» tmux -L test list-windows -a
  session-00:0: window-00- (1 panes) [80x24]
  session-00:1: window-01* (1 panes) [80x24]
  session-00-a:0: window-00* (1 panes) [80x24]
  session-00-a:1: window-01 (1 panes) [80x24]
» tmux -L test swap-window -s session-00-a:0 -t session-00-a:1
» tmux -L test list-windows -a
  session-00:0: window-01- (1 panes) [80x24]
  session-00:1: window-00* (1 panes) [80x24]
  session-00-a:0: window-01* (1 panes) [80x24]
  session-00-a:1: window-00 (1 panes) [80x24]
» pstree --arguments --show-pids --hide-threads 262667
  tmux: server,262667 -L test -f /dev/null -v start-server ; set-option exit-empty off
    |-fish,262670
    `-fish,262672
› tmux -L test list-sessions -f '#{==:#{session_group},session-00}' -F '#{session_name}'
  ⁃ session-00
  ⁃ session-00-a
» tmux -L test kill-session -t =session-00
! Command '['tmux', '-L', 'test', 'kill-session', '-t', '=session-00']' timed out after 119.9 seconds
» kill -s KILL 262667
» pstree --arguments --show-pids --hide-threads 262667
━━━━━━  2023-08-23 18:11:30  ━━━━━━  (2m 01s)
```

### Stack Trace

```
$ eu-stack --inlines --source --pid 262667 | sed 's|/.*tmux/||'
━━━━━━  2023-08-23 18:09:39  ━━━━━━
PID 262667 - process
TID 262667:
#0  0x0000557ba4b50966 winlink_stack_remove
    window.c:259:1
#1  0x0000557ba4b282b8 session_destroy
    session.c:223:3
#2  0x0000557ba4b282b8 session_destroy
    session.c:201:1
#3  0x0000557ba4ad1d0c cmd_kill_session_exec
    cmd-kill-session.c:68:3
#4  0x0000557ba4ad9b33 cmdq_fire_command
    cmd-queue.c:647:11
#5  0x0000557ba4ad9b33 cmdq_next
    cmd-queue.c:763:14
#6  0x0000557ba4b25ab5 server_loop
    server.c:273:14
#7  0x0000557ba4b13f62 proc_loop
    proc.c:217:42
#8  0x0000557ba4b26140 server_start
    server.c:252:2
#9  0x0000557ba4aca634 client_connect
    client.c:164:8
#10 0x0000557ba4aca634 client_main
    client.c:290:7
#11 0x0000557ba4ac5264 main
    tmux.c:519:2
#12 0x00007f893689f1ca __libc_start_call_main
    ../sysdeps/nptl/libc_start_call_main.h:58:16
#13 0x00007f893689f285 __libc_start_main_impl
    ../csu/libc-start.c:360:3
#14 0x0000557ba4ac5621 _start=
```

### Logs

* [tmux-server-262667.log](https://github.com/tmux/tmux/files/12463808/tmux-server-262667.log)
* [tmux-client-262665.log](https://github.com/tmux/tmux/files/12463811/tmux-client-262665.log)

## Related Issues

| Date       | Issue                                    | Title                                                                                      |
|------------|------------------------------------------|--------------------------------------------------------------------------------------------|
| 2020-08-12 | https://github.com/tmux/tmux/issues/2346 | [Feature Request] Command to kill session groups                                           |
| 2023-07-25 | https://github.com/tmux/tmux/issues/3645 | Creating and killing windows quickly causes hang and 100% CPU usage on tmux server process |
| 2023-08-08 | https://github.com/tmux/tmux/issues/3658 | Sometimes tmux crashes while kill a session ()                                             |

## Related Commits

| Date       | Commit                                   | Title                                                                            |
|------------|------------------------------------------|----------------------------------------------------------------------------------|
| 2023-07-19 | b13c2307497c1d905c07e7c21cd78b2c223fa4ee | Correct visited flag when the last window list is rebuilt by renumbering windows |

**Comment by nicm** [comment] 2023-09-01 13:58
I cannot reproduce this either by putting your commands in a script or by running them manually. Are you running exactly these commands from a script?

**Comment by serban** [comment] 2023-09-01 17:21
Interesting.

Yes, I am running exactly the commands listed in “Steps To Reproduce” above. I was able to reproduce the problem again with a fresh, clean build from HEAD (a99d7c63148e7d60c4368a711f6e0e7ff101b56a) on both Debian Bookworm on x86_64 as well as on macOS Ventura on arm64.

**Comment by nicm** [comment] 2023-09-02 08:40
I can reproduce it now, this seems to fix it for me:
~~~~
--- session.c   1 Sep 2023 13:48:54 -0000       1.95
+++ session.c   2 Sep 2023 08:38:37 -0000       1.96
@@ -687,8 +687,10 @@ session_group_synchronize1(struct sessio
        TAILQ_INIT(&s->lastw);
        TAILQ_FOREACH(wl, &old_lastw, sentry) {
                wl2 = winlink_find_by_index(&s->windows, wl->idx);
-               if (wl2 != NULL)
+               if (wl2 != NULL) {
                        TAILQ_INSERT_TAIL(&s->lastw, wl2, sentry);
+                       wl2->flags |= WINLINK_VISITED;
+               }
        }

        /* Then free the old winlinks list. */

**Comment by serban** [comment] 2023-09-02 09:17
Thanks, Nicholas.

The patch fixes the issue for me as well (at least with the “Steps To Reproduce” above). I'll see through the course of normal, daily use if anything else pops up.

**Comment by nicm** [comment] 2023-09-02 09:25
Great, thanks! I'm going to close this but do reply again if you see anything else.

**Closed by nicm** 2023-09-02 09:25 UTC
