### ISSUE TITLE
tmux session in weird semi-zombie state

### ISSUE THREAD

**Issue by wincent** [tmux/tmux#298] opened 2016-02-08 18:31 UTC
This happens to me about once per day. It started when I moved from 1.9a to 2.1.

I'll attach to a running tmux session and all of the windows/panes in it appear frozen. But they're not actually frozen; they're just not redrawing when they receive input.

1. Type some letters in a window, see nothing reflected on screen.
2. Move to another pane, for example with `<Prefix>o`; _see the cursor move to the next pane_ but note that typing still produces no visible output.
3. Use `<Prefix>`c to create a new window, see only an empty window created (no shell prompt visible).
4. Go back to previous window (ie. `<Prefix>l`) and see that the window has now updated with whatever you typed at steps 1 and 2 above.
5. Go back to step 1 and repeat. Observe the exact same symptoms.

The OS X "Sample" tool shows [this](https://gist.github.com/wincent/920a81585c90719a760c) is what tmux is up to when this happens. Nothing looks too suspicious in there.

The workarounds are either:

1. Kill all frozen panes (with `<Prefix>x`). This is always all of them, so you end up having to recreate the session.
2. Use `<Prefix>D` to get a list of attached sessions and detach all others but the one you created. Voila. Everything gets unblocked.

Workarounds that don't work:

- Deattaching then reattaching.

Not sure what the cause of this is, or whether it should be considered a bug or is the result of something funky I am doing. For reference, my `.tmux.conf` is [here](https://github.com/wincent/wincent/blob/master/roles/dotfiles/files/.tmux.conf).

**Comment by maxjacobson** [comment] 2016-02-08 23:11
Wow, I was going to create a similar issue. Let me ask: how do you *start* tmux? I found that when I start tmux via a helper script, this issue occurs, and when I start it via an alias, it does not occur.

Here's a GIF of what is occurring for me (does it look familiar?):

![tmux](https://cloud.githubusercontent.com/assets/1421211/12902449/497ebf10-ce8f-11e5-878d-bad8bdec832b.gif)

and here are the aliases I'm happily/safely using now: https://github.com/maxjacobson/dotfiles/commit/6d883df5989cedec149be1365a18b2ca1b76a958

**Comment by wincent** [comment] 2016-02-09 01:54
Interesting. I'm starting tmux via a function defined [in here](https://github.com/wincent/wincent/blob/master/roles/dotfiles/files/.shells/functions).

**Comment by maxjacobson** [comment] 2016-02-09 02:39
Oo that's a spicy function. Well, I think it might be a bug with tmux, but this should work for now:

```sh
alias 'tmux'='local SOCK_SYMLINK=~/.ssh/ssh_auth_sock; if [ -r "$SSH_AUTH_SOCK" -a ! -L "$SSH_AUTH_SOCK" ]; then ln -sf "$SSH_AUTH_SOCK" $SOCK_SYMLINK; fi; if [[ -n "$@" ]]; then env SSH_AUTH_SOCK=$SOCK_SYMLINK tmux "$@"; return; fi; if [ -x .tmux ]; then local DIGEST="$(openssl sha -sha512 .tmux)"; if ! grep -q "$DIGEST" ~/..tmux.digests 2> /dev/null; then cat .tmux; read -k 1 -r "REPLY?Trust (and run) this .tmux file? (t = trust, otherwise = skip) "; echo; if [[ $REPLY =~ ^[Tt]$ ]]; then echo "$DIGEST" >> ~/..tmux.digests; ./.tmux; return; fi; else ./.tmux; return; fi; fi; SESSION_NAME=$(basename "$(pwd)"); env SSH_AUTH_SOCK=$SOCK_SYMLINK tmux new -A -s "$SESSION_NAME"'
```

:wink:

**Comment by nicm** [comment] 2016-02-10 09:55
Hi

What libevent version?

Does this happen if you run tmux without a .tmux.conf?

**Comment by maxjacobson** [comment] 2016-02-10 10:04
> What libevent version?

Using libevent 2.0.22 (via homebrew on a Mac)

> Does this happen if you run tmux without a .tmux.conf?

Yes:

![tmux](https://cloud.githubusercontent.com/assets/1421211/12944217/b76c1318-cfb3-11e5-9017-f8bf17cb418a.gif)

**Comment by wincent** [comment] 2016-02-10 18:08
Same here (OS X 10.11.3, libevent 2.0.22 via Homebrew, tmux 2.1 via Homebrew).

**Comment by maxjacobson** [comment] 2016-02-17 23:40
I think this might have been resolved by the patch that came out of this issue https://github.com/tmux/tmux/issues/311#issuecomment-185456427 (https://github.com/tmux/tmux/commit/782dd941da97802108628fb068f5462f4c78f431). I tried installing from HEAD and couldn't reproduce the issue anymore, where previously I could reproduce it reliably. :tada:

**Comment by wincent** [comment] 2016-02-18 00:58
Great! Let's assume you're right until proven otherwise.

**Comment by maxjacobson** [comment] 2016-02-18 02:50
actually I just tried to re-open a tmux session and it's frozen again. apologies for the confusion, I think this issue persists :grimacing:

**Comment by wincent** [comment] 2016-02-18 04:14
Awww.

**Comment by nicm** [comment] 2016-02-18 19:31
Are you attaching to a session that is also attached elsewhere?

**Comment by maxjacobson** [comment] 2016-02-18 22:54
I don't think so, although I'm not really sure

**Comment by wincent** [comment] 2016-02-19 01:30
> Are you attaching to a session that is also attached elsewhere?

In my case, no. But when I look at the list of attached sessions, I can see tmux thinks I still have other sessions. Killing them (ie. with `<prefix>-D`) makes things unfreeze.

**Comment by nicm** [comment] 2016-02-19 13:32
Does this still happen in tmux from master? I changed how the backoff stuff works.

**Comment by wincent** [comment] 2016-02-19 16:55
Just updated to master. Will let you know if I see it happen again.

**Comment by wincent** [comment] 2016-02-19 20:13
Alas, just repro'd on master.

**Comment by maxjacobson** [comment] 2016-02-20 04:58
Same

**Comment by nicm** [comment] 2016-02-21 21:02
Hmm I don't know what is going on.

Please kill tmux entirely (tmux kill-server) then start tmux with "tmux -vvvv new" and reproduce then send me the server log from the directory where you started tmux.

**Comment by maxjacobson** [comment] 2016-02-22 00:02
![tmux](https://cloud.githubusercontent.com/assets/1421211/13206231/aeec1748-d8c7-11e5-9218-2412973b5fa2.gif)

OK I've reproduced again with `-vvvv` and made a log. It's more than 3 million lines and 336mb... when I tried to open it in textmate, my computer froze. lol. Here's a link to the log on dropbox: https://www.dropbox.com/s/jz9kdmrf8tguh4n/tmux-server-10591.log?dl=0

it seems to cut off mid-sentence at the end... I'm not sure why...

**Comment by maxjacobson** [comment] 2016-02-22 00:23
![tmux2](https://cloud.githubusercontent.com/assets/1421211/13206649/6ee8d556-d8d0-11e5-97b8-2c2a94cfcbff.gif)

OK reproduced, here's the server log: https://gist.github.com/maxjacobson/19a29d0c52cbac084419

(deleted the earlier comment because I was able to reproduce again and this time with a small enough log that I could upload it to gist)

**Comment by nicm** [comment] 2016-02-22 08:49
There is a client that has probably disconnected but tmux has not been
told it has disconnected, it can't tell that it isn't just slow, so the
backoff mechanism is slowing down all the panes that are in the session
attached to that client. That's why if you kill the other clients it
starts working again.

**Comment by tnn2** [comment] 2016-02-23 08:12
Here are my steps to reproduce:
1. run "tmux attach" on the same session in two xterms
2. xkill one of the xterms
3. resume work in the first xterm
4. typically it gets wedged within 5 seconds

(This is on tmux 2.1 as shipped with NetBSD -current)

**Comment by Duologic** [comment] 2016-02-29 16:21
I can confirm this bug on Arch Linux:

libevent 2.0.22-1
tmux 2.1-1

I've got a desktop which has a terminal connected to the tmux and a Macbook connecting over SSH to the same tmux. It usually gets stuck on my Macbook when my connection dropped for a few seconds and I had to reconnect to SSH, however I don't see the terminal that was connected via SSH, only the local one. Removing (`<Prefix>D`) the locally attached terminal fixes it again.

**Comment by boecko** [comment] 2016-03-11 18:10
i can confirm this with tmux 2.1 on SnowLeopard

- start a tmux session with 2 windows and  just 2 shells (no further output is produced)
- detach
- after several hours re-attach
- type some letters

observations:
- the window doesn't refresh (you don't see the letters you typed)
- the cpu spikes after you type in something
- if you switch between the windows, the screen is refreshed (with the typed letters)
- the cpu goes down to normal level after the switch
- tmux thinks the session is still attached, if you do "tmux list-sessions" outside TMUX

This only happens on sessions, where no output is produces. Sessions, which output something all the time, behave just fine.

**Comment by nicm** [comment] 2016-03-17 14:19
If you bump READ_SIZE and READ_BACKOFF in tmux.h to something huge this problem will probably go away.

**Comment by solotim** [comment] 2016-03-22 01:42
My current approach to "recover" is WAIT. Generally about 10 minutes later, it suddenly comes back normal. 
Hope developers address this issue asap...

**Comment by bridgesense** [comment] 2016-03-23 17:37
I hope there's a cure for this soon. :)

**Comment by boecko** [comment] 2016-03-30 18:45
> If you bump READ_SIZE and READ_BACKOFF in tmux.h to something huge this problem will probably go away.

It just postpones the problem.

**Comment by boecko** [comment] 2016-03-30 19:24
I've made git bisect to narrow down the problem
[tmux_issue_298_bisect.txt](https://github.com/tmux/tmux/files/196270/tmux_issue_298_bisect.txt)

**Comment by boecko** [comment] 2016-03-30 20:13
The bad commit is 3f4ee98162cd5bb7000f93fec0e631e123b1281d
The corresponding merge-commit to master is 00471dc78358bde092df65de5e2c375bf9be7437

**Comment by nicm** [comment] 2016-04-29 15:02
I have removed the backoff timer so this should be resolved in master.

**Closed by nicm** 2016-04-29 15:02 UTC

**Comment by maxjacobson** [comment] 2016-04-29 15:23
Thanks a lot @nicm 😄

**Comment by tamasgal** [comment] 2016-04-29 18:16
Nice ☺️

**Comment by tmartinx** [comment] 2016-05-04 22:49
This is also happening on Ubuntu 16.04:

tmux 2.1-3build1
libevent-2.0-5:amd64                            2.0.21-stable-2

I'll fill a bug report on Launchpad and link it here.

**Comment by bridgesense** [comment] 2016-05-05 07:46
Yeah, this is working for me now in the latest build.  Thank you!

**Comment by leeourand** [comment] 2016-06-30 13:56
I'm running 2.2, and still can replicate this on OS X by starting tmux, killing my terminal, starting a new terminal, and attaching. Here's a server log:
https://gist.github.com/leeourand/9688d67bc1ce73a6e6200d3b78211db0

**Comment by nicm** [comment] 2016-06-30 14:21
2.2 is the same as 2.1.

**Comment by jay-hankins** [comment] 2016-07-27 03:07
I am also seeing this issue with tmux 2.2 and iTerm 2 version 3.0.

**Comment by redhotvengeance** [comment] 2016-08-01 08:28
Running into this issue with tmux 2.2 on Terminal.app on OS X 10.11.6.

**Comment by jmurinello** [comment] 2016-08-10 07:29
I ran into the same `tmux` semi-zombie issue.

I found out that the **Zsh framework** I'm using had a module that originally came with the following **Zsh shell configuration**:

`unsetopt HUP`

As soon as I changed that line unto a _comment_ I no longer experienced the semi-zombie behaviour.

I know it will sound lame but to make sure it wasn't the Zsh framework causing it I disabled the framework an placed the `unsetopt HUP` in the `.zshrc` file and manage to replicate this issue. 

Can anyone tell me what's with `tmux` and the disabled shell `HUP`?

Cheers!

**Comment by NHDaly** [comment] 2016-12-05 23:21
I'm not sure if this is known, but I'm still seeing this issue in `tmux 2.3`.

Ubuntu 14.04 LTS
tmux 2.3
zsh 5.0.5 (x86_64-pc-linux-gnu)

It happens both to my zsh panes as well as any panes running vim.

**Comment by neerajbadlani** [comment] 2016-12-07 21:39
@NHDaly Did you try Prefix key + Capital D (detach other sessions) . It happens to me when I am generally moving from one wifi to other . The terminal feels like its stuck .

**Comment by NHDaly** [comment] 2016-12-08 17:59
@neerajbadlani: Yes, this fixed the issue for me! I almost always connect to my server running tmux over mosh (which tells you when there are other connections still active, and i always kill those before attaching to tmux), so I'd never seen this issue before. Thanks for the help.

**Comment by vikramsg** [comment] 2017-03-07 15:38
I have tmux 2.4 running and whenever there's too much text showing up the screen, it hangs. To test it I just did du -h inside a directory twice and it froze.

**Comment by fnicastri** [comment] 2017-03-10 11:25
same here, cat a log and it froze

**Comment by tmartinx** [comment] 2017-04-21 15:39
This problem is very annoying!   :-(

**Comment by tmartinx** [comment] 2017-04-21 15:40
Thank you @neerajbadlani!
