### ISSUE TITLE
Undercurl (special underline)

### ISSUE THREAD

**Issue by blueyed** [tmux/tmux#1492] opened 2018-09-30 17:59 UTC
What is required for undercurl support in terminals that support it, e.g. kitty?

`printf '\e[4:3mUnderlined\n'` works outside of tmux, but not inside.
I've tried wrapping it in the Ptmux wrapping sequence also without success (`printf '\ePtmux;\e\e[4:3m\e\\Underlined\n' `).

@bfredl left some insights in https://github.com/neovim/neovim/pull/9052#issuecomment-425050320.

**Comment by nicm** [comment] 2018-10-01 08:43
You will need to add it as an attribute, it can be an extended one like strikethrough (look for GRID_ATTR_STRIKETHROUGH) because it will be rarely used. But you will need to get terminfo capabilities added for it. Underline is smul/rmul, I would suggest initially using something like smuc/rmuc, and see how that flies when it comes to add it to the terminfo entry.

**Comment by blueyed** [comment] 2018-10-02 14:11
Thanks for the info.
I've looked briefly into it, but it is not trivial (for me).

For reference: https://sw.kovidgoyal.net/kitty/protocol-extensions.html#colored-and-styled-underlines

**Comment by nicm** [comment] 2018-10-02 14:14
I don't see much need for more types of underline but the extension seems sensible enough, at least by the standards of kitty, so it would not be hard to add at some point.

**Comment by nicm** [comment] 2018-10-02 14:39
You can try this: [tmux-uc.diff.txt](https://github.com/tmux/tmux/files/2438280/tmux-uc.diff.txt)

You will need to set smuc to the right sequence to turn on the new underlines, so something like:
~~~~
set -as terminal-overrides ',*:smuc=\E[4:3m'
~~~~
This is incomplete however - it is missing the bits needed in grid_string_cells_code (marked XXX). Also, it only supports one type of underline, but the extension adds four.

If we were to add the others then I don't see any reason not to use separate bits in GRID_ATTR_*, but I don't know whether it would be better to add additional terminfo(5) capabilities for each, or to have one capability that takes an argument.

It may be best to wait for a while and see what applications actually use, there is no point in adding support for four different types of underline if they are hardly ever used.

**Comment by blueyed** [comment] 2018-10-02 15:33
Thanks for looking into this!

1. Is `printf '\e[4:3mUnderlined\n'` supposed to work inside of tmux when using kitty then?
`printf '\e[4:1mUnderlined\n'` works (underlined), but `printf '\e[4:3mUnderlined\n'` prints "nderline" (missing U, not undercurled).
Does kitty's terminfo need a "smuc" entry for this?

2. Also Neovim uses the `Su` boolean capability flag to check if it is supported - can this be done via terminal-overrides, too?  I've tried adding `Su=1` to terminal-overrides, but without success (AFAIK).

3. > I don't know whether it would be better to add additional terminfo(5) capabilities for each, or to have one capability that takes an argument.

I think one capability with an argument is good, and is what kitty (and others, e.g. VTE) are doing already, no?

**Comment by nicm** [comment] 2018-10-02 15:47
Did you add smuc with terminal-overrides like I said?

A flag is not useful because it is not only entirely different from how all the other attributes appear in terminfo, but also means we need to hardcode the actual escape sequences which defeats the purpose of using terminfo in the first place.

A single capability like smulx or something which takes an argument (so it is set to something like \E[4:%p1%dm) would work for tmux. I don't know if it will be acceptable to upstream but there is no point in proposing it until something uses it.

**Comment by nicm** [comment] 2018-10-03 09:57
Try this instead please [tmux-us2.diff.txt](https://github.com/tmux/tmux/files/2441520/tmux-us2.diff.txt), you will need to set smulx instead, like this:
~~~~
set -as terminal-overrides ',*:smulx=\E[4:%p1%dm'

**Comment by blueyed** [comment] 2018-10-03 12:36
Yes, I've added the terminal-overrides, and replaced it now with the new one.
I am using a minimal tmux conf with only this setting now, and start tmux with `./tmux -L test -f tmux.minimal.conf`.
With the latest patch it still results in `nderlined` to be printed without decorations for `printf '\e[4:3mUnderlined\n'`.

From the server log (with `-v`) it looks like it writes `\033[4Underlined`:

```
input_parse: %0 ground, 172 bytes: \033[4:3mUnderlined\r\n\033[1m\033[3m%\033[23m\033[1m\033[0m                                                                            >
input_csi_dispatch: 'm' "" "4:3"
parameter 0: string 4:3
input_csi_dispatch_sgr_colon: 0 = 4
input_csi_dispatch_sgr_colon: 1 = 3
screen_write_collect_end: 10 Underlined (at 0,1)
input_c0_dispatch: '\r'
input_c0_dispatch: '\n'
screen_write_linefeed: at 0,1 (region 0-49)
input_csi_dispatch: 'm' "" "1"
parameter 0: number 1
input_csi_dispatch: 'm' "" "3"
parameter 0: number 3
screen_write_collect_end: 1 % (at 0,2)
input_csi_dispatch: 'm' "" "23"
parameter 0: number 23
input_csi_dispatch: 'm' "" "1"
parameter 0: number 1
input_csi_dispatch: 'm' "" "0"
parameter 0: number 0
screen_write_collect_end: 94                                                                                                (at 1,2)
input_c0_dispatch: '\r'
screen_write_collect_end: 1   (at 0,2)
input_c0_dispatch: '\r'
input_c0_dispatch: '\r'
input_csi_dispatch: 'm' "" "0"
parameter 0: number 0
input_csi_dispatch: 'm' "" "23"
parameter 0: number 23
input_csi_dispatch: 'm' "" "24"
parameter 0: number 24
input_csi_dispatch: 'J' "" ""
/dev/pts/30: \033[4
/dev/pts/30: Underlined
/dev/pts/30: \r
/dev/pts/30: \n
/dev/pts/30: \033[1m
/dev/pts/30: \033[7m
/dev/pts/30: %
/dev/pts/30: \033(B\033[m
/dev/pts/30:                                                                                               
/dev/pts/30: \033[3;1H
/dev/pts/30:  
screen_write_collect_flush: flushed 4 items (106 bytes)
```

> A flag is not useful because it is not only entirely different from how all the other attributes appear in terminfo, but also means we need to hardcode the actual escape sequences which defeats the purpose of using terminfo in the first place.

As far as I understand it, the flag is useful for detecting this feature in the first place (see https://sw.kovidgoyal.net/kitty/protocol-extensions.html#colored-and-styled-underlines), but I can see that this would not be necessary if it would have a terminfo name in the first place.
(Re)setting the color (`<ESC>[58...m` and `<ESC>[59m`) would need to get a name then also I assume?

/cc @kovidgoyal (for kitty / the terminal extension documentation)

**Comment by kovidgoyal** [comment] 2018-10-03 13:10
There are plenty of boolean capabilities in terminfo already. Just to name a few: am, ccc, kn, mc5i, mir, msgr, npc and on and on and on. Read man terminfo.

There is absolutely no need to a terminfo string var for this capability. We *do not* want different terminals to use different escape codes for the same thing. Therefore, it was a deliberate design decision to use a boolean. And if you used the proposed smuc, then you would either need one for each different underline style or you would need to hardcode the number to style mapping anyway. If you hardcode that, you might as well hardcode the full escape code.

**Comment by nicm** [comment] 2018-10-03 14:06
It would have taken little thought for you to realise that I must naturally be well aware that there are many boolean capabilities. Just because boolean capabilities exist, doesn't mean one is appropriate here.

I think you only have a shallow understanding of terminfo. The flags you mention specify behaviour or modify the use of other capabilities. They do not specify escape sequences - there are only a couple that do. In fact, terminfo does not require that a terminal be modelled on the DEC terminals at all.

Hardcoding parameter meanings is not the same as hardcoding escape sequences, because a terminfo capability is powerful enough to translate parameters if required. So if a new terminal chose to use "\\002_99Q" instead of "\\033[4:2m", it would be possible to write a capability that translated appropriately. For example, look at some of the more sophisticated capabilities in xterm-256color like setaf, where different arguments give quite different results:
~~~~
$ TERM=xterm-256color tput setaf 1|cat -v; echo
^[[31m
$ TERM=xterm-256color tput setaf 100|cat -v; echo
^[[38;5;100m
~~~~
tmux does hardcode a few escape sequences, but I'm not going to add more when it when it is simple and sensible to use a string capability for this instead:
- It would match the existing attribute capabilities.
- It is more future proof.
- It is the whole purpose of terminfo to hide the specific sequences being sent to the terminal.
- It is more likely to be acceptable to upstream when it comes time to discuss it.

**Comment by nicm** [comment] 2018-10-03 14:19
@blueyed I know what the problem is, will get back to you in a bit.

**Comment by kovidgoyal** [comment] 2018-10-03 14:22
Sigh. Did you just ignore everything I said? To quote myself: 

```
There is absolutely no need to a terminfo string var for this capability. We do not want different terminals to use different escape codes for the same thing. Therefore, it was a deliberate design decision to use a boolean. 
```

what has the ability of terminfo to parametrize escape sequences got to do with anything? Just because it can do something, does not mean it should do something. The only use of parametrizations is if different terminals use different escape codes for the same thing. Which they do not here. And we do not want them to start.

But whatever, I dont have the time to waste pointing out the obvious to you. Given your attitude in the past, I am not at all surprised you would choose to be obstructionist just for the sake of being obstructionist. Feel free to get your pointless parametrized escape code added to terminfo and prevent your users from using styled underlines until that happens several years from now.

**Comment by nicm** [comment] 2018-10-03 14:53
@blueyed please try this: [tmux-us3.diff.txt](https://github.com/tmux/tmux/files/2442537/tmux-us3.diff.txt)

You will need to escape the : in terminal-overrides, so try this:
~~~~
set -as terminal-overrides ',*:smulx=\E[4\:%p1%dm'

**Comment by blueyed** [comment] 2018-10-04 17:08
@nicm 
That works!  Thank you very much!

What is your plan for allowing to detect this feature?
I understand that you do not like the "Su" boolean property, correct? (and that it cannot be added via terminal-overrides currently)

Should e.g. Neovim query the `smulx` property then instead, which then would need to be added to tmux' own terminfo also?

**Comment by blueyed** [comment] 2018-10-05 12:15
kitty and gnome-terminal at least support it (and are released).
Both also support setting of the color (`<ESC>[58...m` / `<ESC>[59m`, as mentioned on https://sw.kovidgoyal.net/kitty/protocol-extensions.html).
gnome-terminal/libvte does not appear to support `Su` though also, so for Neovim that means to check the vte version.  vte added it in https://github.com/GNOME/vte/commit/efaf8f3c (0.51.2).

**Comment by blueyed** [comment] 2018-10-05 12:27
0.51.2 (December 2017)

**Comment by nicm** [comment] 2018-10-05 12:34
OK will take a look.

**Comment by blueyed** [comment] 2018-10-06 17:53
Do you plan to add support for colors, too?

**Comment by nicm** [comment] 2018-10-07 11:50
Maybe, but after this is in.

**Comment by blueyed** [comment] 2018-10-08 11:29
`Su` is in kitty's terminfo at least.  But you're right that I can make a PR for Neovim already.

**Comment by nicm** [comment] 2018-10-08 11:31
kitty does not have an official terminfo entry, just one the author made up.

**Comment by nicm** [comment] 2018-10-08 11:34
By that I mean, it is a dead end, you will not see Su in any other entries unless they are also maintained outside of ncurses.

**Comment by nicm** [comment] 2018-10-08 11:47
I don't have time to look at the colours for the moment but it is probably safe to assume that if a terminal has Smulx it will support the colour sequence too. We could probably invent an entry for it too, maybe something like:
~~~~
Setulc=\E[5%p1%dm
~~~~
But I will leave taking that any further until tmux needs it.

**Comment by blueyed** [comment] 2018-10-08 11:59
> but it is probably safe to assume that if a terminal has Smulx it will support the colour sequence too

That won't be the case for tmux then though (until it is added also).  But if I understand you correctly it will be added then after 2.8 and this patch gets merged, right?

**Comment by nicm** [comment] 2018-10-08 12:04
No, but tmux (and it would be safe to say any other terminals that support one but not the other) will ignore it safely, it won't cause any problems with the terminal.

I might merge it to master soon, but it will not be in 2.8, it will be in 2.9.

**Comment by nicm** [comment] 2018-10-08 12:34
I have applied this to master now. I also added some attribute names so you can use the underlines within tmux itself ("curly-underscore" and so on). Let me know if you see any problems.

Adding colour would not be that hard basically you need to:
- Add a int member to grid_cell for the underline colour. The escape sequence can only set either 256 or RGB colours so it will always have one of the COLOUR_FLAG_* bits set, so 0 can be used to mean "not set".
- Modify grid_need_extended_cell to return 1 if the underline colour is set (not 0).
- Parse the escape sequence in input.c and store it into the input cell (look at input_csi_dispatch_sgr and the various helpers).
- Add a TTYC_SETULC or whatever for the terminfo capability and add it to the table in tty-term.c (look at Smulx to see).
- Apply the colour in tty.c. You will need to check with an existing implementation like VTE whether it needs to go through the palette or not (I expect it will, which just means calling window_pane_get_palette for the 256-colour case). Also it needs to cache the current state in the tty like we do for fg and bg so it is not constantly setting it unnecessarily, also clear it on sgr0 and so on. Look at tty_colours, tty_check_fg etc.

**Closed by nicm** 2018-10-08 12:34 UTC

**Comment by nicm** [comment] 2018-10-08 18:42
I am modifying this slightly so you escape : in terminal-overrides as :: not as \: because otherwise it is confusing with multiple layers of escaping, so you will need to change to use this:
~~~~
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'

**Comment by kmoschcau** [comment] 2019-05-07 11:12
Is there anyone looking at the color support for this right now? Otherwise I might have a go at it and try to put together a merge request.

**Comment by nicm** [comment] 2019-05-07 11:13
As far as I know nobody is working on it.

**Comment by kmoschcau** [comment] 2019-05-08 16:16
Alright. The first question I have is:
Should we try to find a way to support 4-bit color indices for the colored underline or would that just not be supported at all? Since there isn't really enough room to do it in a similar way to `30` to `37` and `40` to `47`.

The second one came to me from this comment: https://github.com/neovim/neovim/issues/9270#issuecomment-442025525
There it says that 24-bit escape sequences actually have another, empty parameter. Wouldn't that be a conflict with the way you decided to escape colons in the `terminal-overrides`?

**Comment by kmoschcau** [comment] 2019-05-08 16:19
Alright, the first question is:
What would we use as 4-bit escape sequence numbers, if we choose to support them? We can not use `50` to `57` at least.

The second comes from the comment here: https://github.com/neovim/neovim/issues/9270#issuecomment-442025525
Wouldn't that empty color index parameter for 24-bit escape sequences conflict with the way you escaped the colons in `terminal-overrides`?

**Comment by kmoschcau** [comment] 2019-05-08 16:20
Alright, the first question is:
What would we use as 4-bit escape sequence numbers, if we choose to support them? We can not use `50` to `57` at least.

The second comes from the comment here: https://github.com/neovim/neovim/issues/9270#issuecomment-442025525
Wouldn't that empty color index parameter for 24-bit escape sequences conflict with the way you escaped the colons in `terminal-overrides`?

**Comment by nicm** [comment] 2019-05-08 16:25
My reading of the specification is that it does not support ANSI colour, so
you only need to worry about 256 and RGB colour.

You can process the 58 sequence in the same way as 38 and 48, tmux already
handles the various forms. You should be able to escape the colons in
terminal-overrides as ::. If it doesn't work it will need to be fixed.

**Comment by kmoschcau** [comment] 2019-05-08 16:34
Understood on the first.

Concerning the second, I already got that working on my tmux instance.
What I meant is, it seems that the 24-bit color sequence is seemingly interpreted wrong by most applications, including tmux.
If that comment is correct, it should be :2::rrr:ggg:bbbm and not :2:rrr:ggg:bbbm.
That means on one hand the handling of the escape sequence would need to be corrected,
and on the other hand, it would make it necessary to write the terminal-overrides parameter with 4 colons in the tmux.conf.
But I guess this whole thing is a separate issue entirely and should probably be handled as such.

May 8, 2019 6:25 PM, "Nicholas Marriott" <notifications@github.com (mailto:notifications@github.com?to=%22Nicholas%20Marriott%22%20<notifications@github.com>)> wrote:
My reading of the specification is that it does not support ANSI colour, so
you only need to worry about 256 and RGB colour.

You can process the 58 sequence in the same way as 38 and 48, tmux already
handles the various forms. You should be able to escape the colons in
terminal-overrides as ::. If it doesn't work it will need to be fixed.

**Comment by kmoschcau** [comment] 2019-05-08 16:38
Also sorry for the mess in the comments, it seems GitHub suddenly decided to not show them in chronological order anymore.

**Comment by nicm** [comment] 2019-05-08 16:57
Just treat it the same as 38 and 48.

**Comment by kmoschcau** [comment] 2019-05-18 13:26
Hi, I finally got back to working on this a bit. I got another questions, that's more design related:
Do we want to use this escape sequence only for underscores or for everything, that's not foreground and/or background?

**Comment by nicm** [comment] 2019-05-18 13:31
I don't understand what you are asking. SGR 58 is for underscores only?

**Comment by kmoschcau** [comment] 2019-05-18 13:32
If that is all we want to use it for, that is all I need to know. You already answered my question.

**Comment by nicm** [comment] 2019-05-18 13:47
The fix for the colour space parameter is here https://github.com/tmux/tmux/pull/1742#issuecomment-493331584.

**Comment by kmoschcau** [comment] 2019-05-19 10:35
Next question: Which terminfo entry do we want to use now? `Setulc` or something else?

**Comment by nicm** [comment] 2019-05-19 15:16
Yes that would probably do.
