### ISSUE TITLE
move-pane/select-window now working probably with multiple sessions

### ISSUE THREAD

**Issue by pmnoxx** [tmux/tmux#824] opened 2017-03-11 05:26 UTC
On master, with an empty configuration.

Do the following steps:
``
tmux -Ltest kill-server
``
``
tmux -vvvv -Ltest -f/dev/null new
``
``
new-session
``
``
new-session
``
``
move-pane -t :1
``
Current session got closed, but the expected response was to print "Can't find window: 1"

``
new-session
``
``
new-session
``
``
move-pane -t :2
``
This prints "Source and target panes must be different". It should have printed "Can't find window: 2".

``
new-session
``
``
new-session
``
``
move-pane -t :3 
``
...
``
move-pane -t :9
``
Those work fine, they print message "Can't find window :XXX"

``
new-session
``
``
new-session
``
``
new-window -t :3
``
``
move-pane -t :3 
``
This works, this moves pane in window 0 to pane in window 3.

``
new-session
``
``
new-session
``
``
new-window -t :1
``
``
move-pane -t :1
``
This works fine, it moves pane from window 0 to window 1.

I'm running ubuntu 16.04 with latest version from master branch. I was also able to reproduce on my macbook pro iOS Sierra with old tmux 0.17.

uname -sp && tmux -V && echo $TERM
``
Linux x86_64
``
``
tmux master
``
``
screen-256color
``

Originally I was writing script that uses return value of select-window and move-pane.  Both of that are affected by this issue. The only difference is that move-pane closes current window, and select-window returns exit code 0, even though it failed to select window.

I also tried replacing ``-t :1`` with ``-t:=1``. However, that didn't help..

**Comment by nicm** [comment] 2017-03-11 08:22
This is because we try window parts as sessions and pane parts as windows as well, which matches session '1' in your case. There is perhaps no need to do this at all, and certainly no need unless they look like a session or window ID. Please try this: [x.diff.txt](https://github.com/tmux/tmux/files/835616/x.diff.txt)

**Comment by pmnoxx** [comment] 2017-03-11 09:21
I tested move-pane and select-window on all corner cases I could think off. Now it works now as it was supposed to. Just in case I also tested attach-session to make sure we don't have regression.

**Comment by nicm** [comment] 2017-03-11 15:17
Applied to OpenBSD now, will be in GitHub soon. Thanks!

**Comment by pmnoxx** [comment] 2017-03-11 15:35
Thanks for quick fix! I'll apply new configurations all of my machines.

**Comment by nicm** [comment] 2017-03-13 10:52
This fix breaks other uses, will need to revert it and revisit.

**Comment by nicm** [comment] 2017-03-13 21:15
OK, so the problem is that people commonly do stuff like:

tmux new -sfoo
tmux send -tfoo somekeys

And that has to continue to work, which means that we have to continue to look up windows as sessions unless we are sure the user means one or the other.

However, what we can probably do safely, is not look up windows as sessions (and panes as windows) when they are qualified with a ':' or a '.'. So 'foo' as a window target will look for windows and sessions called 'foo', but ':foo' will only look for windows, and 'foo:' only for sessions.

Please try this and see if it still works for you: [y.diff.txt](https://github.com/tmux/tmux/files/839615/y.diff.txt)

I chose not to accept a session ID given as a window or a window ID as a pane, like the previous diff did. I don't think it is useful to use IDs of a different type as part of a target.

**Comment by pmnoxx** [comment] 2017-03-14 04:45
I tested this code again with the new fix. It works correctly with select-window and move-pane.

**Comment by nicm** [comment] 2017-03-22 07:26
I haven't forgotten about this but I am probably going to wait until after after the next OpenBSD release is prepared which will be a few weeks.

**Comment by nicm** [comment] 2017-04-05 11:05
Applied later diff now, thanks.

**Closed by nicm** 2017-04-05 11:05 UTC
