### ISSUE TITLE
Long command outputs clean up the next pane

### ISSUE THREAD

**Issue by gokceneraslan** [tmux/tmux#948] opened 2017-05-28 20:21 UTC
When I run a command which fills up a pane in tmux, next pane is cleaned up. Here is a tty gif:

![tty](https://cloud.githubusercontent.com/assets/1140359/26531823/08c2f2be-43f2-11e7-9a12-c52cc82840b4.gif)

This bug didn't exist in version 2.3, so I marked tag 2.3 as good and current master as bad and did git bisect. The problem with bisect is that I had to skip commits where `autogen.sh` doesn't exist, since I don't know how to compile tmux without autogen/configure/make. Here is the result of bisect:

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
c34a79b152e1d27ed87417e6a940358990ab9e79
d81a5c630f53e2513feb29815c03f4c90435e450
1afe9e98de5455f75b2753b26069c8d55bd22c81
We cannot bisect more!
bisect run cannot continue any more
```
By the way, this also happens with empty config. Platform info:

tmux: Latest master
OS: Arch linux
$TERM: screen

**Comment by gokceneraslan** [comment] 2017-05-28 20:37
Commits are from Nov 2016, so tmux 2.4 also has the bug:

![image](https://cloud.githubusercontent.com/assets/1140359/26531992/26510902-43f6-11e7-8abf-aaabe9a2bba8.png)

**Comment by ThomasAdam** [comment] 2017-05-28 20:42
On Sun, May 28, 2017 at 01:37:03PM -0700, Gökçen Eraslan wrote:
> Commits are from Nov 2016, so tmux 2.4 also has the bug:

Would you be using fish as your shell here?  If so, does the same thing happen
when using bash?

**Comment by nicm** [comment] 2017-05-28 20:42
Does this happen with master or not? What terminal are you using?

**Comment by gokceneraslan** [comment] 2017-05-28 20:54
I can reproduce the bug in both master and 2.4. Version 2.3 is working fine. I'm using zsh with Terminology 1.0.0. 

I've just tried tmux master with gnome-terminal and it worked properly, so it should be related to terminology.

**Comment by nicm** [comment] 2017-05-28 20:57
Does it work if you do this in .tmux.conf then restart tmux entirely:


set -as terminal-overrides ',*:indn@'

**Comment by gokceneraslan** [comment] 2017-05-28 21:02
No, still not working.

**Comment by nicm** [comment] 2017-05-28 21:09
Show me logs from reproducing with master please

**Comment by gokceneraslan** [comment] 2017-05-28 21:18
[tmux-server-18880.txt](https://github.com/tmux/tmux/files/1034530/tmux-server-18880.txt)

**Comment by nicm** [comment] 2017-05-28 21:20
This is a bug in the terminal - it claims to be VT420 (returns CSI ?64 for DA), but DECSLRM is either not implemented or not working. I suggest you open a bug report with Terminology developers.

**Comment by gokceneraslan** [comment] 2017-05-28 21:23
OK, thanks. Any ideas why it appeared in tmux 2.4?

**Comment by nicm** [comment] 2017-05-28 21:24
We didn't use VT420 style margins until 2.4.

**Comment by gokceneraslan** [comment] 2017-05-28 21:37
Filed a bug report on terminology: https://phab.enlightenment.org/T5533

**Comment by nicm** [comment] 2017-05-28 23:06
You should be able to work around this by doing:

set -as terminal-overrides ',*:XT@'

In .tmux.conf since we will only check if the terminal is a VT420 at all if
TERM has XT.

**Comment by gokceneraslan** [comment] 2017-05-29 07:04
That works, thanks!

**Comment by nicm** [comment] 2017-05-29 07:09
Great, I'm going to close this since it is not a tmux issue. Thanks

**Closed by nicm** 2017-05-29 07:09 UTC

**Comment by nicm** [comment] 2017-05-31 16:25
You should note that if the terminal says it is VT420, tmux expects DECFRA to also work.

**Comment by billiob** [comment] 2017-06-08 17:07
I also implemented DECERA in terminology

**Comment by nicm** [comment] 2017-06-08 17:44
@billiob perhaps I am missing it in the code, but does your implementation of DECFRA handle SGR 0 correctly? It should not alter the colours - compare in xterm:
~~~~
printf '\033[42m\033[2J\033[0m\033[33;10;10;20;20$x'
~~~~
With:
~~~~
printf '\033[42m\033[2J\033[43m\033[33;10;10;20;20$x'
~~~~
DECFRA does change the attributes though:
~~~~
printf '\033[42m\033[2J\033[43;1m\033[10;10Habc\033[H\033[0;4m\033[33;10;10;20;20$x'
~~~~
DECERA does not change background colours, it only clears the content:
~~~~
printf '\033[42m\033[2J\033[43m\033[33;10;10;20;20$x\033[44m\033[10;10;20;20$z\033[0m'
~~~~
I would test myself but I can't get it to run unfortunately.

**Comment by nicm** [comment] 2017-06-08 17:50
I did get it to run... looks like you have some problems with several of the examples I gave, you should be able to compare with xterm and see easily enough :-).

**Comment by billiob** [comment] 2017-06-08 17:58
That's not how I understood "The fill character assumes the visual character attributes set by the last select graphic rendition (SGR) command." from http://vt100.net/docs/vt510-rm/DECFRA.html . I'll fix that when I'll get back from holidays (end of june).

**Comment by nicm** [comment] 2017-06-08 18:04
Yes its not how I understood it when I first tried it either but I asked Thomas Dickey and apparently that is how it is supposed to work. Not being able to clear colours (only replace) does make it much less useful.
