### ISSUE TITLE
Unicode characters are displaying abnormally in CentOS 7

### ISSUE THREAD

**Issue by wizken** [tmux/tmux#3602] opened 2023-06-26 22:56 UTC
### Issue description

How can I display Unicode emoji characters in tmux on CentOS 7? 
Currently, I'm experiencing a situation where I can input a Unicode emoji in a file(`emoji.txt` in compressed file) and it displays correctly when using the 'cat' command in the bash shell, but it doesn't work when inside tmux. 
However, I've tried it on Ubuntu 20 and Unicode characters are displayed correctly in tmux. 
I would like to know how I can configure tmux or CentOS 7 to enable the display of Unicode emoji characters in tmux on CentOS 7.

### Required information

Please provide the following information:

* tmux version (`tmux 3.3a`).
* Platform (`Linux x86_64`).
* $TERM inside and outside of tmux (`xterm-256color`).
* Logs from tmux ([tmux_log.tar.gz](https://github.com/tmux/tmux/files/11875277/tmux_log.tar.gz)).

**Comment by krader1961** [comment] 2023-06-26 23:46
CentOS tends to have old versions of tools like Tmux. Are you really using Tmux 3.3a on that platform or is that the version on your Ubuntu platform? What Unicode code points are causing a problem? What does "doesn't work" mean? Do all non-ASCII code points cause problems or just emojis?

P.S., Using `TERM=xterm-256color` inside a Tmux session is unlikely to be a problem for this specific issue but it can cause problems. You should always use one of the `screen` or `tmux` TERM variants inside Tmux.

**Comment by wizken** [comment] 2023-06-27 02:37
1. The version under Ubuntu 20 is also 3.3a
2. It doesn't work is mean unicode emoji is not show

**When I tried using version 2.9, it was able to display properly. Thanks a lot, I love you**
version：`3.3a`
![1](https://github.com/tmux/tmux/assets/35460563/ec34d44a-3cfc-4b73-a44d-7228d794be3d)
version: `2.9`
![2](https://github.com/tmux/tmux/assets/35460563/9d399260-23cb-4f83-8dad-69c4e9ec6928)

**Comment by krader1961** [comment] 2023-06-27 03:27
I don't understand why you closed this since the issue exists in the current, supported, version of Tmux. Also, I have no trouble displaying any of those code points inside Tmux using a version slightly newer than the 3.3a release.

**Comment by krader1961** [comment] 2023-06-27 03:52
Can you upload a Tmux server log produced when handling just a single code point such as U+1F642? That would make analyzing the log simpler.

**Comment by wizken** [comment] 2023-06-27 04:31
**I tried installing versions 2.9 to 3.2, and I found that this issue started occurring from version 3.3 onwards.**

this log file is only run `cat emoji.txt` 
[tmux-server-5741.log](https://github.com/tmux/tmux/files/11877640/tmux-server-5741.log)

emoji.txt
```txt
emoji="🙂"
```

**Comment by krader1961** [comment] 2023-06-27 05:20
FWIW, I built Tmux 3.3a from source on macOS using `./configure --enable-utf8proc` and `./configure --disable-utf8proc` and could not reproduce the problem. On my system the server log contains these lines:

```
1687842664.989259 input_parse_buffer: %0 ground, 14 bytes: emoji="\360\237\231\202"\r\n
1687842664.989270 screen_write_collect_end: 7 emoji=" (at 0,3)
1687842664.989282 input_top_bit_set 4 '\360\237\231\202' (width 2)
```

On your system the log contains these lines:

```
1687840109.832923 input_parse_buffer: %0 ground, 14 bytes: emoji="\360\237\231\202"\r\n
1687840109.832930 screen_write_collect_end: 7 emoji=" (at 0,0)
1687840109.832949 UTF-8 \360\237\231\202, wcwidth() -1
```

The problem is that the code point has an undefined width (-1) on your system so Tmux ignores it. You'll need to talk to the CentOS maintainers regarding why those code points are not recognized. As I said earlier this type of problem is usually because CentOS is very conservative and does not include the latest version of various libraries and programs. You can try building Tmux from source starting with `./configure --enable-utf8proc`.

@nicm has undoubtedly seen this reported by other people and may have different advice for how to work around whatever CentOS shortcoming is causing the problem.

**Comment by krader1961** [comment] 2023-06-27 05:40
I should point out that I used to be a Linux level 3 support engineer for IBM. Which meant handling problems like this for IBM customers which used RHEL (RedHad Enterprise Linux) which is what CentOS is based on. Distros like RHEL (and SLES: SUSE Linux Enterprise Server) are attractive to corporate customers willing to pay lots of money for support (and bug fixes) because they value the stability provided by the distro. But that stability means a lot of the OS components were typically two or more years old relative to what you would find on "consumer" distros like Ubuntu.

**Comment by wizken** [comment] 2023-06-27 06:07
Thanks, it works on centos7 when i using `./configure --disable-utf8proc`

**Closed** 2023-06-27 18:40 UTC
