### ISSUE TITLE
tmux-prefix-highlight is broken on master

### ISSUE THREAD

**Issue by aaronjensen** [tmux/tmux#2579] opened 2021-02-22 17:14 UTC
### Issue description

https://github.com/tmux-plugins/tmux-prefix-highlight displays a marker when the prefix key is active. On master, it's reversed. That is, it shows it when the prefix key is not active and it hides when it is active.

After bisecting, one of these commits it the cause (I'm guessing the second):

8986c8dfcd0083e5c767b8a247c119a25e1f8093
e858270006a9041b9016ed9e6cc12d622ac8fe31
cb7e6698f3241cecfac31a045b907988a4c286f1

I'm not familiar enough with the workings of `tmux-prefix-highlight` to narrow the repro down at the moment, but I hope that someone here may know what's going on at a glance. 

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux next-3.3
* Platform (`uname -sp`): Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`): inside: xterm-256color, outside: xterm-256color-italic
* Logs from tmux (`tmux kill-server; tmux -vv new`): n/a

**Comment by lacygoill** [comment] 2021-02-23 18:23
I was about to open an issue for this.  It looks like a regression introduced in cb7e6698f3241cecfac31a045b907988a4c286f1.

I can reproduce with this minimal `tmux.conf`:

    set -g status-left ' #[fg=colour7]#{?client_prefix,#[fg=colour0],}#S#[fg=colour7]'

In the status line, the session name should be white by default.  And when the prefix key has been pressed (`C-b` by default), the sessions should be black.  But since the aforementioned commit, it's the reverse; the session name is now black by default, and white when the prefix key has been pressed.

Logs:

- [tmux-client-3892.log](https://github.com/tmux/tmux/files/6031066/tmux-client-3892.log)
- [tmux-out-3894.log](https://github.com/tmux/tmux/files/6031067/tmux-out-3894.log)
- [tmux-server-3894.log](https://github.com/tmux/tmux/files/6031069/tmux-server-3894.log)

---

> $TERM inside and outside of tmux (echo $TERM): inside: xterm-256color, outside: xterm-256color-italic

Unrelated to this issue but your `$TERM` inside tmux is wrong.  It should be `tmux`, `screen`, or some derivative like `tmux-256color`.  The latter is the best one (for colors and italics).

**Comment by aaronjensen** [comment] 2021-02-23 18:30
> Unrelated to this issue but your `$TERM` inside tmux is wrong. It should be `tmux`, `screen`, or some derivative like `tmux-256color`. The latter is the best one (for colors and italics).

Hm, I have 256 and 24-bit color inside tmux, italics, bold, etc... what am I missing?

**Comment by lacygoill** [comment] 2021-02-23 18:55
> what am I missing?

I don't know your current setup (which programs you're using, and with which config).  If it works for you, that's fine, but it's still wrong.  Have a look at the [man page](https://man.openbsd.org/OpenBSD-current/man1/tmux.1#default-terminal):

   > Set the default terminal for new windows created in this session - the default value of the TERM environment variable. For tmux to work correctly, this must be set to ‘screen', ‘tmux' or a derivative of them.

This is also written on the [contributing page](https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md):

   > $TERM inside tmux is screen, screen-256color, tmux or tmux-256color. Check by running echo $TERM inside tmux.

As for italics, have a look at [this FAQ entry](https://github.com/tmux/tmux/wiki/FAQ#i-dont-see-italics-or-italics-and-reverse-are-the-wrong-way-round).

Maybe you have some settings in your programs configuration which override the effect of `$TERM`.  For example, even if `$TERM` doesn't contain the string `-256color`, you can tell Vim that your terminal really supports 256 colors by setting the Vim terminal option `t_Co`.  Many popular colorschemes do that.  But that's still wrong.  `$TERM` should be properly set; especially since it can have so many effects, creating subtle (and sometimes not-so-subtle) issues.  Here is [an example](https://github.com/tmux/tmux/issues/2044#issuecomment-570137779).

FWIW, here's [how I configure the `default-terminal` option](https://github.com/lacygoill/config/blob/c94dcd0f0d3a8c624566cb1f34f1552196001f38/.config/tmux/tmux.conf#L155-L227).  It contains some comment which give a little more info.

**Comment by aaronjensen** [comment] 2021-02-23 19:20
Thanks, I had to add this to my vim config:

```
if exists('+termguicolors')
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endif
```

But Emacs seemed to work out of the box with `tmux-256color`.

**Comment by nicm** [comment] 2021-02-24 09:27
This (`client_prefix`) should be fixed as soon as GitHub syncs, thanks!

**Closed by nicm** 2021-02-24 09:27 UTC
