### ISSUE TITLE
tmux 2.3 cannot set-hook in `after-new-session` hook

### ISSUE THREAD

**Issue by iblis17** [tmux/tmux#572] opened 2016-10-09 13:30 UTC
```
┌─[~]
| [-- INSERT --]
└─[iblis@abeing]% cat ~/code/tmux/test-hook.conf
set-hook -g after-new-session 'set-hook after-new-session refresh'
┌─[~]
| [-- INSERT --]
└─[iblis@abeing]% tmux -f ~/code/tmux/test-hook.conf -S ~/code/tmux/socket
```
I try to add `refresh` to the session-scoped hooks via `-g after-new-session`.
But I got the message: `no current session`.

Is this behavior intended or a bug?

----

```
┌─[~]
| [-- INSERT --]
└─[iblis@abeing]% uname -a
FreeBSD abeing 12.0-CURRENT FreeBSD 12.0-CURRENT #0 r306646: Tue Oct  4 02:31:47 CST 2016     root@abeing:/usr/obj/usr/src/sys/GENERIC  amd64
┌─[~]
| [-- INSERT --]
└─[iblis@abeing]% tmux -V
tmux 2.3
```

**Comment by nicm** [comment] 2016-10-10 08:12
I think this is a bug...

**Comment by ThomasAdam** [comment] 2016-10-10 09:28
On Mon, 10 Oct 2016 at 09:12 Nicholas Marriott <notifications@github.com>
wrote:

> I think this is a bug...
>

Hmm.  I'm sure we said originally that setting hooks from hooks could have
would have a bad idea, and indeed, the cmdq->flags would already be in a
HOOK state when processing the first command.

Nesting these might get complicated...

-- Thomas Adam

>

**Comment by nicm** [comment] 2016-10-10 13:26
Hmm maybe you are right...

**Comment by nicm** [comment] 2016-10-10 13:27
No - setting hooks from hooks should work: RUNNING hooks from hooks
shouldn't be allowed.

after-new-session should always have a session available, right?

**Comment by ThomasAdam** [comment] 2016-10-10 13:49
On Mon, 10 Oct 2016 at 14:27 Nicholas Marriott <notifications@github.com>
wrote:

> No - setting hooks from hooks should work: RUNNING hooks from hooks
> shouldn't be allowed.
>
> after-new-session should always have a session available, right?
>

Ah, yes.  You're right, that's the distinction.  The session should be
available, yes.  So if it isn't, or it's something else then there's a bug
here.

Thomas

**Comment by iblis17** [comment] 2016-10-10 16:11
FYI: following config make `tmux` core dump...
```
┌─[~]
| [-- INSERT --]
└─[iblis@abeing Oops]% cat code/tmux/test-hook.conf
set-hook -g after-new-session 'new-window'
```

**Comment by nicm** [comment] 2016-10-10 22:16
I think this is the same issue, session should not be NULL for after-new-session.

**Comment by nicm** [comment] 2016-10-10 22:22
This is the same problem I had when trying to get rid of set-remain-on-exit - the state is not re-prepared before after hooks. Below is my solution, and indeed it fixes the problems you demonstrate. However, the problem is that sometimes we want the new session (eg after-new-session, after-new-window, etc) and sometimes we want the original session (eg after-move-window, after-join-pane, etc).

~~~~
--- cmd-queue.c	28 Sep 2016 14:40:07 -0000	1.37
+++ cmd-queue.c	10 Oct 2016 22:17:33 -0000
@@ -235,9 +235,12 @@ cmdq_continue_one(struct cmd_q *cmdq)
 	if (retval == CMD_RETURN_ERROR)
 		goto error;
 
-	if (hooks != NULL && hooks_wait(hooks, cmdq, NULL,
-	    "after-%s", name) == 0)
-		retval = CMD_RETURN_WAIT;
+	if (hooks != NULL) {
+		if (cmd_prepare_state(cmd, cmdq, cmdq->parent) != 0)
+			goto error;
+		if (hooks_wait(hooks, cmdq, NULL, "after-%s", name) == 0)
+			retval = CMD_RETURN_WAIT;
+	}
 	cmdq_guard(cmdq, "end", flags);
 
 	return (retval);

**Comment by nicm** [comment] 2016-10-10 22:23
17:15 < nicm> thomas_adam: there is an irritating problem with hooks
17:16 < nicm> if i do: tmux set-hook after-split-window 'display'
17:16 < nicm> or neww or similarr
17:16 < nicm> then it will show the previous pane
17:16 < nicm> ie the cur pane before splitw
17:17 < nicm> which is obviously wrong and not useful for splitw
17:17 < nicm> i can fix this by re-prepareing the state before the after hook
17:17 < nicm> which will parse the target again and in this case get the new cur win
17:18 < nicm> the problem with that, is that it will be incorrect for commands which do want the old target
17:18 < nicm> say you had done movew or joinp or suchlike with a target, you'd want the after hook to continue to use that target, not parse it again which could get a different pane
17:19 < nicm> i think we may need a mechanism for commands which changed the cur pane to say so
17:19 < nicm> i had code to do that at one point i think
17:24 < nicm> for example say i have %0 and %1 in a window
17:25 < nicm> and set-hook after-break-pane 'display -p "#{pane_id}"'
17:25 < nicm> then tmux breakp -ds:.0 from that pane
17:26 < nicm> if i prepare again, i will get %1 (now :.0) not %0 (previous :.0)
17:26 < nicm> i think neww and splitw and new (and what else?) will need to update cmdq->current

**Comment by nicm** [comment] 2016-10-10 22:27
Perhaps this would be OK: [Uploading x.diff.txt…]()

~~~~
Index: cmd-new-session.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/cmd-new-session.c,v
retrieving revision 1.88
diff -u -p -r1.88 cmd-new-session.c
--- cmd-new-session.c	10 Oct 2016 21:51:39 -0000	1.88
+++ cmd-new-session.c	10 Oct 2016 22:26:16 -0000
@@ -46,7 +46,7 @@ const struct cmd_entry cmd_new_session_e
 
 	.tflag = CMD_SESSION_CANFAIL,
 
-	.flags = CMD_STARTSERVER,
+	.flags = CMD_STARTSERVER|CMD_REPREPARE,
 	.exec = cmd_new_session_exec
 };
 
Index: cmd-new-window.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/cmd-new-window.c,v
retrieving revision 1.60
diff -u -p -r1.60 cmd-new-window.c
--- cmd-new-window.c	10 Oct 2016 21:51:39 -0000	1.60
+++ cmd-new-window.c	10 Oct 2016 22:26:16 -0000
@@ -44,7 +44,7 @@ const struct cmd_entry cmd_new_window_en
 
 	.tflag = CMD_WINDOW_INDEX,
 
-	.flags = 0,
+	.flags = CMD_REPREPARE,
 	.exec = cmd_new_window_exec
 };
 
Index: cmd-queue.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/cmd-queue.c,v
retrieving revision 1.37
diff -u -p -r1.37 cmd-queue.c
--- cmd-queue.c	28 Sep 2016 14:40:07 -0000	1.37
+++ cmd-queue.c	10 Oct 2016 22:26:16 -0000
@@ -235,9 +235,13 @@ cmdq_continue_one(struct cmd_q *cmdq)
 	if (retval == CMD_RETURN_ERROR)
 		goto error;
 
-	if (hooks != NULL && hooks_wait(hooks, cmdq, NULL,
-	    "after-%s", name) == 0)
-		retval = CMD_RETURN_WAIT;
+	if (hooks != NULL) {
+		if ((cmd->entry->flags & CMD_REPREPARE) &&
+		    cmd_prepare_state(cmd, cmdq, cmdq->parent) != 0)
+			goto error;
+		if (hooks_wait(hooks, cmdq, NULL, "after-%s", name) == 0)
+			retval = CMD_RETURN_WAIT;
+	}
 	cmdq_guard(cmdq, "end", flags);
 
 	return (retval);
Index: cmd-split-window.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/cmd-split-window.c,v
retrieving revision 1.71
diff -u -p -r1.71 cmd-split-window.c
--- cmd-split-window.c	10 Oct 2016 21:51:39 -0000	1.71
+++ cmd-split-window.c	10 Oct 2016 22:26:16 -0000
@@ -45,7 +45,7 @@ const struct cmd_entry cmd_split_window_
 
 	.tflag = CMD_PANE,
 
-	.flags = 0,
+	.flags = CMD_REPREPARE,
 	.exec = cmd_split_window_exec
 };
 
Index: tmux.h
===================================================================
RCS file: /cvs/src/usr.bin/tmux/tmux.h,v
retrieving revision 1.650
diff -u -p -r1.650 tmux.h
--- tmux.h	10 Oct 2016 17:28:30 -0000	1.650
+++ tmux.h	10 Oct 2016 22:26:17 -0000
@@ -1473,6 +1473,7 @@ struct cmd_entry {
 
 #define CMD_STARTSERVER 0x1
 #define CMD_READONLY 0x2
+#define CMD_REPREPARE 0x4
 	int		 flags;
 
 	enum cmd_retval		 (*exec)(struct cmd *, struct cmd_q *);

**Comment by nicm** [comment] 2016-10-10 22:35
That diff makes "set-hook -g after-new-window 'set remain-on-exit on'" work too... not sure if there is any downside though... :-)

**Comment by ThomasAdam** [comment] 2016-10-10 22:59
Looks good.  Do breakp/joinp need similar, I wonder?

Thomas

**Comment by nicm** [comment] 2016-10-11 06:18
This will actually not work with new/neww/splitw -d, so we may need
something else instead.

**Comment by nicm** [comment] 2016-10-11 06:36
This works but I am not convinced there won't be side effects: [y.diff.txt](https://github.com/tmux/tmux/files/521088/y.diff.txt)

**Comment by iblis17** [comment] 2016-10-11 07:27
I applied the latest patch (y.diff) .. and i guess i found another issue: 
seems seesion-scoped hooks got poluted.

```
┌─[~]
| [-- INSERT --]
└─[iblis@abeing]% cat code/tmux/test-hook.conf
set-hook -g after-new-session 'set-hook after-new-session "set-option @foo 42"'
```
Then, open a new session:
```
┌─[~]
| [-- INSERT --]
└─[iblis@abeing]% tmux -f ~/code/tmux/test-hook.conf -S ~/code/tmux/socket 

------
(In this session)
┌─[~]
| [Venv(py3)] [-- INSERT --]
└─[iblis@abeing]% tmux show-options 
(empty)
┌─[~]
| [Venv(py3)] [-- INSERT --]
└─[iblis@abeing]% tmux show-hooks
after-new-session -> set-option @foo 42
┌─[~]
| [Venv(py3)] [-- INSERT --]
└─[iblis@abeing]% tmux show-hooks -g
after-new-session -> set-hook after-new-session "set-option @foo 42"
```

Then, open another terminal
```
┌─[~]
| [-- INSERT --]
└─[iblis@abeing]% tmux -f ~/code/tmux/test-hook.conf -S ~/code/tmux/socket 

------
┌─[~]
| [Venv(py3)] [-- INSERT --]
└─[iblis@abeing]% tmux show-options
@foo "42"
(WTF?)
┌─[~]
| [Venv(py3)] [-- INSERT --]
└─[iblis@abeing]% tmux show-hooks  
(empty, omg?)
┌─[~]
| [Venv(py3)] [-- INSERT --]
└─[iblis@abeing]% tmux show-hooks -g
after-new-session -> set-hook after-new-session "set-option @foo 42"
```

**Comment by nicm** [comment] 2016-10-11 15:11
When you make a new session, the session hooks will be used from the current session, so it is running the after-new-session hook from the first session after the second session is created. I don't think there is much we can do about that - in practice, after-new-session and before-new-session are only really useful as global hooks.

**Comment by iblis17** [comment] 2016-10-12 17:47
hmm.. Here is my senario:
I want to store some state on each tmux session. E.g. When I create a new session, i will need to store a label which came from `run-shell "invoke my own script"`. 

So I leveage the global hook to trigger `run-shell` after creating a new-session. Then,  I try to make the global hook run only one time via setting session-scope hook, and hope the global hook won't affect old sessions . But found the session will copy the session-scoped hook from first session and `show-hooks` is empty in the second session.

Any suggestion? I just want to do some state initialization on each session.

**Comment by nicm** [comment] 2016-10-12 18:29
Firstly, here is a new diff that might fix your problem, by looking the after hooks up in the new session. I'm not really certain this is what we want - I think there could be arguments either way. But give it a go anyway: [tmux-hooks-reprepare.diff.txt](https://github.com/tmux/tmux/files/525339/tmux-hooks-reprepare.diff.txt)

Secondly, I wouldn't solve the problem like this at all. Instead of trying to stop the global script running twice, why not just make it so it doesn't matter? Perhaps something like this at the start of the script:

[ -n "$(tmux display -p '#{@marker}')" ] && exit
tmux set @marker "$(date)"
...then do your stuff here...

**Comment by iblis17** [comment] 2016-10-13 05:39
This patch works fine on `show-hook`.

----
Nice suggestion!
My script works fine now 😛

**Comment by nicm** [comment] 2016-10-13 10:04
I have applied most of this change with some further changes, it should be in GitHub soon (look for a commit to tmux.h etc with "some improvements and bug fixes for hooks"). Please test and let me know if you see any further problems.

**Closed by nicm** 2016-10-13 10:04 UTC
