### ISSUE TITLE
"pane-died" hook called inconsistently.

### ISSUE THREAD

**Issue by systemmonkey42** [tmux/tmux#2483] opened 2020-11-27 00:24 UTC
### Issue description

I have the following options in place:
```
set-window-option -g remain-on-exit on
set-hook -g pane-died "if-shell '\$HOME/bin/tmux-pane-manager' ''"
```
The function 'tmux-pane-manager' may perform a couple of actions related to layout, then call `kill-pane -t <pane id>` on the deceased pane.

I use a shell function which splits the current window into 4, launches SSH in each, and enables `set-option -w synchronize-panes`.

When I finished and type 'exit', all four panes die immediately.

The pane-died hook, (and hence the tmux-pane-manager script) are called at least once.
They may trigger once or twice or more seemingly at random, with a single call being the most common.

As a result, a single pane may be cleaned up, and the rest remain in the dead state.

I have tested (a) ensuring the script returns 0, (b) avoiding make changes to the layout (in case calling kill-pane which re-numbers the panes may cause the hooks to fail)

### Expected behaviour :
The hook function will be called once per pane;
log attached where this occurred:
[tmux-server-664697.log](https://github.com/tmux/tmux/files/5605387/tmux-server-664697.log)

### Actual behaviour:
The hook function is called less than once per pane:
log attached where this occurred:
[tmux-server-658886.log](https://github.com/tmux/tmux/files/5605388/tmux-server-658886.log)

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux next-3.3
* Platform (`uname -sp`): Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`):  screen-256color / xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment] 2020-11-27 10:40
Can you reproduce this with a simple config and hook that has, for example:
~~~~
set -g remain-on-exit on
set-hook -g pane-died { run 'date >>/tmp/died' }

**Comment by systemmonkey42** [comment] 2020-11-28 07:05
Ok, I created a fresh account with no local customization (default ubuntu 20.04 user profile, no desktop, logged in via putty)
```sh
#!/bin/bash -x

tmux split -d -h -t .0 sleep 2
tmux split -d    -t .1 sleep 2
tmux split -d    -t .0 sleep 2
sleep 2
```
with the .tmux.conf file containing only the two lines requested.

the simple test was
```
rm /tmp/died; tmux -vv new-session '/tmp/test'; cat -n /tmp/died
After a two second delay, all panes die at about the same moment.
when I can see four 'Pane is dead' messages, I press <kbd>Ctrl-B</kbd><kbd>:</kbd>
and type the command "kill-window" which returns me to the console.

Test 1
```
tmuxtest@kcontrol:~$ tmux -vv new-session '/tmp/test'; cat -n /tmp/died
[exited]
     1  Sat 28 Nov 2020 06:47:46 AM UTC
     2  Sat 28 Nov 2020 06:47:46 AM UTC
     3  Sat 28 Nov 2020 06:47:46 AM UTC
     4  Sat 28 Nov 2020 06:47:46 AM UTC
tmuxtest@kcontrol:~$
```

Test 2
```
tmuxtest@kcontrol:~$ rm -f /tmp/died; tmux -vv new-session '/tmp/test'; cat -n /tmp/died
[exited]
     1  Sat 28 Nov 2020 06:49:14 AM UTC
     2  Sat 28 Nov 2020 06:49:14 AM UTC
     3  Sat 28 Nov 2020 06:49:14 AM UTC
     4  Sat 28 Nov 2020 06:49:14 AM UTC
tmuxtest@kcontrol:~$
```

Test 3
```
tmuxtest@kcontrol:~$ rm -f /tmp/died; tmux -vv new-session '/tmp/test'; cat -n /tmp/died
[exited]
     1  Sat 28 Nov 2020 06:51:46 AM UTC
     2  Sat 28 Nov 2020 06:51:46 AM UTC
     3  Sat 28 Nov 2020 06:51:46 AM UTC
tmuxtest@kcontrol:~$
```

I did additional tests, and generally for 4 lines of output, only rarely got 3 lines of output.

As an additional test, I changed the .tmux.conf as follows
```
set -g remain-on-exit on
set-hook -g pane-died { run 'date >>/tmp/died; sleep 0.01' }
```

With a `sleep` value of zero, I got the usual four results.  with a sleep value of `0.01` I get two results.  Any larger than that and I only ever get one result.

```
tmuxtest@kcontrol:~$ rm -f /tmp/died; tmux -vv new-session '/tmp/test'; cat -n /tmp/died
[exited]
     1  Sat 28 Nov 2020 07:02:55 AM UTC
     2  Sat 28 Nov 2020 07:02:55 AM UTC
tmuxtest@kcontrol:~$
```

It seems the time taken inside the hook (where the hook is a "run") is critical.

I have all the logs and can upload them if you have trouble reproducing.

thanks

**Comment by nicm** [comment] 2020-11-30 10:21
We stop nested hooks by checking what is on the global command queue and ignoring the hook if it has the NOHOOKS flag set (hooks are always run from the global command queue so there is no way for a nested hook to happen on a client command queue). This is failing for you because `run-shell` blocks the queue and returns which means that another hook that is not triggered by a command can be fired but it looks like `run-shell` is still running. I think it is enough just to ignore a command if the current item is waiting, please try this: [x.diff.txt](https://github.com/tmux/tmux/files/5615306/x.diff.txt)

**Comment by systemmonkey42** [comment] 2020-11-30 13:06
Thanks for that, the patch made a huge difference.
The hooks run sequentially, and dont seem to get skipped

I increased the sleep time to a full second.  
```
tmuxtest@kcontrol:~$ cat .tmux.conf
set -g remain-on-exit on
set-hook -g pane-died { run 'date >>/tmp/died; sleep 1' }
```
You can see each log record is 1 second apart.
```
tmuxtest@kcontrol:~$ rm /tmp/died; tmux -vv new-session './tmux_test'; cat -n /tmp/died
[exited]
     1  Mon 30 Nov 2020 12:48:24 PM UTC
     2  Mon 30 Nov 2020 12:48:25 PM UTC
     3  Mon 30 Nov 2020 12:48:26 PM UTC
     4  Mon 30 Nov 2020 12:48:27 PM UTC
tmuxtest@kcontrol:~$
```

The only caveat is if the windows is killed and the server exits, the cmd queue is discarded, but if thats a problem
you can always disable server exit.

```
 (sleep 4; tmux kill-window) & rm /tmp/died; tmux -vv new-session './tmux_test'; cat -n /tmp/died
[1] 28779
[exited]
     1  Mon 30 Nov 2020 12:50:55 PM UTC
     2  Mon 30 Nov 2020 12:50:56 PM UTC
[1]+  Done                    ( sleep 4; tmux kill-window )
```

The following (which is closer to my specific use case) works perfectly.

```
set -g remain-on-exit on
set-hook -g pane-died { run 'date >>/tmp/died; tmux kill-pane -t #{pane_id}' }
```

Thanks again.

**Comment by nicm** [comment] 2020-11-30 13:41
Great, applied to OpenBSD now, will be in GitHub later. Thanks!

**Closed by nicm** 2020-11-30 13:41 UTC
